### ISSUE TITLE
Eingefügte Bilder skalieren

### ISSUE THREAD

**Issue by misterunknown** [ckruse/cforum#106]
Es sollte möglich sein eingebettete Bilder zu skalieren. Ein width-Wert würde reichen, da das Bild ja in der Höhe relativ zu diesem Wert mit skaliert wird. Als Maximalwert kann man im CSS ja 100% angeben, um zu verhindern, dass eine fehlerhafte Angabe den Post-Div sprengt.

**Comment by MatthiasApsel** [comment]
Wenn du nichts dagegen hast, werde ich mal den fastix ansprechen.

**Comment by ckruse** [comment]
Tu dir keinen Zwang an. Denk aber dran, dass Fastix auch nur ein Laie
ist. Um sicher zu gehen, wirst du einen Anwalt (z.B. den Herrn Vetter?)
befragen müssen.

**Comment by MatthiasApsel** [comment]
Wer ist Herr Vetter?

**Comment by ckruse** [comment]
Udo Vetter ist einer der bekanntesten Netz-Anwälte, der betreibt das
Law-Blog (<https://www.lawblog.de/>). Siehe auch
<http://de.wikipedia.org/wiki/Udo_Vetter>.

**Comment by MatthiasApsel** [comment]
Kennst du ihn zufällig persönlich aus deiner Tätigkeit beim CCC? In seinem Impressum steht sinngemäß, dass er für Hinweise usw. nicht zur Verfügung steht.

**Comment by ckruse** [comment]
nein, da müsste man ihn beauftragen. Ich sprach deshalb von ihm, weil er sich mit sowas auszukennen scheint 

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by ckruse** [comment]
Anything new about this? Ich würde den Bilder-Upload *wirklich* gerne haben, das kann doch nicht sein, dass das rechtlich nicht lösbar ist, dafür machen es doch zu viele Leute... ich hab da einen Workflow mit Drag-and-Drop im Kopf, so ähnlich wie hier.

**Comment by MatthiasApsel** [comment]
nein, keine Neuigkeiten. Wir brauchen dann aber den Hinweis, dass nur CC-Bilder gepostet werden und 

> Dann sollte es eine Möglichkeit geben ähnlich wie #95 ein Posting mit einer Urheberrechtswarnung zu versehen. Bei einem Posting, das dieses flag hat, können nur der Posting-Autor und die Admins das Bild sehen.

Außerdem habe ich es auch versäumt, die rechtliche Seite abzuklopfen. :-(

**Comment by MatthiasApsel** [comment]
Ich würde es toll finden, wenn die Abmessungen der selbstgehosteten Bilder dann im HTML auftauchen, damit das Scrollen zu einem Anker besser funktioniert.

**Comment by ckruse** [comment]
Dann können wir halt die Skalierung via `max-width` vergessen

**Comment by MatthiasApsel** [comment]
Für das Scrollen reicht ja die Höhe. Und wenn mehrere Bilder in einer Zeile stehen, die dann umbricht, erwischt man halt in diesen wenigen Fällen den Anker eben nicht.

**Comment by ckruse** [comment]
Das würde dazu führen, dass die Perspektive verzerrt wird, weil das Bild nicht mehr in der Höhe skaliert werden kann.

**Comment by ckruse** [comment]
Implementiert
