### ISSUE TITLE
Quelle der Zitate kennzeichnen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#109]
Die Zitate werden ja mit blockquote-Elementen kaskadiert. Diese Elemente sollten/könnten ein cite-Attribut bekommen. Vielleicht kann man auch einen Link zur Quelle hinten anhängen.

**Comment by ckruse** [comment]
Ich halte das (nicht zuletzt wegen Markdown) nicht für sinnvoll umsetzbar.
