### ISSUE TITLE
Installations-Schwierigkeiten

### ISSUE THREAD

**Issue by RaoulSchaffranek** [ckruse/cforum#153]
Hallo Christian,
trotz deiner [Kurz-Anleitung](https://github.com/ckruse/cforum/issues/151#issuecomment-60201076), habe ich leider keine funktionierende Installation zu Stande bekommen. Seit Stunden schlage ich mich mit Versionsinkompatibilitäten zwischen den Installationspaketen herum. Das gesamte Ruby-Ökosystem stellt für mich momentan noch eine enorme Überforderung dar. Bis ich mich darin eingearbeitet habe, vergehen sicher noch viele Stunden Selbststudium. Für den Moment ist das allerdings hauptsächlich eine große Einstiegshürde, die ich ohne weitere Hilfe vermutlich nicht so schnell überwinden kann. Ich erwarte keine Schritt-für-Schritt-Installationsanleitung, allein die genauen Paketbezeichnungen inkl. Versionsbezeichnungen, die vorausgesetzt werden, wären schon ein willkommener Start.

**Comment by RaoulSchaffranek** [comment]
@ckruse entwickelst du zufällig in einer Vagrant-Maschine? Ich hatte vor mich nochmal mit dem Forum zu befassen, das würde mir den Einstieg erleichtern.

**Comment by ckruse** [comment]
Oh puh, ehrlich gesagt habe ich von Vagrant noch gar keine Ahnung. Ist das viel Arbeit sowas bereit zu stellen?

**Comment by RaoulSchaffranek** [comment]
Wenn man weiß wie, dann nicht. Wenn man das zum ersten mal macht, allerdings schon. Ich werde mal probieren aus der Installationsanleitung eine solche Maschine zu erstellen. Es wäre praktisch, wenn die Maschine der selfhtml-Installation möglichst ähnlich ist. Weißt du welches OS dort läuft? Oder ist das dedlfix' Terrain?

**Comment by ckruse** [comment]
Ich habe dort Debian 7 installiert:

~~~
root@morpork:~# cat /etc/debian_version 
7.11
root@morpork:~# 
~~~

**Comment by ckruse** [comment]
Ich bin gar nicht mal so sicher, ob das hier Sinn macht. Das Deployment von Rails unterscheidet sich wesentlich von PHP, und bei Rails ist es üblich, dass man einen Development-Mode mit eingebautem Webserver hat (gestartet über `rails server`) während man im Production-Mode eher sowas wie NGinx davor schaltet und damit einen Application Server (z.B. Unicorn) befragt; der Dev-Mode hat so Features wie Code-Reloading und transparentes Handling von Assets, während der Production-Mode nichts neu lädt und Assets minified und als eine einzelne Datei ausliefert.

Meines Erachtens nach macht es mehr Sinn, die Installation wie im Wiki zu machen.

**Comment by RaoulSchaffranek** [comment]
Die Vagrant-Maschine wäre ja nur für das Entwickeln da, nich fürs Deployment. Das hat ein paar ganz bequeme Vorteile:

- Jedes Vagrant-fähige System kann sofort eine lauffähige Instanz mit `vagran up` starten, ohne dass man die Installationsschritte manuell wiederholen müsste.
- D.h. ich kann auch mal das ganze System zerschießen, dann setze ich die Vagrant-Maschine einfach zurück oder bringe eine neue Instanz up.
- Ich muss die Entwicklertools und Abhängigkeiten nicht auf meinem Gastgeber-System installieren, sondern nur in der VM. Dadurch muss ich mich nicht mit Versionskonflikten zwischen veschiedenen Projekten rumschlagen.

Die Vagrant-Maschine würde also den Development-Mode nutzen, nicht den Production-Mode. Übrigens werden Vagrant-Konfigurationen auch in Ruby geschrieben.

**Comment by ckruse** [comment]
Du hast mich falsch verstanden, ich bezog mich auf das "möglichst nah am Server" :)

Am Mi. Juli 20 17:38:10 2016 GMT+0200 schrieb Raouλ:
> Die Vagrant-Maschine wäre ja nur für das Entwickeln da, nich fürs Deployment. Das hat ein paar ganz bequeme Vorteile:
> 
> - Jedes Vagrant-fähige System kann sofort eine lauffähige Instanz mit `vagran up` starten, ohne dass man die Installationsschritte manuell wiederholen müsste.
> - D.h. ich kann auch mal das ganze System zerschießen, dann setze ich die Vagrant-Maschine einfach zurück oder bringe eine neue Instanz up.
> - Ich muss die Entwicklertools und Abhängigkeiten nicht auf meinem Gastgeber-System installieren, sondern nur in der VM. Dadurch muss ich mich nicht mit Versionskonflikten zwischen veschiedenen Projekten rumschlagen.
> 
> Die Vagrant-Maschine würde also den Development-Mode nutzen, nicht den Production-Mode. Übrigens werden Vagrant-Konfigurationen auch in Ruby geschrieben.
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ckruse/cforum/issues/153#issuecomment-23398857

-- 
Gesendet von meinem Jolla

**Comment by RaoulSchaffranek** [comment]
Achso, ja hast' Recht, das kann uns eigentlich egal sein. Mit Wheezy stehe ich sowieso auf Kriegsfuß, ich würde lieber eine Ubuntu als Basis-Maschine nehmen.

**Comment by ckruse** [comment]
So, ich habe mir Vagrant mal angeschaut. Das ist ja wirklich nicht so kompliziert. Ich versuch mich morgen mal dranzusetzen ein Vagrantfile zurecht zu bauen.

**Comment by ckruse** [comment]
[x] done <https://github.com/ckruse/cforum/commit/217ac132f7be4d0b5565797dd88699a58ec12910>

Zum starten:

~~~
vagrant up
vagrant ssh
cd /vagrant
bundle exec rails s -b 0.0.0.0
~~~

Ich bin mir aber nicht 100% sicher, dass das stabil funktioniert - teste das doch bitte mal :) danke!

**Comment by ckruse** [comment]
Chef konnte mich übrigens nicht wirklich überzeugen, es ist mir z.B. nicht gelungen den notwendigen DB-User oder die Datenbanken selber anzulegen - die Doku ist teilweise echt beschissen.

**Comment by RaoulSchaffranek** [comment]
Hui, vielen Dank!

Ich habe noch ein paar Probleme. Zwei betrafen nur mein Hostsystem (die habe ich lösen können), das letzte betrifft die Chef-Version des Gast-Systems.

- Windows 10 kann ohne die [C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)  die Basis-Maschine nicht herunterladen. 
- Als mächstes hatte ich einen Versionskonflikt mit den Vagrant-Guest-Additions. Dagegen gibt es glücklicherweise ein Vagrant-[Plugin](http://kvz.io/blog/2013/01/16/vagrant-tip-keep-virtualbox-guest-additions-in-sync/).
- Die Chef-Version hat einen [Bug](https://github.com/chef/chef/issues/4948), der dafür sorgt, dass HTTP-Anfragen alle mit einem 404-Error quittiert werden. Ein Downgrade auf eine frühere Version, wie im verlinkten Ticket empfohlen, hilft bei mir leider nicht... Hier komme ich gerade nicht weiter. Da muss ich nochmal zu einer früheren Stunde nach gucken.

**Comment by ckruse** [comment]
Für die Chef-Sache verwende ich `vagrant-librarian-chef-nochef`, das hat bei mir gut geholfen.

**Comment by RaoulSchaffranek** [comment]
Juuhuu, klappt nun.

**Comment by ckruse** [comment]
Cool!

**Comment by ckruse** [comment]
Die Vagrant-Maschine legt einen Default-User mit dem Usernamen `admin` an, das Passwort… argh, habe ich vergessen zu vergeben. Ich pushe mal eine Änderung… [so](https://github.com/ckruse/cforum/commit/10f571f2773309f708b0100eca905e6240311c7c), das Passwort ist `admin`. Damit erhältst du Zugriff auf die Admin-Funktionen des Forums.
