### ISSUE TITLE
weitere Links in div class "message-links"

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#175]
Ich hätte dort auch gern einen Link zur Startseite mit Anker zum zuletzt geöffneten Beitrag, damit [dies](http://wiki.selfhtml.org/wiki/SELFHTML:Forum/Tipps_und_Tricks#Zum_ersten_nicht_geschlossenen_Thread_springen) ggf. wieder eingestellt werden kann sowie die Links "anmelden/registrieren" und "administratoransicht" mindestens in der nested-Ansicht.

**Comment by ckruse** [comment]
Hey,

MatthiasApsel <notifications@github.com> writes:

> Ich hätte dort auch gern einen Link zur Startseite mit Anker zum zuletzt geöffneten Beitrag, damit [dies](http://wiki.selfhtml.org/wiki/SELFHTML:Forum/Tipps_und_Tricks#Zum_ersten_nicht_geschlossenen_Thread_springen) ggf. wieder eingestellt werden kann sowie die Links "anmelden/registrieren" und "administratoransicht" mindestens in der nested-Ansicht.

Ich weiss nicht… der Bereich ist schon *echt* voll.

LG,
-- 
Christian Kruse
http://ck.kennt-wayne.de/

**Comment by MatthiasApsel** [comment]
>  Ich weiss nicht… der Bereich ist schon *echt* voll.

Es würde die Bedienung des Forums aber extrem erleichtern, denn man kann 
nach dem Lesen eines Beitrags ohne große Mausbewegung zur Startseite 
gelangen. So bediene ich derzeit das aktuelle Forum.

Matthias

**Comment by ckruse** [comment]
Bitte um kurze Sichtung, was hier noch umgesetzt werden muss. Mir fehlt ein wenig die Übersicht gerade...

**Comment by MatthiasApsel** [comment]
Am 03.03.2015 um 11:01 schrieb Christian Kruse:
> Bitte um kurze Sichtung, was hier noch umgesetzt werden muss. Mir fehlt
> ein wenig die Übersicht gerade...

Es wäre wohl gut, wenn man das trennen würde:

<div class="message-links"> ... </div>
<div class="forums-links">
     Link zur Forumshauptseite
     Link zur Startseite des aktuellen Forums
     anmelden/registrieren
     Administrator Ansicht
</div>

sorgt für kurze Mauswege. Und wen es stört, der kann es per User-CSS 
ausblenden.

-- 
Matthias
