### ISSUE TITLE
Admin sieht "Antwort akzeptieren" auch für fremde Beiträge

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#178]

**Comment by ckruse** [comment]
Working as intended. Weil es durchaus vorkommt, dass ein OP vergisst zu akzeptieren 

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by MatthiasApsel** [comment]
Es ist bestimmt nicht notwendig, dass jede Frage eine akzeptierte Antwort besitzt.

**Comment by ckruse** [comment]
Das ist wohl richtig, nichtsdestotrotz halte ich den Wunsch nach „Admins
können akzeptieren“ als für unrealistisch.

**Comment by MatthiasApsel** [comment]
Hm. in dem Satz ist irgendwas verloren gegangen.

**Comment by ckruse** [comment]
äh. "nicht für unrealistisch" sollte das heissen, sorry.

**Comment by MatthiasApsel** [comment]
Ja, dann passt es auch zu "Funktioniert wie vorgesehen". Das dürfen dann aber wirklich nur admins oder kann man sich dieses Recht auch verdienen?

Allerdings würde ich diese Funktion wohl eher nicht nutzen ;-)

**Comment by ckruse** [comment]
Das können tatsächlich nur Admins. Dass du das eher nicht benutzen
wirst, ist ja auch völlig ok und so gedacht. Zur Regel sollte die
Nutzung wirklich nicht werden.
