### ISSUE TITLE
Nach einer Anmeldung soll man auf der Seite landen, auf der man war

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#181]
Das könnte auch für eine Abmeldung gelten, wobei hier noch die Zugriffsrechte beachtet werden müssten.

**Comment by ckruse** [comment]
Für die Abmeldung wird sich das nicht machen lassen. Für die Anmeldung ist das doch schon umgesetzt?

**Comment by MatthiasApsel** [comment]
Am 03.03.2015 um 11:00 schrieb Christian Kruse:
> Für die Abmeldung wird sich das nicht machen lassen. Für die Anmeldung
> ist das doch schon umgesetzt?

Nö?

Beispiel: Ich lese 
http://forumtest.selfhtml.org/cforum/2014/dec/22/roadmap-todos-cforum-4-0-mal-wieder/584#m584

melde mich an und lande auf http://forumtest.selfhtml.org/

Wünschenswert wäre, wieder auf der Beitragsseite zu landen, weil man 
sich vermutlich anmeldet um zu antworten.

-- 
Matthias

**Comment by ckruse** [comment]
Ach so, du meinst, wenn man sich von Hand anmeldet. Wie soll das denn gehen? ;)

**Comment by ckruse** [comment]
Da es ein neues Feature ist verschiebe ich es mal auf 4.1; wir müssen uns allerdings durchaus überlegen, wie man das technisch umsetzen will.

**Comment by MatthiasApsel** [comment]
Im Wiki geht es auch: 
~~~~
http://wiki-test.selfhtml.org/index.php?title=Spezial:Anmelden&returnto=CSS
~~~~
Wobei CSS die Seite ist, von der die Anmeldung aufgerufen wurde.

**Comment by ckruse** [comment]
Im Wiki ist die URL-Struktur aber auch viel einfacher. Da muss man nur
die Seiten-Namen wissen und das wars. Im Forum ist die Struktur
komplizierter… aber mal sehen.

**Comment by MatthiasApsel** [comment]
:+1:
