### ISSUE TITLE
Änderung der Beitragsköpfe

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#182]
gemeint ist

~~~~ HTML
<article class="thread-message">
  <header id="m585" class="message first">
    <h2><a href="...#m585">Roadmap/Todos CForum 4.0 mal wieder</a></h2>
    <div class="details">
       <span class="author">...</span>
      <a href="...#m585"><time datetime="...">...</time></a>
   </div>
  </header>
~~~~

Es ist zweimal ein Link auf `m585`, diese beiden Links stehen jedoch im Element mit der id `m585`.

Dort sollte noch die Mail-Adresse und die Website des Autors hinein. Über die visuelle Gestaltung müsste man sich wieder Gedanken machen.

**Comment by ckruse** [comment]
Gibt es hier schon mehr Infos, wie das grafisch umgesetzt werden soll?

**Comment by MatthiasApsel** [comment]
Wie im jetzigen Forum auch, wenn nichts dagegen spricht.

**Comment by ckruse** [comment]
War das Feedback aus Trello nicht, dass das mithilfe von Icons umgesetzt werden soll?

**Comment by ckruse** [comment]
Ja: "Wenn es programmtechnisch die Wahl gibt, würde ich zugunsten der Übersichtlichkeit ein Icon vorziehen, sowohl für E-Mail als auch für die Website."
