### ISSUE TITLE
Meldung "Nachricht erfolgreich gelöscht" stimmt nicht

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#183]
Wenn ich den Löschen-button in Nachrichten klicke und zuvor keine Nachricht zum löschen ausgewählt habe, erscheint die Meldung "Nachricht erfolgreich gelöscht"

Zwei Lösungsvorschläge:

- Meldungstext "keine Nachricht zum löschen ausgewählt"
- Button per JS erst dann einblenden, wenn auch eine Nachricht ausgewählt wurde

Ich bin für den 2. weil man sich dann auch den Request sparen kann

Gilt auch für Benachrichtigungen

**Comment by ckruse** [comment]
Ich sehe hier keinen Handlungsbedarf. Die Meldung ist nicht falsch per
se sondern höchstens ungenau und selbst wenn sie falsch wäre: es richtet
keinen Schaden an und sorgt höchstens für ein Schmunzeln.

**Comment by MatthiasApsel** [comment]
Oder auch für ein "Nicht einmal das können die richtig." ;-)

**Comment by ckruse** [comment]
Glaub ich nicht - aber wenn, dann wär das für mich auch ok ;)
