### ISSUE TITLE
whitelist für Links, die kein no-follow brauchen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#186]
Siehe http://forum.de.selfhtml.org/?t=219146&m=1512288#m1512288

**Comment by ckruse** [comment]
Würde ich auf 4.1 verschieben. Will endlich ein Release draus machen...

**Comment by MatthiasApsel** [comment]
Am 03.03.2015 um 11:02 schrieb Christian Kruse:
> Würde ich auf 4.1 verschieben. Will endlich ein Release draus machen...

einverstanden

-- 
Matthias

**Comment by MatthiasApsel** [comment]
Kann auch für User-Homepages gelten. Dazu sollte der User sich aber auch das Recht erwerben müssen. Vielleicht auch 200 Punkte?
