### ISSUE TITLE
Tabulatoreingabe in Antwortfeld ermöglichen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#187]
z.B. http://css-tricks.com/snippets/javascript/support-tabs-in-textareas/

**Comment by ckruse** [comment]
Ich wüsste ehrlich gesagt nicht, wofür das gut sein sollte

**Comment by MatthiasApsel** [comment]
Am 03.03.2015 um 10:56 schrieb Christian Kruse:
> Ich wüsste ehrlich gesagt nicht, wofür das gut sein sollte

Damit man die Möglichkeit hat, mithilfe der Tabulatortaste Einrückungen 
vorzunehmen. Mir passiert das gelegentlich, dass ich das aus lauter 
Gewohnheit mit tab probiere um mich dann hinterher zu ärgern.

-- 
Matthias

**Comment by ckruse** [comment]
Gleichzeitig würde es mich gewaltig ärgern, wenn ich nicht mehr Tab drücken könnte, um zum nächsten Feld zu kommen. Ich bin wirklich nicht sicher, ob es eine gute Idee ist, das Default-Verhalten der Textarea zu ändern...

**Comment by ckruse** [comment]
Vielleicht als Button in der Toolbar?

**Comment by MatthiasApsel** [comment]
Das wäre zumindest hilfreich. Vielleicht auch STRG+@ als Tabersatz?
