### ISSUE TITLE
Fehlermeldung Tagerstellung

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#189]
Ich wollte meine letzte Antwort mit dem Tag "offtopic" versehen und habe die Fehlermeldung "Dieses Tag existiert nicht. Bitte wählen Sie ein anderes." (Eigentlich stand da 'Dieser Tag existiert nicht. Bitte wählen Sie einen anderen.') Es ist aber imho das Tag.

Das Tag wurde schlussendlich aber doch hinzugefügt.

**Comment by ckruse** [comment]
Working as intended, du bist Admin. Wenn du als Admin/Moderator einen
nicht verwendeten Tag einträgst, wird der einfach angelegt.

**Comment by ckruse** [comment]
Genau genommen: wenn du Admin/Moderator bist oder du den Badge "create tags" hast... ;)

**Comment by MatthiasApsel** [comment]
Ist die irreführende Fehlermeldung denn jetzt raus?

**Comment by ckruse** [comment]
Wieso irreführend? Was genau stört dich?

Am 13. März 2015 09:09:41 MEZ, schrieb MatthiasApsel <notifications@github.com>:
>Ist die irreführende Fehlermeldung denn jetzt raus?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ckruse/cforum/issues/189#issuecomment-78859660

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by MatthiasApsel** [comment]
Wenn ich neue Tags erstellen darf, sollte die Fehlermeldung "Dieser Tag existiert nicht. Bitte wählen Sie einen anderen." nicht zu sehen sein.

**Comment by ckruse** [comment]
Das sehe ich anders, man sollte in jedem Fall darüber informiert werden, dass man einen neuen Tag anlegt.

Um einem Kompromiss genüge zu tun habe ich diesen Fall jetzt unterschieden und man bekommt keine Fehlermeldung mehr, sondern eine Warnung, wenn man Tags erstellen darf.

**Comment by MatthiasApsel** [comment]
Einverstanden.

**Comment by MatthiasApsel** [comment]
Die Warnung erhält man aber nur beim ersten Versuch, ein nicht existierendes Tag anzulegen. Wenn ich in einer Antwort zwei nicht existierende Tags anlegen möchte, erfahre ich so gar nicht, dass auch das zweite Tag nicht existiert.

Btw. die unterschiedliche Größe gefällt mir gut.

**Comment by ckruse** [comment]
Die Warnung verschwindet, wenn man einen zweiten Tag angibt. Und sie
taucht wieder auf, wenn das auch ein unbekannter Tag ist. Wenn man also
einen zweiten unbekannten Tag eingibt, sieht es so auch als würde die
Nachricht verschwinden um dann direkt wieder aufzutauchen.

Welche unterschiedliche grösse von welchen Objekt meinst du?

**Comment by MatthiasApsel** [comment]
Am 13.03.2015 um 18:40 schrieb Christian Kruse:
> Die Warnung verschwindet, wenn man einen zweiten Tag angibt. Und sie
> taucht wieder auf, wenn das auch ein unbekannter Tag ist. Wenn man also
> einen zweiten unbekannten Tag eingibt, sieht es so auch als würde die
> Nachricht verschwinden um dann direkt wieder aufzutauchen.

Wenn du das nicht innerhalb der letzten 2 Stunden geändert hast, kann 
ich dieses Verhalten nicht bestätigen.
>
> Welche unterschiedliche grösse von welchen Objekt meinst du?

Die Tag"wolke".

-- 
Matthias

**Comment by ckruse** [comment]
Kannst du das bitte nochmal prüfen? Ich kann mir nocht vorstellen, dass
das unter Windows so anders funktioniert als unter Linux oder OS X.

**Comment by MatthiasApsel** [comment]
Das Verhalten ist unter Linux Mint und Win 8.1 identisch. Ich kann bestätigen, dass die Warnung auch beim zweiten unbekannten Tag auftaucht. Allerdings gibt es keine Warnung mehr, wenn ein unbekannter Tag wieder entfernt wird.

Tag: bla -> Warnung
bla entfernen
Tag: blu -> keine Warnung
