### ISSUE TITLE
fixierte Hinweise auch ausblenden

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#190]
Die Hinweise, dass man erfolgreich angemeldet ist, gevotet hat , ... könnten nach 2 Sekunden auch ausgeblendet werden.

**Comment by ckruse** [comment]
Du bist der zweite innerhalb von zwei Tagen, der das sagt. Sollten wir also wohl doch implementieren.

**Comment by ckruse** [comment]
Fixed
