### ISSUE TITLE
Anmeldung mit Benutzernamen oder E-Mail möglich

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#191]
Ich weiß nicht, ob das eine gute Idee für die 4.1 wäre, aber verschiedene Seiten (twitter, meine ich) erlauben die Anmeldung sowohl mit Benutzernamen als auch mit E-Mail-Adresse.

**Comment by ckruse** [comment]
Das wollte ich schon seit Monaten implementiert haben, habs aber immer vergessen. Danke :)

**Comment by MatthiasApsel** [comment]
Bitte. Gern. GitHub macht es auch so.

**Comment by ckruse** [comment]
Hahahahahaha, ich habe das schon lange implementiert. Ich pass dann mal den Text an ;)
