### ISSUE TITLE
Identische Tags ausblenden

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#193]
Im Threadbaum könnten identische Tags ausgeblendet werden (genau wie bei identischen Betreffen)

**Comment by ckruse** [comment]
Darüber hatte ich auch schon nachgedacht und es dann aber verworfen:
Tags sind ja keine Pflicht, wie sollte man dann ungetaggte Nachrichten
von getaggten unterscheiden?

**Comment by MatthiasApsel** [comment]
Wir führen das Tag "ungetagte Nachricht" ein.

**Comment by ckruse** [comment]
hehe ;-)

**Comment by MatthiasApsel** [comment]
So ganz schlecht finde ich die Idee gar nicht.

**Comment by ckruse** [comment]
Was möchtest du denn damit erreichen?

**Comment by MatthiasApsel** [comment]
Dass man im Threadbaum zwischen Beiträgen, die keine Tags haben, und denen, die im Vergleich zu ihrem Eltenbeitrag keine geänderten Tags haben, unterscheiden kann. Zudem können Administratoren oder sonstige Tagger gezielt die ungetagten Beiträge anschauen, um sie zu taggen. Bei der Funktion "Tags neu vergeben" könnte zudem ein Schalter sein "Diese Tags auch an alle Antworten heften"

**Comment by auge8472** [comment]
Sollte es nicht reichen, bei Nachrichten, die getaggt sind, ein weiteres Symbol, das eben dies bestätigt, anzuzeigen?

**Comment by ckruse** [comment]
Ich finde ehrlich gesagt, dass das unnötig viel Komplexität
hinzufügt. Für 4.0 sicher nicht mehr (heck, wir stehen kurz vor dem
Release!) und für nach 4.0 sollten wir darüber nochmal nachdenken. IMHO
ist der Thread-Baum ja so schon ein Icon-Wald.

**Comment by MatthiasApsel** [comment]
Ja, wir haben sogar schon einen feature-freeze festgelegt.

**Comment by auge8472** [comment]
> IMHO ist der Thread-Baum ja so schon ein Icon-Wald.

Nicht, dass ich dir da widersprechen will, aber eine andersartige Markierung (so sie denn kommt) wird den Wald auch nur dichter machen. Wenn es *nur* darum gehen soll, anzuzeigen, dass ein Posting Tags oder eben kene Tags hat, halte ich das Bild für die beste Wahl.
