### ISSUE TITLE
Beitragsselektion

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#194]
Ich bin gerade in einem [Forum](http://forum.matheguru.com/) über

"alle Beiträge" / "Beiträge, denen ich folge" gestolpert. Die Idee finde ich für V4.1 oder V4.2 gar nicht so schlecht.

**Comment by auge8472** [comment]
Wie legst du fest, welchen Threads du folgst? Sind es die als interessant markierten? Sind es (zusätzlich?) die, an denen du beteiligt bist? Soll hier eine zusätzliche Markierung greifen? Ist die Möglichkeit, Threads auszublenden, nicht schon das Pendant dieser Funktion?

**Comment by ckruse** [comment]
Nein, Threads ausblenden hat eine andere Funktion. Während Threads
ausblenden eine Blacklist ist („die will ich auf keinen Fall sehen“),
ist die Selektion eine Whitelist („die will ich sehen“). Semantisch ein
kleiner Unterschied, effektiv aber IMHO ein grosser.

Die Idee das an die Interessant-Markierung zu hängen hatte ich auch
schon, deshalb gibt es ja auch

<http://forumtest.selfhtml.org/interesting>

Das ist aber natürlich bei weitem nicht so stark integriert wie die
Funktion, auf die Matthias sich bezieht.

**Comment by ckruse** [comment]
(da fällt mir ein, in der 4.0 fehlt da noch der Link dorthin...)

**Comment by auge8472** [comment]
Hallo

> (da fällt mir ein, in der 4.0 fehlt da noch der Link dorthin...)

Das erspart mir ein neues Issue. Das ist mir nämlich auch gerade aufgefallen.

> Während Threads ausblenden eine Blacklist ist („die will ich auf keinen Fall sehen“), ist die Selektion eine Whitelist („die will ich sehen“). Semantisch ein kleiner Unterschied, effektiv aber IMHO ein grosser.

Ok, ich könnte nun sagen, dass ich so oder so zu einer Auswahl der mich interessierenden Threads komme. Das ist aber nur eine mögliche Sichtweise eines Anwenders. Programmseitig ist es natürlich ein erheblicher Unterschied, ob ich zu diesem oder jenem *nein* sage und mir das, was übrig bleibt angezeigt wird (wozu auch kein "Beiträge, denen ich folge" nötig ist, denn diese Ausgabe ist dann Standard) oder ob ich zu diesem oder jenem *ja* sage, um es aus der Masse hervorzuheben.

Ich hoffe nur, dass zur momentan verfügbaren Infrastruktur an Bedienelementen nicht noch weitere hinzukommen sollen (wenn denn vermeidbar). Sonst stehen wir auch nur im Wald. :-)

**Comment by ckruse** [comment]
Bzgl des Links: Done.

Bzgl whitelist vs blacklist: auch für den User ist es ein grosser Unterschied. Aber egal, wir sind uns im Grunde ja einig.

**Comment by ckruse** [comment]
Sollte mit der neuen Version der interessanten Beiträge gelöst sein.
