### ISSUE TITLE
"Zusammenfassung" der Zitat-Zeilen

### ISSUE THREAD

**Issue by ckruse** [ckruse/cforum#195]
Google Groups und ähnliche Dienste machen das schon lange: sie fassen Zitat-Zeilen zusammen:

![screen shot 2015-03-16 at 16 34 52](https://cloud.githubusercontent.com/assets/175095/6669680/7252170e-cbfa-11e4-9c24-5de2676f9613.png)

Ich finde das ein wirklich tolles Feature und bin der Meinung, wir sollten das für 4.1 ins Auge fassen.

**Comment by MatthiasApsel** [comment]
Klingt gut, ist mir noch garnicht aufgefallen. Sag mir mal einen ähnlichen Dienst, bei dem man das mal ohne Anmeldung anschauen kann. Ich würde dabei sogar auf eine CSS-Lösung setzen.
~~~~ 
.posting-content > blockquote {
  height: 1.4em;
  overflow: hidden;
}
.posting-content > blockqoute > :first-child {
  margin-top: auto;
}
.posting-content:hover > blockquote {
  height: auto;
  overflow: visible;
}
~~~~
Bleibt das Verhalten bei Touch

**Comment by ckruse** [comment]
Google Groups macht das. Aber auch nicht bei allen Zitaten; schau
z.B. mal hier:

<https://groups.google.com/forum/#!topic/mu-discuss/Z1NvRflnGT4>

Bei der Nachricht von Tamas Papp ist bei mir das Zitat eingeklappt.

Ich glaube, eine CSS-Hover-Lösung gefällt mir nicht, da will ich glaub
ich eine JS-Lösung mit onclick haben.

LG,

-- 
Christian Kruse
http://ck.kennt-wayne.de/

**Comment by MatthiasApsel** [comment]
Aber für jeden Benutzer einstellbar machen. Im Forum gab es schon Kritik. Ich find die Idee super, aber das trifft nicht für alle zu.

**Comment by ckruse** [comment]
Klar konfigurierbar.

**Comment by ckruse** [comment]
Sollte das per default an oder aus sein?

**Comment by ckruse** [comment]
PS: ich find das Feature total geil :)

**Comment by ckruse** [comment]
aktuell ist es für anonyme User eingeschaltet und für registrierte User per default ausgeschaltet. Einwände?

**Comment by MatthiasApsel** [comment]
Hätt ich auch so gemacht.
