### ISSUE TITLE
Retagging eines kompletten Teil-Baums

### ISSUE THREAD

**Issue by ckruse** [ckruse/cforum#206]

**Comment by MatthiasApsel** [comment]
Wenn man über "Beitrag bearbeiten" dahinkommt (weil auf meinen Wunsch hin, diejenigen, die bearbeiten dürfen, den Button "Tags neu vergeben" nicht zu sehen bekommen) gibt es die Möglichkeit nicht, das geänderte Tag an alle Antworten zu vergeben.

**Comment by auge8472** [comment]
Auch für den normalen, berechtigten Nutzer ist da ein Wurm drin. Issue ist angelegt (#396).
