### ISSUE TITLE
Sortierung der Nachrichten und Benachrichtigungen beibehalten

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#214]
Die gewählte Sortierung der PMs und Benachrichtigungen könnte im localStorage gespeichert werden.

**Comment by MatthiasApsel** [comment]
Im Zusammenhang damit hätte ich bei den Mails (und Benachrichtigungen) eine zeitlich absteigende Default-Sortierung.

**Comment by MatthiasApsel** [comment]
> Im Zusammenhang damit hätte ich bei den Mails (und Benachrichtigungen) gern eine zeitlich absteigende Default-Sortierung.

Das würde ich schon **sehr gerne** haben würden wollen. Ich hätte es dir auch als PR geschickt, aber ich habe die passende Stelle nicht gefunden :-(

**Comment by ckruse** [comment]
Das Problem ist, dass es da mit ein wenig JS nicht getan ist. Ich muss
dafür eine Konfigurations-Einstellung schaffen.

**Comment by MatthiasApsel** [comment]
Und die default-Sortierung?

**Comment by ckruse** [comment]
Die Default-Sortierung umzustellen ist kein Thema.

**Comment by MatthiasApsel** [comment]
Würdest du das bitte tun?

**Comment by ckruse** [comment]
Selbstverständlich. ;-)

**Comment by ckruse** [comment]
So. Ich habe das jetzt ganz anders gelöst. Überall, wo sortiert werden kann, wird die ausgewählte Sortierung in einem Cookie gespeichert und beim nächsten mal wieder angewandt.

**Comment by MatthiasApsel** [comment]
Cool. Also im Prinzip so, wie ich es vorgeschlagen hatte. Danke.

**Comment by ckruse** [comment]
Naja. Du hattest LocalStorage und JS vorgeschlagen ;-)
