### ISSUE TITLE
"alle Threads zuklappen" klappt nicht alles zu

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#219]
Ich habe im [Meta-Forum] (http://forum.selfhtml.org/meta) zuerst alle Threads als gelesen markiert und danach den Button, um alle Threads zuzuklappen gedrückt. Es wurden einige mitten drin stehende Threads nicht zugeklappt. Darüber und darunter stehende Threads wurden zugeklappt.

Weiterhin klappt das nochmalige drücken auf den Button "alle Threads zuklappen" alle Threads wieder auf, auch wenn es direkt daneben einen Button für genau diesen Zweck gibt. Das ist zumindest etwas verwirrend.

**Comment by auge8472** [comment]
Zusatzinfo zum Szenario: Ich war im Forum angemeldet, die Einstellung für das automatische zuklappen gelesener Threads war zu diesem Zeitpunkt nicht aktiv und die tatsächlich nicht zugeplappten Threads hatte ich alle vollständig gelesen.

**Comment by ckruse** [comment]
Hm. *grybel*

**Comment by ckruse** [comment]
Ich glaub, ich weiss, woran es liegt

**Comment by ckruse** [comment]
Tritt das Problem immer noch auf? Ich kann das einfach nicht nachstellen.

**Comment by auge8472** [comment]
> Tritt das Problem immer noch auf? Ich kann das einfach nicht nachstellen.

Ich gehe [auf eine Seite](http://forum.selfhtml.org/self?p=7), auf der noch alle Threads offen *und ungelesen* sind (/self?p=7) und drücke den Button "alle Threads zuklappen". Ergebnis: Ich lande auf der Seite p=0 und die Threads auf der Ursprungsseite p=7 sind nach wie vor alle offen.

Zweiter Versuch: Ich schalte das automatische Zuklappen gelesener Threads in den Benutzereinstellungen ab und benutze den Button "Alle Nachrichten als gelesen markieren", der mir tatsächlich alle Threads auf Seite p=9 als gelesen markiert. Nun drücke ich den Button "alle Threads zuklappen", lande auf Seite p=0 und stelle nach Aufruf der Seite p=9 fest, dass alle Threads nach wie vor aufgeklappt sind.

Ich hoffe, diese Schrit-für-Schritt-Anleitung hilft weiter. Zu deiner Kenntnis: Ich habe die technische Seitenzahl benutzt, deswegen auch immer das "p=" davor.

**Comment by ckruse** [comment]
Jetzt verstehe ich das Problem, dass du hast. Fixed.

**Comment by MatthiasApsel** [comment]
Ich kann das Problem noch nachstellen.

- angemeldet
- "alle zuklappen" -> alle sind zu
- einen einzelnen aufklappen
- "alle zuklappen" toggelt jetzt nur den Klapp-Status (wiederholbar)

bei "alle aufklappen" funktioniert es korrekt

**Comment by ckruse** [comment]
Bei mir gehts...?

**Comment by ckruse** [comment]
ah, jetzt, ja
