### ISSUE TITLE
Links aus dem Archiv zur Doku wurden beim Import nicht umgewandelt

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#221]
Also: Links in Beiträgen, die der Syntax für Links zur Doku folgen (`[ref:self812;`) wurden beim Import nicht wie "normale" Links umgewandelt. Als Beispiel möchte ich [dieses Posting] (http://forum.selfhtml.org/self/2008/aug/3/schriftart-fuer-spalten-definieren/1273983#m1273983) anführen, dass mir heute morgen über den Weg lief.

**Comment by ckruse** [comment]
*seufz* ich hatte sowas befürchtet.

**Comment by auge8472** [comment]
Grundsätzlich ist ja auch noch zu klären, wo der Link hinzeigen soll, falls das behoben wird. Der alte Automatismus verwies ja auf die im BB-Code angegebene Version der Doku. Da will man aber nicht mehr hinzeigen. Ob diese Seiten zudem dauerhaft erreichbar bleiben – und sei es nur zur Bereitstellung einer Weiterleitung auf das Wiki – ist ja auch eine stellenswerte Frage (@MatthiasApsel).

**Comment by MatthiasApsel** [comment]
> Ob diese Seiten zudem dauerhaft erreichbar bleiben – und
> sei es nur zur Bereitstellung einer Weiterleitung auf das Wiki – ist
> ja auch eine stellenswerte Frage (@MatthiasApsel).

Die alte Doku wird 301. Ich habe schon alle Weiterleitungen im 
.htaccess-Format fertig und an Dedlfix geschickt. Er weiß noch nicht 
ganz genau, wie er das an geschicktesten anstellt, auch wegen der 
Server.

-- 
Matthias

**Comment by ckruse** [comment]
Dann hast du ja eine Map, mit der ich das umschreiben kann?

**Comment by MatthiasApsel** [comment]
Ja, aber erst heute abend. Dedlfix ist vielleicht schneller.

**Comment by ckruse** [comment]
Schnell ist nicht nötig - das braucht eh Vorbereitung.

**Comment by ckruse** [comment]
Ich werde das auf die alten URLs weiterleiten, aus drei Gründen:

- es wäre für mich ein riesen Aufwand, die Redirects zu übertragen und die Ref-Ziele umzuschreiben. Dazu wäre es sehr fehleranfällig.
- es wäre Ressourcen-technisch eine echte Kathastrophe, die Liste bei *jedem* Posting abarbeiten zu müssen
- wir können die Rewrites so an einem Ort pflegen (nämlich in der Server-Konfiguration) und auch später noch Anpassungen vornehmen

**Comment by ckruse** [comment]
Kann bitte jemand (@auge8472 vielleich?) das Script überprüfen, bevor ich es auf das Achiv loslasse?

**Comment by auge8472** [comment]
Ich spreche zwar kein Ruby und stehe mit regulären Ausdrücken ein wenig auf Kriegsfuß, aber die beiden Blöcke, die die Links zur alten Doku betutteln (Zeilen 30-36 und 38-44), sehen korrekt aus.

Eine Frage stellt sich mir noch. Gab es diese Linksyntax für die Doku schon vor der SelfHTML-Version 8.1.2? Nicht, dass da noch weitere Fallen in den Tiefen des Archivs liegen.

**Comment by ckruse** [comment]
Nicht den Diff anschauen, das Endprodukt anschauen ;-)

    if %w(self8 self81 self811 self812 sel811 sef811 slef812).include?(ref)

Die URL (genauer: der sich ändernde Part der URL) ist bei `[ref:]` im ref enhalten. Es gab auch mal `[ref:ticket]` und `[ref:bug]` (wurde ja von der Foren-Software automagisch umgewandelt von `[link:]` in `[ref:]`), aber da die Softwares vollständig verschwunden sind aus dem Internet (`[ref:bug]` lag sogar noch bei teamone.de) wandele ich die auch nicht um.

**Comment by ckruse** [comment]
So, bitte nochmal gucken, ich hab das komplett neu geschrieben. Dedl ist gestern aufgefallen, dass man auch `]` in Titeln haben konnte (escaped mit `\`). @dedlfix @auge8472

**Comment by ckruse** [comment]
Ich habe das jetzt ganz anders gelöst. Wir importieren das Archiv gerade neu und lassen es im alten Format. Jedes Posting hat jetzt ein Flag `format`, alte Postings haben da den Wert `cforum` und es wird on the fly umgewandelt nach Markdown.
