### ISSUE TITLE
fehlerhafte Portierung

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#224]
Wenn zwischen Zitat und Antwort keine Leerzeile ist, wird die Antwort dem Zitat zugeschlagen. Siehe http://forum.selfhtml.org/meta/2015/mar/25/fehlerhafte-portierung/1635216#m1635216

**Comment by ckruse** [comment]
Das ist halt Markdown. Kann man nicht ändern.

**Comment by ckruse** [comment]
Also, das ist keine fehlerhafte Portierung, sondern die lagen so vor. Und Markdown sagt halt, dass man sowas machen darf:

~~~
> abc
 def
 ghi
~~~

**Comment by MatthiasApsel** [comment]
Das Problem ist aber, dass damit eine ganze Reihe archivierter Beiträge wertlos sind.

**Comment by ckruse** [comment]
Sei doch mal konstruktiv und schlage eine Lösung vor ;)

Man könnte willentlich gegen den Markdown-Standard verstossen in dem Fall und künstlich eine Leerzeile einfügen, wenn man dieses Konstrukt hat. Aber wie gesagt: das ist ein Verstoss gegen den Standard.

**Comment by MatthiasApsel** [comment]
> Sei doch mal konstruktiv und schlage eine Lösung vor ;)
> 
> Man könnte willentlich gegen den Markdown-Standard verstossen in dem
> Fall und künstlich eine Leerzeile einfügen, wenn man dieses Konstrukt
> hat. Aber wie gesagt: das ist ein Verstoss gegen den Standard.

In den gestern importierten Beiträgen sollte das Konstrukt
~~~
> abc
def
~~~

eigentlich immer (TM) bedeuten, dass `abc` das Zitat ist und `def` die 
Antwort. Sehe ich das richtig?

Markdown macht aber in diesen Fällen die Beiträge kaputt. Also muss man 
sich für die gestern importierten Beiträge was einfallen lassen. Da muss 
eine Leerzeile eingefügt werden, damit die Struktur des Beitrags 
erhalten bleibt.

Matthias

**Comment by ckruse** [comment]
Die importierten Beiträge nachträglich nochmal überarbeiten ist problematisch... das halte ich für keine gute Idee. Eigentlich finde ich das mit dem Einfügen einer Leerzeile ganz gut. Gibt es da, ausser "Standard!!1", einen Einwand?

**Comment by MatthiasApsel** [comment]
Am 2015-03-25 14:13, schrieb Christian Kruse:
> Die importierten Beiträge nachträglich nochmal überarbeiten ist
> problematisch... das halte ich für keine gute Idee. Eigentlich finde
> ich das mit dem Einfügen einer Leerzeile ganz gut. Gibt es da, ausser
> "Standard!!1", einen Einwand?

Der Standard ist mir Wurscht. ;-) Du willst das also jedesmal beim 
Rendern machen? Dann könnte man aber auch nicht mehr

~~~
> abc
def
~~~

schreiben, wenn man eigentlich

~~~
> abc
> def
~~~

meint.

Matthias

**Comment by MatthiasApsel** [comment]
Selbst dieses Markdown (Ansicht in Github https://github.com/ckruse/cforum/issues/224) rendert es richtig. Also muss Kramdown einen Fehler haben?

**Comment by ckruse** [comment]
Hey,

MatthiasApsel <notifications@github.com> writes:

> Der Standard ist mir Wurscht. ;-) Du willst das also jedesmal beim 
> Rendern machen? Dann könnte man aber auch nicht mehr

Ja, jedes mal beim Rendern.

> ~~~
>> abc
> def
> ~~~
>
> schreiben, wenn man eigentlich
>
> ~~~
>> abc
>> def
> ~~~
>
> meint.

Das würde mich nicht wirklich interessieren… ;)

LG,

-- 
Christian Kruse
http://ck.kennt-wayne.de/

**Comment by ckruse** [comment]
> Selbst dieses Markdown (Ansicht in Github https://github.com/ckruse/cforum/issues/224) rendert es richtig. Also muss Kramdown einen Fehler haben?

Emails laufen nicht durch den Markdown-Parser bei Github, die haben da
einen eigenen E-Mail-Parser (sichtbar z.B. daran, dass die ~~~ ignoriert
werden). Kramdown ist da korrekt.


-- 
Christian Kruse
http://ck.kennt-wayne.de/

**Comment by MatthiasApsel** [comment]
GitHub auch, wenn man es direkt hier reinschreibt. Ich bin für die zusätzliche Leerzeile.

**Comment by ckruse** [comment]
> test
test

Ne, das stimmt nicht. Die machen das genau so.

**Comment by ckruse** [comment]
Egal. Wir machen das mit der automagischen Leerzeile.

**Comment by MatthiasApsel** [comment]
>> Kramdown ist da korrekt.

> GitHub auch.

;-)

**Comment by ckruse** [comment]
Ach sorum.

**Comment by ckruse** [comment]
Da muss ich nochmal dran. So ist es auch scheisse.

**Comment by MatthiasApsel** [comment]
Ich denke, so richtig richtig ists immer noch nicht. siehe zum Beispiel hier: 
- [1635572#m1635572](http://forum.selfhtml.org/self/2015/mar/26/zellen-und-zeilen-einer-tabelle-ausblenden/1635572#m1635572) weniger schlimm, Lücken zwischen zusammenhängenden Zitaten
- [1635553#m1635553](http://forum.selfhtml.org/self/2015/mar/26/zellen-und-zeilen-einer-tabelle-ausblenden/1635553#m1635553) schlimmer mehrfache pre-Elemente
