### ISSUE TITLE
automatischer Reload für angemeldete Nutzer

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#225]
Featurerequest: angemeldete Benutzer sollen einen automatischen Reload der Hauptseite und/oder der Übersichtseite eines Forums einschalten können. Dabei ist es mMn ausreichend, von der Anbieterseite einen Rhythmus vorzugeben (z.B. alle 20 oder 30 Minuten).

**Comment by MatthiasApsel** [comment]
Ja, das hatten wir gestern auch schon auf dem Schirm.

**Comment by ckruse** [comment]
Eigentlich wollte ich das nicht mehr implementieren, da mir da eher sowas wie das automatische aktualisieren der Hauptdatei via JS vorschwegt. Aber nun gut, es ist ja wenig Arbeit.
