### ISSUE TITLE
mehrere erhaltene Bewertungen eines Postings zusammenfassen

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#226]
Ich habe mittlerweile ein Posting, dass zweimal bewertet wurde. In meinem Profil wird dieses Posting in der Liste der erhaltenen Bewertungen auch zweimal mit jeweils 10 Punkten statt ein mal mit 20 Punkten aufgeführt.

**Comment by ckruse** [comment]
Das ist eigentlich so gewollt. Ist da wirklich ein Bedürnis, das
zusammen zu fassen?


-- 
Christian Kruse
http://ck.kennt-wayne.de/

**Comment by auge8472** [comment]
> Das ist eigentlich so gewollt. Ist da wirklich ein Bedürnis, das zusammen zu fassen?

Ich sag mal so, ich sehe (bis jetzt) keinen nachvollziehbaren Grund, die Bewertungen einzeln aufzuführen. Wenn es den gibt, soll es so sein.

**Comment by ckruse** [comment]
Der Grund ist, dass so einfacher nachvollziehbar ist was genau bewertet wurde. Was sagen denn die anderen dazu? @MatthiasApsel @dedlfix

**Comment by dedlfix** [comment]
Solange nicht dabeisteht, wer das bewertet hat, sind mehrfache Zeilen nicht weiter informativ. +1 für GroupBy

**Comment by ckruse** [comment]
> Solange nicht dabeisteht, wer das bewertet hat, sind mehrfache Zeilen nicht weiter informativ. +1 für GroupBy
Wer da bewertet hat wird so schnell nicht dabei stehen ;) Das sorgt zu
schnell für soziale Spannungen.

**Comment by MatthiasApsel** [comment]
Am 2015-03-25 22:27, schrieb Christian Kruse:
> Der Grund ist, dass so einfacher nachvollziehbar ist was genau
> bewertet wurde. Was sagen denn die anderen dazu? @MatthiasApsel
> @dedlfix

Ich würde die einzelnen Bewertungszahlen in eine gemeinsame 
Tabellenspalte stecken. So gibt es nicht mehrere Zeilen.

Matthias

**Comment by ckruse** [comment]
Gute Idee, hab ich jetzt zo implementiert
