### ISSUE TITLE
Tags werden grundsätzlich kleingeschrieben

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#229]
Ich habe im internen Forum den Tag "Moderation" angelegt, er wird als "moderation" gespeichert, auch eine Änderung in "Moderation" wird nicht übernommen.

**Comment by ckruse** [comment]
Working as intended, ich lasse da ein downcase drüberlaufen.

**Comment by MatthiasApsel** [comment]
Hm. Vielleicht steht es uns besser zu Gesicht, die deutsche Rechtschreibung zu berücksichtigen.

**Comment by ckruse** [comment]
Sehe ich anders, kann aber bedenken nachvollziehen.
