### ISSUE TITLE
Dokumentation zu Markdown bei der Textarea verlinken

### ISSUE THREAD

**Issue by ckruse** [ckruse/cforum#230]

**Comment by dedlfix** [comment]
Dazu fällt mir nochwas ein: Ein Feld in den Einstellungen des Forums (oder auch generell) hinzufügen, in das man als Admin eine Anleitung zu den wichtigsten Syntaxelemente eintragen kann (in Markdown-Syntax). Diesen Inhalt dann unter der Antwort-Textarea anzeigen. (Am besten vom Nutzer in seinen Einstellungen ausblendbar. Default: On)

**Comment by ckruse** [comment]
Bitte?

**Comment by dedlfix** [comment]
Im WIki haben wir unter dem Eingabefeld beim Bearbeiten solch eine Box "Beispiele Wiki-Syntax:" Sowas ist vielleicht auch für das Forum gut.

**Comment by MatthiasApsel** [comment]
Ich möchte hier gern ein wenig drängeln: Zunächst sollte es einen Hilfe-Button geben, innerhalb des Elementes `<div class='md-header' >` besser vielleicht als Link. Die zu verlinkenden Ressourcen sollten deutschsprachig sein. 

- https://wiki.selfhtml.org/wiki/SELFHTML:Forum/Bedienung
- http://markdown.de/syntax/index.html

Ich würde mich auf die Wiki-Seite beschränken, dort gibt es auch einen Link zur 2. genannten Seite.

**Comment by MatthiasApsel** [comment]
Dieser Link sollte zwischen Button-Leiste und Textarea. Da der ganze Bereich mit JS erzeugt wird (ich hatte dir schon mal einen Pullrequest geschickt) muss man den wohl auch mit JS erzeugen. Um Leuten ohne JS trotzdem diesen Hinweis zu geben, sollte der jetzige Hinweis bleiben und bei aktiviertem JavaScript entweder ausgeblendet oder entfernt werden.
