### ISSUE TITLE
"Thread als gelesen markieren" in "alle Foren" lädt "SELFHTML-Forum"

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#234]
Wenn ich einen Thread in der Übersichtsseite "alle Foren" über das Häkchen als vollständig gelesen markiere, wird danach die Übersichtsseite des Unterforums "SELFHTML-Forum" geladen.

**Comment by ckruse** [comment]
Da muss ich mir echt noch was einfallen lassen...

**Comment by auge8472** [comment]
Die Ursache liegt ja im Aufbau der URL. Z.B.

http://example.org/self/2015/mar/26/foo-bar/mark_read

Mit der Angabe **self** wird das Forum benannt, in dem sich der Thread befindet, ohne darauf Rücksicht zu nehmen, in welcher Forenauswahl sich der Benutzer mit seiner aktuellen Ansicht befindet. So weit, so bekannt, denke ich mal.

Zusätzlich interessant wird es, wenn ich mich auf einer der weiter hinten liegenden Seiten befinde. Dann könnte der Link so aussehen:

http://example.org/self/2015/mar/26/foo-bar/mark_read?p=9

Auf der neunten Seite von **all** (wo ich mich gerade befinde) finde ich mit großer Wahrscheinlichkeit andere Threads als auf der neuten Seite von **self** (wohin ich weitergeleitet werde). Das kann bei unachtsamen Benutzern zu einiger Verwirrung führen.

**Comment by ckruse** [comment]
Ja, der Grund ist mir bekannt, aber ich bin mir noch nicht so sicher wie ich das verhindern will ;)
