### ISSUE TITLE
Bei "Flattr this" hinweisen, wer das Ziel ist.

### ISSUE THREAD

**Issue by dedlfix** [ckruse/cforum#235]
Das "Flattr this!" steht nun einfach so unter dem Posting, zum Beispiel beim denen von auge. Mir fällt aber grad nicht ein, wie man das am besten formuliert, dass der Autor (und nicht das Projekt) belohnt wird.

(Den) Autor belohnen: Flattr this!
Dem Autor danken: Flattr this!

**Comment by ckruse** [comment]
Was hälst du davon, das im Title zu verstecken?

**Comment by dedlfix** [comment]
Nicht viel. Da ist doch genügend Platz in der Zeile.
Und Hover gibts auch nicht überall.`</bittersmann>`

**Comment by MatthiasApsel** [comment]
Für title trifft das auch deutlich mehr zu als für hover.
