### ISSUE TITLE
Todo: Defaultwerte bei Einstellungsseiten anzeigen

### ISSUE THREAD

**Issue by dedlfix** [ckruse/cforum#237]
Überall wo man Einstellungen vornehmen kann, sollten die übergeordneten oder Default-Werte angezeigt werden. Also neben den Forumseinstellungen sollten die globalen Einstellungen zu sehen sein oder ein Defaultwert, wenn da auch festgelegt wurde.

**Comment by ckruse** [comment]
Das ist problematisch, deshalb hab ich sie auch weg gelassen: wenn man die Default-Werte da einträgt, dann wird bei einer Änderung der Wert gespeichert und überschreibt ggfls einen globalen Wert.

**Comment by dedlfix** [comment]
Ich dachte an hinter das Eingabefeld als Text.

**Comment by MatthiasApsel** [comment]
Unbedingt.

**Comment by ckruse** [comment]
oh, schon lange implementiert

**Comment by MatthiasApsel** [comment]
Ich hatte an anderer Stelle schon mal geschrieben, dass mir das nicht weit genug geht. Wahrscheinlich per Mail, da ich es hier nicht finde. 

Es sollte notiert werden, ob das ein ererbter Wert ist oder ob das default in dieser Ebene selbst festgelegt wurde.
