### ISSUE TITLE
unter jedem Beitrag Links auf Hauptseite, forum/all und aktuelles Forum

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#238]
Ein Link zu forum/all erscheint mir sinnvoll

**Comment by ckruse** [comment]
Mir ist die Region ehrlich gesagt aktuell viel zu voll, das sollten wir erst zu 4.1 angehen, wenn wir die Region etwas aufgeräumt haben.

**Comment by MatthiasApsel** [comment]
Das ist eigentlich die Region mit dem meisten Platz ;-) Vergleiche http://selfhtml.apsel-mv.de/CForum/thread2.html 

'Hauptseite' 'alle Foren' 'Meta-Forum' wären die Links für die allgemeine Ansicht.

**Comment by ckruse** [comment]
Ach da meinst du.
