### ISSUE TITLE
Im Nachrichten-Modul wird der Kommunikationspartner fehlerhaft angezeigt

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#239]
Es wird immer der Autor des Postings angezeigt in "Kommunikation mit $autor" Es muss aber ggf. auch der Empfänger sein. Heißt, wenn ich meine eigene Mail lese, sehe ich "Kommunikation mit MAtthias Apsel"

**Comment by ckruse** [comment]
Ach, du meinst in der Ansicht einer einzelnen PM. Ja, guter Einwand.
