### ISSUE TITLE
für die Benutzer einstellbar machen, ob Links in einem neuen Tab geöffnet werden sollen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#240]

**Comment by ckruse** [comment]
Dafür ist STRG+Click gut? Vor allem weil ich ja eh nicht in einem neuen Tab öffnen kann, sondern höchstens mit `target="_blank"` oder so.

**Comment by MatthiasApsel** [comment]
Ja, ich empfand das im alten Forum jedoch als angenehm, für mich target=_blank eingestellt zu haben.

**Comment by ckruse** [comment]
Das sollte nur für "neuen Beitrag erstellen", die Links in der Thread-Liste und die Antwort-Buttons gelten, richtig?

**Comment by MatthiasApsel** [comment]
Im alten Forum galt es für alle ...

**Comment by ckruse** [comment]
Das hab ich nicht gefragt *g*

**Comment by MatthiasApsel** [comment]
Ich habe es als angenehm empfunden, dass es für alle Links galt ...

**Comment by MatthiasApsel** [comment]
Ich weiß, danach hast du auch nicht gefragt. ;-) Aber wenn du schon fragst:

~~~
Links automatsch in neuem Tab/Fenster öffnen
   [ ] Links in Beiträgen 
   [ ] Links zur Bedienung des Forums
~~~

Aber ich kann mir auch ein User-JS schreiben.

**Comment by ckruse** [comment]
Hm, macht Sinn.

Am sinnvollsten überschreibe ich einfach `link_to` und die Kramdown-Funktion, es sollten dann nur keine Links mehr händisch gemacht werden ;-)
