### ISSUE TITLE
Navigation anpassen - zunächst für Anmeldung

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#241]
Da müssen wir insgesamt noch mal schauen, was man kürzen oder wo anders hin verschieben kann.

Auf den Seiten http://forum.selfhtml.org/users/registration sowie http://forum.selfhtml.org/users/login lässt sich wohl auf die Buttons "PW vergessen" und "Bestätigung" verzichten.

"PW vergessen" steht jetzt beim Input-Feld, was ich sehr gut finde. Die ganze Bestätigungsseite finde ich überflüssig. Sie macht doch nichts anderes, als dieselbe Mail wie auch bei "PW vergessen" zu versenden - oder sehe ich das falsch?

**Comment by ckruse** [comment]
Ich sehe das völlig anders, sorry.

Während ich die Argumentation für den Vergessen-Link nachvollziehen kann, auch wenn ich es anders sehe, ist das mit der Bestätigung eine völlig andere Funktion. Das ist für Benutzer-Registrierungen, die nicht bestätigt wurden, kann ja z.B. sein, dass ein User die E-Mail verliert.

**Comment by MatthiasApsel** [comment]
>  kann ja z.B. sein, dass ein User die E-Mail verliert.

Und wie gehts dann für den Nutzer weiter?

**Comment by ckruse** [comment]
Er bekommt ein neues Confirmation-Token zugeschickt. Das ist *nicht das
gleiche* wie das „Passwort vergessen“-Token.

**Comment by MatthiasApsel** [comment]
Ah.

Also der Fall, dass die E-Mail nicht ankommt oder im Spamordner landet. 
Das hat natürlich seine Berechtigung.

Es fehlt dann auf der Seite:

Bestätigungsanweisungen erneut senden

"Bitte prüfen Sie zunächst Ihren Spamordner." oder ähnlich.
