### ISSUE TITLE
Edit-Diffs speichern

### ISSUE THREAD

**Issue by ckruse** [ckruse/cforum#244]
Diffs zu Edits sollten angezeigt werden können, so dass Änderungen nachvollziehbar sind

**Comment by MatthiasApsel** [comment]
Eigentlich nicht zwingend, da wir ja nur dann editieren zulassen, wenn noch keine Antwort geschrieben wurde. Und das Recht, Beiträge zu editieren zu denen es schon eine Antwort gibt, sollten tatsächlich nur Admins haben.

**Comment by auge8472** [comment]
Dennoch ist, auch aus juristischen Gründen, die Nachvollziehbarkeit von Änderungen sinnvoll (auch wenn das arg konstruiert wirken mag).

**Comment by ckruse** [comment]
Ausserdem hab ich bock das zu bauen ;)
