### ISSUE TITLE
ungelesen Markierung für startposting

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#247]
Wir sollten uns überlegen, ob die ungelesen-Markierung im Startposting 
* für den gesamten Thread (mein Favorit)
* nur für das Startposting (derzeit)

gelten soll

**Comment by MatthiasApsel** [comment]
Für meinen Favoriten spricht zudem, dass sich der Link in einem span "thread-icons" befindet, gemeinsam mit anderen, die auch Auswirkungen auf den gesamten Thread haben.

**Comment by ckruse** [comment]
Dann sollte es eher zwei Varianten geben, eine die sich auf den ganzen Thread auswirkt und rechts ist und eine, die sich auf die Nachricht auswirkt und links ist.

**Comment by ckruse** [comment]
Invalid da Feature enfernt
