### ISSUE TITLE
CSS und JavaScript als Einstellungen für das Forum

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#248]
Es sollte zusätzliches CSS und JavaScript unabhängig vom Template für jedes Unterforum einzeln eingebunden werden können.

**Comment by ckruse** [comment]
Nein, das sehe ich nicht so. Stattdessen sollten die einzelnen Foren besser eine Unterscheidbarkeit anhand einer ID oder so bekommen, so dass man im CSS/JS darauf agieren kann.

**Comment by MatthiasApsel** [comment]
Die Betreiber sollten die Möglichkeit haben, einzelne Foren anders zu formatieren, ohne dass dazu die "globale" CSS- oder JS- Ressource angefasst werden muss. 

Also sowas wie ein User-CSS nur halt auf Foren-ebene.
