### ISSUE TITLE
Akzeptierte Antwort als solche kennzeichnen

### ISSUE THREAD

**Issue by dedlfix** [ckruse/cforum#250]
Akzeptierte Antworten stehen direkt unter dem OP, sind aber nicht direkt als solche ersichtlich. Es steht erst unter der Antwort, dass sie eine solche ist. Mein Vorschlag: den Text "Akzeptierte Antwort" nach oberhalb der Antwort verlegen und zwischen Frage und Antwort eine optische Trennung einfügen, beispielsweise `<hr>`.

**Comment by auge8472** [comment]
Meiner Meinung nach ist auch die Verkleinerung der Schriftgröße kontraproduktiv. Die gilt offensichtlich für den ganzen Block der akzeptieren Antwort. Für mich persönlich (das ist natürlich der persönliche Eindruck) ist die gewählte Schriftgröße grenzwertig. Eine Hervorhebung durch Rahmen und/oder Farben bei "normaler" Schriftgröße neben dedlfix' Ansinnen halte ich für sinnvoller.

**Comment by MatthiasApsel** [comment]
Ja, da muss noch was gemacht werden. Die Schriftgröße ist, denke ich ein Versehen, weil dieser article in die Klasse .message-links geraten ist. Ich hab mal temporär was geschraubt. Das wäre doch ein Fall für ![Stern](//src.selfhtml.org/forum/fachlich-hilfreich-32.png)?

**Comment by MatthiasApsel** [comment]
Vergleiche: http://forum.selfhtml.org/meta/2015/apr/03/akzeptierte-antwort-gilt-da-das-highlander-prinzip/1636281#m1636281 Wenn man dies berücksichtigen möchte, dann könnte unterhalb der Frage eine Liste mit Verweisen zu akzeptierten Antworten stehen.

**Comment by ckruse** [comment]
Fixed
