### ISSUE TITLE
reopen leerzeilen zwischen Zitat und Text

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#251]
Es ist immer noch nicht ganz in Ordnung, jetzt bei zitierten Zitaten siehe http://forum.selfhtml.org/meta/2015/mar/27/kann-die-sortierungsregeln-nicht-nachvollziehen-punkt-punkt-punkt/1635693#m1635693

**Comment by MatthiasApsel** [comment]
Und auch dies hier http://forum.selfhtml.org/meta/2015/mar/28/bewertungen/1635734#m1635734 hängt wahrscheinlich damit zusammen.

**Comment by MatthiasApsel** [comment]
Und auch hier: http://forum.selfhtml.org/self/2002/nov/30/noch-ne-frage/315563#m315563

**Comment by ckruse** [comment]
Oh je, ich dachte, ich hätte das gefixed, aber gerade ist es noch kaputter als vorher...
