### ISSUE TITLE
Administrations-Icons

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#253]
Die Icons zum "persönlichen Komfort" sollten in der Admin-Ansicht nicht auftauchen.

Also in der Admin-Ansicht nur
* Beitrag löschen / wiederherstellen
* Antworten verbieten / erlauben
* Thread verschieben
* Thread anpinnen
* Thread nicht archivieren

**Comment by ckruse** [comment]
Warum?

**Comment by MatthiasApsel** [comment]
Um admin- und normale Ansicht deutlich von einander zu trennen.
