### ISSUE TITLE
korrekte Formulierungen bei Numeralen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#255]
Ich weiß, das ist aufwändig, aber derzeit heißt es beispielsweise:

`1 Bewertungen`

das sollte so nicht sein. Das ist bei den Bewertungen leicht aber unschön zu korrigieren:

`1 Bewertung(en)`

aber bei Beitrag/Beiträgen geht das nicht.

**Comment by dedlfix** [comment]
Das Thema Pluralisierung ist in der Softwarewelt nicht unbekannt. In einigen Sprachen ist es sogar von der Menge abhängig, welchen Plural man nehmen muss. Meist ist das Problem in Frameworks schon zur allgemeinen Zufriedenheit gelöst. Man muss es nur noch einsetzen und bekommt dann eine ordentliche Sprache ohne solche Behelfslösung(en).

**Comment by MatthiasApsel** [comment]
Ich wollte auch nicht die Behelflösung(en) favorisieren. Im alten Forum habe ich dafür viele ifs und elses verwenden müssen.

**Comment by ckruse** [comment]
Am besten wäre eine vollständige Auflistung, wo das relevant ist...

**Comment by MatthiasApsel** [comment]
- new_notifications: "%{num} neue Benachrichtigungen"
- messages_threads: "Es gibt {{messages}} neue Nachrichten und {{threads}} neue Threads."
admin.de.yml/users
- error_message: "%{errors_count} verhinderten, dass dieser Benutzer gespeichert werden konnte:"
admin.de.yml/groups
- error_message: "Fehler verhinderten, dass diese Gruppe gespeichert werden konnte:" (Fehlt hier die Fehleranzahl?)
bei badges gibt es zweimal edit?
mails.de.yml
- error_message: "Fehler verhinderten, dass diese Nachricht gespeichert werden konnte:" (Fehlt hier die Fehleranzahl?)
- new_mails_num: "%{num} neue Nachrichten"
messages.de.yml
- num_messages: "%{num} Beiträge"
- error_message: "%{errors_count} verhinderten, dass dieser Beitrag gespeichert werden konnte:"
- invalid_tags: "Sie dürfen keine neuen Tags erstellen und diese Tags existieren bisher nicht: %{tags}." (Es kann ja auch nur ein nicht existierendes Tag sein)
- votes: "%{num} Bewertungen"
- error_message: "%{errors_count} verhinderten, dass diese Sperr-Abstimmung gespeichert werden konnte:"
