### ISSUE TITLE
Bei Bedienung von "Thread als gelesen markieren" beim Thread bleiben

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#258]
Wenn ich auf den Link “Thread als gelesen markieren” auf der Hauptseite klicke, komme ich wieder ganz nach oben auf die Seite. Ich würde aber lieber beim Thread selbst bleiben, weil ich den vermutlich deswegen markiert habe, weil ich alle “dort unten” markieren will.

Der article, wo ich hin will, hat sogar eine passende ID, die man einfach als Hash in die URL packen könnte.

http://forum.selfhtml.org/meta/2015/mar/28/bei-bedienung-von-thread-als-gelesen-markieren-beim-thread-bleiben/1635740#m1635740

**Comment by ckruse** [comment]
Hm. Ich habe das etwas anders gelöst, aber ich befürchte, da muss ich nochmal ran.
