### ISSUE TITLE
Im Threadbaum zwischen Posting und Antwortfeld fehlen Klassen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#261]
zum Beispiel die für hervorgehobene Nutzer

**Comment by dedlfix** [comment]
Generell könnten mehr Selektoren eingebaut werden. Ich hab mich teilweise an data-Attributen orientieren müssen, weil es kaum andere Erkennungsmerkmale für Seiten und Bereiche in ihnen gibt.

**Comment by ckruse** [comment]
Fixed. Ich mache aus dem zweiten Teil mal ein neues Issue. Es wäre nett, wenn du das etwas weiter ausführen könntest, @dedlfix. Siehe #289
