### ISSUE TITLE
Hinweis an bisheriger Stelle unterbringen, wenn ein Thread verschoben wurde.

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#263]
Das kann ein article-Elemente der Klasse thread sein, das einen close-button bekommt, alternativ könnte dieser Hinweis für einen angemeldetern Nutzer auch verschwinden, sobald dieser die Nachricht am neuen Ort öffnet.

**Comment by ckruse** [comment]
Das führt doch den Sinn einer Verschiebung ad absurdum. Man will es doch gerade nicht mehr in dem Forum haben.

**Comment by MatthiasApsel** [comment]
Wenn ich aber den Thread beobachte oder aktiv in diesem Thread war, würde ich mich schon wundern, wo der Thread hin ist. Manchmal werden threads ja auch gelöscht. Man kann die Benachrichtigung ja auf diejenigen beschränken, die in diesem Thread gepostet haben. Eine Benachrichtigung an die Beteiligten würde vielleicht auch reichen.

**Comment by ckruse** [comment]
Eine Notification macht mehr Sinn, ja

Am 4. April 2015 21:36:08 MESZ, schrieb MatthiasApsel <notifications@github.com>:
>Wenn ich aber den Thread beobachte oder aktiv in diesem Thread war,
>würde ich mich schon wundern, wo der Thread hin ist. Manchmal werden
>threads ja auch gelöscht. Man kann die Benachrichtigung ja auf
>diejenigen beschränken, die in diesem Thread gepostet haben. Eine
>Benachrichtigung an die Beteiligten würde vielleicht auch reichen.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ckruse/cforum/issues/263#issuecomment-89646483

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by MatthiasApsel** [comment]
Ist das schon online?

**Comment by ckruse** [comment]
Nein.

**Comment by ckruse** [comment]
Jetzt schon. Aber man muss es aktivieren, in den Nutzer-Einstellungen

**Comment by MatthiasApsel** [comment]
Wenn der Beitrag in ein nicht erreichbares Forum verschoben wurde ist ja für den Nutzer identisch mit Löschen. Dann soll es keinen Hinweis geben.

**Comment by ckruse** [comment]
Fixed.
