### ISSUE TITLE
Markieren-Recht aufdröseln

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#264]
Die Möglichkeit auf strafrechtlich relevanten Inhalt oder UR-Verstöße hinzuweisen, sollte jeder haben.

**Comment by ckruse** [comment]
Dann können wir den Badge auch abschaffen.

**Comment by MatthiasApsel** [comment]
Ich hab jetzt mal einen Beitrag im internen Forum geflagt. Was kann ich als Admin dann damit machen? Entflagen offenbar nicht. Da sollte noch der Hinweis hin, dass die Mitteilung anonym erfolgt.

Die 4 jetzt genannten Sperrgründe (die einfach nur Grund heißen sollten) sollten erst bei einer bestimmten Punktzahl erreicht werden können. Verstöße gegen das Urheberrecht oder strafrechtlich relevantes steht da übrigens nicht dabei, sondern nur bei "Sperrabstimmung erstellen" Darüber sollte man nicht abstimmen.

**Comment by ckruse** [comment]
Das Flaggen ist nur Aufmerksamkeit erregen. Das Posting kriegt ne Klasse und du kriegst ne Notification.

**Comment by MatthiasApsel** [comment]
Aber ein admin kann das Flag nicht wieder entfernen? Oder ist das so gewollt? Einmal Aufmerksamkeit erregt reicht. Das würde bedeuten, dass man jeden Beitrag höchstens einmal flagen kann.

**Comment by dedlfix** [comment]
Ich bekam zwar erzählt, dass meine Aufmerksamkeit erforderlich sei, aber was ich mir da anschauen soll, stand nicht dabei, weder in der Nachricht, noch konnte ich was im Posting entdecken.

**Comment by MatthiasApsel** [comment]
Und konntest du das Flag entfernen?

**Comment by ckruse** [comment]
Man kann aktuell nicht „entflaggen,” nein

**Comment by ckruse** [comment]
So, jetzt dürfen alle User (auch die anonymen) einen Beitrag flaggen. Ein Mod bekommt unter der Nachricht einen Hinweis angezeigt. Ein Mod kann das Flag entfernen.

**Comment by ckruse** [comment]
(Hab nur gerad kein Internet und kann deshalb nix hochladen)

**Comment by ckruse** [comment]
Ist online.
