### ISSUE TITLE
Cookie für Cookie-Erlaubnis

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#265]
Da bereits beim ersten Kontakt Cookies setzen, sollte eine Leiste oben eingeblendet werden: "Cookies helfen uns bei der Bereitstellung unserer Dienste. Durch die Nutzung unserer Dienste erklären Sie sich damit einverstanden, dass wir Cookies setzen. [mehr erfahren] [ok]"

Dieser Cookie könnte ein Jahr Gültigkeit haben und bei jedem Besuch erneuert werden,

**Comment by ckruse** [comment]
Ich habe ehrlich gesagt ein Problem damit, das einzubauen. Lt unseres RA ist das aktuell nicht nötig, da reicht die Datenschutzerklärung. Ich wurde das ungern einbauen, vorauseilender Gehorsam stinkt mir.

**Comment by MatthiasApsel** [comment]
ok
