### ISSUE TITLE
Wenn ein Beitrag gelöscht wurde, soll an Admins eine Benachrichtigung gehen ...

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#266]
... "Damit diese bei einer Spammwelle generelle Maßnahmen ergreifen können" [(Dedlfix)](http://forum.selfhtml.org/intern/2015/mar/30/weiteres-forum-fuer-geloeschte-threads/1635875#m1635875)

**Comment by ckruse** [comment]
Inwiefern? Wie ist das gemeint?

**Comment by dedlfix** [comment]
Ich hab keine Übersicht, was sich so an ungewünschten Dingen im Forum abspielen, wenn ich nicht in die Administrator-Ansicht wechsle. Entweder eine Benachrichtigung oder eine Ansicht wäre gut, in der Thread mit gelöschten Nachrichten aufgelistet werden.

**Comment by ckruse** [comment]
Hm. Ok. Nachvollziehbar.

**Comment by MatthiasApsel** [comment]
Quasi eine Seite "letzte Änderungen". Dedlfix hatte das an anderer Stelle schon mal vorgeschlagen. Bleibt nur die Frage, was da rein soll:
- Löschung von Beiträgen
- no-archive von Threads
- Hochladen von Bildern
- Löschen von Bildern
- Flaggen von Beiträgen (?)
- Neuanmeldung (nice to have)
- Löschung von Benutzerkonten (nice to have)

**Comment by ckruse** [comment]
Ich hab mal ein Beispiel implementiert, erreichbar unter `/notifications/last-changes` (aber noch nicht verlinkt). Meinungen? Bisher sind das alles nur Informationen, die Admins interessieren, der Mehrwert für den User fehlt noch...
