### ISSUE TITLE
Umwandlung der Codeblöcke von Markdown nach HTML in Zitaten kaputt

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#267]
Die Markierung von Codeblöcken (drei Tilden) wird in Zitaten (mit vorangestellter Klammer) nicht nach HTML umgewandelt. Werden die Zitatzeichen händisch entfernt (aus der Codeblockmarkierung und dem Codeblock selbst), wird in der Ausgabe auch wieder ein Codeblock gerendert.

**Comment by MatthiasApsel** [comment]
Ja, das passt zu [issue 251](https://github.com/ckruse/cforum/issues/251)

**Comment by ckruse** [comment]
Fixed
