### ISSUE TITLE
CSS für :visited spezifischer machen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#269]
Und ebenso Links in Beiträgen unterstreichen? Die Kritik war berechtigt.

**Comment by dedlfix** [comment]
Vorab gibts eine Regel in der test.css

**Comment by MatthiasApsel** [comment]
Hast du schon oder soll ich?

**Comment by dedlfix** [comment]
War schon längst drin. Jetzt gibts sie zweimal. Meine steht oben als zweites.

**Comment by MatthiasApsel** [comment]
War ich blind?
