### ISSUE TITLE
Frage zu verschobenen Threads

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#270]
Ist ein Beitrag, der verschoben wird, auch noch unter der alten URL erreichbar?

Das wäre klug.

**Comment by ckruse** [comment]
Nein, ist er nicht. Verschieben bedeutet einfach nur, dass die `forum_id` geändert wird.

**Comment by ckruse** [comment]
Aber ja, es wäre sinnvoll.

**Comment by MatthiasApsel** [comment]
Eine 301 würde ja reichen.

**Comment by ckruse** [comment]
Jup, das schwebte mir im Sinn.
