### ISSUE TITLE
Frage maximale Anzahl von Nachrichten pro Thread

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#271]
Was passiert, wenn die Anzahl erreicht wird? der erste Thread ist gleich so weit.

**Comment by auge8472** [comment]
Warum gibt es diese Beschränkung überhaupt, wenn es sie denn gibt?

**Comment by MatthiasApsel** [comment]
Es gibt sie, warum weiß ich nicht.

**Comment by dedlfix** [comment]
Es war bereits passiert. Mit genau dem Thread. Der musste aus dem Archiv zurückgeholt werden. Und dann hat man den Wert hochgesetzt. Ich hab mal die Grenze noch weiter auf 500 angehoben.

**Comment by ckruse** [comment]
Diese Funktion gibt es, weil es Threads wie den legendären [Test - bitte ignorieren!](http://forum.selfhtml.org/meta/2001/may/28/test-bitte-ignorieren/123212#m123212)-Thread gab, der dazu geführt hat, dass die gesamte Hauptseite nur noch aus einem Thread bestand. Irgendwann wurde er dann händisch archiviert, und mit Einführung des CForums gab es dann eine Begrenzung, die zur Zwangs-Archivierung geführt hat.
