### ISSUE TITLE
 fa-repeat ist besser geeignet für ungelesen markieren

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#273]
http://fortawesome.github.io/Font-Awesome/icon/repeat/?

**Comment by MatthiasApsel** [comment]
Oder auch http://forum.selfhtml.org/meta/2015/mar/24/umstellung-auf-classic-forum-4-punkt-0/1636005#m1636005

**Comment by MatthiasApsel** [comment]
Vorläufig das durchgestrichene Auge.

**Comment by ckruse** [comment]
Fixed
