### ISSUE TITLE
Default-Werte und Checkboxen

### ISSUE THREAD

**Issue by dedlfix** [ckruse/cforum#274]
Wenn per Default-Konfiguration beispielsweise "Archiv nutzen" aktiviert ist, wie kann man das dann für ein Forum aufheben? Die Checkbox leer zu lassen bedeutet ja Default-Wert verwenden. Oder ändert sich das, wenn man es einmal anhakt und dann wieder abhakt zu einem individuellen "nein"?

Vielleicht sollte man sowas zu einer ja/nein/default-Radiogruppe ändern.

**Comment by MatthiasApsel** [comment]
Ich hab auch keinen Plan, wie das passiert ist. Btw. Was passiert, wenn $anzthreads > $maxthreads ist und das Archiv nicht genutzt werden soll?

**Comment by MatthiasApsel** [comment]
Das betrifft jetzt bestimmt auch die Editiermöglichkeit. Die aktuell verwendete Einstellung sollte auch dahinter stehen und woher sie kommt falls es nicht die Einstellung für ein einzelnes Forum ist.
* maximale Anzahl von Threads: 200 (globale Einstellung)
* maximale Anzahl von Beiträgen: 500 (default)

**Comment by ckruse** [comment]
Fixed
