### ISSUE TITLE
Bug: gelöschte Beiträge werden in der Sortierung berücksichtigt

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#275]
Es gibt zwei archivierte Threads, auf die geantwortet wurde http://forum.selfhtml.org/meta/2008/mar/17/probleme-mit-dem-posten-unter-dem-eigenen-namen/1224513#m1224513 und http://forum.selfhtml.org/self/2011/jul/30/typumwandlung-2-x-16-bit-word-zu-1-x-32-bit-fliesskomma/1518659#m1518659 In beiden habe ich die "neuen" Beiträge gelöscht, trotzdem werden sie bei der Sortierung nach jüngstem Posting berücksichtigt.

**Comment by ckruse** [comment]
Hm, ja. Das stimmt.
