### ISSUE TITLE
Frage: Wie weit treiben wir die CSS-mäßige Unterstützung von Kramdown

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#276]
Sollten etwa Überschriften, die man mit === bzw. --- machen kann tatsächlich als Überschriften dargestellt werden?

**Comment by ckruse** [comment]
Ich verstehe die Frage nicht so richtig. Wir haben `h3`-`h6` in den Beiträgen (bzw `hX`-`h6`, das ist Konfigurations-Sache). Warum sollten wir die nicht unterstützen?

**Comment by MatthiasApsel** [comment]
Ich habe nichts dagegen. Aber man braucht ja eine `.posting-content h3` nicht mit einer Schriftgröße von 2em zu formatieren.

Im Moment gibt es allerdings noch kein gesondertes CSS dafür.

**Comment by ckruse** [comment]
naja, du siehst ja was hier los ist... ;) tu dir also keinen Zwang an!

**Comment by MatthiasApsel** [comment]
Mach da mal lieber eine 4.1 draus, das Abitur steht vor der Tür.

**Comment by ckruse** [comment]
Das ist dann ja erledigt? :)

**Comment by MatthiasApsel** [comment]
Ja.
