### ISSUE TITLE
Bug: Man kann seine eigene Antwort akzeptieren und erhält dafür Punkte

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#277]
Das sollte nicht sein. Ersteres ist ja vielleicht sinnvoll, weil sich der TO die Mühe macht, mehrere Antworten zusammenzufassen, aber Auswirkungen auf die Bewertungen sollte das nicht haben.

**Comment by MatthiasApsel** [comment]
http://forum.selfhtml.org/users/3902 hat etwa 15 Punkte (von einer selbstakzeptierten Antwort) aber "bisher keine bewerteten Beiträge"

**Comment by ckruse** [comment]
Das ist eigentlich durchaus Absicht, Q/A-Style. Das mehrt das Wissen und sollte belohnt werden.

**Comment by ckruse** [comment]
Kein Einwand?

**Comment by MatthiasApsel** [comment]
Hab ich verstanden.
