### ISSUE TITLE
Frage: Ist "Profil löschen" identisch mit "User löschen"

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#278]
Falls ja, reicht ein einfaches confirm nicht aus. Falls nein, muss eine Erklärung dahin.

**Comment by ckruse** [comment]
Ja.

**Comment by ckruse** [comment]
äh, hups. Warum reichte ein `confirm` nicht aus?

**Comment by MatthiasApsel** [comment]
Weil ein "sind sie sicher" ein wenig wenig ist, falls man versehentlich seinen Benutzeraccount löscht.

Sowas wie "Achtung: Diese Aktion kann nicht rückgäng gemacht werden." sollte es schon sein. Ich hätte gern eine eigene Seite dafür forum.selfhtml.org/delete-account.html

**Comment by dedlfix** [comment]
Und bitte auch konkrete Aussagen, statt "Diese Aktion ..." besser "Das Löschen des Accounts ...". Manchmal verklickt man sich und der Bezug der Nachfrage zur Aktion des Nutzers geht dadurch verloren.
