### ISSUE TITLE
Anzahl der Bewertungen bei http://forum.selfhtml.org/users/number#erhaltene_Bewertungen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#279]
Die Information dort ist redundand.

**Comment by ckruse** [comment]
Inwiefern?

**Comment by MatthiasApsel** [comment]
Schau zum Beispiel [deine Übersicht](http://forum.selfhtml.org/users/1) an, bei den erhaltenen Bewertungen steht 

`10 	Fehler beim Antworten? Christian Kruse 24.03.2015 23:04  ... 1 Bewertungen`

Die `1 Bewertungen` kann dort weg, die Info steckt schon in der 10.

**Comment by ckruse** [comment]
Nein: die Anzahl der Bewertungen könnte auch höher sein wenn sie nicht innerhalb der letzten 10 war

Am 4. April 2015 20:42:11 MESZ, schrieb MatthiasApsel <notifications@github.com>:
>Schau zum Beispiel [deine Übersicht](http://forum.selfhtml.org/users/1)
>an, bei den erhaltenen Bewertungen steht 
>
>`10 	Fehler beim Antworten? Christian Kruse 24.03.2015 23:04  ... 1
>Bewertungen`
>
>Die `1 Bewertungen` kann dort weg, die Info steckt schon in der 10.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ckruse/cforum/issues/279#issuecomment-89637079

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by MatthiasApsel** [comment]
Du sollst doch deinen Besuch umsorgen ;-)

Unter "erhaltene Bewertungen" stehen die 10 neuesten bewerteten Beiträge. - richtig? Bei diesen könnte ich 4 x 10 Punkte haben und trotzdem 5 Bewertungen??

**Comment by ckruse** [comment]
Es zeigt nur die letzten 20 *Bewertungen*.

Am 4. April 2015 21:28:42 MESZ, schrieb MatthiasApsel <notifications@github.com>:
>Du sollst doch deinen Besuch umsorgen ;-)
>
>Unter "erhaltene Bewertungen" stehen die 10 neuesten bewerteten
>Beiträge. - richtig? Bei diesen könnte ich 4 x 10 Punkte haben und
>trotzdem 5 Bewertungen??
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ckruse/cforum/issues/279#issuecomment-89645431

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by ckruse** [comment]
die letzten 10! Sorry, vertippt.

**Comment by MatthiasApsel** [comment]
Das wird dann aber zu Fragen führen ...

**Comment by ckruse** [comment]
Vorschläge?

**Comment by MatthiasApsel** [comment]
derzeit keine, außer Überschrift ändern - Bewertungsverlauf
