### ISSUE TITLE
Anonymisierung anbieten

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#282]
Wenn jemand seinen Account löscht, könnte es die Möglichkeit geben, seine Beiträge zu pseudonymisieren. Dazu könnte es eine umfangreiche Liste mit Pseudonymen geben, und alle Vorkommen seines Benutzernamens in seinen Beiträgen und Antworten darauf werden ersetzt.

**Comment by ckruse** [comment]
Das halte ich für höchstgradig problematisch. Was ist, wenn der Algorithmus einen Fehler hat und das falsche ersetzt? Was ist, wenn es im Kontext um etwas ganz anderes ging?

**Comment by ckruse** [comment]
Ping? ;)

**Comment by auge8472** [comment]
Was ist, wenn das Pseudonym zufällig einem Nutzernamen eines anderen Benutzers entspricht oder wenn es, ebenso zufällig, mehrfach verwendet wird?

**Comment by MatthiasApsel** [comment]
Ich sehe die Probleme. Also lassen wir das die Admins händisch machen, wie bisher auch.

**Comment by auge8472** [comment]
Ich kenne natürlich das Admininterface nicht. Dein *händisch* macht mir aber ein wenig Angst. Händisch heißt hier doch bestimmt, dass der Admin ein Pseudonym vorgibt, in das der Name auf Knopfdruck umgewandelt wird, oder?

Quasi ein Halbautomatismus.

**Comment by ckruse** [comment]
Nein, das bedeutet er geht an jedes Posting und wechselt per Editieren-Knopf den Text aus.

**Comment by MatthiasApsel** [comment]
Genau. So wie jetzt auch, wenn es Forderungen nach Löschung gibt.
