### ISSUE TITLE
Mailverkehr zwischen gelöschten Nutzern und Mods/Admins sollte nicht verloren gehen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#283]
Wenn man einen Nutzer löscht, werden auch all seine PMs gelöscht. Aus Beweisgründen sollte der Mailverkehr zwischen Mods/Admins und einem anderen Nutzer auch nach Löschung des Kontos erhalten bleiben.

**Comment by ckruse** [comment]
Ich weiss nicht, das zieht viele Probleme nach sich, sowohl technischer als auch menschlicher Natur. Da sollten wir nochmal drüber nachdenken, ich verschiebe es mal in die 4.1

**Comment by MatthiasApsel** [comment]
Ich meine nicht sämtliche PMs, die gehen ja auch niemanden etwas an. Aber wenn ein Nutzer gelöscht wird, zum Beispiel als letzte Maßnahme oder der Nutzer sich aus Frust selbst löscht, kann man davon ausgehen, dass vorher Mail- oder PM-Verkehr zwischen Nutzer und einem admin stattgefunden hat. Ausschließlich diese sollten erhalten bleiben, bis der admin sie löscht.

**Comment by dedlfix** [comment]
Zumindest auf Admin-Seite. Falls PMs auf Admin-Seite erhalten bleiben, ist mein Kommentar als gegenstandslos zu betrachten. Aber wenn nicht, dann wäre es unklug, die Antwort des Nutzers ungelesen wegzuwerfen, wenn der kurz darauf sein Konto löscht, ohne dass der Admin in der Zwischenzeit die Chance hatte, sie zu lesen.

**Comment by ckruse** [comment]
Technisch ist das Problem, dass bisher die PMs einen FK-Constraint haben und der Autoren-Name bei der PM nicht gespeichert wird. Menschlich ist das Problem, dass ich irgendwie ein schlechtes Gefühl dabei habe, persönlichen Mailverkehr nicht vollständig zu löschen wenn der User den Account löscht. Das fühlt sich echt nicht richtig an.

**Comment by MatthiasApsel** [comment]
Du vergisst, dass $nutzer willentlich eine Nachricht an einen admin geschickt hat, Genauso wie man das Senden einer Mail nicht ungeschehen machen kann, sollten PMs zwischen $nutzer und $admin nicht automatisiert verloren gehen, zumal sie möglicherwerise etwas über die Löschung aussagen könnten. PMs zwischen beliebigen Nutzern sollten davon nicht betroffen sein,

**Comment by dedlfix** [comment]
Sobald man eine Nachricht abgesendet hat, gehört sie nicht mehr dem Absender. Wenn ich meine Email-Adresse aufgebe, kann ich auch nicht all meinen bisherigen Korrespondenzpartnern die Mails aus ihren Postfächern löschen. Das erwartet auch keiner.
