### ISSUE TITLE
Frage: Lassen sich einzelne Kramdown-Syntaxes gezielt vom Parsen ausschließen?

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#284]
Nicht alles, was möglich ist, ist auch sinnvoll.Siehe http://forum.selfhtml.org/meta/2015/apr/03/markdown-so-gewollt/1636228#m1636228

**Comment by ckruse** [comment]
Lassen sich, indem ich den Parser an der Stelle überschreibe. Aber in diesem Fall würde ich das nicht wollen, `ol`s mit Nummern machen imho durchaus Sinn und die User werden sich daran gewöhnen.
