### ISSUE TITLE
Auf der Hauptseite auch die Anzahlen der neuen Threads und Beiträge anzeigen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#288]
Platz ist ja genug. 

Threads           Beiträge
243162 	(3)    1597467 (31) 

Eine Tausendertrennlücke wäre an dieser Stelle ebenfalls nicht schlecht.

**Comment by ckruse** [comment]
Ich verstehe nicht so richtig, was du genau möchtest. Magst du das näher ausführen?

**Comment by MatthiasApsel** [comment]
In der Tabelle auf der Hauptseite forum.selfhtml.org stehen die Anzahlen der Threads bzw. Beiträge. Dort könnten für angemeldete Nutzer auch die Anzahlen der neuen bzw. ungelesenen Threads und Beiträge hin. Zumindest die Information der neuen Beiträge steht ja zur Verfügung, denn sie steht ja in ggf. der Titlezeile. Und auch, dass es neue Threads gibt, wird ja manchmal in einem grünen Hinweisdiv eingeblendet.

**Comment by ckruse** [comment]
Die Info steht so nicht zur Verfügung. Und ich möchte das auch gern auf 4.1 verschieben, das ist noch etwas Arbeit.

**Comment by MatthiasApsel** [comment]
kein Problem.
