### ISSUE TITLE
weitere Auszeichnungen und Klassen

### ISSUE THREAD

**Issue by ckruse** [ckruse/cforum#289]
Generell könnten mehr Selektoren eingebaut werden. Ich hab mich teilweise an data-Attributen orientieren müssen, weil es kaum andere Erkennungsmerkmale für Seiten und Bereiche in ihnen gibt. (by @dedlfix)

**Comment by dedlfix** [comment]
Für Javascript oder seiten-individuelles CSS muss man wissen, auf welcher Seite man sich befindet. Bin ich auf der Startseite oder in /all oder in Forum X oder Y? Man weiß es nicht. Es gibt nur die Attribute data-controller und data-action, die eindeutig sind. Prinzipiell reicht das zwar, aber das ist so umständlich zu adressieren. Und vermutlich auch nicht als Selektionskriterium gedacht, oder? Jedenfalls kann man damit zwar die Seite addressieren, aber wenn dann da mehrere beispielsweise Sections sind, wie finde ich dann die richtige, die ich meine? Anhand der Anordnung der HTML-Elemente? Nun, das wird bei genügend Selektoren auch irgendwann eindeutig, aber schön ist was anderes. Eine bedeutungsklärende ID würde sehr helfen. À la `<section id=posting>`, `<section id=threadlist>` und `<section id=answer>`

**Comment by ckruse** [comment]
äh, genau dafür ist `data-controller=` und `data-action=` ;) Selektieren mit jQuery ganz einfach: `$("[data-controller=cf_threads]")`

**Comment by dedlfix** [comment]
Das hab ich ja auch verwendet. Nur interessiert es mich im HTML/CSS nicht, welcher Controller und Action das erstellt hat. Nenn es doch page-controllername-actionname oder ähnlich. Das ist dann noch ganz einfacher zu adressieren.

Unabhängig davon sind die Teile in der Seite damit noch nicht (einfach) ansprechbar.

**Comment by ckruse** [comment]
Magst du prüfen, ob dir das reicht an Klassen und IDs? Und, falls nicht, mir sagen wo dir etwas fehlt?

**Comment by ckruse** [comment]
closed due to request

**Comment by MatthiasApsel** [comment]
body class="archive" für die Übersichtsseiten, außerdem wäre es schön, wenn auch für archivierte Einzelbeiträge der body die Klasse "archive" bekäme. Das hilft bei der Wahl des richtigen Logos http://src.selfhtml.org/selfhtml_forum_archiv.png

**Comment by MatthiasApsel** [comment]
Ich weiß nicht, ob es eine ganz gute Idee ist: 

Man könnte, falls es in zugeklappten Threads ungelesene Antworten gibt, das Element `<span class="num-unread">` in einer anderen Schrift darstellen. Dazu braucht es eine weitere Klasse.
