### ISSUE TITLE
Thread-Bäume werden abgeschnitten

### ISSUE THREAD

**Issue by ckruse** [ckruse/cforum#290]
Siehe [im Forum](http://forum.selfhtml.org/meta/2015/apr/04/thread-abgeschnitten/1636293#m1636293)

**Comment by MatthiasApsel** [comment]
In der thread-ansicht ist es möglich und sehr wahrscheinlich, dass der Threadbaum breiter als der Beitrag wird.

Abhilfe schafft `#content {display: inline-block;}`

Auf Nebenwirkungen nicht getestet,

**Comment by ckruse** [comment]
Nee, das hilft nicht:

![screen shot 2015-04-05 at 00 01 05](https://cloud.githubusercontent.com/assets/175095/6994823/f45fec40-db26-11e4-9d49-6ac11d3d4c70.png)

Und übrigens nicht nur in der Thread-Ansicht, sondern auch auf der Hauptseite:

![screen shot 2015-04-05 at 00 02 02](https://cloud.githubusercontent.com/assets/175095/6994827/121fe3ca-db27-11e4-87cf-32d315931208.png)

Und in der Nested-Ansicht:

![screen shot 2015-04-05 at 00 03 26](https://cloud.githubusercontent.com/assets/175095/6994829/378d4bf2-db27-11e4-83ed-2f8b142762d7.png)

Firefox, Safari, Chrome. Linux und OS X.

**Comment by ckruse** [comment]
Das liegt an dem `overflow:hidden`, dass wir für die `ol` brauchen... das führt dazu, dass ein paar Pixel von den Tags abgeschnitten werden.

Abhilfe schafft ein `margin-right` auf die Tag-Liste.

**Comment by MatthiasApsel** [comment]
Das ist aber dort nur Kosmetik das letzte Stückchen vom tag ;-) In der Thread-Ansicht wird ohne das display: block signifikant viel angeschnitten.

Weil dort die Breite nach dem sichtbaren Beitrag bestimmt wird und der nachfolgende Threadbaum wesentlich breiter werden kann.

**Comment by MatthiasApsel** [comment]
![ohne inline-block](https://cloud.githubusercontent.com/assets/2847625/6994908/6207b90a-db2a-11e4-8404-d51705c7e004.png)
![mit inline-block](https://cloud.githubusercontent.com/assets/2847625/6994909/6bfff2c4-db2a-11e4-851b-2940f3f45544.png)

Achte auf den Scrollbalken.

**Comment by ckruse** [comment]
Passiert hier nicht...

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by ckruse** [comment]
Hm, ok, ich sehe was du meinst. Aber wie gesagt: inline-block hilft auch nicht

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by MatthiasApsel** [comment]
Bei mir schon, für das umgebende Element, also das mit der ID content.

**Comment by ckruse** [comment]
Hehe, aber das können wir auf keinen Fall machen ;)

Egal, ist jetzt gefixed, da war ein max-width zu viel.

**Comment by MatthiasApsel** [comment]
Oder so. Die Liste musste die Möglichkeit haben, sich auszudehnen.

**Comment by MatthiasApsel** [comment]
Die -1em für die Liste sollte unabhängig davon übernommen werden.
