### ISSUE TITLE
Alle Bedienelemente in .message-links in *ein* Element

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#291]
Dann lässt sich das einfacher stylen. Außerdem gibts da noch leere p-Elemente.

**Comment by ckruse** [comment]
*seufz*

**Comment by ckruse** [comment]
Das ist problematisch. Das betrifft ja auch open und close votes bzw. deren Ergebnisse. Du musst genauer spezifizieren, was du möchtest.

**Comment by MatthiasApsel** [comment]
Das verschieben wir erstmal solange, bis es eine zündende Idee gibt, wie wir die Voting-Geschichte stackoverflow-mäßig darstellen wollen. Siehe [Trello](https://trello.com/c/saRulBud/8-voting-area).

**Comment by MatthiasApsel** [comment]
Die leeren p-Elemente entstehen durch einen Verschachtelungsfehler

~~~ html
<p>
  <form>
</p>
  </form>

**Comment by ckruse** [comment]
Oh, fixed.
