### ISSUE TITLE
Wir sollten jetzt auch einen Link zum Archiv unterbringen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#295]

**Comment by ckruse** [comment]
Ja, und am besten auch in der 4.0.1 noch ;)

**Comment by ckruse** [comment]
Ne Idee?

**Comment by MatthiasApsel** [comment]
Ja, da gehört er thematisch hin. Allerdings ist der Bereich jetzt echt voll.

**Comment by ckruse** [comment]
Für angemeldete User: ja. Für unangemeldete User: nein.
