### ISSUE TITLE
Benutzername schützen

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#299]
Wird der Benutzername eines registrierten Benutzers automagisch vor der Verwendung durch andere geschützt oder gibt es diese Funktion in der neuen Verson nicht mehr? Einen Punkt dazu habe ich in den Benutzereinstellungen jedenfalls nicht gefunden.

**Comment by MatthiasApsel** [comment]
Ja, ich darf meinen Benutzernamen zwar in "auge", nicht aber in "Auge" umbenennen. Deshalb ist es eine gute Idee, dort noch einmal ein tolower rüberlaufen zu lassen. Unregistrierte können auch nicht unter einem schon vorhandenen Benutzernamen posten.

**Comment by ckruse** [comment]
Ja, das ist der Plan, genauer gesagt will ich da mehr machen: einen `UNIQUE INDEX users(LOWER(username))`. Die Frage ist nur: was machen wir mit den Duplikaten, die es bereits gibt?

**Comment by ckruse** [comment]
Sind zwei Stück

**Comment by ckruse** [comment]
Und auch noch wirklich unterschiedliche ;)

**Comment by ckruse** [comment]
Allerdings auch zwei nicht bestätigte User.

**Comment by MatthiasApsel** [comment]
zwei Stück oder zwei Paar ;-)

Wir benennen den neueren um und schreiben ihm eine Mail.

**Comment by ckruse** [comment]
Habe ich jetzt anders gemacht. Bei einem der Paare war nur ein User aktiv, bei einem der Paare war kein User aktiv. Beim Paar, wo nur ein User aktiv war, war keine E-Mail-Adresse beim inaktiven User. Beim Paar, wo beide aktiv waren, war bei beiden keine E-Mail hinterlegt. Ich habe kurzerhand den inaktiven und den älteren umbenannt.
