### ISSUE TITLE
Auswahl der Foren auch bei Erstellung eines neuen Beitrages anbieten?

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#306]
So ganz schlecht ist die Idee nicht. Siehe http://forum.selfhtml.org/self/2015/apr/05/zeit-einstellen-im-cronjob/1636361#m1636361

**Comment by MatthiasApsel** [comment]
Dann könnte man auch bei der gemischten Variante (wenn man auf der Hauptseite “Alle” ausgewählt hat) den Button “neuen Beitrag verfassen” anbieten. - mudguard

**Comment by ckruse** [comment]
Ich kann verstehen, warum das gewollt ist. Aber es führt zu allerhand technischen Problemen. Frühestens in der 4.1
