### ISSUE TITLE
user-info-table auch bei http://forum.selfhtml.org/users/2/edit unterbringen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#307]

**Comment by ckruse** [comment]
Warum? IMHO hat sie dort nichts zu suchen.

**Comment by MatthiasApsel** [comment]
- Warum soll der Nutzer nicht auch an dieser Stelle über seine Punkte und Registrierungsdatum informiert werden?
- Schadet die Info da?
- Es sieht besser aus ;-) 
- Es ist konsistent zwischen info und edit. Man könnte sogar den kompletten Kopf übernehmen.
- in die Tabelle könnte noch die Anzahl der Beiträge rein.

**Comment by ckruse** [comment]
Mehr Scrolling, unübersichtlicher. Da geht es darum seine Benutzer-Konfiguration zu editieren, nicht darum Infos angezeigt zu bekommen?

**Comment by MatthiasApsel** [comment]
Meinetwegen.

**Comment by MatthiasApsel** [comment]
In die Tabelle könnte noch die Anzahl der Beiträge hinein.

**Comment by ckruse** [comment]
Das ist ein Performance-Problem. Ich müsste das cachen als Spalte beim User und dann via Trigger aktuell halten.

**Comment by MatthiasApsel** [comment]
Braucht ja nur einmal täglich aktualisiert zu werden.

**Comment by ckruse** [comment]
Pfui, er hat das böse Wort gesagt! ;)

Ne, wenn dann machen wir es richtig, via Trigger. Kostet ja auch nicht so viel.

**Comment by ckruse** [comment]
Stellt sich raus: PostgreSQL ist viel smarter als ich und macht das über einen Index-Only-Scan ;)
