### ISSUE TITLE
In den erhaltenen Bewertungen stehen auch die drin, die man selbst zu verantworten hat

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#310]
Soll das so? Sollte da noch eine Info hin?

**Comment by ckruse** [comment]
Das kann ich nicht nachvollziehen, bist du da sicher?

**Comment by MatthiasApsel** [comment]
Ja, ich habe einen Beitrag negativ bewertet, der steht bei mir als erhaltene Bewertung drin. http://forum.selfhtml.org/users/2/

**Comment by ckruse** [comment]
Ah, negative Bewertungen - ja, da ist da ja auch richtig. Dafür kassierst du ja einen Minus-Punkt.

**Comment by MatthiasApsel** [comment]
Ja, schon klar. Aber die Bewertung habe ich ja nicht erhalten, sondern mir selbst verpasst. Deshalb die Frage nach der eventuellen zusätzlichen Info. Wie das konkret sein könnte, weiß ich auch nicht.

**Comment by ckruse** [comment]
Du hast sie erhalten indem du sie jemand anderem verpasst hast ;) Ich würde ehrlich gesagt einfach umbenennen von "erhaltene Bewertungen" in "Punkteverlauf" oder so.
