### ISSUE TITLE
Nach einer Bewertung zum bewerteten Beitrag weiterleiten

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#315]
Wenn man in der nested-Ansicht einen Beitrag bewertet, landet man ganz oben auf der Seite. Schön wäre, wenn man wieder beim Beitrag landet. Aber das wird sich ja spätestens dann erledigt haben, wenn kein Request mehr nötig ist.

**Comment by ckruse** [comment]
Es muss ja auch weiterhin eine Non-JS-Variante geben.

**Comment by ckruse** [comment]
Fixed
