### ISSUE TITLE
Archiv-Übersichtsseiten haben keinen Link zur statistik

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#316]
Möglicherweise hast du noch irgendwo welche vergessen, denn so stark rückläufig sind die Besucherzahlen bestimmt nicht. http://www.browser-statistik.de/benutzer/forum.selfhtml.org/ Was sagen denn die Logs? Läuft ein Munin oder so?

**Comment by ckruse** [comment]
Ich hatte doch extra gefragt, wo überall einer hin soll :)

**Comment by MatthiasApsel** [comment]
Damals gabs das Archiv so noch gar nicht. Als du im Urlaub warst, hatten wir ca. 2500 Besucher täglich.
