### ISSUE TITLE
Sortierung der User nach Administrator ist fehlerhaft

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#319]
Zumindest bei mir:

Reihenfolge: nein, ja, ja, ja, ja, ja, nein .... mikikado steht an erster Stelle.

mikikado habe ich übrigens per Hand seine E-Mail-Adresse zugeordnet.

**Comment by MatthiasApsel** [comment]
Ist bei mir immer noch so.

**Comment by ckruse** [comment]
in der Admin-Ansicht oder wo?

**Comment by MatthiasApsel** [comment]
ja: http://forum.selfhtml.org/admin/users?dir=asc&sort=admin

**Comment by ckruse** [comment]
Jetzt ist es aber online ;-)
