### ISSUE TITLE
Markierung von gesperrten Threads in der Übersicht des Unterforums

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#320]
Füge gesperrten Threads eine Markierung, z.B. mit [fa-ban](http://fontawesome.io/icon/ban/), hinzu. 

Ach, wo wir gerade dabei sind, gibt es noch die Funktion, Threads zwar laufen zu lassen, aber nicht zu archivieren? Da wäre ja auch eine Markierung notwendig.

**Comment by ckruse** [comment]
`no archive` gibt es weiterhin, ja.

**Comment by auge8472** [comment]
Auch wenn es fürchterlich off-topic ist: Huch, das ging ja schnell.

**Comment by ckruse** [comment]
Zufall: ich war gerade dabei Issues zu sortieren :)
