### ISSUE TITLE
als ungelesen markieren funktioniert offenbar nur in den Hauptseiten

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#323]
also forum/all, forum/meta

nicht aber auf Beitragsseiten. (nested getestet)

Was unter Umständen schwierig ist, weil nach Verlassen der EInzelansicht ja wieder die gelesen-Markierung gesetzt wird. Ich halte es aber für wichtig, dass man gerade dort den Beitrag als ungelesen markieren kann.

**Comment by ckruse** [comment]
Hihi, ja, da schiesst man sich in den Fuss: ungelesen markiert wird es, aber danach wird man zum Beitrag weiter geleitet.

**Comment by MatthiasApsel** [comment]
Ja, es müsste so sein, dass ein Klick auf dieses Icon den Beitrag **grundsätzlich** auf ungelesen setzt, egal wie oft man ihn liest. Den Status kann man nur durch einen Klick auf "Beitrag als gelesen markieren" wieder rückgängig machen. Insofern finde ich das Icon vor der h2- bzw. h3-Überschrift im Beitragskopf gar nicht schlecht.

Das klingt mir nach recht viel Aufwand 4.0.1 -> 4.1?

**Comment by ckruse** [comment]
Ich bin mir nicht so sicher, ob es eine permanente "das ist ungelesen"-Markierung geben sollte. Dafür ist ja im Grunde schon "Thread als interessant markieren" da. Ich denke nur, man sollte nicht unbedingt zu dem Beitrag zurück redirecten ;-) Aber ja, bis das ausdiskutiert ist 4.1

**Comment by MatthiasApsel** [comment]
Das eine bezieht sich auf einzelne Beiträge, das andere auf komplette Threads.

**Comment by ckruse** [comment]
Ich habe die "ungelesen markieren"-Funktion vollständig entfernt.
