### ISSUE TITLE
CSS-Fehler

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#324]
`.thread > header > .thread-icons { float: right; }` macht die Darstellung des Threadbaums kaputt. Interessanterweise nur dann, wenn nur ungelesene Beiträge folgen. Lösung hab ich erstmal keine. 
![screen](https://cloud.githubusercontent.com/assets/2847625/7138207/09ead562-e2bf-11e4-898a-42a49bb8e6ba.png)

**Comment by ckruse** [comment]
Hier sieht alles normal aus...?

**Comment by MatthiasApsel** [comment]
Hast du denn auch threads mit nur ungelesenen Beiträgen?

**Comment by MatthiasApsel** [comment]
Es ist tatsächlich nur der Firefox, der diesen Fehler bringt.

**Comment by ckruse** [comment]
Unter osx konnte ich das auch mit dem ff nicht beobachten. Aber ich schau mir das nachher nochmal an

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by MatthiasApsel** [comment]
Bei mir macht er dafür konsequent, Win7, Win8.1, Linux mint

**Comment by MatthiasApsel** [comment]
Bei mir hilft 
~~~ css
.thread > ol { clear: right; }
~~~
