### ISSUE TITLE
aktuellen Beitrag auch im Threadbaum hervorheben, wenn man eine Antwort schreibt

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#332]
und zwar das, auf das man gerade antwortet. Vielleicht will man auch mal einen anderen Beitrag noch öffnen, um etwas nachzulesen.

Für den Threadbaum sollte dort auch eine Mindestbreite von 54.5em gelten. 
`.root, .thread.root {min-width: 54.5em}`

**Comment by MatthiasApsel** [comment]
Teil 2 (CSS) fehlt noch ;-)

**Comment by ckruse** [comment]
Nee, durch das geänderte Markup (das hätte eigentlich schon so sein sollen, die JavaScripte brauchen ein Container-Element `.root`) greift jetzt der Selector, der auch für die anderen greift.
