### ISSUE TITLE
Nutzer referenzieren wie in Twitter

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#334]
oder github oder Trello oder Facebook oder oder ...

Ich bin der Meinung, das hatten wir auch schon mal:

Wenn man in einen Beitrag zum Beispiel @ckruse schreibt, soll der Benutzer eine Nachricht bekommen. (Ich glaube, referenzieren ist der falsche Begriff) Eine Auswahlliste nach dem @ wäre auch nicht schlecht.

**Comment by ckruse** [comment]
das habe ich auch schonmal überlegt aber bisher noch nicht aufgenommen (weil soviel anderes zu tun war). +1!
