### ISSUE TITLE
Auf der Anmeldeseite tab-index setzen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#336]
In der Reihenfolge
* Benutzername (hat ja schon autofocus)
* Passwort
* Login merken
* Passwort vergessen

Wäre aber nicht ganz so wichtig.

**Comment by ckruse** [comment]
Da bin ich ehrlich gesagt dagegen, ausser vielleicht `tabindex="-1"` auf den Passwort-vergessen-Link. [Siehe auch.](http://blog.adrianroselli.com/2014/11/dont-use-tabindex-greater-than-0.html)

**Comment by MatthiasApsel** [comment]
Damit ist das gewünschte Ziel auch erreicht. Obwohl das sicher sehr selten gebraucht wird.

**Comment by MatthiasApsel** [comment]
Könnte es jetzt passieren, dass es Leute gibt, die den PW-vergessen-Link überhaupt nicht erreichen können?

- 1
- 2
- 4
- 3

wäre dann doch die bessere Wahl? Alle anderen fokussierbaren Elemente sind ja davon unbeeinflusst. Aber siehe oben: So richtig wichtig ist es nicht. Und: Es hat zu einer inhaltlichen Verbesserung des Wikis geführt.

**Comment by ckruse** [comment]
Nur via Tab nicht. Und wie gesagt, ich halte nichts von `tabindex` mit positiven Zahlen, das macht zu viel kaputt und ist zu inkonsistent.
