### ISSUE TITLE
bug markdownleiste markiert eingegebenes Element

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#337]
Wenn man über die Bearbeitungsleiste eines der Einzelzeichen (hellip, TM ... ) eingibt, wird dieses markiert. Das sollte nicht sein, stattdessen wäre ein folgendes Leerzeichen und danach der Cursor sinnvoll

**Comment by ckruse** [comment]
hm, das war eigentlich Absicht, aber es ist für mich nachvollziehbar, warum man das nicht will.

**Comment by ckruse** [comment]
Die Leertaste lasse ich erstmal aussen vor, die finde ich nicht so sinnvoll.
