### ISSUE TITLE
in code.block ist white-space: pre-wrap ohne Wirkung

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#338]
Für die code.block-Elemente ist white-space: pre-wrap festgelegt. Das kommt aber nicht zum tragen, weil da noch ein pre-Element eingeschoben ist. Auf dieses könnte man ggf. verzichten.

Daher kam vielleicht auch die zu hohe line-height.

**Comment by MatthiasApsel** [comment]
Dann sollte jetzt auch die CSS-Änderung rückgängig gemacht werden (line-height) oder was meinst du? 
http://forum.selfhtml.org/self/2015/apr/16/gleiches-formular-new-und-edit/1637476#m1637476 zum Anschauen.

**Comment by ckruse** [comment]
`1em` ist vielleicht zu wenig, aber der default value (`1.4em`, ererbt) ist zuviel. Ich setze es mal auf `1.2em`

**Comment by MatthiasApsel** [comment]
Ich find die 1.4 gar nicht so schlecht.

**Comment by ckruse** [comment]
`1.4em` schadet IMHO der Übersichtlichkeit von Code, besonders bei längeren Code-Stücken, enorm.
