### ISSUE TITLE
Tagvorschläge auch bei Null getippten Buchstaben im Auswahlfeld anzeigen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#344]
Es mag vorkommen, dass für einen Beitrag keine Tagvorschläge gemacht werden bzw. die gemachten Vorschläge dem Poster nicht passend erscheinen.

Wenn er jetzt per Hand welche eintragen möchte, werden ihm erst bei Tippen des ersten Buchstaben Vorschläge angezeigt. Wenn es aber keine Tags (die auch vorgeschlagen werden sollen) mit diesem Buchstaben gibt, bekommt er keine Vorschläge, darf aber seinen Tagwunsch auch nicht verwenden.

**Comment by ckruse** [comment]
ich verstehe ehrlich gesagt nicht so recht, was du meinst...

**Comment by MatthiasApsel** [comment]
Ah. Es wird sogar die Gesamtliste eingeblendet, aber erst nachdem ich die Fehleingabe per Backspace gelöscht habe. Das Einblenden sollte bereits dann passieren, wenn der Focus auf das Inputfeld gesetzt wird.
