### ISSUE TITLE
Beim Retaggen kann man ebenfalls Beiträge ohne Tags erzeugen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#347]
Laut Einstellungen ist auch im internen Forum eine Mindest-Tag-Zahl von 1 festgelegt.

**Comment by ckruse** [comment]
das reicht mir nicht als Fehlerbeschreibung. Kannst du das bitte näher ausführen?

**Comment by MatthiasApsel** [comment]
Wenn ich Beiträge retagge, kann ich auch alle Tags entfernen. 

(Ich habe das im internen Forum getestet, auch dort muss jeder Beitrag mindestens ein Tag besitzen, da war ich mir zuerst nicht sicher)
