### ISSUE TITLE
Unmittelbar aufeinander folgende Code-Blöcke sollen zu einem zusammengefasst werden

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#349]
Siehe http://forum.selfhtml.org/self/2015/apr/18/css-before-width/1637873#m1637873

**Comment by ckruse** [comment]
Nein, ich will nicht zu viel Magie da reinbringen. Warum hast du das nicht einfach als HTML ausgezeichnet? Der Syntax-Highlighter switcht dann im richtigen Kontext automatisch auf z.B. CSS.
