### ISSUE TITLE
Feedback fürs uploaden fehlt

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#358]
siehe http://forum.selfhtml.org/meta/2015/apr/22/neues-feature-bilderupload/1638377#m1638377

Deshalb habe ich ein Bild versehentlich doppelt hochgeladen.

Und nun, weiß ich nicht, welches gelöscht werden kann.

Bilder, die nach dem Hochladen nicht in einem Beitrag (oder einer PM?) auftauchen, sollten vielleicht auch automatisiert gelöscht werden.

**Comment by MatthiasApsel** [comment]
Der springende Punkt - nice.

Und der andere Punkt? 
> Bilder, die nach dem Hochladen nicht in einem Beitrag (oder einer PM?) auftauchen, sollten vielleicht auch automatisiert gelöscht werden.

**Comment by ckruse** [comment]
Das ist problematischer. Ich kriege nicht wirklich mit, welche Bilder referenziert werden und welche nicht.

**Comment by dedlfix** [comment]
Ungünstig. Nicht dass das jemand als privates Fotoalbum verwendet.

**Comment by ckruse** [comment]
Kann er ja nicht: /images ist nur durch admins einsehbar.

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by dedlfix** [comment]
Das hab ich dann auch noch gefunden. Nun hätte ich gern auch noch die neuen Bilder in die Recent-Changes-Seite für Admins eingefügt. Welche Recent-Changes-Seite? Na die, die du noch erstellen musst ... ;)
