### ISSUE TITLE
Bewertung für akzeptierte Antwort

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#359]
Wenn es später mehrere akzeptierte Antworten gibt, sollte jede akzeptierte Antwort auch einen Punkt bekommen.

**Comment by MatthiasApsel** [comment]
Frage: Bleibt die Bewertung jetzt so, wie sie ist?

**Comment by ckruse** [comment]
Jede Akzeptierung generiert 15 Punkte für den Autor.

**Comment by ckruse** [comment]
Das Zurücknehmen einer Akzeptierung löscht die Punkte. Das Akzeptieren einer weiteren Antwort generiert 15 Punkte für den Autor der weiteren Antwort.

**Comment by MatthiasApsel** [comment]
Soll der ***Beitrag*** auch einen Punkt bekommen?

**Comment by ckruse** [comment]
Nein. Warum?

**Comment by MatthiasApsel** [comment]
Ich fände es sinnvoll, wenn sich das Akzeptieren einer Antwort auch im Punktestand niederschlägt, denn es ist ja eine Wertung.
