### ISSUE TITLE
Vorschau liefert Bilder in Originalgröße

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#361]
Die Bilder auf http://forum.selfhtml.org/images werden in Originalgröße ausgeliefert. Das ist zwar schön, wenn man schnell schauen möchte, aber schlecht für den Traffic.

Vorschlag: | Vorschau | Link zum Bild

**Comment by ckruse** [comment]
/images ist eh nur für Administratoren zugänglich. Nichtmal für Moderatoren, nur für Admins.

**Comment by ckruse** [comment]
Halt, ich habe gelogen. Für Admins und Moderatoren.

**Comment by ckruse** [comment]
hm, hier ist echt was kaputt. Das sollte nur für Admins zugänglich sein.

**Comment by MatthiasApsel** [comment]
Unabhängig davon wäre ein Thumbnail sinnvoll.

**Comment by MatthiasApsel** [comment]
Und die default-Sortierung sollte Hochladedatum absteigend sein.

**Comment by MatthiasApsel** [comment]
Eine CSS-Vorschau gibt es schon lange, ein Erstellen von von Vorschaubildchen ist vielleicht eher nicht notwendig.
