### ISSUE TITLE
Alias für Benutzernamen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#362]
Wäre das eine Idee für Renate-Elisabeth Schlickschlumpf-Schott? 

Siehe http://forum.selfhtml.org/meta/2015/apr/23/3-bedienfragen-zum-neuen-forum/1638419#m1638419.

Bei Twitter gehts imho auch.

**Comment by ckruse** [comment]
Du meinst also das, was wir auf deinen Vorschlag hin abgelöst haben? ;-)

**Comment by MatthiasApsel** [comment]
Nein, auf gar keinen Fall. 

Der Name in den Beiträgen sollte immer der Benutzername sein. Aber das Login sollte möglich sein mit  Benutzername, E-Mail-Adresse und einem Alias, der natürlich forumsweit eindeutig sein muss. Ich hatte gedacht, ich könnte mich bei Twitter sowohl mit `Matthias Apsel` als auch mit `@Matthias_Apsel` anmelden, dem ist aber nicht so.

Also unsere Renate soll sich anmelden können mit
* Renate-Elisabeth Schlickschlumpf-Schott
* renate-elisabeth@example.com
* r1

Setzt natürlich voraus, dass der frei wählbare Alias weder ein Benutzername noch der Alias eines anderen Benutzers ist.

Für mich selbst ist das nicht wichtig, aber Marvins Sicht kann ich nachvollziehen, Nicht jeder hat seine Passwörter auf einem USB-Stick und nicht auf jedem Fremdrechner darf man USB-Sticks verwenden.

**Comment by ckruse** [comment]
Was ist der Unterschied zwischen dem (jetzt abgeschafften) Usernamen und dem Alias? Das erschliesst sich mir nicht.

**Comment by MatthiasApsel** [comment]
dass man den Alias lediglich zum Login verwenden kann.

**Comment by ckruse** [comment]
Also doch wie der alte Username.

**Comment by MatthiasApsel** [comment]
Nö. Früher gab es einen Usernamen mit dem man sich anmelden **musste**, meine Idee wäre ein Alias, den man sich einrichten **darf**. Die Beiträge werden nicht dem Alias zugeordnet, damit kann auch ein Admin nicht sehen, wenn ein Benutzer den Benutzernamen wechselt. Aber wie schon geschrieben, für mich persönlich nicht wichtig und wenn du das als ein Schritt zurück ansiehst, kann ich das auch verstehen.

Fälle wie Marvin werden wohl eher selten sein.

**Comment by ckruse** [comment]
Mal sehen, heute abend mag ich da nicht drüber nachdenken, bin zu müde.

**Comment by MatthiasApsel** [comment]
Da muss wohl gründlich drüber nachgedacht werden, wer weiß, was das für Nebenwirkungen hat.

**Comment by ckruse** [comment]
Zum Beispiel muss verhindert werden, dass ein User ein Alias mit dem Wert eines Usernamens anlegt...

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by MatthiasApsel** [comment]
Gesichtserkennung wäre ein cooles Feature, würde aber Marvin sicher auch nicht weiterhelfen ;-)

**Comment by campingrider** [comment]
Betroffene User können das doch auf ihrer Seite des Internets regeln - immerhin können sie sich jederzeit, wenn sie denn so lange Namen haben, einen entsprechend kürzeren E-Mail-Alias anlegen und diesen im Forum angeben; das zahlt sich ja auch außerhalb des Forums aus. Ich denke nicht, dass wir uns damit befassen müssen. Wir sind doch nicht dafür verantwortlich, wer sich bemüßigt fühlt, eine entsprechend lange E-Mail-Addresse zu benutzen, oder? ;)

**Comment by ckruse** [comment]
won't fix
