### ISSUE TITLE
kaputte Links

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#363]
Ich kann nicht sagen, ob es der Link vorher schon kaputt war, aber http://forum.selfhtml.org/self/2005/nov/1/target-_blank-umgehen-im-firefox/892821#m892821

**Comment by auge8472** [comment]
Jene Links aus dem alten Forum, die keinen Linktext haben, sehen alle so aus.

**Comment by ckruse** [comment]
Kann bitte jemand (@auge8472 vielleich?) das Script überprüfen, bevor ich es auf das Achiv loslasse?

**Comment by MatthiasApsel** [comment]
Oder vielleicht auch @dedlfix?

**Comment by ckruse** [comment]
Ich habe das jetzt ganz anders gelöst. Wir importieren das Archiv gerade neu und lassen es im alten Format. Jedes Posting hat jetzt ein Flag `format`, alte Postings haben da den Wert `cforum` und es wird on the fly umgewandelt nach Markdown.
