### ISSUE TITLE
Tag-Wolke des Users aufteilen nach Foren

### ISSUE THREAD

**Issue by ckruse** [ckruse/cforum#364]
[siehe auch](http://forum.selfhtml.org/meta/2015/apr/24/bug-doppelte-tags/1638550#m1638550)

**Comment by auge8472** [comment]
[siehe auch](http://forum.selfhtml.org/meta/2015/apr/24/bug-doppelte-tags/1638564#m1638564)

**Comment by ckruse** [comment]
Die Idee gefällt mir noch besser

**Comment by MatthiasApsel** [comment]
Mir auch. Wobei ich das Forum nur dann voranstellen würde, wenn denn tatsächlich gleichlautende Tags _angezeigt_ werden.

**Comment by dedlfix** [comment]
Gefällt mir nicht. Mal da, mal nicht, das gibt Erklärungsbedarf. Ein vorangestelltes Forum macht die Tags länger. Gruppiert nach Forum mit Zwischenüberschrift wäre mein Favorit.

**Comment by MatthiasApsel** [comment]
Könnte man das wie folgt bauen?
`<a class="cf-tag" href="..."><span>Forum: </span>Tag</a>`
Ich kriegs so nicht hin :-(

**Comment by ckruse** [comment]
Done
