### ISSUE TITLE
Nutzungsbedingungen Bilderupload

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#366]
Sammelsurium

- http://www.bilder-hosting.info/nutzungsbedingungen.php
- http://www.bilder-upload.eu/agb.php
- http://bilder.mybbservice.de/tos.php
- http://www.heise.de/foto/Erweiterte-Nutzungsbedingungen-473445.html

(für mich zum Wiederfinden)

**Comment by MatthiasApsel** [comment]
**Nutzungsbedingungen Bilderupload SELFHTML-Forum**{: style="font-size: 1.3em;"}

SELFHTML hat ein großes Interesse daran, die Fragestellungen dauerhaft für Jedermann zur Verfügung zu stellen. Das schließt auch Skizzen, Illustrationen oder Screenshots ein. In der Vergangenheit war es häufig so, dass diese Darstellungen nach einer gewissen Zeit durch die Fragesteller oder Antwortenden gelöscht wurden, sodass manche Fragestellung heute nicht mehr nachvollzogen werden kann. Deshalb bietet SELFHTML Ihnen die Möglichkeit eigene Bilder hochzuladen.

**Rechteeinräumung**

Mit dem Upload erteilen Sie SELFHTML das zeitlich unbeschränkte und unentgeltliche Recht zur Veröffentlichung im Internet für eine unbestimmte Anzahl von Nutzern sowie das Vervielfältigungsrecht auf den Servern von SELFHTML. Durch die Einräumung dieses Rechtes ist SELFHTML berechtigt, die von Ihnen eingestellten Bilder sowohl im Forum, als auch im Wiki oder im Blog zu verwenden.

Sie räumen SELFHTML und jedem Nutzer des SELFHML-Forums zudem ein Bearbeitungsrecht ein, falls beispielsweise eine Größenanpassung oder die Wahl eines Bildausschnittes notwendig erscheint bzw. Korrekturen, Hinweise oder Hilfestellungen. gegeben werden sollen. Sofern SELFHTML eine Ihrer Grafiken außerhalb des SELFHTML-Forums verwendet, werden Sie als Urheber der Grafik genannt.

**Einschränkungen, Freistellung**

Sie sind nicht berechtigt, urheberrechtlich geschütztes Material, an dem Sie nicht das alleinige Nutzungsrecht haben, hochzuladen.  
Sie sichern zu, dass das hochgeladene Material frei von Rechten Dritter ist.  
Sie verpflichten sich, keine rechtswidrigen, verunglimpfenden Inhalte oder solche, die Persönlichkeitsrechte verletzen, hochzuladen. Dies gilt ebenso für pornografisches Material und erotische Darstellungen sowie Ressourcen, die Viren oder andere schädliche Inhalte enthalten. 

SELFHTML behält sich das Recht vor, hochgeladene Bilder ohne Angabe von Gründen zu löschen.  
SELFHTML wird hochgeladene Grafiken auf ausdrücklichen Wunsch des Autors oder eines Betroffenen, etwa weil ein Screenshot die eigene Webseite unvorteilhaft darstellt, unverzüglich löschen oder verfremden. 

Sie stellen SELFHTML von jeglicher Haftung für die eingestellten Inhalte frei.

**Comment by ckruse** [comment]
Ich sehe das mal als erledigt an, ist ja im Impressum und verlinkt
