### ISSUE TITLE
Darstellung von Bewertungen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#367]
Wenn aus dem [Forum](http://forum.selfhtml.org/meta/2015/apr/21/bug-bewertungsfunktion/1638230#m1638230) nichts weiter kommt, schlage ich vor:

* Es gibt noch keine Bewertungen
  * title-Attribut: "noch keine Bewertungen"
  * in den headern: "Bewertung: keine"
  * in der voting-Area: "&ndash;"

* Es gibt schon Bewertungen
  * title-Attribut: "Bewertung: [+|±|-][Summe], [Anzahl] Stimmen"
  * in den headern: "Bewertung: [+|±|-][Summe], [Anzahl] Stimmen"
  * in der voting-Area: "[+|±|-][Summe]"

**Comment by MatthiasApsel** [comment]
Kann man bei der Bewertung mit JavaScript auch das Vorzeichen beachten?

Beispiel: Ein Beitrag hat "+2", nach der Bewertung wird daraus "3". Erst wenn man die Seite neu lädt, wird "+3" draus.

**Comment by ckruse** [comment]
Kann man...

**Comment by MatthiasApsel** [comment]
Soll ich das als Aufforderung sehen ? ;-)

**Comment by ckruse** [comment]
Nein :) das war nur eine Bestätigung, dass ich daran arbeite.
