### ISSUE TITLE
Tags sind zugeordnet, aber wo?

### ISSUE THREAD

**Issue by dedlfix** [ckruse/cforum#368]
Bei "wettstreit" (Selfforum) ist es mir aufgefallen. Es werden keine Beiträge angezeigt, aber das Tag lässt sich nicht löschen, weil es zugeordnet ist.

**Comment by MatthiasApsel** [comment]
Vielleicht in gelöschten Beiträgen. Hilft `?view_all=yes`?

**Comment by dedlfix** [comment]
Hilft nicht.

**Comment by ckruse** [comment]
`view_all` funktioniert aktuell nicht bei tags. ich mach mal nen patch fertig...

**Comment by MatthiasApsel** [comment]
Das Tag `wettstreit` ist gelöscht. Es waren 2 gelöschte Beiträge, die ich über die alte Suche gefunden habe, die dieses Tag trugen.

**Comment by ckruse** [comment]
So, `view_all` wird hier jetzt unterstützt
