### ISSUE TITLE
Frage: Markdown rendert horizontale Ellipse automatisch ...

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#369]
könnte/sollte der Button weg?

`...` ist ja nun wirklich intuitiv, im Gegensatz zu `--` deshalb würde ich den Gedankenstrich durchaus lassen.

**Comment by ckruse** [comment]
Ich würde eher dazu übergehen, `...` nicht länger automatisch zu konvertieren glaub ich.

**Comment by MatthiasApsel** [comment]
Warum denn das?

**Comment by ckruse** [comment]
Weil es automagisch die eingegebenen Zeichen ändert. Aus dem gleichen
Grund haben wir doch die automatische Konvertierung von `""` in `„“`
abgeschaltet?

**Comment by MatthiasApsel** [comment]
Die Umwandlung von `""` in `„“` war imho fehlerhaft. (#252) Und zudem werden in Codeauszügen ja auch wirklich `""` gebraucht. Ich würde die automagische Konvertierung von

* ... in &hellip;
* -- in &ndash;
* --- in &mdash;

lassen

**Comment by ckruse** [comment]
In Code-Auszügen wurde `""` nicht angefasst. Und buggy war das nicht, es wurde nur durch die englische Variante ersetzt. Das hätte man auch anders machen können, etwa durch die deutsche Variante. Es gab nur Beschwerden, deshalb hatten wir das deaktiviert.

**Comment by ckruse** [comment]
Beschwerden wohl deshalb, weil die meisten User keine korrekte Code-Auszeichnung verwenden. Ansonsten ist die Transliteration von `...`, `--` und `---` genau so bescheuert in Code.

**Comment by MatthiasApsel** [comment]
Glücklicherweise findet innerhalb von Code keine Ersetzung statt.

**Comment by ckruse** [comment]
Entweder wir ersetzen alles (also auch `""`) oder wir ersetzen gar nix, meine Meinung.

**Comment by MatthiasApsel** [comment]
Außerhalb von Code könnten wir auch `""` ersetzen. Ich find die Ersetzungen praktisch. Möglicherweise gibt es sogar noch mehr, wenn man in den Quellcode von kramdown schauen würde, wüsste man dies. Dann könnten wir nach einer Übergangszeit die Buttons für hellip und double quote aus der Leiste entfernen.

**Comment by auge8472** [comment]
Ich bin der Meinung, dass, egal ob in oder außerhalb von Codeblöcken, überhaupt keine Zeichen in den Postings ersetzt werden sollte. Das verfälscht eventuell die gewünschte Eingabe von Zeichen aufgrund gut gemeinter aber nicht zutreffender **Annahmen**. Mit Postings, die sich nicht nach der deutschen Typografie richten, müssen wir eh rechnen, warum also an **mMn** unwichtigen Feinheiten rumdoktorn, die sowieso nicht alle auftretenden Fälle erschlagen können?

Zudem, was ist so schlimm daran, dass drei Punkte statt der Ellypsis oder das für alle Fälle einfach zu erreichende Minus statt des evtl. notwendigen M- oder N-Dash oder die falschen Anführungszeichen in der Datenbank stehen? Wer sich Mühe geben will, tut es Kraft seines Tastaturtreibers oder der Buttons. Den Rest interessiert so oder so nicht, welches Zeichen benutzt wurde, wenn denn der Sinn des Postings erkennbar ist.

**Comment by ckruse** [comment]
Ich sagte ja, dass gibt Kritik ;-)

**Comment by ckruse** [comment]
Wie verbleiben wir jetzt hier? Ich mag das nicht entscheiden.

**Comment by MatthiasApsel** [comment]
Tja, bei den einfachen Anführungsstrichen kommt es zu Fehlern, wenn das fälschlicherweise als Apostroph verwendet wird. Ansonsten bin ich dafür, die eingebauten kramdown-Funktionen für hellip, em-dash und en-dash sowie die doppelten Anführungszeichen zu lassen. 

Und in der Datenbank steht ja sowieso der Rohtext, also 3 Punkte, 2 bzw. 3 Minuszeichen und die falschen Anführungszeichen.

**Comment by ckruse** [comment]
Also streichen wir die Auto-Ersetzungen ganz.
