### ISSUE TITLE
Button in .message-links ggf. redundand

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#373]
Wenn der Button "Beitrag bearbeiten" zur Verfügung steht, braucht es den Button "Tags neu vergeben" nicht zu geben.

Denn Beitrag bearbeiten schließt Tagänderung mit ein.

Das hätte den Vorteil, dass der Bereich weniger Bedienelemente hätte, aber eventuell den Nachteil, dass "Tags neu vergeben" mal sichtbar und mal unsichtbar wäre.

**Comment by ckruse** [comment]
Das sehe ich anders. Tags neu vergeben fasst den Beitrag nie an. Beitrag
bearbeiten immer. Und damit löst es auch ein „dieser Beitrag wurde
editiert“ aus. Allerdings könnte man es umbenennen auf z.B. „Tags
ändern“ oder so.

**Comment by MatthiasApsel** [comment]
Es sollte keinen Unterschied machen ob ich "Tags ändern" wähle und die Tags ändere oder ob ich "Beitrag bearbeiten" wähle und dann nur die Tags ändere. Ich bin dafür, dass ein Beitrag bereits dann als editiert gilt, wenn seine Tags geändert wurden.

**Comment by ckruse** [comment]
Das sehe ich grundlegend anders. Retaggen ist kein editieren des Beitrags. SO sieht das übrigens so wie ich, gerade überprüft.

**Comment by MatthiasApsel** [comment]
Das gilt doch hoffentlich nur für meinen 2. Satz, denn 
> Es sollte keinen Unterschied machen, ob ich "Tags ändern" wähle und die Tags ändere oder ob ich "Beitrag bearbeiten" wähle und dann __nur__ die Tags ändere.

Ich habe kein Problem, wenn man das Ändern der Tags nicht als Editieren zählt.

**Comment by ckruse** [comment]
Sobald du die Funktion "Beitrag editieren" auswählst und auf "speichern" klickst hast du den Beitrag editiert. Alles andere würde in übermässigen technischen Aufwand ausarten.

**Comment by MatthiasApsel** [comment]
Naja, wenn du später die Diff-Historie schreibst (Das siehst du ja als interessante Aufgabe #244) hast du den Aufwand ja sowieso.

**Comment by ckruse** [comment]
äh, das ist etwas völlig anderes ;-)

**Comment by MatthiasApsel** [comment]
> Sobald du die Funktion "Beitrag editieren" auswählst und auf "speichern" klickst hast du den Beitrag editiert. Alles andere würde in übermässigen technischen Aufwand ausarten.

Braucht man nicht einfach nur den ursprünglichen Beitragstext mit dem neuen zu vergleichen ??
