### ISSUE TITLE
Zusätzlicher Whitespace in zitierten Codeblöcken

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#376]
In zitierten Codeblöcken wird eine zusätzliche Leerzeile angehängt. Ich hoffe, es wird nicht zu aufwändig ( #251) SIehe http://forum.selfhtml.org/self/2015/apr/28/bild-kopieren/1638864#m1638864

**Comment by ckruse** [comment]
Ich sehe ehrlich gesagt nicht, worauf du hinaus willst. Magst du das näher ausführen?

**Comment by MatthiasApsel** [comment]
Original:
~~~
Code
~~~

Zitat:
> ~~~
> Code
> 
> ~~~

**Comment by ckruse** [comment]
Wo ist das denn der Fall? In dem von dir verlinkten Beitrag auf jedenfall nicht...

**Comment by MatthiasApsel** [comment]
Entschuldige, ich vergaß, dass du nicht so gern die nested-Ansicht nutzt, deshalb war nur das Startposting verlinkt

Original http://forum.selfhtml.org/self/2015/apr/28/bild-kopieren/1638888#m1638888

Zitat: http://forum.selfhtml.org/self/2015/apr/28/bild-kopieren/1638890#m1638890

**Comment by ckruse** [comment]
Hm, interessant. Aber das kommt nicht von mir, wenn du dir den Source anschaust: da ist kein zusätzliches Newline oder `<br>`.

**Comment by ckruse** [comment]
Nein, da ist kein Unterschied. Original-HTML:

~~~ html
<code class="block">        <span class="local-variable">$kl</span> = <span class="predefined">strstr</span>(<span class="local-variable">$p_bild</span>, <span class="string"><span class="delimiter">'</span><span class="content">.</span><span class="delimiter">'</span></span>);
        <span class="local-variable">$source</span> = <span class="string"><span class="delimiter">&quot;</span><span class="content">img/produkte/</span><span class="delimiter">&quot;</span></span>;
        <span class="local-variable">$file</span> = <span class="local-variable">$source</span>.<span class="local-variable">$p_bild</span>;
        <span class="local-variable">$p_bild</span> = <span class="local-variable">$source</span>.<span class="local-variable">$tocken_foto</span>.<span class="local-variable">$kl</span>;

        <span class="predefined">copy</span>(<span class="local-variable">$file</span>, <span class="local-variable">$p_bild</span>);
</code>
~~~

Zitat:

~~~ html
  <code class="block">        <span class="local-variable">$kl</span> = <span class="predefined">strstr</span>(<span class="local-variable">$p_bild</span>, <span class="string"><span class="delimiter">'</span><span class="content">.</span><span class="delimiter">'</span></span>);
        <span class="local-variable">$source</span> = <span class="string"><span class="delimiter">&quot;</span><span class="content">img/produkte/</span><span class="delimiter">&quot;</span></span>;
        <span class="local-variable">$file</span> = <span class="local-variable">$source</span>.<span class="local-variable">$p_bild</span>;
        <span class="local-variable">$p_bild</span> = <span class="local-variable">$source</span>.<span class="local-variable">$tocken_foto</span>.<span class="local-variable">$kl</span>;

        <span class="predefined">copy</span>(<span class="local-variable">$file</span>, <span class="local-variable">$p_bild</span>);
  </code>
~~~

Der einzige Unterschied ist, dass bei dem Zitat das ganze im `<blockquote>` steckt.

**Comment by MatthiasApsel** [comment]
Firebug zeigt;
Original: 
![oiginal](https://cloud.githubusercontent.com/assets/2847625/7386845/8be0901c-ee58-11e4-9578-1a8b5cc2d434.png)

Zitat:
![zitat](https://cloud.githubusercontent.com/assets/2847625/7386851/9b0972c0-ee58-11e4-91fe-6953054b26c1.png)

> Der einzige Unterschied ist, dass bei dem Zitat das ganze im <blockquote> steckt.

Und dort eingerückt ist. Wenn man die mal testweise rausnimmt? Falls das überhaupt machbar ist?

Also statt
~~~
<blockquote>
  <code>
  </code>
</blockquote>
~~~

~~~
<blockquote>
<code>
</code>
</blockquote>
~~~

Denn Markdown meint auch [Um einen Code-Block in Markdown zu erstellen, wird einfach jede Zeile des Blocks mit mindestens 4 Leeerzeichen oder einem Tab eingerückt.](http://markdown.de/syntax/index.html#precode)

**Comment by ckruse** [comment]
Du hast recht mit der Einrückung, das ist mir zuerst gar nicht aufgefallen. Hm. Mal sehen...

**Comment by MatthiasApsel** [comment]
Jetzt siehts schick aus :)
