### ISSUE TITLE
Latex-Unterstützung?

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#377]
Wär das was?

**Comment by ckruse** [comment]
Da hatten wir schonmal drüber gesprochen, ich halte da ehrlich gesagt nicht viel von. Enorme Komplexität (man muss das ja auch sicher kriegen) für zweifelhaften Nutzen.

**Comment by MatthiasApsel** [comment]
Einverstanden. Im alten Forum wurde es auch nur sporadisch / praktisch gar nicht genutzt. Vielleicht kann man ja auf irgendsowas (https://www.google.de/search?q=online+latex+to+png) verlinken?

**Comment by ckruse** [comment]
Hat denn jemand danach gefragt?

**Comment by MatthiasApsel** [comment]
Nein, bisher noch nicht. Aber es gab schon immer mal mathematische Fragen. Und deshalb wäre es schön, wenn in einem Fachforum auch die Möglichkeit bestünde, mathematische Ausdrücke korrekt darzustellen.

**Comment by ckruse** [comment]
In dem Fall würde ich das einfach ignorieren... wer Wert darauf legt wird von selber auf die Idee kommen LaTeX-Ausdrücke zu konvertieren, der Rest wird das eh nicht nutzen.

**Comment by MatthiasApsel** [comment]
Einverstanden: Milestone 5.0 ;-)
