### ISSUE TITLE
Threads mit interessanten Beiträgen kennzeichnen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#378]
Wenn ein zugeklappter Thread als interessant markierte Beiträge enthält, könnte/sollte das gekennzeichnet werden, zum Beispiel durch [einen halben Stern](http://fortawesome.github.io/Font-Awesome/icon/star-half-o/) und das entsprechende Title-Attribut "enthält {%num} interessante Beiträge".

**Comment by MatthiasApsel** [comment]
Kann man einen Beitrag schon als interessant markieren, wenn man ihn noch garnicht gelesen hat? ;-) Im Threadbaum sollte man  nur bereits gelesene Beiträge als interessant markieren können.

Die Markierungsmöglichkeit sollte es auch in der Beitragsansicht geben.

Änderung der title-Attribute nach performers Vorschlag: "als interessant markieren / Interessant-Markierung  entfernen"

**Comment by ckruse** [comment]
Das sehe ich anders. Es macht IMHO überhaupt keinen Sinn, die Funktion von Gelesen-Status abhängig zu machen. Das verwirrt nur den User: mal ist das Icon da, mal nicht. Auch wenn man sich überlegt, wie der User das Forum oft nutzt: Nachricht im neuen Fenster/Tab öffnen und nach dem Lesen das Fenster/den Tab wieder schliessen. Da wäre dann das Icon nicht da, obwohl man es eigentlich dort haben will.

Nein, eigentlich finde ich den Ansatz von Performer, dass man **nur** im Beitrag interessant markieren kann, viel sinnvoller. Da bin ich nur noch nicht zu gekommen ;)

**Comment by ckruse** [comment]
Hm, ich hab das mal eingebaut, in schwarz, aber das sieht scheisse aus:

![screenshot from 2015-05-16 12-07-20](https://cloud.githubusercontent.com/assets/175095/7665692/26edac02-fbc4-11e4-8a16-033b9f3e8f72.png)

Da müssen wir noch was dran tun. Vorschläge?

**Comment by MatthiasApsel** [comment]
Ich würde einfach den Stern, der das Startposting als interessant markiert, verwenden. Und zwar grün (#8db243). Wenn das Startposting auch als interessant markiert ist, ist der Stern eben komplett ausgefüllt. Am wichtigsten ist die Anzeige, wenn der Thread zugeklappt ist. Bei einem geöffneten Thread kann man sich überlegen, ob man diese Info sogar ganz weglässt.

**Comment by ckruse** [comment]
Genau das wollte ich vermeiden, weil es dann dem Symbol eine schwer zu erfassende Doppel-Bedeutung zukommen lässt. Ich probier nochmal was rum...

**Comment by ckruse** [comment]
Mit dem Grün sieht das wieder recht gut aus. Ich schalte das mal online, mal sehen wie die Reaktionen sind.

**Comment by MatthiasApsel** [comment]
Versuch mal zusätzlich noch den Stern nicht "grün-transparent" zu machen sondern "grün-weiß".

**Comment by MatthiasApsel** [comment]
einfach ein weißer Hintergrund sieht blöd aus.
Man könnte einen weißen und einen grün-transparenten übereinander legen, der weiße als before- und der grün-transparente als after-Pseudoelement

**Comment by ckruse** [comment]
Dann gibt es halt ein weisses Viereck um den Stern drum herum.

**Comment by ckruse** [comment]
Ich denke, da macht es mehr Sinn daraus eine Grafik zu machen (`asset-data-url`)
