### ISSUE TITLE
Zitate zusammenfalten soll auch für zitierte Zitate gelten

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#379]
Der Klick auf das äußere Zitat lässt das innere eingeklappt. Ich halte es für sinnvoll, wenn nach einem Klick das gesamte Zitat zu sehen ist. Man könnte das auch anders sehen. Wenn es auch aus deiner Sicht sinnvoll ist, ...

Zudem würde ich gern aus 

`[...]` bzw. `- zitierten Text anzeigen -` Span-Elemente machen, die die Farbe unbesuchter Links bekommen und unterstrichen werden.

**Comment by ckruse** [comment]
Ich hatte das eigentlich absichtlich so implementiert, weil ich das sehr angenehm finde nur einen Teil des Kontexts zu sehen, halt gerade soviel wie ich brauche.

Bzgl der Trigger-Geschichten: ich lasse es nicht unterstreichen weil ich finde, dass das schlimm aussieht. Aber ich habe es in den Link-Farben.

**Comment by MatthiasApsel** [comment]
> Ich hatte das eigentlich absichtlich so implementiert, weil ich das sehr angenehm finde nur einen Teil des Kontexts zu sehen, halt gerade soviel wie ich brauche.

Das ist sicher Geschmackssache. Damit habe ich kein Problem.

> Bzgl der Trigger-Geschichten: 

Sieht in Linkfarbe gut aus. Ich meine mich zu erinnern, auch `[...]` in diesem Zusammenhang gesehen zu haben. Habe ich mich geirrt?

Schön wäre es jetzt noch, wenn der Focus wieder entfernt wird, der blnkende Textcursor stört irgendwie.

**Comment by ckruse** [comment]
> Ich meine mich zu erinnern, auch `[...]` in diesem Zusammenhang gesehen zu haben. Habe ich mich geirrt?

Naja, zumindest hast du das nicht im CForum so gesehen :)

**Comment by ckruse** [comment]
Hm, welches Element hat denn den Fokus? Ich entferne das zusammen gefaltete Element ja vollständig aus dem Baum.

**Comment by MatthiasApsel** [comment]
keine Ahnung. Ich weiß auch nicht, wie ich das herausbekommen könnte. Auf jeden Fall ist der blaue Strich im Bild der Textcursor. An diese Stelle kann man den Cursor mit der Tastatur gar nicht setzen.

![focus](https://cloud.githubusercontent.com/assets/2847625/7666645/051cd818-fbed-11e4-94d8-eb1fad654b21.png)

**Comment by ckruse** [comment]
Hm. Interessant.

~~~
$(document).on('focus', function(ev) { console.log(ev.target); });
~~~

kannst du das mal nach dem Laden der Seite in der Konsole ausführen und dann ein Element ausklappen? Weil bei mir wird kein Fokus gesetzt.

**Comment by MatthiasApsel** [comment]
Antwort: Document 1640627#m1640627

Aber selbst,wenn ich zum Beispiel in http://forum.selfhtml.org/meta/2015/may/16/link-xxxx-forum-nach-einem-detail-view/1640632/new den Focus in eines der input-Felder setze, bekomme ich keine andere Angabe, dort natürlich `document new`

**Comment by ckruse** [comment]
hm, was kommt wenn du nach dem aufklappen eines Zitats das hier ausführst?

~~~
console.log(document.activeElement)
~~~

**Comment by MatthiasApsel** [comment]
Das Verhalten kann ich nur im Firefox nachstellen, Chrome, IE und Opera tun das nicht.

**Comment by MatthiasApsel** [comment]
> `console.log(document.activeElement)`

body

**Comment by ckruse** [comment]
faszinierend. Wieso hast du dann da einen Cursor? Weder ist `contentEditable` gesetzt noch ist das Element fokusiert.

**Comment by MatthiasApsel** [comment]
Wahrscheinlich weil Firefox doof ist. An dieser Stelle befindet sich auch kein Elementinhalt. Dort sind überlappende margins von p und blockquote.

**Comment by ckruse** [comment]
Ich hake das mal als Browserbug ab...
