### ISSUE TITLE
maximale Anzahl von Tags

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#381]
Um Wildwuchs bei den Tags zu vermeiden, könnte es eine maximale Anzahl verwendbarer Tags geben.

**Comment by ckruse** [comment]
Gibt es doch. Genau drei pro Nachricht aktuell.

**Comment by MatthiasApsel** [comment]
Um es mit 6 aus 49 zu vergleichen: Wir haben eine Grenze für die 6, nicht aber für die 49.

**Comment by dedlfix** [comment]
Finde ich jetzt nicht so prickelnd die Idee. Wildwuchs kann man auch innerhalb der Grenze erzeugen und dann ist kein Platz mehr für wirklich sinnvolle Tags. Der Wildwuchs sollte durch die Administratoren gejätet werden.

**Comment by MatthiasApsel** [comment]
Dann sollten die Administratoren eine Benachrichtigung erhalten, wenn ein neues Tag erstellt worden ist.

**Comment by dedlfix** [comment]
Es müsste eine generelle Lösung für die Frage "Was geht in diesem Forum vor?" geben. Benachrichtigungen sind da weniger hilfreich. Eher sowas wie "Spezial:Logbuch" wie im Wiki. Die üblichen Aktivitäten in Threads (neue erstellen, antworten und bewerten) brauchen da nicht zu erscheinen, die sieht man ja jetzt schon nachverfolgbar.

**Comment by ckruse** [comment]
Fixed durch Audit-Log
