### ISSUE TITLE
Beitrag bearbeiten ist u.U. fehlerhaft

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#382]
Folgendes Szenario:
- Beitrag bearbeiten
- Vorschau
- Abbrechen

Der Klick auf Abbrechen sollte zurück zum Beitrag führen, er bleibt aber beim Bearbeiten.

**Comment by ckruse** [comment]
Das Problem ist die URL. Das ist die gleiche URL wie für die Preview. Deshalb folgt der Browser der URL nicht.
