### ISSUE TITLE
Code in Zitaten ist u.U. fehlerhaft

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#383]
Siehe http://forum.selfhtml.org/meta/2015/may/03/zitierter-code-wird-fehlerhaft/1639326#m1639326

**Comment by MatthiasApsel** [comment]
Es hängt offenbar mit der nested-Ansicht zusammen.

**Comment by ckruse** [comment]
Fixed. (Und nein, tat es nicht :-) Ansonsten wäre es total super, wenn du solche Sicherheitsprobleme mir via Mail oder so mitteilen würdest, denn so setzt du mich unter Druck alles stehen und liegen lassen zu müssen um das zu fixen. War immerhin eine XSS-Lücke...

**Comment by MatthiasApsel** [comment]
Sorry. Das war mir an der Stelle gar nicht bewusst und ist mir erst jetzt klar geworden. Die letzte (meiner Meinung nach) Sicherheitslücke hab ich dir per Mail mitgeteilt. (Benutzer der eine vorhandene E-Mail-Adresse als Benutzernamen verwenden möchte) Du kannst sicher sein, wenn ich das als Sicherheitsproblem eingestuft hätte, hätte ich das nicht öffentlich gemacht.

**Comment by ckruse** [comment]
öffentlich machen ist richtig und wichtig, nur halt mit einer "Galgenfrist" damit ich überlegen kann, was der beste Weg ist und mir das zeitlich auch einteilen kann ;-)

**Comment by MatthiasApsel** [comment]
Wie gesagt, es war keine Absicht. Da zeigt sich halt wieder, dass ich kein Software-Entwickler bin ...

**Comment by ckruse** [comment]
Ich wollte dir keinen Vorwurf machen. Alles gut, ich sass ja eh am Rechner. Dachte nur ich weise darauf hin.
