### ISSUE TITLE
Versions: Link zurück zur aktuellen Version

### ISSUE THREAD

**Issue by ckruse** [ckruse/cforum#385]

**Comment by MatthiasApsel** [comment]
Den gibts doch schon. Der Header im Kopf ist quasi ein kompletter Link. Nur wissen das die meisten nicht.

**Comment by ckruse** [comment]
Ja eben ;-) Also ist er nutzlos.

**Comment by MatthiasApsel** [comment]
~~~css
.thread-message header h2 a,
.thread-message header h3 a,
.thread-message header .details a.versions,
.thread-message header.visited h2 a,
.thread-message header.visited h3 a,
.thread-message header.visited .details a.versions {
  color: #3481cd;
}

.thread-message header h2 a:hover,
.thread-message header h3 a:hover,
.thread-message header .details a.versions:hover,
.thread-message header.visited h2 a:hover,
.thread-message header.visited h3 a:hover,
.thread-message header.visited .details a.versions:hover {
  color: #990909;
}
~~~

Die Klasse `versions` muss noch vergeben werden. Ich habe nicht getestet, ob es nicht auch weniger spezifisch geht. Der Link sollte immer hellblau sein. Ich habe ebenfalls nicht getestet, welche Auswirkungen die Pseudoklasse :visited hat.

**Comment by ckruse** [comment]
Wofür soll die Klasse sein?

**Comment by ckruse** [comment]
Für den `editiert von`-Link?

**Comment by MatthiasApsel** [comment]
genau, die Klasse für den Link zu den Versionen.

**Comment by ckruse** [comment]
Dann ist das jetzt online.

**Comment by MatthiasApsel** [comment]
Sieht schick aus.
