### ISSUE TITLE
akzeptierte Antwort u.U. zu breit

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#386]
![akzeptiert](https://cloud.githubusercontent.com/assets/2847625/7499653/66fb954a-f429-11e4-8ab3-d26af129d3a2.png)

An irgendeiner Stelle müsste man kürzen. Ich weiß nicht, was das Sinnvollste wäre, aber das einfachste wäre

~~~css
.thread-message .accepted {
  overflow: hidden;
}
~~~

Deshalb auch mein testedit: Ich wollte wissen, ob der Link zu den Versionen auch mit dargestellt wird.

**Comment by auge8472** [comment]
Spricht außer der einheitlichen Optik etwas gegen mehrzeilige Links zu den akzeptierten Antworten?

**Comment by MatthiasApsel** [comment]
Ein Umbruch sähe gruselig aus, schon bei editierten Beiträgen ist das so. Ich find jetzt gerade keinen, bei dem der header-text umbricht.

**Comment by ckruse** [comment]
ich glaube ich würde eher ein `overflow:scroll` machen

**Comment by MatthiasApsel** [comment]
Das ist, so glaube ich, ein Scherz.

Was hältst du von

#### akzeptierte Antworten zum Thema von ...

und dann die h2 bzw. h3 des Betreffs auf `display: none` setzen?

**Comment by ckruse** [comment]
Von `display:none` halte nicht viel. Aber weglassen kann man den Betreff ;-)
