### ISSUE TITLE
Edit-Diff-Speicherung gezielt ausschalten

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#387]
Wenn auf Wunsch eines Nutzers eine Anonymisierung vorgenommen werden muss, soll dies natürlich nicht dokumentiert werden, weil es ja so trotzdem noch sichtbar ist.

**Comment by ckruse** [comment]
Sichtbar, aber nicht mehr indiziert (noindex, nofollow). Langt das nicht?

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by MatthiasApsel** [comment]
Ich denke nicht, die Information ist ja dennoch erreichbar. Jeder könnte den Link anklicken, nur weil Suchmaschinen den nicht finden, ist sie ja nicht weg. Und wer weiß, ob sich alle Suchmaschinen an das Gentlemens-Agrement, no-follow-Links nicht zu folgen, halten.

Gelöschte Beiträge sind ja auch gelöscht und nicht für jederman unter dem Link "gelöschte Beiträge" erreichbar.

**Comment by ckruse** [comment]
ok, folgender Vorschlag: man bekommt beim Editieren als Admin (und nur als Admin) eine Checkbox "vorherige Versionen löschen". Was sinnvolleres fällt mir einfach nicht ein.

**Comment by MatthiasApsel** [comment]
Das finde ich eine sehr sinnvolle Lösung.

**Comment by MatthiasApsel** [comment]
Falls du das nicht schon umgesetzt hast, funktioniert es im meta-Forum nicht richtig. Ich habe http://forum.selfhtml.org/meta/2015/may/11/vorschlag-fuer-neuen-tag-typographie-oae/1640108/edit geändert und es gibt aber keine editierten Versionen.

**Comment by ckruse** [comment]
Nein, habe ich noch nicht implementiert. Was hast du denn geändert? Wenn
sich content und subject nicht geändert haben, gibt es keine neue Version.

**Comment by MatthiasApsel** [comment]
Ich habe vor und nach der Liste Leerzeilen eingefügt, um aus der Liste tatsächlich eine Liste zu machen.

**Comment by ckruse** [comment]
Oh huch, falsche Reihenfolge im Code. Jetzt werden wieder Versionen angelegt.

**Comment by MatthiasApsel** [comment]
Hm. Haut nicht hin. Details siehe Mail.

**Comment by MatthiasApsel** [comment]
Der Link zu den Versionen sollte weg, wenn die alten Versionen gelöscht werden.
