### ISSUE TITLE
Positionierung der Fußnoten vor die Signatur

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#390]
siehe http://forum.selfhtml.org/meta/2015/may/18/position-von-fussnoten/1640833#m1640833

**Comment by MatthiasApsel** [comment]
Zitierte fußnoten sollten direkt unter das Zitat.

**Comment by ckruse** [comment]
Das mit den zitierten Fussnoten kriegen wir ziemlich sicher nicht hin.
