### ISSUE TITLE
PM als ungelesen markieren

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#391]
wäre eine gute Idee.

**Comment by ckruse** [comment]
Braucht man das wirklich? Mir fehlt da irgendwie das Anwendungsbeispiel...

**Comment by MatthiasApsel** [comment]
Wenn ich ein PM bekomme, diese aber aus Zeitgründen erst am Nachmittag beantworten kann, kann ich auf diese Weise mir eine Erinnerung schaffen, weil oben rechts dann "Post (1)" steht.
