### ISSUE TITLE
"Irgendetwas ist schiefgelaufen, keine Ahnung was ..." soll Mail an dich senden

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#394]
Währe das sinnvoll?

**Comment by ckruse** [comment]
Ich bin dir weit voraus: die Vorbereitungen dafür sind bereits getroffen
(Liste eingerichtet, Filter-Regeln, etc), ich hatte nur noch keine Zeit
das umzusetzen ;-)
