### ISSUE TITLE
sporadisch nicht funktionierende Funktionssymbole für Threads

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#395]
Hallo

Immer wieder passiert es mir, dass beim ausblenden oder gelesen markieren eines Threads in der Übersicht eines Forums die Meldung „Etwas ist schief gegangen“ erscheint. Manchmal funktioniert es einige Minuten später wieder, manchmal kann ich den Thread (wie diesen: [Piwik-Login](http://forum.selfhtml.org/self/2015/may/01/piwik-login/1639066#m1639066) von glupto) auch am nächsten Tag nicht ausblenden.

**Comment by ckruse** [comment]
Hm - sehr merkwürdig. Ich zieh mir heute abend mal einen Datenbank-Dump
und schau mir das mal genauer an.

**Comment by ckruse** [comment]
Kannst du das nochmal ausprobieren? Ich bekomme jetzt bei Fehlern eine Mail mit nem Stacktrace, dann kann ich das vllt nachvollziehen.

**Comment by auge8472** [comment]
Habe soeben (2015-05-21 15:51 MESZ) das Ausblenden getestet und beim oben verlinkten Thread den Fehler ausgelöst.

**Comment by ckruse** [comment]
Hm, ich krieg einen CSRF-Fehler im Log. Kannst du mal im Web-Inspector schauen, ob das hidden-Feld `authenticity_token` übereinstimmt mit dem Wert von `<meta name="csrf-token">`?

**Comment by auge8472** [comment]
Wo in der [Übersichtseite des SelfHTML-Forums](http://forum.selfhtml.org/self) finde ich das Hidden-Feld? Ich finde nur ein Meta-Element namens csrf-param, welches `authenticity_token` als Inhalt des Attributs `content` mit sich führt.

Nicht, dass wir aneinander vorbei reden.

**Comment by ckruse** [comment]
Faszinierend. Kannst du mal mit der Konsole den HTTP-Request verfolgen? (Sorry für die Mühe, ich kann das bei mir nicht nachvollziehen)

**Comment by ckruse** [comment]
Interessant sind Header und Content sowohl des Requests als auch der Response.

**Comment by auge8472** [comment]
Mir ist soeben wieder etwas „schiefgelaufen“. Ich wollte [dieses Posting](http://forum.selfhtml.org/self/2015/may/21/facebook-share-button-plus-infos-auf-statischer-html-seite-einbauen/1641131#m1641131) bewerten, wobei die mir sattsam bekannte Meldung aufpoppte.

Diesmal habe ich sofort in den Quelltext geschaut und tatsächlich, die Tokens des Meta-Elements und des Formulars der Bewertungsfunktion unterscheiden sich. Da ich nicht weiß, ob ich die hier veröffentlichen soll, kannst du sie auf Anfrage haben.

PS: Wegen der Verfolgung des Requests werde ich dich kontaktieren.

**Comment by ckruse** [comment]
Im Ernst? Die Tokens unterscheiden sich?! WTF?!

**Comment by ckruse** [comment]
Mir die Tokens zukommen zu lassen macht keinen Sinn, die gelten für mich nicht (die sind User-spezifisch). Aber die hier nicht zu veröffentlichen war eine gute Idee ;-)

**Comment by auge8472** [comment]
> Faszinierend. Kannst du mal mit der Konsole den HTTP-Request verfolgen?

Mit Live HTTP headers (sorry, mit der Webkonsole von Firefox komme ich nicht zurecht) stelle ich folgendes fest. Will ich den oben verlinkten Thread „Piwik-Login“ ausblenden, geht **kein Request** raus. Ebenso ergeht es mir beim bewerten wollen des heute morgen erwähnten Postings.

Bei anderen Threads und Postings, bei denen die Funktionen tun, was sie sollen, geht jeweils ein Request raus.

**Comment by ckruse** [comment]
aber es kommt die rote Box, dass da was schief gelaufen sei?

**Comment by auge8472** [comment]
> aber es kommt die rote Box, dass da was schief gelaufen sei?

Jep.

**Comment by ckruse** [comment]
Ich hole mir jetzt das Token aus den Meta-Tags, kannst du bitte prüfen, ob es jetzt geht? Falls ja muss ich nur noch herausfinden, warum die Tokens differieren...

**Comment by auge8472** [comment]
[Die Übersichtsseite](http://forum.selfhtml.org/self) neu geladen und versucht, [den nämlichen Thread](http://forum.selfhtml.org/self/2015/may/01/piwik-login/1639066#m1639066) auszublenden: *Fehler*.  
[Woodfighters Posting](http://forum.selfhtml.org/self/2015/may/21/facebook-share-button-plus-infos-auf-statischer-html-seite-einbauen/1641131#m1641131) neu geladen und versucht abzustimmen: *Fehler*.

**Comment by ckruse** [comment]
Ich will ehrlich sein: ich bin ernsthaft ratlos.

**Comment by auge8472** [comment]
Aus der vor kurzem aufgerufenen Übersicht des SelfHTML-Forums habe ich folgende (hier gekürzte) Tokens extrahiert.

Meta.csrf-token: bQqmQn4W…StbQ==
Input.hidden: FlMC421S…s7nw==

Ich habe natürlich nicht alle Inputs aller Threads geprüft, aber bei sechs willkürlich ausgewählten, war es immer der angegebene Token. Natürlich habe ich auch um den Piwik-Login-Thread herum geprüft und das gleiche Ergebnis erzielt. Interessant ist, dass sich die beiden Threads ober- und unterhalb von Piwik-Login ausblenden ließen, Piwik-Login selbst aber nicht. ???

**Comment by ckruse** [comment]
ich habe jetzt mal debug code eingebaut (ein `console.log`). kannst du mal prüfen, ob du in der Konsole etwas siehst?

**Comment by auge8472** [comment]
Wenn kein Fehler auftritt:

~~~
POST 
XHR 
http://forum.selfhtml.org/self/2015/may/09/browser-version-erkennen-und-weiterleiten/hide.json [HTTP/1.1 204 No Content 190ms]

~~~


Wenn ein Fehler auftritt:

~~~
12:20:47.946 Object { readyState: 0, getResponseHeader: .ajax/w.getResponseHeader(), getAllResponseHeaders: .ajax/w.getAllResponseHeaders(), setRequestHeader: .ajax/w.setRequestHeader(), overrideMimeType: .ajax/w.overrideMimeType(), statusCode: .ajax/w.statusCode(), abort: .ajax/w.abort(), state: .Deferred/n.state(), always: .Deferred/n.always(), then: .Deferred/n.then(), 11 weitere… } "error" ""1 application-33a8c019be34c829c613d965b0d4bcfa2187b1415901ddfb4e7d61c5546e1241.js:479:14499
~~~

**Comment by ckruse** [comment]
Hm, kannst du mal das hier in der Konsole auf der Index-Seite ausführen?

~~~ js
$("#t246093 .thread-icons form:nth(1)").submit();
~~~

Wird dann der Thread ausgeblendet?

**Comment by ckruse** [comment]
Wirklich schwierig zu debuggen ist es halt deshalb, weil ich dieses Problem bei mir lokal nicht reproduzieren kann. Übrigens auch nicht auf dem Server, ich kann den Thread problemlos ausblenden...

**Comment by auge8472** [comment]
> Hm, kannst du mal das hier in der Konsole auf der Index-Seite ausführen?

Schwein+Uhrwerk=Öhhm

Wie mache ich das? Die browsereigene Konsole in den Entwicklertools des FF 38 ist read-only. ich kann dort keine Befehle eingeben.

**Comment by ckruse** [comment]
Unter der Konsole ist ein Eingabe-Feld, einzeilig, da kann man beliebiges JS evaluieren

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by ckruse** [comment]
![screen shot 2015-05-22 at 15 04 16](https://cloud.githubusercontent.com/assets/175095/7770957/da3b85bc-0093-11e5-8f51-7c1f9ecb7284.png)

Da wo der blaue Doppelpfeil ist.

**Comment by auge8472** [comment]
So, eingegeben und ausgeführt. Der Thread wurde durch das Neuladen der ganzen Seite und mit folgend eingeblendeter Erfolgsmeldung ausgeblendet. Brauchst du die Angaben aus der Konsole und wenn ja, lasse ich sie dir ganz Oldschool per Email zukommen?

Jetzt habe ich mich des Studienobjekts beraubt. :-)

**Comment by ckruse** [comment]
Nein, die helfen mir nicht weiter, leider. 😤 danke für die Mitarbeit... Ich werde mal eine Pause machen, vllt sehe ich ja dann was schief läuft

**Comment by ckruse** [comment]
Ich habe jetzt mal etwas mehr Debug code eingebaut, magst du das nochmal testen und mir die Ausgabe aus der Konsole zukommen lassen? Du kannst den Thread ja wiederherstellen.

**Comment by auge8472** [comment]
Morgen, wenn ich auf Arbeit bin (Arbeitszeit ist Leistungszeit!).

**Comment by ckruse** [comment]
;-D

**Comment by auge8472** [comment]
> … magst du das nochmal testen und mir die Ausgabe aus der Konsole zukommen lassen?

Mag ich wohl, aber …

> Du kannst den Thread ja wiederherstellen.

… *das* kann ich nicht. In der Übersicht der ausgeblendeten Threads fehlt der Piwik-Thread. So weit ich das nach erstem Augenschein überblicke, fehlen weitere Threads, die ich in der letzten Zeit ausgeblendet habe. Ich kann zwar nicht sagen, welche es sind – ich habe die ja nicht umsonst ausgeblendet –, aber da sind noch Threads aus dem Jahr 2014, also sollten die Neueren auch da sein.

Die Sortierung der ausgeblendeten Threads (von alt nach neu) ist auch etwas gewöhnungsbedürftig, ist es doch im Forum gerade anders herum.

**Comment by MatthiasApsel** [comment]
Dann sollte sich die eingestellte Sortierung auch auf alle derzeitigen und noch gebildeten Teilmengen von Threads auswirken.

**Comment by auge8472** [comment]
Ich zitiere mich mal selbst.

> In der Übersicht der ausgeblendeten Threads fehlt der Piwik-Thread.

Ich habe noch einmal etwas genauer hingeschaut. Der älteste Thread in der Liste der ausgeblendeten threads stammt vom 23.11.2014, der jüngste in der Liste aufgeführte stammt vom 17.03.2015. Das sind alles Threads, die *aus dem alten Forum* stammen.

Kann es sein, dass die aktuell ausgeblendeten Threads auf einer anderen Seite, die ich zu finden unfähig bin, aufgeführt werden? Oder ist das ein Bug, den noch keiner gefunden hat, weil sich typischerweise keiner mehr die von ihm ausgebledenten Threads anschaut?

**Comment by ckruse** [comment]
Das war Zufall. Das liegt daran, dass die Threads aufsteigend nach Datum sortiert wurden und nach 50 Threads die Seite voll war. Das eigentliche Problem war, dass ich vergessen hatte unten den Pager einzufügen... ;-) ein echter [brown paper bag bug](http://www.catb.org/jargon/html/B/brown-paper-bag-bug.html)

**Comment by auge8472** [comment]
Schön, bevor ich mich dran setze noch ein Hinweis zur Pagination. Das Phänomen mit den 50 Threads trat sowohl mit ein- als auch mit abgeschalteter Pagination auf. Soweit ich das jetzt sehe, ist die Pagination bei den ausgeblendeten Threads *grundsätzlich* eingeschaltet. Ich weiß nicht, ob es sinnvoll ist, sie in dieser Hinsicht analog zu den Hauptansichten zu behandeln.

*Bei mir* hat die Übersicht des SelfHTML-Forums zwei Seiten, die Übersicht der ausgeblendeten Threads jedoch derer sieben. Überlegen kann man ja mal.

**Comment by ckruse** [comment]
Ich habe die Pagination an der Stelle mit Absicht nicht ausschaltbar gemacht. Während bei der Hauptdatei der Aufwand abschätzbar ist (durch das Archivieren) gilt das für ausgeblendete Threads nicht. Hier können theoretisch ausgeblendete Threads seit 1998 drin sein.

**Comment by auge8472** [comment]
> Hier können theoretisch ausgeblendete Threads seit 1998 drin sein.

Oh, das war mir nicht klar. Ich dachte, ein Thread, der im Archiv landet, fliegt auch aus der Ausgeblendet-Liste heraus.

**Comment by auge8472** [comment]
***Zurück zum Thema***

Thread wiederhergestellt, Konsole mit dem oben genannten Code befüllt und heute (2015-05-27 16:46 MESZ) Ausführung ausgelöst.

~~~
Object { 0: <form.button_to>, length: 1, prevObject: Object, context: HTMLDocument → self, selector: "#t246093 .thread-icons form:nth(1)" }
"Select2: The lanugage file for "select2/i18n/de" could not be automatically loaded. A fallback will be used instead."
~~~

Ob die zweite Zeile zur relevanten Ausgabe gehört, bezweifle ich. Sie erschien binnen ein paar Zehntelsekunden nach der ersten Zeile.  Sie hier zu zeigen, wird aber vermutlich nicht schaden.

**Comment by auge8472** [comment]
Zweiter Test:

Thread wieder wiederhergestellt und den Thread über den Button **erfolgreich ausgeblendet** (2015-05-27 16:53 MESZ).

**Comment by ckruse** [comment]
ok, ich bin ratlos. Ich würde folgendes vorschlagen: ich lass den Debug-Code drin und wenn das nochmal auftritt, sagst du bescheid. Ist das in Ordnung?

**Comment by auge8472** [comment]
Klar doch.

**Comment by auge8472** [comment]
Mist, vergessen. \***grml**\*

Heute vormittag gegen 10:30 Uhr (MESZ) war es mal wieder soweit. Diesmal war es die Übersicht des SelfHTML-Forums, in der sich die drei Threads, die am 31.05.2015 gestartet wurden, weder als gelesen markieren noch (testweise) ausblenden ließen. In der Meta-Übersicht konnte ich den [Thread zu den Wiki-Disskussionseiten](http://forum.selfhtml.org/meta/2015/may/31/wiki-diskussionsseiten/1641859#m1641859) problemlos ausblenden.

Da die Übersichtsseite des SelfHTML-Forums kurze Zeit später neu geladen wurde, konnte ich leider nicht nach differierenden Tokens gucken.

**Comment by ckruse** [comment]
Ich kann den Fehler jetzt nachvollziehen. Aber ich bin absolut ratlos, woran das liegt. Das XHR-Objekt wirft eine Exception `InvalidAccessError`. Lt. Standard sollte das aber gar nicht passieren… `async` ist `true`, `timeout` ist `0`, `withCredentials` ist `false` und `responseType` ist ein Leerstring. Wirklich faszinierend.

**Comment by ckruse** [comment]
Oh wow, hast du zufällig uBlock oder sowas aktiv?

**Comment by ckruse** [comment]
Ahaha, ja, daran scheint es zu liegen. Deshalb auch so sporadisch. Folgendes passiert: der Blocker überschreibt `XMLHttpRequest.open()` und prüft, ob eine URL geblockt werden sollte. Falls ja, wirft er eine Exception (`InvalidAcessError`). Und dann erscheint die oben zitierte Meldung. Deshalb z.B. auch der Thread mit dem Piwik (geblockt wegen Tracking). Bei mir trat das gerade auf bei dem Twitter-Userstylesheet-Thread von frankx auf – Twitter wird bei mir geblockt.

**Comment by auge8472** [comment]
> Oh wow, hast du zufällig uBlock oder sowas aktiv?

Ja, ich habe auf meinem Firmenrechner uBlock an. Dort ist der Fehler auch aufgetreten.

**Comment by ckruse** [comment]
Na dann haben wir ja endlich des Rätsels Lösung gefunden :)
