### ISSUE TITLE
retaggen funktioniert nicht

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#396]
Ich möchte und darf [ein Posting](http://forum.selfhtml.org/self/2015/may/26/tags/1641431) retaggen.

Ich trage also einen neuen Tag ein und speichere die Änderung über den dafür vorgesehenen Button ab. Nach dem laden der Ergebnisseite wird mir auch der neue Tag angezeigt. Kehre ich danach zum Thread zurück, fehlt der neu vergebene Tag. Auch ein Neuladen der Seite über [STRG]+[F5] hilft nicht.

Noch ein Hinweis: Kurz vor meinem Retag-Versuch scheint jemand anderes das Eröffnungsposting des Threads retaggt zu haben. Dieses hat nun das Tag "zu diesem forum", das es vor einigen Minuten noch nicht hatte.

**Comment by MatthiasApsel** [comment]
> Kurz vor meinem Retag-Versuch scheint jemand anderes das Eröffnungsposting des Threads retaggt zu haben. Dieses hat nun das Tag "zu diesem forum", das es vor einigen Minuten noch nicht hatte.

Das war ich.
