### ISSUE TITLE
Benachrichtigungen sammeln sich an

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#399]
**Szenario:**
1. Ich habe mehrere Tabs mit verschiedenen Forenseiten offen.
2. Ich habe die Benachrichtigung mittles der Forenfunktion z.B. für Antworten auf meine Postings aktiviert.
3. Einzelne Tabs werden ohne Notwendigkeit nicht aktualisiert.
4. Ich lese die Antworten auf meine Postings.

In den nicht aktualisierten Tabs steigt die Anzahl der Benachrichtigungen an, obwohl ich diese in einem anderen Tab zur Kenntnis genommen bzw. die betreffenden Postings gelesen habe. Im Gegensatz dazu stellen Tabs, die ich aktualisiere, die Anzahl der vorhandenen Benachrichtigungen zurück, weil die Seiten mit der korrekten Anzahl der Benachrichtigungen frisch vom Server geladen werden.

Es werden also neue Benachrichtigungen an den Browser gepusht, es gibt aber keinen Push für „verfallene“ Benachrichtigungen. Das empfinde ich – um mal die Dringlichkeit einzuordnen – als inkonsequent, aber nicht als Beinbruch.

**Comment by ckruse** [comment]
Hab mich schon gefragt wie lange es dauert, bis das wem auffällt ;-) Wird aber nichts vor 4.2

**Comment by ckruse** [comment]
Oh, das ist übrigens mit der Einführung von ActionCable gefixed worden.
