### ISSUE TITLE
fehlerhafte Weiterleitung nach Beitragslöschung

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#402]
Auch wenn man einen Beitrag löscht, wird man (in der nested-Ansicht) wieder zum urpsrünglichen Beitrag zurückgeleitet. Den gibts dann natürlich nicht mehr.

Man bekommt dann allerdings eine unschöne (Apache?)-Fehlermeldung zu Gesicht. "
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved."

Vielleicht lässt sich da ja was tun.

**Comment by ckruse** [comment]
Ich verstehe das Problem noch nicht. Man sollte doch mit `view_all=yes` weitergeleitet werden?

**Comment by MatthiasApsel** [comment]
in http://forum.selfhtml.org/meta/2015/jun/04/selfhtml-ist-20/1642269#m1642269

administrator-ansicht

beitrag löschen

administrator-ansicht deaktivieren

![unbenannt 1](https://cloud.githubusercontent.com/assets/2847625/8056645/85de3bfc-0eaa-11e5-9198-2be913fa31ff.png)

**Comment by ckruse** [comment]
Naja, gut, da kann ich aber nicht viel machen. Aber wir sollten hübschere Fehlerseiten schreiben.

**Comment by MatthiasApsel** [comment]
- Zur Beitragsseite weiterleiten http://forum.selfhtml.org/meta/2015/jun/04/selfhtml-ist-20/1642207?

Dazu müsste man das Eröffnungsposting kennen.

Wenn ein kompletter Thread gelöscht wurde, nach http://forum.selfhtml.org/meta/ weiterleiten?

**Comment by ckruse** [comment]
Eine Weiterleitung kommt nicht in Frage, damit müsste ich den 404-Status
(der technisch richtig ist) in einen 30x-Status ändern.

Das einzige, was sinnvoll wäre, wäre ein angepasster Link. Aber das
finde ich ehrlich gesagt die Mühe nicht wert…

**Comment by MatthiasApsel** [comment]
Dass Seiten ohne message-number nicht sinnvoll angezeigt werden, ist dir bewusst?

http://forum.selfhtml.org/self/2015/jun/07/seite-von-http-auf-https-umleiten-sinnvoll-oder-nicht/

Lässt sich da was unternehmen?

**Comment by ckruse** [comment]
Das ist mir bewusst. Wie bist du dort hin gekommen? Die Ressource ist
nur für die AJAX-Hooks da, um sich einen Thread-Baum rendern zu
lassen. Ein normaler User sollte dort niemals landen?

**Comment by MatthiasApsel** [comment]
> Wie bist du dort hin gekommen? Durch Eingabe in die Adresszeile, also löschen von `123445/`

**Comment by ckruse** [comment]
Ok, du hast also eine Adresse eingegeben, die so nirgends verlinkt ist und wunderst dich, dass da was passiert, was nicht für den User gedacht ist. Soweit richtig? ;-)

**Comment by MatthiasApsel** [comment]
Gewundert habe ich mich nicht. Auf die Idee mit der URL zu spielen, können ja auch andere kommen. Zum Beispiel könnte man ja unter http://forum.selfhtml.org/self/2015/jun/09/ eine Übersicht der Beiträge des 9.6.2015 erwarten.

**Comment by ckruse** [comment]
Auf die Idee werden andere auch kommen, da bin ich sicher. Aber das ist
ja kein Problem :-)

Bzgl der Tages-Ansicht: eigentlich eine gute Idee.

**Comment by MatthiasApsel** [comment]
Dann ist es aber auch eine gute Idee, auf http://forum.selfhtml.org/self/2015/jun/07/seite-von-http-auf-https-umleiten-sinnvoll-oder-nicht/ eine Übersichtsseite, sprich den Threadbaum, anzuzeigen.

**Comment by ckruse** [comment]
Wird doch. Nur halt ohne Styles. Ich hole mir von dort den Thread-Baum
für die Ajax-Funktionen.

**Comment by MatthiasApsel** [comment]
Ähm ne? Diese Seite enthält genau 1 article-Element, im Original sind es aber 27 Antworten. Nix Baum.

**Comment by ckruse** [comment]
Nur wenn der Thread eingeklappt werden müsste lt Einstellungen. Siehe
auch <http://forum.selfhtml.org/self/2015/jun/07/seite-von-http-auf-https-umleiten-sinnvoll-oder-nicht/?fold=false>

**Comment by MatthiasApsel** [comment]
ah. Ja.
