### ISSUE TITLE
fehlerhafte Darstellung der Bewertungen im Threadbaum

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#404]
Dieser Beitrag http://forum.selfhtml.org/self/2015/jun/04/link-fett-darstellen/1642205#m1642205 hat (zum jetzigen Zeitpunkt) eine positive und eine negative Bewertung. Im Threadbaum steht zu der Null allerdings "noch keine Bewertungen"

**Comment by auge8472** [comment]
> Im Threadbaum steht zu der Null allerdings "noch keine Bewertungen"

Um genau zu sein, steht im title-Attribut "noch keine Bewertungen". Ich habe mir nämlich eben 'nen Wolf gesucht. :-)

~~~html
<span class="votes" title="noch keine Bewertungen">0</span>
~~~

**Comment by ckruse** [comment]
passend dazu die Nummer des issues: 404 ;-)
