### ISSUE TITLE
LaTeX codes in the selfhtml-archive are being escaped

### ISSUE THREAD

**Issue by woodfighter** [ckruse/cforum#406]
Hi,

in an [archived thread](http://forum.selfhtml.org/self/2008/apr/18/unix-timestamp-javascript-verrechnet-sich/1235867#m1235867) (in the second footnote) of the selfhtml forum the underscores in the LaTeX block are being escaped with a backslash. I guess that the original contents the original contents of the posting is converted to kramdown, but the converter isn't aware that kramdown syntax inside a LaTeX block needn't be escaped.

mfg
Woodfighter

P.S. See also <http://forum.selfhtml.org/meta/2015/may/27/latex-im-forum/1642109#m1642109>

**Comment by ckruse** [comment]
Thanks, fixed.
