### ISSUE TITLE
Verschiedene Sprachen für Code-Blöcke anbieten

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#410]
Siehe http://forum.selfhtml.org/intern/2015/jun/24/problem-mit-script/1644017#m1644017

Vielleicht reicht ja

```
'~~~language here
'code text here
'~~~
```

**Comment by campingrider** [comment]
Das wäre eine Möglichkeit, ja... Allerdings ist dann die Gefahr, dass "language here" stehen bleibt. Wirft das dann einen Fehler im Kramdown?

**Comment by MatthiasApsel** [comment]
Kramdown kennt keine Fehler ;-)

Wenn man `language_here`, also ein Wort verwendet, wird es genau wie Code unbekannter Sprache gerendert.
