### ISSUE TITLE
Markdown-Buttons erweitern: Tabelle, Fußnote, ...

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum#411]
Zusätzlich zur Auswahl der Skriptsprache (Issue #410 ) sollten auch weitere fortgeschrittene Markups per Button verfügbar sein, insbesondere:

- Tabellen (hier reicht es mMn ein Pattern einzufügen, dass der User dann erweitern/ausfüllen kann)
- Fußnoten (sollte auf jeden Fall als Button zur Verfügung stehen)
- Latex (mMn wichtig, das als Button zu haben)
- optional: Inline-Code
- optional: Beschreibungslisten

Bei letzteren gibt es imho auch Nachteile, deshalb optional.

**Comment by auge8472** [comment]
Bei Inlinecode bin ich der Meinung, dass der Button *nicht optional* sein sollte. In den letzten Wochen fielen mir immer wieder Postings auf, bei denen das Rendern von Code als Code nicht funktionierte, weil der per Button eingefügte Codeblock ganz offensichtlich Inlinecode auszeichnen sollte. Deshalb gilt mMn für Inlinecode: Wenn, dann weg mit „optional“!

Die restlichen Vorschläge stellen sich mir mit Fragen in den Weg.

Bei LaTex und Tabellen stellt sich mir die Frage nach der Häufigkeit der Benutzung. LaTex wird nur von *sehr wenigen* benutzt. Die wissen dann auch, wie sie es ohne Button(s) notieren. Zudem wäre da wohl mehr als ein Button fällig, oder?

Tabellen werden nach meiner Beobachtung fast immer einfach als Text eingegeben. Das funktioniert natürlich nur solange, wie dicktengleiche Fonts als Standard für den Postingtext benutzt werden. Auch wenn sich die Eingabe der Kramdown-Tabellensyntax durch ein vorgegebenes Schema vereinfachen würde, halte *ich* es für dennoch für umständlich und ich glaube nicht, dass das zu einer merklichen Benutzung führt.

Fußnoten werden auch relativ selten benutzt, wobei ich bisher auch nur nummerierte Fußnoten hinbekommen habe. Fußnoten, die ich mit Text als Identifikator eingegeben habe, funktionieren komischerweise nie. Von daher wäre ich von dem Button begünstigt. Deshalb bin ich gespalten, einerseits wäre der Button (auch für mich) hilfreich, andererseits werden Funßnoten insgesamt recht selten gesetzt.

Mit Beschreibungslisten meinst du `<dl>` mit `<dt>` und `<dd>`? Gebrauchen wir die **im Forum** wirklich?

Insgesamt bin ich der Meinung, dass wir aufpassen sollten, das UI nicht mit tausend, im Zweifelsfall selten benutzten Optionen zu überfrachten.

**Comment by campingrider** [comment]
Für Latex halte ich es für ausreichend, einen Button zu haben, der die $$ erzeugt, welche die Code-Umgebung einleiten. Du hast Recht, dass wer latex nutzen will des latex mächtig sein sollte, aber wie die Codeumgebung für Latex eingeleitet wird ist durchaus von Syntax zu Syntax unterschiedlich, deshalb ein Button dafür.

Inline-Code: stimme ich dir völlig zu.

Tabellen werden imho vA deshalb als Ascii-Art ausgeführt, weil es den Beteiligten zu lästig ist, Tabellensyntax nachzuschauen (oder über diese Möglichkeit nicht Bescheid wissen), das ist ja gerade der Grund, warum ich einen Button für sinnvoll halte, der eine Tabelle zum selber anpassen einfügt.

Fußnoten werden zwar recht selten eingesetzt, sind aber da, wo sie eingesetzt werden, so gut wie immer sinnvoll.

Mit Beschreibungslisten hast du Recht, deshalb das 'optional'. Ich habs auch nur der Vollständigkeit halber erwähnt. Gerne weglassen.

Ich sehe grundsätzlich keine Gefahr, dass die UI mit diesen paar wenigen Buttons mehr überladen wirkt ;)

**Comment by auge8472** [comment]
**Momentan** (2015-06-25 16:27 CEST) gibt es **23 Buttons** als Formatierungshilfe für die Postings. Das ist schon nicht unerheblich, auch wenn man argumentieren könnte, dass die paar weiteren Buttons nun auch nicht mehr auffallen.

In Sachen Tabellen und den Gründen, warum typischerweise ASCII- statt Markdown-Tabellen genutzt werden, bin ich anderer Meinung als du. Die (mMn **aller**-)meisten Benutzer kennen die Markdown-Art, eine Tabelle anzulegen, nicht. Die ASCII-Tabelle hingegen erschließt sich in einer Umgebung mit dicktengleicher Schrift intuitiv. Nun kann man die Tabellen-Markdown-Syntax mit einem entsprechenden Button durchaus popularisieren, wer dreimal eine Tabelle mit dem Button erstellt hat und evtl. noch ein oder zwei Zeilen per copy'n'paste hinzugefügt hat, weiß auch, wie er die Tabelle händisch erzeugt, ich befürchte aber haufenweise verkrüppelte Möchtegern- und Hättenseinsollentabellen, die ich nicht korrigieren müssen möchte.

… und das Ganze mit nur sechs Sätzen … ;-)

**Comment by MatthiasApsel** [comment]
@auge8472 

> ... wobei ich bisher auch nur nummerierte Fußnoten hinbekommen habe. Fußnoten, die ich mit Text als Identifikator eingegeben habe, funktionieren komischerweise nie.

Die Kombination aus [^Zahl] und [^Zahl]: erzeugt eine Fußnote. Die Nummerierung der Fußnoten beginnt bei 1, unabhängig von den gewählten Zahlen, die eigentlichen Fußnoten können als eigene Zeile in beliebiger Reihenfolge an eine beliebige Stelle des Textes gesetzt werden.

**Comment by auge8472** [comment]
@MatthiasApsel: Wie ich schon schrieb, ist die Erzeugung einer Fußnote mit numerischem Bezeichner für mich auch ohne das Zitat aus dem Wiki kein Problem. Was ich nicht hinbekomme, ist eine Fußnote *mit **nichtnumerischem** Bezeichner*. Laut Syntaxdoku auf gettalog.org sind alphabetische Bezeichner möglich.

> [a footnote marker can be created by placing the footnote name in square brackets. The footnote name has to start with a caret (^), followed by a word character or a digit and then optionally followed by other word characters, digits or dashes.](http://kramdown.gettalong.org/syntax.html#footnotes)

Ein Vergleich der Kramdown-Hilfe des Wikis mit der Syntaxdoku auf gettalog.org lässt mich vermuten, dass der Kramdown-Sprachumfang an dieser Stelle beschnitten wurde.

**Comment by MatthiasApsel** [comment]
Ja. Ich wollte darauf hinweisen, dass es bei uns nur mit Zahlen geht.

**Comment by ckruse** [comment]
Ich halte es nicht für sinnvoll, die UI mit noch mehr Buttons aufzublähen. Die am häufigsten genutzten Features sind abgedeckt, der Rest fällt eher in den Bereich "speziell" und der kann in der verlinkten Hilfe nachgeschlagen werden.

**Comment by ckruse** [comment]
Keine Einwände?

**Comment by auge8472** [comment]
Tja, meine Meinung steht oben. Die Frage richtet sich wohl primär an @campingrider .

**Comment by MatthiasApsel** [comment]
Meinetwegen müssen nicht noch mehr buttons sein.

**Comment by campingrider** [comment]
Nein, keine Einwände ;) Wir haben die fürs und widers ja ausführlich diskutiert, und selbst wenn meine Meinung immer noch ähnlich ist wie anfangs, habe ich trotzdem überhaupt kein Problem damit, wenn das so nicht konsensfähig ist. Ist immerhin auch kein wirklich wichtiger Punkt, sondern mehr eine Detailfrage.
