### ISSUE TITLE
Pipe sign in LaTeX leads to table

### ISSUE THREAD

**Issue by woodfighter** [ckruse/cforum#416]
Hi,

again [an archived thread](http://forum.selfhtml.org/self/2010/mar/10/gamephysik-abprall-nach-freiem-fall-durch-gewicht-beeinflussen/1433693) shows the problem. Pipe symbols in LaTeX aren't rendered as expected (in this case as a non optimal representation of the absolute operator), the problem only seems to exist in inline LaTeX, LaTeX blocks are ok. [Upstream knows of the problem](http://kramdown.gettalong.org/syntax.html#math-blocks), but proposes only a workaround (and one which isn't applicable here) . There are probably not many instances of this, so it could be easier to replace those with an suitable alternative directly in the database, but the ones I tried (\abs, \vert, \lvert) don't work (probably because the LaTeX packages that'd be necessary aren't included).

mfg
Woodfighter

**Comment by ckruse** [comment]
Changing the contents in the database is a problem. The content is saved in the original CForum 3.4 format and gets translated to markdown on the fly. This has proven to be the best practice; converting the contents to markdown once has led to a lot of rendering bugs.

That means that we would have to change the old format, which I hesitate to do...

**Comment by ckruse** [comment]
We're waiting for upstream to fix the bug
