### ISSUE TITLE
spam-user entfernen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#418]
Gefühlt 1000 Nutzer haben sich in den letzten Tagen angemeldet mit einer E-Mail-Adresse @sina.com Auch wenn es die Datenbank vielleicht nicht stört, könnte man die Nutzer, die nach sagen wir 3 Tagen noch keinen Beitrag erstellt haben, automatisiert löschen.

**Comment by ckruse** [comment]
Nein, Lurker sollten wir nicht einfach löschen. Da müssen wir uns was anderes überlegen, sind denn die Benutzer bestätigt worden? *guck* ja, sind sie, uns sie haben sich sogar auch eingeloggt.

**Comment by MatthiasApsel** [comment]
Am 2015-07-19 21:06, schrieb Christian Kruse:
> Nein, Lurker sollten wir nicht einfach löschen. Da müssen wir uns was
> anderes überlegen, sind denn die Benutzer bestätigt worden? *guck* ja,
> sind sie, uns sie haben sich sogar auch eingeloggt.


http://forum.selfhtml.org/admin/users?dir=desc&sort=created_at ?

**Comment by ckruse** [comment]
Ja. Jeder User hat sich mindestens zwei mal eingeloggt, einige sogar mehr als zwei mal.

Für die konkrete Welle könnte ich alle User mit `@sina.com` löschen, aber generell alle Lurker-Accounts löschen halte ich nicht für sinnvoll.

**Comment by MatthiasApsel** [comment]
Ich habe auch keinen Plan, was man da macht. Über die IP gibt es in Zeiten von IPv6 nicht mehr so ganz viele Möglichkeiten. Andererseits kommen auch ganz viele echte User mit wahrscheinlich derselben IP. Im Wiki habe ich schon ukrainische IP-Ranges dauerhaft gesperrt. Lesen können die ja trotzdem. Wieviele sinas sind es eigentlich? Ich tippe 500.

**Comment by ckruse** [comment]
hehe, weit daneben:

~~~
selfforum=> select count(*) from users where email like '%@sina.com';
 count 
-------
  1005
(1 row)
~~~

**Comment by ckruse** [comment]
Ich hab die jetzt einfach mal gelöscht...

**Comment by ckruse** [comment]
Ich habe jetzt einen Cleanup-Task geschrieben, der alle User löscht, die nach 7 Tagen noch nicht bestätigt wurden. Damit erwischt man diese `@sina.com`-Leute allerdings nicht, da gibt es nichts was ich tun kann...

**Comment by ckruse** [comment]
(Und ich habe nochmal alle `@sina.com`-User gelöscht...)

**Comment by MatthiasApsel** [comment]
Am 04.08.2015 um 16:15 schrieb Christian Kruse:
> (Und ich habe nochmal alle |@sina.com|-User gelöscht...)

noch mal 1000? ;-)

**Comment by ckruse** [comment]
Nur 742 ;-)

**Comment by auge8472** [comment]
Als ich vorhin mein [User-CSS für die neuen Sortierlinks](http://forum.selfhtml.org/meta/2015/jul/27/beitraege-akzeptieren/1647285#m1647285) getestet habe, standen auf der ersten Seite (Sortierung: erstellt, DESC) schon wieder nur drei nach namen klingende Benutzernamen. Dem täglich hinterherzurennen, kann mMn keine dauerhafte Lösung sein (auch wenn **ich** nicht davon betroffen bin).

Ist die Abfrage eines Dienstes wie Stop-Forum-Spam bei der Registrierung sinnvoll oder handelt man sich dabei unerwünschte Nebeneffekte ein?

**Comment by ckruse** [comment]
Ich kenne den Dienst nicht, kann also nichts zu Nebenwirkungen sagen.

**Comment by ckruse** [comment]
Das Problem ist auch, dass diese Spam-Registrierungen auch bestätigt werden. Ich kann sie also auch nicht automatisiert einfach löschen. Ich werde es mal mit Honeypot-Captchas probieren...

**Comment by ckruse** [comment]
So, done. Und auch nochmal:

~~~
selfforum=> begin;
BEGIN
selfforum=> delete from users where email like '%@sina.com';
DELETE 60
selfforum=> commit;
COMMIT
~~~
