### ISSUE TITLE
Zeilennummern für Codeblöcke

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#419]
siehe http://forum.selfhtml.org/meta/2015/jun/19/feature-wunsch-zeilennummern-fuer-code-bloecke/1643596#m1643596 und dort vor allem "Zeilennummern sind nur dann wirklich sinnvoll, wenn sie auch über Zitate und Verstümmelungen hinweg eindeutig bleiben (denn erst dann kann man sich sinnvoll darauf beziehen)."

**Comment by ckruse** [comment]
Ich habe nicht vor so etwas zu implementieren. Wenn sich jemand anderes findet - bitte. Aber mir ist das zu viel Aufwand für zu wenig Nutzen.
