### ISSUE TITLE
Links "problematische Seite" werden mal angezeigt und mal nicht

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#421]
In diesem Beitrag http://forum.selfhtml.org/meta/2015/jul/22/farbnummmern-in-beispielen/1646465#m1646465 habe ich einen problematische-Seite-Link (pSL) angegeben und danach hatten **alle** Beiträge einen pSL (ich habe nicht geprüft, ob es immer derselbe Link ist)

Anschließend habe ich auf meinen Beitrag geantwortet, ohne einen pSL anzugeben und als Ergebnis hatte **kein** Beitrag mehr einen pSL.

Ich fände es gut, wenn ein vorhandener pSL beim Antworten schon immer eingetragen ist. Für das Editieren müsste es dann die Möglichkeit geben, **alle** pSL eines Threads zu entfernen

**Comment by auge8472** [comment]
Wegen des auch von dir beantworteten Beitrags hatte ich in das Eröffnungsposting geschaut, ob Wiwekus Link zur problematischen Seite überhaupt da wäre. Der wird ja oft genug ignoriert. Es war aber keiner vorhanden. Da scheint noch mehr nicht oder nur manchmal zu funktionieren.
