### ISSUE TITLE
Notifications funktionieren nicht richtig

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#423]
Autovervollständigen geht nicht,
`(@username` sollte ebenso zu einer Benachrichtigung führen. Das hängt sicher mit dem Ausschluss von E-Mail-Adressen zusammen.

**Comment by auge8472** [comment]
Man könnte bei der Prüfung auf eine eventuell vorhandene Emailadresse die Klammer „(“ ausschließen, aber wie weit will man dabei gehen? Was soll erlaubt werden (Bestimmte einzelne Zeichen vor dem „@“, aber nach einem Leerzeichen oder Zeilenumbruch? Keine Zeichen, die nicht in die vorgenannte Gruppe fallen?), was nicht (Mehrere Zeichen vor dem „@“?)?

Falls das bedeutet, dass hier Filter geschrieben und den eventuellen Änderungen an der erlaubten Syntax für den Local Part von Emailadressen angepasst werden müssen, um die Gruppe der erlaubten Zeichen vor dem „@“ zu schützen, stellt sich die Frage, ob es das wert ist. Funktioniert denn das Mention bei Twitter und ähnlichen Diensten, wenn der Name in Klammern steht? Wenn nicht, haben deren Nutzer sich an diese Einschränkung gewöhnt. Dann können wir das den Unseren auch zutrauen.

**Comment by MatthiasApsel** [comment]
derzeit sieht es so aus:
`if(c == '@' && (i == 0 || text.substr(i - 1, 1).match(/\s/)) )`
könnte 
`if(c == '@' && (i == 0 || text.substr(i - 1, 1).match(/\s|\(/)) )`
werden.

**Comment by auge8472** [comment]
Mit diesem Kostrukt erwischst du *zusätzlich zum bisherigen Verhalten* genau nur die öffnende Klammer. Das ist genug für den momentanen Fall und die in der deutschen Sprache gängige Notation. Mal sehen, wann der Nächste ein anderes Zeichen vor das @ als Einleitung der/des (?) Mention schreiben will. ;-)

**Comment by MatthiasApsel** [comment]
Ja. Ich hab es so mal in meinen aktuellen Pull-Request eingebaut. Allerdings ist das nur das Auslösen des Autocomplete. Das Versenden der Notifications geschieht an anderer Stelle. Zum Beispiel erhalte ich bei einer Antwort von Gunnar immer zwei Benachrichtigungen.

**Comment by MatthiasApsel** [comment]
> Mal sehen, wann der Nächste ein anderes Zeichen vor das @ als Einleitung der/des (?) Mention schreiben will. ;-)

`//` könnte ich mir noch vorstellen. Aber das macht die ganze Sache schon wieder wesentlch komplexer.

**Comment by auge8472** [comment]
> `//` könnte ich mir noch vorstellen. Aber das macht die ganze Sache schon wieder wesentlch komplexer.

Ja eben, mein Reden. Da muss Vorsicht walten, sonst kommen weitere Wünsche und Ansprüche™ aus allen Ecken und Enden hervor.

**Comment by MatthiasApsel** [comment]
> Zum Beispiel erhatte ich bei einer Antwort von Gunnar immer zwei Benachrichtigungen.

Zur Klarstellung: Eine "hat auf Ihren Beitrag geantwortet" und eine "hat Sie in einem Beitrag erwähnt". Also durchaus richtig. Allerdings sollte `@@` nicht zu einer Notifikation führen, weil schon nicht das autocomplete anspringen sollte.

**Comment by ckruse** [comment]
Ich finde die Lösung, die du im PR geschrieben hast, nicht gut. Ich habe sie mal raus gelassen... den Rest habe ich gemerged.

Ich muss Heiko zustimmen, für die Klammer eine Ausnahme zu machen finde ich nicht sinnvoll, dann lieber prüfen, ob das vorhergehende Zeichen zu einer E-Mail-Adresse gehören kann - oder genau definieren, unter welchen Umständen das Zeichen vor dem `@` als Nicht-Wort-Zeichen definiert wird. Die `|\)` ist mir da zu wenig vorausschauend...

**Comment by MatthiasApsel** [comment]
einverstanden. Bleibt die Tatsache, dass `@@username` zu einer notifiacation führt. Dies sollte imho nicht so sein, weil nach `@@` richtigerweise auch nicht das autocomplete angeboten wird.

**Comment by ckruse** [comment]
Ja, der Algorithmus im Frontend und im Backend unterscheiden sich noch, das ist richtig und ein Bug.
