### ISSUE TITLE
Ausgeblendete Threads bleiben ewig. Ist das so gewollt?

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#427]
Ich habe festgestellt, dass in meiner Liste der ausgeblendeten Threads uralte Einträge vorhanden sind, die vermutlich schon längst ins Archiv gehören. So war der älteste Eintrag bis eben [ein Thread vom 23.11.2014](http://forum.selfhtml.org/meta/2014/nov/23/warum-wurde-mein-beitrag-geloescht/1625303#m1625303). Den habe ich zu Testzwecken händisch aus der Liste geworfen und ihn daraufhin auch im Archiv gefunden. Ob er dort vorher schon vorhanden war, habe ich nicht geschaut.

Ein weiterer Test mit dem [nächstältesten Thread (2015-02-07 10:15)](http://forum.selfhtml.org/self/2015/feb/7/strategie-zum-laden-von-css-js/1633117#m1633117) ergibt folgendes Bild. Der Thread existiert zum Zeitpunkt des Schreibens dieses Berichts in meiner Liste der ausgeblendeten Threads, nicht jedoch [auf der passenden Archivseite](http://forum.selfhtml.org/self/2015/feb?page=4) zwischen den Threads [Sprung auf ein Element in der Webseite (2015-02-06 20:50)](http://forum.selfhtml.org/self/2015/feb/6/sprung-auf-ein-element-in-der-webseite/1631780#m1631780) und [Musikvideo auf Youtube zeigen - GEMA (2015-02-07 10:43)](http://forum.selfhtml.org/self/2015/feb/7/musikvideo-auf-youtube-zeigen-gema/1631784#m1631784), wo er – mindestens _ebenfalls_ – hingehört.

Nach dem Betätigen des Buttons „Thread wieder anzeigen“ verschwindet der Thread folgerichtig aus der Liste der ausgeblendeten Threads und wird nun auf der oben verlinkten Archivseite angezeigt.

Der Zeitpunkt der Archivierung ist vermutlich schon Ewigkeiten her. Auch wenn sich ein Benutzer bewusst dazu entschieden hat, einen Thread während dessen Zeit der **Aktivität** wegen Desinteresses (oder warum auch immer) auszublenden, sollte das mMn bei der Archivierung keine Rolle spielen. Zudem bliebe mit der Überführung dieser Threads in's Archiv die Liste der ausgeblendeten Threads übersichtlich lang. Meine z.B. hatte vor den beschriebenen Tests eine Länge von 12 Seiten erreicht.

**Comment by ckruse** [comment]
Nein, das ist nicht gewollt. Diese Funktionalität gibt es auch gar nicht im Archiv (ich habe sie da absichtlich ausgebaut). Ich habe nur vergessen beim archivieren eine Cleanup-Query laufen zu lassen :)
