### ISSUE TITLE
Wiedereinführung der Quicklinks

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#428]
Ich schlage vor, den Bereich unterhalb des Headers, also `nav` und `aside` zweispaltig zu gestalten um in der linken Spalte untereinander die Links zu neuer Beitrag, Hauptseite, Zitatesammlung und Chat unterzubringen.

**Comment by ckruse** [comment]
mir erschliesst sich noch nicht so recht, wie du dir das vorstellst. magst du mal eine Zeichnung oder sowas machen?

**Comment by MatthiasApsel** [comment]
Ich hab schon mein Linux angewärmt. Mal sehen ob ich das mit dem git noch kann...

**Comment by ckruse** [comment]
Du solltest dein Linux die meiste Zeit benutzen! ;-)
