### ISSUE TITLE
audit-log

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#431]
Es wäre schön, wenn es für das audit-Log eine Suchen-Funktion gäbe oder wenigstens eine sortierbare Tabelle.

**Comment by ckruse** [comment]
Eine Suche gestaltet sich als schwierig. Wonach würdest du denn suchen wollen? Ich kann dir Event-Typ (als Auswahl), Relation (auch als Auswahl) und Autor anbieten.

**Comment by MatthiasApsel** [comment]
* Aktion
* Benutzer
* Objekt
* Datum

Wie gesagt, die Tabelle sortierbar würde mir reichen.
