### ISSUE TITLE
gelesene Threads anzeigen/ausblenden

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#435]
Es wäre mMn. sinnvoll wenn dieser Status für die Dauer der Browsersitzung gespeichert werden könnte. (session-storage) Wenn ich mehrere eigentlich gelesene Threads noch mal lesen möchte, muss ich anderenfalls immer wieder neu umschalten.

**Comment by ckruse** [comment]
Es gibt keine Session in dem Sinne mehr wenn der User das "Remember me"-Häckchen setzt.

**Comment by MatthiasApsel** [comment]
Aber der session-storage (JavaScript) funktioniert doch unabhängig davon und ist imo perfekt geeignet, den Zustand eines buttons zu speichern. Wenn der Browser geschlossen wird oder ein angemeldeter Benutzer einen anderen Browser benutzt, ist wieder die Benutzereinstellung aktiv.

**Comment by ckruse** [comment]
JS hilft uns hier aber nicht, denn das ist eine Funktion die einerseits
serverseitig umgesetzt wurde und andererseits nur sehr schwer
clientseitig umzusetzen ist. Nein, das muss serverseitig umgesetzt
werden.
-- 
Christian Kruse
http://ck.kennt-wayne.de/

**Comment by MatthiasApsel** [comment]
Warum? Es wird doch ohnehin nur ein URL-Parameter angehängt? `?srt=yes`, `?srt=no`

**Comment by ckruse** [comment]
Eben.

**Comment by MatthiasApsel** [comment]
Das betriffr auch die Paginierung. Es ist recht umständlich, etwa die zweite Seite mit den gelesenen Beiträgen anzuzeigen. Und vielleicht verschwinden dann sogar noch Beiträge in der Lücke zwischen Seite 1 und 2.

**Comment by ckruse** [comment]
Ich habe ja gesagt, dass es mit ein bisserl JS nicht sinnvoll ist. Mir schwebt da schon eine Lösung vor, aber ich habe zur Zeit keine Zeit für das CForum (ich will erst meine Webseite in Ordnung bringen)

**Comment by ckruse** [comment]
Ging doch über Sessions ;)

**Comment by MatthiasApsel** [comment]
:-)
