### ISSUE TITLE
angepinnte Threads sollen nicht wenn gelesen ausgeblendet werden

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#436]

**Comment by ckruse** [comment]
Mit welcher Begründung? Der Gund, warum man sie anpinnt ist doch, dass
man will dass alle sie lesen, unabhängig von ihrer Position in der
Thread-Liste. Wenn ich ihn gelesen habe, warum sollte ich dann weiter
von ihm genervt werden?

**Comment by MatthiasApsel** [comment]
Genau. Alle sollen ihn lesen und auch immer wieder dran erinnert werden. Quasi ein vereinfachtes MOTD.

**Comment by ckruse** [comment]
Neee, das sehe ich überhaupt nicht so. Wenn man ein MOTD möchte, dann soll man ein MOTD machen. Angepinnte Threads sind nur dazu da, dass man sicherstellen kann, das jeder sie sieht. Sie dem User immer wieder ins Gesicht zu drücken finde ich nicht gut.

**Comment by MatthiasApsel** [comment]
Und es besteht die Gefahr, dass angepinnte Threads "vergessen" werden. Unangemeldete (und solche die gelesene Threads anzeigen lassen) sehen sie dann aber immer noch, obwohl sie ggf. wirklich nicht mehr aktuell sind. Das spricht sowohl für ein MOTD als auch dafür angepinnte gelesene Threads nicht auszublenden ;-) Ich finde einen angepinnten Thread wesentlich wirksamer als ein MOTD, wenn man sich zum Beispiel gegen Fremdenhass positionieren möchte. Außerdem lassen sich angepinnte Threads ausblenden. (Ich weiß, es ist nicht dasselbe)
