### ISSUE TITLE
PM-Bereich "aufräumen"

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#437]
Wenn man, wie ich, seine PMs nicht löscht sammeln sich auf der Seite <http://forum.selfhtml.org/mails/> recht viele Icons an, was ja auch grundsätzlich richtig ist. Befinde ich mich jedoch auf einer Unterseite, etwa <http://forum.selfhtml.org/mails/Christian%20Kruse>, könnten die Buttons für die anderen Personen weg, damit der Button "neue Post" einfacher zu finden ist. Statt der vielen könnte es einen "Übersicht" o.ä. geben, der zurück zu http://forum.selfhtml.org/mails/ führt.

**Comment by ckruse** [comment]
Hmhmhm. Ich überlege gerade, ob wir nicht für die Mails eine Ausnahme machen wollen:

<img width="1240" alt="screen shot 2015-09-16 at 22 09 22" src="https://cloud.githubusercontent.com/assets/175095/9917224/c107ea98-5cc0-11e5-937b-bf14c8b6b81f.png">

**Comment by ckruse** [comment]
Finde ich zumindest besser als auf einmal die Usernamen wegzulassen, glaub ich

**Comment by MatthiasApsel** [comment]
Was für eine Ausnahme meinst du?

**Comment by ckruse** [comment]
Die Verwendung von zwei Zeilen beim Menü, wie im Screenshot

**Comment by MatthiasApsel** [comment]
Ah, bei mir ist das dort sowieso mehrzeilig, deshalb fiel mir das nicht auf. Mit "Benutzer" eine neue Zeile beginnen. Und "neue Mail" an den Anfang der ersten, gern auch mit dem Format von "neuen Beitrag verfassen"
