### ISSUE TITLE
protocol-relative URLs

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#444]
* die Suchergebnisse erscheinen als http-Link
* Kramdown rendert `<//selfhtml.org>` nicht als Link

**Comment by ckruse** [comment]
Zum ersten: Ja, da muss der Such-Index neu generiert werden…
Zum zweiten: https://github.com/gettalong/kramdown/issues/285 <https://github.com/gettalong/kramdown/issues/285>

**Comment by ckruse** [comment]
Der Such-Index ist regeneriert und Kramdown hat das Problem für die 2.0 vorgemerkt. Damit sehe ich das als erledigt an.
