### ISSUE TITLE
Mail und Homepage in archivierten Beiträgen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#445]
Im alten Forum hieß es sinngemäß: "Mailadresse und Homepage werden nicht mit in das Archiv übernommen" - Nun sind sie aber doch da. Bevor uns eine Welle an Änderungswünschen erreicht, sollten wir da vielleicht was tun.

**Comment by ckruse** [comment]
Was schwebt dir vor?

**Comment by MatthiasApsel** [comment]
Falls es möglich ist, würde ich Mail und eigene Homepage in archivierten Threads wie bisher auch nicht anzeigen.

**Comment by ckruse** [comment]
Klar ist das möglich. Doch was ist mit dem neuen „problematische Seite?”

**Comment by MatthiasApsel** [comment]
Da das für den Beitrag wichtig ist, würde ich es lassen. Allerdings steht zu befürchten, dass die "problematische Seite" repariert wird, also nicht mehr problematisch ist.

**Comment by ckruse** [comment]
Das ist nicht zu ändern. Wir können nicht alles abfangen…
