### ISSUE TITLE
latex-Tags durch Kramdownsyntax ersetzen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#446]
Die Tags `[latex]` und `[/latex]` in archivierten Beiträgen sollten durch `$$` ersetzt werden.

**Comment by ckruse** [comment]
Das passiert bereits. Wenn das bei einem Beitrag noch nicht passiert, dann musst du mir sagen wo weil da dann ein Bug sein wird.

**Comment by MatthiasApsel** [comment]
* https://forum.selfhtml.org/self/2011/sep/9/pervers-ein-bruch-teilen-aber-doch-lieber-multiplizieren/1524360#m1524360
* https://forum.selfhtml.org/self/2011/sep/9/pervers-ein-bruch-teilen-aber-doch-lieber-multiplizieren/1524379#m1524379
* https://forum.selfhtml.org/self/2011/jan/23/anzahl-kalenderwochen-echt-so-einfach/1491013#m1491013

**Comment by ckruse** [comment]
Hast du die Beiträge editiert? Denn die sind in Markdown verfasst, und wir haben das Archiv eigentlich in seinem Ursprung gelassen.

**Comment by MatthiasApsel** [comment]
eigentlich nicht. Den ersten wollte ich editieren, dann kam aber der Fehler mit der URL, sodass meine Änderungen nicht gespeichert werden konnten.

**Comment by ckruse** [comment]
Wie sind denn dann daraus Markdown-Beiträge geworden??

**Comment by ckruse** [comment]
So ist es auf jedenfall nicht lösbar, entweder der Beitrag ist Markdown und dann kann ich ihn auch nur so rendern oder er ist kein Markdown und dann kann ich ihn auch übersetzen

**Comment by MatthiasApsel** [comment]
> Wie sind denn dann daraus Markdown-Beiträge geworden??

Diese Frage kann ich dir nicht beantworten.

**Comment by ckruse** [comment]
Nun, ich kann da leider nichts machen. Da musst du bei deinem Edit dann auch die `[latex]` editieren.
