### ISSUE TITLE
homepage ist not an URL

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#447]
Beim Versuch einen Beitrag im Archiv zu ändern, erhalte ich die o.g. Fehlermeldung, die beanstandete URL ist brückentage.info

**Comment by ckruse** [comment]
URL? wenn da nur `brueckentage.info` drin steht, dann fehlt das Protokoll.

**Comment by MatthiasApsel** [comment]
Nein, das Protokoll fehlt nicht, aber es ist eine Umlaut-URL. Beispiel https://forum.selfhtml.org/self/2011/jan/23/anzahl-kalenderwochen-echt-so-einfach/1491013/edit

**Comment by ckruse** [comment]
Ah, verstehe. Hm, das ist Rails-code, mal gucken was da schief läuft…

**Comment by ckruse** [comment]
Fixed.
