### ISSUE TITLE
Zitate auch von markdown rendern lassen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#450]
Kann es sein, dass die Zitate nicht durch den markdown-parser laufen?

**Comment by ckruse** [comment]
Ja. Da die alten Zertifikate alle in der gerenderten Form vorliegen habe
ich da kein Markdown drüber laufen lassen, sondern gehe von plain text
aus. Das ist Konsistent zum Verhalten der alten Zitatesammlung.
