### ISSUE TITLE
zurück-Button auf /users/ID

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#452]
Dieser führt nicht zurück, im SInne von history.back sondern zu /users

Es gibt zwei Möglichkeiten,
* history.back (mein Favorit)
* eine andere Beschriftung, "Benutzer" zum Beispiel

**Comment by ckruse** [comment]
Ich werde nicht anfangen JS-Links zu nutzen…

**Comment by MatthiasApsel** [comment]
Es gibt auch noch eine dritte Möglichkeit: Der Link kommt weg.

**Comment by MatthiasApsel** [comment]
Der Zurück-Button auf users/[ID]/edit ist ebenfalls überflüssig.

**Comment by ckruse** [comment]
Nein. Er gibt dem User die Möglichkeit sicherzugehen, dass er die Seite verlassen kann ohne die Änderungen zu speichern.

Man kann darüber diskutieren, dass man die Beschriftung auf „Abbrechen” ändert, aber überflüssig ist er nicht.
