### ISSUE TITLE
Diese Website hat eine ungültige Strict-Transport-Security-Kopfzeile angegeben.

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#454]
sagt Firebug für die Hauptseite (und wohl für alle anderen auch)

**Comment by ckruse** [comment]
Dann ist Firebug kaputt. Der STS-Header ist völlig in Ordnung (sagt auch SSLLabs):

~~~
Strict-Transport-Security: max-age=31536000
~~~

**Comment by MatthiasApsel** [comment]
War gestern schon zu Hause nicht reproduzierbar und ist jetzt auch hier nicht mehr nachzuvollziehen, ohne dass es ein Update von Firebug gegeben hätte.

**Comment by ckruse** [comment]
Ich verstehe nicht, warum du noch Firebug benutzt - warum nicht die Firefox-internen Developer Tools? Firebug ist doch wirklich einfach nur kaputt…

**Comment by MatthiasApsel** [comment]
Gewohnheitssache. Ich mach eh nur CSS und da finde ich das Ändern von Eigenschaften bequemer als in anderen ET, auch Chrome oder IE.
