### ISSUE TITLE
Postings nicht erreichbar bei tieferer Hierarchie

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum#462]
Beispiel https://forum.selfhtml.org/self/2015/sep/18/hilfe-aktuelle-farblink/1650592#m1650592 (OS X)

Die Titel der Antworten erscheinen nicht im Threadbaum. Sie sind dadurch nicht anwählbar und damit nicht lesbar. (Außer in der Nested-Ansicht, aber wer weiß das schon?)

<img width="1431" alt="bildschirmfoto 2015-09-25 um 10 54 33" src="https://cloud.githubusercontent.com/assets/409844/10096704/e5ea18c2-6373-11e5-976f-bfe2201b4495.png">

**Comment by ckruse** [comment]
oh wow. Was passiert denn da??

**Comment by ckruse** [comment]
Krass. Das ist ein Firefox-Bug. Im Chrome (auch OS X) sieht es so aus:

![screen shot 2015-09-25 at 11 05 02](https://cloud.githubusercontent.com/assets/175095/10096884/6410337a-6375-11e5-9b96-739fd7a4db50.png)

Und im Safari:

![screen shot 2015-09-25 at 11 06 24](https://cloud.githubusercontent.com/assets/175095/10096894/808e5fb8-6375-11e5-97bf-8100e5fcdbe0.png)

**Comment by ckruse** [comment]
Auch der Parsebaum sieht  da ganz komisch aus

![screen shot 2015-09-25 at 11 13 08](https://cloud.githubusercontent.com/assets/175095/10097035/75835d84-6376-11e5-98b1-3046fbb46422.png)

**Comment by ttepasse** [comment]
Beide Probleme sind auch im aktuellen Firefox Developer Edition/Aurora vorhanden.

**Comment by ttepasse** [comment]
Mozilla ist sich [eines Fehlers bei tiefer Verschachtelung bewusst](https://bugzilla.mozilla.org/show_bug.cgi?id=256180). Seit 2004.

**Comment by ckruse** [comment]
Ich sehe auch nicht wirklich, wie wir das Problem umgehen könnten.

**Comment by MatthiasApsel** [comment]
Das wäre ggf. noch ein Grund für nested als default.

**Comment by ckruse** [comment]
Ich frage mich schon seit längerem, warum du das noch nicht umgestellt hast, @MatthiasApsel ;-) ich persönlich finde die Ansicht unbrauchbar, aber du scheinst ja sehr überzeugt davon zu sein

**Comment by MatthiasApsel** [comment]
Bin ich. Ich kenne quasi nichts anderes.

Weil du die nested-Ansicht unbrauchbar findest, hast du vergessen, die default-Einstellung dafür konfigurierbar zu machen ;-)

**Comment by ckruse** [comment]
Gerade nochmal geprüft: nein, kann man definitiv konfigurieren

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by ckruse** [comment]
Ich schliesse das Issue mal, ich denke nicht, dass wir hier viel tun können

**Comment by MatthiasApsel** [comment]
> Gerade nochmal geprüft: nein, kann man definitiv konfigurieren

Das hast du aber so gut versteckt, dass ich es gar nicht finden kann.

**Comment by ckruse** [comment]
Hm, du hast recht, was hab ich denn da eben gesehen? Merkwürdig... ich bau es morgen ein (heute muss ich noch auf einen Junggesellenabschied -.-)
