### ISSUE TITLE
Bugtracker im Forum verlinken

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum#463]
Der Bugtracker sollte auf den Startseiten (Hauptseite und Startseite jedes Forums) verlinkt sein.

**Comment by MatthiasApsel** [comment]
Ja, gerade ist mir aufgefallen, dass das Feld mit "Für Anregungen, Fehlermeldungen oder Kritik sende bitte eine E-Mail an forum@selfhtml.org." nur auf der Hauptseite, nicht aber auf anderen sichtbar ist.

Zudem wäre es sinnvoll, wenn dieser Text für Admins anpassbar wäre, etwa als "Kontaktinfo" o.ä. Dort könnte dann der Link zu github hinein.

@gunnarbittersmann Allerdings gibt es im Footer einer jeden Seite einen Link zu github/ckruse/cforum  ;-p

**Comment by auge8472** [comment]
> Allerdings gibt es im Footer einer jeden Seite einen Link zu github/ckruse/cforum ;-p

Dass der Bug Tracker hier Issues heißt und dass man als meldewilliger einen Github-Account braucht, sprich, wie man von der verlinkten Seite aus zum Fehler melden kommt, weiß aber auch nur der Github-Kundige. Wie man das ohne weitere, Verwirrung stiftende Zwischenschritte erläutern soll, weiß ich auch nicht so recht.

**Comment by MatthiasApsel** [comment]
Am 25.09.2015 um 13:42 schrieb Heiko August:
>     Allerdings gibt es im Footer einer jeden Seite einen Link zu
>     github/ckruse/cforum ;-p
>
> Dass der Bug Tracker hier Issues heißt ...

Ja, das ist mir bewusst und so war dieser Hinweis auch eher als Joke 
gedacht um ein wenig den Gunnar zu kitzeln.

Wichtig wäre schon, dass der E-Mail-Kasten auf jeder Seite erscheint.
