### ISSUE TITLE
Auswahl des Forums beim einfügen neuer Threads per Websocket defekt?

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#465]
Alle Eröffnungspostings, die in den letzten Tagen neu erstellt wurden, werden automatisch in beiden Foren (Meta, SelfForum) in die Übersichtsseite eingefügt und sind erst nach einem Reload der Übersichtsseiten nur noch im korrekten Forum zu sehen. Zudem wird ein Eröffnungsposting oberhalb angepinnter Threads in die Liste eingefügt, wie es momentan im Meta-Forum zu sehen ist.

**Comment by ckruse** [comment]
Das mit den angepinnten Threads ist mir auch aufgefallen. Das mit den Threads in allen Foren noch nicht, danke für den Hinweis
