### ISSUE TITLE
Codesprache braucht eine Längenbeschränkung

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#472]
![code-sprache](https://cloud.githubusercontent.com/assets/2847625/10573750/0f3d0ce8-7652-11e5-9234-953cc5f84bd9.png)

Das führt zu katastrofalen Codeauszeichnungen. Es wurde schon kompletter Code dort eingegeben.

**Comment by ttepasse** [comment]
Wäre eine `select` da nicht sinnvoller?

**Comment by MatthiasApsel** [comment]
Und: "Abbrechen führt trotzdem zur Eingabe von `~~~` usw.

**Comment by MatthiasApsel** [comment]
> Wäre eine select da nicht sinnvoller?

Ich meine, es handelt sich um eine Fremdlösung mit einer Vielzahl unterstützten Sprachen, die option-liste wäre also irsinnig lang.

**Comment by ckruse** [comment]
Dass abbrechen trotzdem zu `~~~` führt ist natürlich ein Bug, aber eine Längenbeschränkung finde ich nicht sinnvoll. Sie hätte den Fehler nicht verhindert. Das war einfach nur eine Rotz-Bedienung: ich rotz mal schnell meinen Kot dahin, damit die das reparieren.

**Comment by MatthiasApsel** [comment]
Naja, du kannst ja nach 25 Zeichen eimfach abbrechen,  dann hätte auch dieser Nutzer gesehen, dass die Eingabe fehlerhaft war.

**Comment by ckruse** [comment]
Genau das ist der Punkt: glaub ich nicht. Der hat da keinen zweiten Blick drauf verschwendet. Sonst wäre es ihm so auch aufgefallen, in der Live-Vorschau.

**Comment by MatthiasApsel** [comment]
Die Frage ist aber auch: Schadet die Beschränkung?

**Comment by ckruse** [comment]
Nein. Aber das ist ja kein Grund eine Beschränkung einzuführen ;-)
