### ISSUE TITLE
Antwortfeld nicht editierbar

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum#473]
Vorgeschichte (keine Ahnung, ob das von Belang ist): Ich hab [dieses Posting von romi](https://forum.selfhtml.org/self/2015/oct/16/problem-mit-template-und-grid-photogallerie/1652373#m1652373) editiert: den Code als solchen markiert.

Beim Versuch, auf dieses Posting zu [antworten (mit Zitat)](https://forum.selfhtml.org/self/2015/oct/16/problem-mit-template-und-grid-photogallerie/1652373/new?quote_old_message=yes) reagiert das Eingabefeld nicht auf Tastatureingaben.

Antworten ohne Zitat [geht aber](https://forum.selfhtml.org/self/2015/oct/16/problem-mit-template-und-grid-photogallerie/1652653#m1652653).

**Comment by ckruse** [comment]
Das wird vermutlich ein Browser-Fuckup gewesen sein, ich kann das Problem nicht nachvollziehen. Hast du in die Konsole geschaut? Ich glaube nicht, dass das an mir liegt, zumal antworten ohne Zitat ja ging - das ist der identische Code.

**Comment by gunnarbittersmann** [comment]
Als das Problem im Firefox auftrat, hab ich im Safari gecheckt: selbes Resultat, keine Reaktion auf Tastatureingaben.

**Comment by ckruse** [comment]
Naja, und hast du mal in den Inspektor geschaut? Ich kann das nicht nachvollziehen, bin also auf Informationen von dir angewiesen.

**Comment by gunnarbittersmann** [comment]
Nichts Auffälliges zu sehen.
Hab mal ein [anderes Posting](https://forum.selfhtml.org/self/2015/oct/16/problem-mit-template-und-grid-photogallerie/1652381#m1652381) bearbeitet (den URI zum Pen verlinkt). Dort tritt das Problem nicht auf; das Antwortfeld reagiert nach wie vor auf Eingaben.
Solche Fehler sind mir ja auch die Liebsten, die mal auftreten, mal nicht …

**Comment by ckruse** [comment]
Aha, ich weiss, woran es liegt… die Textarea hat eine `maxlength` von 12288 (12k). Durch die unendlich vielen Leerzeichen ist die Überschritten worden, deshalb kannst du nichts mehr eingeben; fängst du an Teile des Posts zu löschen, dann geht es wieder.

Fragt sich nur, warum der Server mehr als 12k angenommen hat? Da gibts eigentlich eine Validation:

~~~ ruby
validates :content, length: { in: 10..12288 }, presence: true
~~~

**Comment by ckruse** [comment]
Ha, weil es gar nicht 12kb sind, sondern erst durch die Zitat-Zeichen 12kb werden
