### ISSUE TITLE
Keine Vorschau für Formaln in LaTeX

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum#476]
Mit Abschaffung des Vorschau-Buttons hat man keine Vorschau mehr, ob eine in LaTeX eingegebene Formel korrekt ist.

Entweder (vorzugsweise): In der Live-Vorschau wird auch LaTeX-Code richtig gerendert angezeigt

oder: Der Vorschau-Button darf nicht wegfallen.

**Comment by MatthiasApsel** [comment]
Interessanterweise wird Latex in der Vorschau korrekt gerendert, so lange man noch nichts geschrieben hat, also wenn im Zitat Latex steht. Schreibt man was, wird auch das Zitierte entlatexisiert.

**Comment by ckruse** [comment]
Weil MathJax erst nach dem ersten Vorschau-Rendern ausgeführt wird.

Whatever, ich kann das nur asynchron auslösen, das kann ggfls etwas komisch aussehen. Ich schalte das mal online, dann seht ihr, was ich meine.
