### ISSUE TITLE
Design für Archivierte Beiträge stört Lesbarkeit

### ISSUE THREAD

**Issue by ttepasse** [ckruse/cforum#477]
Eventuell wäre hier etwas padding-top angemessen:

![bildschirmfoto 2015-10-24 um 00 20 45](https://cloud.githubusercontent.com/assets/118031/10706201/2758cb3c-79e5-11e5-9e28-9da713fbf038.png)

**Comment by ckruse** [comment]
@MatthiasApsel habichsnichtgesagt ;D

**Comment by MatthiasApsel** [comment]
Es ist ja nichts, was wahnsinnig kompliziert zu beheben wäre. Allerdings würde ich das sogar lassen. Ich habe jetzt durch mehrere längere archivierte Threads geblättert und nur sehr wenige Stellen gefunden, an der der Text in die Grafik ragt. Unleserlich war er in keinem Fall. 

padding sieht sch. aus. Deshalb haben wir 

~~~css
.thread-message .posting-content > *:first-child {
    margin-top: 0;
}
~~~

Es sind allerdings nur Absatz-Elemente, die verquer tun. Deshalb schlage ich salomonisch vor (**zusätzlich** zu obigem)

~~~css
.thread-message .posting-content > p:first-child {
    display: inline-block;
    background-color: #fdfcf3;
}
~~~

**Comment by MatthiasApsel** [comment]
oder besser

~~~css
.thread-message .posting-content > p:first-child {
    display: inline-block;
    background-color: inherit;
}
~~~

Dann braucht man nur an einer Stelle zu ändern.
