### ISSUE TITLE
aussagekräftigere Fehlermeldung beim Bilder-upload

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#478]
Ein nicht unterstütztes Format beim Bilderupload führt zu "Ein interner Fehler ist aufgetreten." Man könnte "Nicht unterstütztes Dateiformat" oder ähnlich draus machen.

**Comment by ckruse** [comment]
Das Anzeigen von Fehlermeldungen ist da irgendwie noch kaputt, siehe auch die `[object object]`-Meldung.

**Comment by ckruse** [comment]
Ist bereits gefixed.
