### ISSUE TITLE
Beitrag drucken

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#482]
Wäre ein Drucken-Button sinnvoll, der auch in der nested-Ansicht nur den aktuellen Beitrag druckt? Für die Einzelansicht ist ein print-stylesheet ja kein grundsätzliches Problem, aber für die nested-Ansicht ist es nicht ganz so einfach. Was meinst du?

**Comment by ckruse** [comment]
Ich bin prinzipiell dagegen, Sachen aus den Internet auszudrucken ;-)

That said: ich sehe kein Problem darin, ein Print-Stylesheet für die
Nested-Ansicht zu machen. Man müsste halt die Indention wegmachen und
das als Liste ausdrucken?

**Comment by MatthiasApsel** [comment]
Ich auch. Vor allem in der Schule.

Ich würde es sinnvoll finden, nur den aktuellen Beitrag zu drucken. Den kompletten Thread will sicher niemand haben.
Dazu müsste er (das heißt das entsprechende div der Klasse `.posting-nested.thread-message`) zusätzlich die Klasse `print` bekommen und einen drucken-button, der vielleicht besser nur das print-stylesheet aktiviert. ("Druck-Ansicht" o.ä.) Ausdrucken muss der Nutzer das schon selbst. Siehe dazu auch <https://blog.selfhtml.org/2015/07/15/graceful-degradation-vs-progressive-enhancement/> und dort "print-this-page"-Links.

~~~css
@media print {
  main ~ .flex-item,
  footer,
  h1, #content > h2,
  .thread-message:not(.print),
  .thread-message > .voting, .message-links, .forum-links,
  .root {
    display: none;
  }
  main {
    padding: 0;
  }
  .thread-message {
    background: transparent;
    border: none;
    max-width: none;
    width: auto;
  }
  .thread-message .posting-content {
    background: transparent;
    color: black;
    border: none;
  }
  .answers {
     padding: 0;
  }
}
~~~

**Comment by ckruse** [comment]
Lass uns da nächste Woche drüber reden. Die kommende Woche bin ich
wieder zwei Tage geschäftlich verreist und werde deshalb wenig Zeit
haben, mich um sowas zu kümmern.

**Comment by MatthiasApsel** [comment]
Es eilt ja nicht. Bisher hat sich noch keiner beschwert, dass er einen Beitrag nicht ausdrucken konnte.

**Comment by MatthiasApsel** [comment]
closed via #621
