### ISSUE TITLE
Autoupdate löscht neu erstelltes Posting

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum#484]
Ich bin gerade zum zweiten Mal daran gescheitert, ein neues Posting zu erstellen. Angefangen zu schreiben, zwischendurch musste ich in andere Browsertabs, um Informationen zusammenzutragen. Als ich wieder zum Tab zurückkehrte, um mein Posting weiter zu bearbeiten, war alles bereits Eingegenene weg. Autoupdate hat zugeschlagen und die Eingabeseite für ein neues Posting durch die aktualisierte Startseite ersetzt. Ärgerlich, das.

**Comment by ckruse** [comment]
Es gibt kein „autoupdate” auf der Neues-Posting-Seite. Das gibt es 
nur und ausschliesslich in den Index-Seiten. Da muss etwas anderes 
kaputt sein, bist du sicher, dass du dich nicht mit den Tabs vertan 
hast?

Vor allem ersetze ich auch nichts, dass nicht der Thread-Baum ist, das 
kann also so oder so nicht sein. Kannst du genauer beobachten, was da 
passiert?

**Comment by ckruse** [comment]
Oder meinst du nicht Autoupdate, sondern Autorefresh?

**Comment by gunnarbittersmann** [comment]
Ja, vermutlich das.

**Comment by ckruse** [comment]
[x] Fixed.

Ansonsten: das Feature ist doch obsolet, warum verwendest du das überhaupt? ;-)

**Comment by auge8472** [comment]
Wenn mit „Autorefresh“ der automatische Reload der Forenhauptseite gemeint ist, möchte ich anmerken, dass diese Funktion für mich wichtig ist.

Das automatische Einfügen neuer Postings in das DOM ohne Reload der Seite ist ja ganz nett, aber auf diese Art sammeln sich die als „Neu“ markierten Postings an, ohne – **Achtung**, krude Wortschöpfung – „entneut“ zu werden. Das „Neu“ verschwindet ja bis zu einem „echten“ Reload der Seite nicht. Auf diese Weise erhöht sich auch die Anzahl der in der Benachrichtigungsleiste angegebenen neuen Nachrichten, auch wenn ich die meisten der Postings mittlerweile bereits gelesen habe.

Um den Überblick zu behalten, lasse ich deshalb zusätzlich die Übersichten alle 20 Minuten neu vom Server laden.

**Comment by ckruse** [comment]
Keine Angst, ich will sie nicht entfernen ;-) Ich bin nur erstaunt, dass es tatsächlich noch User gibt, die sie verwenden.
