### ISSUE TITLE
gelesene Beiträge folden

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#485]
Ein Einfügen eines neuen Beitrages in einen Thread führt dazu, dass auch bisher noch ungelesese Beiträge den gelesen-Status bekommen und somit zugeklappt sind. Das sollte nicht sein. Der gelesen-Status sollte wirklich erst dann gesetzt werden, wenn der Thread verlassen wird. Das Antworten auf einen Beitrag des Threads sollte nicht dazu zählen.

**Comment by ckruse** [comment]
Ich verstehe das Problem nicht. Wenn du den Thread aufrufst wird nach
dem Rendern der Gelesen-Status gesetzt. Das führt dazu, dass solange du
den Thread im gleichen Tab auf hast, die Nachrichten als ungelesen
gelten. Und eingefügt wird da gar nichts.

Wenn du antwortest verlässt du die Seite und sie muss damit neu vom
Server geholt werden, wenn du sie später nochmal besuchst. Das führt
natürlich dazu, dass die Nachrichten diesmal bereits gelesen markiert
sind.

Abhängig von irgendwelchen Browser-Tabs machen kann ich das nicht. Und
wenn ich es könnte würde ich es auch nicht wollen.

**Comment by MatthiasApsel** [comment]
Ich bin da ganz anders als der Martin ;-) Ich habe möglichst wenig Tabs auf. Und nutze das Forum meist nur in einem. Lediglich Links aus den Beiträgen werden in einem neuen Tab geöffnet.

> Wenn du antwortest verlässt du die Seite und sie muss damit neu vom
Server geholt werden, wenn du sie später nochmal besuchst. Das führt
natürlich dazu, dass die Nachrichten diesmal bereits gelesen markiert
sind.

Ja, das ist mir bewusst. Aber rein logisch verlasse ich den Thread ja nicht, nur weil ich in ihn eine neue Antwort einfüge.

**Comment by MatthiasApsel** [comment]
Außerdem **könnten** in der administrator-Ansicht auch die gelesenen Beiträge ausgeklappt sein.

**Comment by ckruse** [comment]
Hey,

> Ich bin da ganz anders als der Martin ;-) Ich habe möglichst wenig
> Tabs auf. Und nutze das Forum meist nur in einem. Lediglich Links aus
> den Beiträgen werden in einem neuen Tab geöffnet.

Das ist ja auch ok, aber du musst dich da trotzdem mit den technischen
Gegebenheiten abfinden ;-)

>> Wenn du antwortest verlässt du die Seite und sie muss damit neu vom
>> Server geholt werden, wenn du sie später nochmal besuchst. Das führt
>> natürlich dazu, dass die Nachrichten diesmal bereits gelesen markiert
>> sind.
>
> Ja, das ist mir bewusst. Aber rein logisch verlasse ich den Thread ja
> nicht, nur weil ich in ihn eine neue Antwort einfüge.

Das sehe ich anders; aber selbst wenn man das so sieht wie du gibt es
immer noch das Problem, dass es da technische Grenzen gibt ;-)

LG,
-- 
Christian Kruse
https://wwwtech.de/

**Comment by MatthiasApsel** [comment]
ach lösbar wäre das bestimmt ;-) Wenn sogar ich in der Umgangssprache eine Lösung formulieren kann ;-)

* Klick auf Anworten
* merke dir (im browser-storage) , welche Beiträge ungelesen sind sowie den slug des aktuellen Threads.
* der Refferer enthält `new`, den `slug` und es handelt sich um denselben Thread
   * setze bzw. entferne per JS die entsprechenden Klassen.
   * verwirf danach und anderenfalls die "gemerkten" Fakten

**Comment by ckruse** [comment]
Mir wird schlecht…

**Comment by MatthiasApsel** [comment]
:ghost:
