### ISSUE TITLE
Inteligentere Suche

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#486]
Ich habe gerade nach Christoph Schnauß' aktuellem Thread gesucht und dabei `schnaus` als Suchbegriff eingegeben. Lässt sich einstellen, dass nach `ß` auch bei `s` und nicht nur bei `ss` gesucht wird? Vielleicht nur automatisch in einer zweiten Runde, falls im ersten Durchgang nichts gefunden wird? Ist das sinnvoll?

**Comment by ckruse** [comment]
Ich halte das für wenig sinnvoll. Technisch machbar wäre es, aber das
würde dazu führen, dass ich z.B. bei diesem Suchbegriff:

Schnaus ist schnell seine Suppe

5^2 = 25 Kombinationen suchen müsste.

**Comment by ckruse** [comment]
Da keine Rückmeldung gehe ich von keinem Einspruch aus. Closed.
