### ISSUE TITLE
die Punkte eines Users können nicht unter -1 fallen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#489]
Zitat aus <https://github.com/ckruse/cforum/wiki/Scoring-Regeln>, was du hinzu gefügt hast <https://github.com/ckruse/cforum/wiki/Scoring-Regeln/_compare/08074cae7520202dc294c7080304038bdf8a969f...cf42561a655fc8234c4ee01a596af9c99f70f5e1>

Es gibt aber einen [Nutzer](https://forum.selfhtml.org/users/107), der hat -2.

**Comment by ckruse** [comment]
Hm, tja... gute Frage.
