### ISSUE TITLE
Fehlermeldung Mail

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#491]
> ~~~
> 2 Fehler verhinderten ...
>   * Betreff muss ausgefüllt werden
>   * Betreff zu kurz (mindestens ... Zeichen)
> ~~~

Wenn der Betreff nicht ausgefüllt ist, ist er auch automatisch zu kurz. Ich schlage deshalb vor, bei fehlendem Betreff folgende Fehlermeldung zu generieren

~~~
1 Fehler verhinderte dass diese Nachricht gespeichert werden konnte.
  * Betreff muss ausgefüllt werden (mindestens ... Zeichen)
~~~

**Comment by ckruse** [comment]
Das wird aufgrund der Validierungs-Systematik bei Rails vermutlich eher nichts.
