### ISSUE TITLE
problematische Seite auch in Vorschau anzeigen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#495]
Weder in der Live- noch in der normalen Vorschau wird `.problematic-site` dargestellt.

**Comment by ckruse** [comment]
In der richtigen[tm] Vorschau kann ich die Kritik nachvollziehen; aber in der Live-Vorschau finde ich das ehrlich gesagt eher überflüssig?

**Comment by MatthiasApsel** [comment]
* Naja, warum sollten sich die Vorschauen unterscheiden?
* Die Vorschau sollte auch das Ergebnis zeigen, sonst fragt sich der unbedarfte Nutzer, warum die problematische Seite angegeben werden muss.

**Comment by ckruse** [comment]
Sie unterscheiden sich eh schon massiv. Die Live-Vorschau rendert nur und ausschliesslich den Markdown-Input. Ich finde es nicht sinnvoll hier die problematische Seite anzuhängen.

Dass sie bei der „normalen” Vorschau angezeigt werden sollte sehe ich auch so, dass war nur ein Bug im Thread-erstellen-Template.

**Comment by ckruse** [comment]
Da kein Einspruch kommt sehe ich das als erledigt an ;-)
