### ISSUE TITLE
Userseiten-Links im Posting-Header deutlicher machen.

### ISSUE THREAD

**Issue by ttepasse** [ckruse/cforum#496]
![bildschirmfoto 2015-11-05 um 13 05 10](https://cloud.githubusercontent.com/assets/118031/10967869/e2b9e6fe-83bd-11e5-80d0-a0f66d48267d.png)

Die Linkstruktur der einzelnen Bestandteile im Header eines Postings (Nested Ansicht) scheint wie folgt zu sein:

- Titel des Postings → Permalink auf das Posting
- Profilbild → linkt auf Userseite
- Name des Posters → Permalink
- Mailto, Homepage → Was der Titel sagt
- Datum des Postings → Permalink
- Tag → Einzelseite der Tags

Es gibt drei unterschiedliche Varianten den Permalink eines Postings aufzurufen. Der Link auf die Userseite des Posters dagegen ist auf einen winzigen, kaum erkennbaren 14px × 14px Bereich beschränkt. Ich würde mindestens den Namen des Posters zu einem Link auf die Userseite machen, da wenig einen User so symbolisiert, wie dessen eigener Name.

**Comment by ckruse** [comment]
Diese Diskussion wurde bereits im Forum auch schon geführt. Da wurde entschieden, den Usernamen auf das Posting zu verlinken, um auf Mobil-Geräten den wichtigen Link mehr accesible zu machen (Stichwort Touch & Finger). Die weniger wichtigen Links, die selten einer besucht, sind dann auf die kleinen Elemente verlinkt.

**Comment by ckruse** [comment]
Keine Einwände? Keine konstruktiven Vorschläge?

**Comment by ttepasse** [comment]
Ich kann nur argumentieren, dass Username = Userseite und Datum/Titel = Permalink in Weblogs und anderen Systemen eine weit gebrauchte Konvention sind. Wegen eben dieser Irritation öffnete ich den Bug. ;)

**Comment by auge8472** [comment]
Den Namen wieder mit dem Profil zu verlinken, wie es bei Einführung der 4-er Version ja war, bedeutet, im Threadbaum den Link zum Posting in den meisten Fällen auf den Bereich von Datum und Uhrzeit zu beschränken. Standardmäßig wird ja der Titel des Postings ausgeblendet, wenn er sich nicht vom Titel des Elternpostings unterscheidet.

Ich möchte die zusätzliche Fläche des Links zum Posting nicht missen. Dazu sei gesagt, dass ich das Forum in der Einzelpostingansicht fast ausschließlich an Desktop-Rechnern benutze.

Im Falle der Nested-Ansicht braucht man den Link zum nächsten Posting aber nicht. Es werden ja eh alle Postings am Stück angezeigt. Deswegen kann ich mir *grundsätzlich* vorstellen, den Namen mit dem Profil zu verlinken. Allerdings ist das dann über alle Ansichten wieder nicht konsistent. Irgendwer™ wird ankommen und fragen, warum das hier nicht so ist, wo es doch dort genau so funktioniert.

**Comment by ckruse** [comment]
Ich glaube, im Thread-Baum will ich den Namen auf das Posting verlinkt lassen, das ist sonst einfach zu wenig benutzbar für Mobilgeräte. Aber in den Einzel-Ansichten könnte man den Autoren aufs Profil verlinken, das würde IMHO auch Sinn machen.

**Comment by MatthiasApsel** [comment]
Mit Einzelansicht meinst du hier `.header` der Beiträge?

**Comment by ckruse** [comment]
Ja
