### ISSUE TITLE
Fehlermeldung Tags

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#498]
Ich weiß nicht, ob es mit deinem Commit zu  #491 zusammenhängt, aber es gibt, wenn man keinen Tag setzt, nur noch die Fehlermeldung "1 Fehler verhinderte, dass dieser Beitrag gespeichert werden konnte."

Das ist besonders problematisch, weil der unbedarfte User nicht weiß, dass er einen Tag verwenden muss.

**Comment by ckruse** [comment]
Hängt nicht damit zusammen, aber der Fehler war mir auch aufgefallen. 
Hatte noch keine Zeit das Problem zu beheben.

**Comment by ckruse** [comment]
Das liegt an deinem Pull-Request. Der war nicht vollständig :)
