### ISSUE TITLE
Default-Forum für die Hauptseite definieren

### ISSUE THREAD

**Issue by ttepasse** [ckruse/cforum#499]
Ich empfinde die derzeitige Hauptseite als sehr klinisch und unnötig. Im wesentlichen zeigt es nur an, dass – im Falle von Self – 2 Foren existieren und man sich eine Ansicht aussuchen kann. Für eher faule Besucher kann ich mir auch vorstellen, dass die tabellarische Ansicht abschreckend wirkt. Für mich selber ist es meist nur ein unnötiger Klick. 

Ich würde:

- Für unangemeldete Besucher stattdessen das Selfhtml-Forum auf die Hauptseite setzen; Meta interessiert diese meist weniger.
- Einen Wechsel zwischen Foren über ein Popup-Menü ermöglichen, damit unterschiedliche Foren nicht ganz unsichtbar sind.
- Für angemeldete Besucher würde ich mir wünschen, man könne in den Einstellungen eine Foren-Ansicht (Self, Meta, All) als Default setzen.

**Comment by ckruse** [comment]
Auf der anderen Seite ist das Element der Forenliste gut bekannt und weit verbreitet. Und bald[tm] bekommt man als User dort auch seine Notifictations und PMs aufgelistet. Und sie gibt einem einen Überblick, ob überhaupt etwas passiert ist, ohne gleich den ganzen Index laden zu müssen. Sie gibt einem einfach einen Überblick über das Geschehen. Darauf zu verzichten könnte auch nach hinten losgehen.

**Comment by MatthiasApsel** [comment]
Die Weiterleitung für unangemeldete und referer von Außerhalb auf /self könnte trotzdem eine gute Idee sein.

**Comment by ckruse** [comment]
Da bin ich nicht so sicher. Wir haben ja durchaus Stammuser, die sich nicht anmelden mögen.

**Comment by MatthiasApsel** [comment]
Es könnte vielleicht so aussehen:

* ungelesene Post
  * maximal 5 / Button für alle anzeigen

* ungelesene Antworten
  * maximal 5 / Button für alle anzeigen

* Beiträge, in denen Sie erwähnt wurden
  * maximal 5 / Button für alle anzeigen

* Admin/Mod-Benachrichtigungen
  * immer alle anzeigen

* Foren
  * Threads mit ungelesenen Beiträgen, Link auf ältesten ungelesenen Beitrag des entsprechenden Threads
  * max 5 / Button für alle anzeigen

Die Zusammenfassung "alle Foren" braucht es dann wohl eher nicht. Die "Statistik" würde ich hinter einem **i** verstecken.

**Comment by MatthiasApsel** [comment]
Die Darstellung könnte dann ähnlich `/users/nr` sein.

**Comment by MatthiasApsel** [comment]
die am häufigsten verwendeten Tags könnten dort auch mit hin.
