### ISSUE TITLE
Lese-Status im Browser dynamisch über Tabs synchronisieren.

### ISSUE THREAD

**Issue by ttepasse** [ckruse/cforum#500]
Nutzungs-Szenario:

- Nutzer T. öffnet das Forum in einem Tab.
- T. öffnet einen Thread im neuen Tab in der Nested-Ansicht
- T. liest den Thread und schliesst den Tab wieder.

In der Forumshauptdatei ist nun nur das vorher geöffnete Posting des Threads als Gelesen markiert; der Rest der Postings sind bis zu einem Neuladen des Indexes als Nicht gelesen markiert und damit verwechselbar mit dynamisch über Websockets eingefügten neuen Postings, ignoriert man das Neu-Label.

Ich fände es sinniger, den Lese- und anderen Status einzelner Postings in einer Browsersession über verschiedene Tabs zu verwalten, so das der Nutzer unabhängig vom Ladestatus einzelner Seiten immer aktuelle Daten sieht.

Vorstellbar wäre zur Implementation Cross-Window-Messaging, irgendwas aus den neuen Worker-Infrastrukturen oder einfach ein Vorhalten der Threads und Postings mit deren Stati in localstorage/sessionstorage mit Update des Storage nach jeweiliger Aktion und dem Listening auf Storage-Events in anderen Tabs.

**Comment by ckruse** [comment]
Ja, das ist noch nicht optimal gelöst. Die Sychronisation über Websockets bedarf noch einiges an Liebe. Aber bisher hatte ich keine Zeit dazu daran zu arbeiten.

**Comment by ckruse** [comment]
Das ist implementiert
