### ISSUE TITLE
forum.selfhtml.org/users

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#506]
Ist diese Information wirklich notwendig? Was hat der normale Nutzer davon, wenn er sieht, wann die Nutzer erstellt wurden? Lediglich Name und Punkte könnten tatsächlich interessant sein und dazu die aktuelle Aktivität

Name | Punkte | Anzahl Beiträge in den letzten 30 Tagen

vergleiche <https://wiki.selfhtml.org/wiki/Spezial:Aktive_Benutzer>

Vielleicht sollte man das auch auf die beschränken, die tatsächlich in den letzten 30 Tagen Beiträge geschrieben haben.

**Comment by ckruse** [comment]
Die Information, seit wann ein Benutzeraccount existiert finde ich durchaus interessant. Aber der Rest ist in der Tat etwas überflüssig für die Public-Ansicht. Ob man die Anzahl der Beiträge in den letzten 30 Tagen performant darstellen kann, weiss ich noch nicht, das muss ich prüfen.
