### ISSUE TITLE
Menüstruktur + Seite /help

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#507]
Falls die Gruppen so übernommen werden können, schlage ich vor, die Gruppen je in eine eigene Liste zu stecken.

Eine Seite `/help` müsste erstellt werden, um den Inhalt kann ich mich gern kümmern.

**Comment by ckruse** [comment]
Von welchen Gruppen sprichst du hier? Fehlt hier vielleicht ein Link?

**Comment by MatthiasApsel** [comment]
von [diesen](https://forum.selfhtml.org/meta/2015/nov/14/menuestruktur-des-forums/1654453#m1654453) also eine eigene Liste für Filter, eine für Bedienelemente, ...
