### ISSUE TITLE
neues Markdown-Bedienelement: ASCII-Tabelle

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#508]
Wenn man Tabellen in Code-Blöcke einschließt, werden die Tabellen als ASCII dargestellt. Durch Vergabe einer Klasse könnte man im CSS reagieren und eventuell den weißen Hintergrund entfernen.

**Comment by ckruse** [comment]
Sorry, das soll kein Rant sein, das ist wirklich unverständnis auf meiner Seite. Dieses Issue macht auf mehreren Ebenen keinen Sinn. Was meinst du mit "als ASCII dargestellt?" Was meinst du mit dem weissen Hintergrund?

**Comment by MatthiasApsel** [comment]
Ich meine die Beschwerden über die fehlende Möglichkeit Tabellen mithilfe von Pipes darzustellen, falls man die nicht maskieren möchte.

![asciiart](https://cloud.githubusercontent.com/assets/2847625/11305888/324bea76-8faf-11e5-864f-0fb2b87de905.png)

Das Einschließen in ein code-Element wäre eine Möglichkeit. Wenn man die Klasse "asciiart" oder ähnlich vergeben würde, könnte man sich überlegen, ob dieser code-block wirklich einen weißen Hintergrund braucht.

**Comment by ckruse** [comment]
Ich sträube mich ehrlich gesagt den Meckerern nachzugeben. Es stört mich
*wirklich*, dass jetzt alle aus ihren Löchern gekrochen kommen und vor 2
Jahren es keinen Arsch interessiert hat.

**Comment by MatthiasApsel** [comment]
Einverstanden. Ich werde die Möglichkeit so im Wiki vorstellen.
