### ISSUE TITLE
svg-icons

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#510]
Überall, wo wir den font awesome verwenden, könnten wir auch auf svg setzen. Z.B. https://github.com/encharm/Font-Awesome-SVG-PNG

**Comment by ckruse** [comment]
Darüber habe ich auch schon nachgedacht, hatte bisher aber noch keine Zeit.

**Comment by MatthiasApsel** [comment]
Das ist ja auch in keiner Weise ein Vorwurf. Nur eine Ideensammlung. So ungeduldig bin ich nun auch wieder nicht.

**Comment by ckruse** [comment]
Habs nicht so aufgefasst, keine Angst ;-)

**Comment by ckruse** [comment]
Das benutzen von svg hat ein paar gravierende Nachteile.

Entweder ich benutze Inline-SVG, das ist toll weil man dann mit CSS und JS darauf arbeiten kann. Aber das ist doof, weil für jedes Icon dann einmal das SVG inlined wird, die Grösse der Seite steigt also stark an.

Oder ich nutze img, das hat ein paar gravierende technische Probleme, man kann z.B. nicht mit CSS/JS darauf arbeiten und ich bräuchte 4 Varianten von jedem Icon: Unbesucht, unbesucht Hover, besucht, besucht Hover.

Oder ich nutze object - das zwingt aber meinen Firefox ziemlich in die Knie, die Seite braucht dann ca 60s bis zum fertigen Aufbau.

Bleibt noch background-image via CSS. Da hat man wieder das CSS-Problem: man braucht wieder 4 Varianten

**Comment by ckruse** [comment]
Unterschied für interesting-icons inline-svg vs icon-fonts: 500kb mehr bei inline-svg

**Comment by ckruse** [comment]
Man könnte noch eine JS-Lösung anstreben. `<img class="svg">` und dann die Nodes via JS ersetzen durch das Inline-SVG. Das würde die zu übertragende Datenmenge reduzieren, aber es würde einen deutlich sichtbaren Effekt erzeugen.

Wenn wir wirklich auf SVG-Icons umsteigen wollen, dan würden SVG-Sprites vermutlich am besten funktionieren.

Aber ich sehe hier dann echt keinen Vorteil mehr gegenüber Icon-Fonts.

**Comment by ckruse** [comment]
Nutze ich Inline-SVG nimmt btw die Responsiveness der Seite deutlich ab, mein kleines 12"-Notebook hat da ziemlich dran zu knacken, der Firefox reagiert deutlich langsamer.

**Comment by ckruse** [comment]
Es hat schon seinen Grund, dass die meisten immer noch Icon-Fonts verwenden, das ist insgesamt einfach deutlich unproblematischer. SVG zu Nutzen hat zu viele Nachteile, und SVG selber ist ziemlich broken. Fast alle SVGs, die ich bisher gesehen habe, bestehen aus 1-n `path`-Elementen mit ewig langen, kryptischen `d`-Attributen - in einem XML-Format. WTF...

**Comment by MatthiasApsel** [comment]
Dann sollten wir bei Icon-fonts bleiben.
