### ISSUE TITLE
Längenbegrenzung für Beiträge

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#511]
siehe https://forum.selfhtml.org/meta/2015/nov/21/idee-fuer-neue-medaille/1655216#m1655216

**Comment by ckruse** [comment]
Da bin ich definitiv dagegen. 12k Text sind ja wohl mehr als ausreichend.

**Comment by MatthiasApsel** [comment]
Hm. Dann solltest du auch im Thread antworten.

**Comment by MatthiasApsel** [comment]
Zumindest die Warnung sollte umgesetzt werden. Zum Beispiel einfach durch Ändern der Hintergrundfarbe der Textarea. #ffebe6 und #c32e04 wenn nichts mehr geht.

**Comment by ckruse** [comment]
Eine Warnung ist schon notwendig, ja, siehe auch #473

**Comment by ckruse** [comment]
Ich habe mal etwas geschmackvollere Farben gewählt ;-)

<img width="327" alt="screen shot 2015-12-06 at 22 28 13" src="https://cloud.githubusercontent.com/assets/175095/11615711/b21d1af2-9c68-11e5-946a-c3a4f4d6070c.png">
<img width="375" alt="screen shot 2015-12-06 at 22 28 06" src="https://cloud.githubusercontent.com/assets/175095/11615713/b67c2b6a-9c68-11e5-9c90-8e8f007d06af.png">
