### ISSUE TITLE
Zitatesammlung

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#512]
In letzter Zeit kommt es vor, dass dieselben Zitate mehrfach vorgeschlagen werden.

Vielleicht könnte man einstellen, das jeder Beitrag nur einmal in die Zitatesammlung darf. Das in einem Beitrag tatsächlich mehrere **verschiedene** der Zitatesammlung würdige Stellen auftauchen ist wohl eher selten.

Alternativ könnte man auch beim Eintragen prüfen, ob der Beitrag schon in der ZS ist und einen Hinweis ausgeben mit der Frage, ob das Zitat wirklich vorgeschlagen werden soll.

Siehe [audit-log](https://forum.selfhtml.org/admin/audit?utf8=%E2%9C%93&term=&start_date[day]=20&start_date[month]=11&start_date[year]=2015&stop_date[day]=21&stop_date[month]=11&stop_date[year]=2015&objects[]=cites&events[]=cites_create&events[]=cites_destroy)

**Comment by auge8472** [comment]
> Alternativ könnte man auch beim Eintragen prüfen, ob der Beitrag schon in der ZS ist und einen Hinweis ausgeben mit der Frage, ob das Zitat wirklich vorgeschlagen werden soll.

Verschiedene zitatwürdige Stellen halte ich auch für unwahrscheinlich. Was aber vorkommen kann, ist der mehrfache Vorschlag mit überlappenden Inhalten. Der erste Vorschlag kommt mit den ersten zwei Sätzen eines dreisätzligen Absatzes daher. Der zweite Vorschlag zitiert nur den zweiten Satz und der dritte Vorschlag wirbt mit dem zweiten **und** dritten Satz des Absatzes.

Das müsste bei der Prüfung berücksichtigt werden. Ob der relevante Satz in einem Posting eventuell in zwei Zusammenhängen vorkommt **und** zudem – wieder eventuell – in beiden Fällen zitatwürdig ist, ist damit noch nicht gesagt. Aber dazu gibt es ja den menschlichen Vorschlagenden und die den Vorschlag Gutierenden.

**Comment by MatthiasApsel** [comment]
Ja, das war so ähnlich auch meine Überlegung beim Schreiben dieser Issue. Deshalb kam ich auch zu dem Schluss, nicht das Eintragen eines Zitatvorschlages zu verhindern sondern eine weitere Prüfung anzubieten. Das müsste auch und gerade für Vorschläge gelten, die erst in der Abstimmungsphase sind.

**Comment by ckruse** [comment]
Ich halte das für mit Kanonen auf Spatzen geschossen, wenn ich ehrlich bin. Den Check, ob eine URL bereits vorhanden ist, kann man IMHO durchaus einbauen, aber alles, was darüber hinaus geht, halte ich für übertrieben.
