### ISSUE TITLE
Leerzeilen ober- und unterhalb von Listen 

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#513]
Bei der Verwendung der Buttons um Listen einzufügen sollten die benötigten Leerzeilen mit eingefügt werden.

**Comment by ckruse** [comment]
Schwierig, ob ich dem zustimmen würde. Zur Zeit ist das Verhalten wie folgt:

- ist nichts markiert
  - füge einfach nur ein `- ` ein
- ist etwas markiert
  - nimm jede Zeile und prefixe sie mit `- `
  - setze ein `\n\n` davor
  - hänge ein `\n` an

Man könnte den ersten Fall verändern in

- ist nichts markiert
  - Prüfe, ob die vorherige Zeile ein List-Item ist
  - nein:
    - füge `\n\n- ` ein
  - ja:
    - füge `- ` ein

**Comment by MatthiasApsel** [comment]
Einverstanden. Und bitte beide Listen berücksichtigen.
