### ISSUE TITLE
Beiträge referenzieren

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#515]
Folgende Situation:
* Es gibt einen Beitrag A.
* Autor schreibt einen Beitrag B und verlinkt in diesem auf Beitrag A.

Dann soll unter dem Beitrag A hinzugefügt werden:
"Autor hat diesen Beitrag am Datum verlinkt: Titel des Beitrags B", wobei natürlich der Autor und der Titel ihrerseits auch entsprechende Links sind.

Wäre das sinnvoll?

**Comment by ckruse** [comment]
Weiss ich nicht ;-) Was möchtest du damit erreichen?

**Comment by MatthiasApsel** [comment]
Informationen für den geneigten Leser. Wahrscheinlich wird es ja einen 
Grund haben, dass dieser Beitrag in einem anderen verlinkt wurde. 
Möglicherweise stehen deshalb dort noch weitere Infos, die zur Lösung 
meines Problems beitragen könnten.

**Comment by ckruse** [comment]
Klingt logisch. Für neue Beiträge ist das durchaus machbar, für alte Beiträge muss man schauen, dass man ein Script schreibt, dass jedes Posting nochmal durchgeht und parsed und die notwendigen Daten generiert.

**Comment by ckruse** [comment]
Ich würde das auf 2015 reduzieren. Meinungen?

**Comment by MatthiasApsel** [comment]
Grundsätzlich immer nur die letzen 12 Monate? Oder erst mit den aktuellen Beiträgen beginnen? Bei letzterem hätte ich überhaupt nichts dagegen, es ist halt ein neues Feature, das erst 2015 in das Forum Einzug gehalten hat. Wir sollten uns mit den Beiträgen im alten Formalt nicth noch mehr Probleme schaffen, als es ohnehin schon gibt.

**Comment by ckruse** [comment]
Ich spreche davon, erst bei Beiträgen anzufangen, die mit V4 geschrieben wurden. Und um exakt diese Probleme geht es mir.

**Comment by MatthiasApsel** [comment]
Ich stimme zu.
