### ISSUE TITLE
urldecode für subject

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#516]
Wenn das subject als URL-Paremeter aus dem Wiki gesendet wird, und der Seitentitel im Wiki Leerzeichen enthält, sieht das unschönerweise so aus: `foo_bar`. Das könnte umgewandelt werden in `foo bar`

**Comment by ckruse** [comment]
Die URL-kodierte Variante eines Leerzeichens ist %20 und kein Unterstrich. Was genau hättest du gern? Um welche URL-Parameter geht es wo?

**Comment by MatthiasApsel** [comment]
Ok. Mein Fehler. Es geht um 
https://wiki.selfhtml.org/wiki/Diskussion:JavaScript/Anwendung_und_Praxis/JavaScript_und_CSS 
Dort hat der Seitentitel Leerzeichen. Wenn die Leerzeichen im 
Seitentitel bleiben, wird der Link im Wiki zerschossen, weil das 
Leerzeichen in wiki-syntax URL und Linktext trennt. (`[URL Linktext]`) 
Deshalb habe ich die Leerzeichen durch den Unterstrich ersetzt, weil 
mediawiki das auch tut. Ich kann das aber auch in `%20` ändern. Es geht 
um die URL-Parameter subject bzw. problematic-site.

**Comment by MatthiasApsel** [comment]
> Ich kann das aber auch in `%20` ändern.

Damit ist das Problem keins mehr.

**Comment by ckruse** [comment]
Die Frage ist vielmehr: warum musst du das überhaupt ersetzen? Das sollte das JS automatisch machen, dass wir entwickelt hatten, dafür ist die jQuery-Funktion doch da?

**Comment by MatthiasApsel** [comment]
Wenn im Titel Leerzeichen auftauchen, funktioniert die Wikisyntax mit den Links nicht mehr.

`[http://example.com Linktext]` wird richtig zu [http://example.com](Linktext) gerendert
`[http://example.com Linktext mit Erläuterungen]` zu [http://example.com](Linktext mit Erläuterungen)
`[http://example.com/CSS und JavaScript Linktext]` zu [http://example.com/CSS]( und JavaScript Linktext)

Das "und JavaScript" gehört aber nicht zum Linktext, sondern zur URL.

Das JavaScript, was du meinst, ist außerdem nicht für die Links von den Diskussionsseiten aus zuständig sondern nur für die Links neben den Überschriften und in der grauen Leiste. Das funktioniert auch. Was nicht funktioniert hat, war der zweite Link in der grünen Box <https://wiki.selfhtml.org/wiki/Diskussion:JavaScript/Anwendung_und_Praxis/JavaScript_und_CSS> Der Code ist 

~~~mediawiki
[https://forum.selfhtml.org/meta/new?cf_thread%5Bmessage%5D%5Bsubject%5D=selfhtml-wiki:+{{#replace:{{SUBPAGENAME}}| |%20}}&cf_thread%5Bmessage%5D%5Bproblematic_site%5D=https://wiki.selfhtml.org/wiki/{{#replace:{{ARTICLEPAGENAME}}| |%20}}&tags%5B%5D=selfhtml-wiki https://forum.selfhtml.org/meta/new]
~~~

**Comment by ckruse** [comment]
Ah, verstehe. Du solltest hier lieber `#urlencode` benutzen anstelle von `#replace`: Space ist nicht das einzige Zeichen, dass man maskieren sollte.

**Comment by MatthiasApsel** [comment]
Das waren auch meine ersten Versuche, aber leider ist `#urlencode` nicht implementiert. Das wird vielleicht mit der neuen mediawiki-Version. Anderenfalls sollte dazu eine extension installiert werden, @dedlfix.

Aber ich *glaube*, andere kritische Zeichen sind von vornherein verboten, weil mediawiki den Titel auch als URL verwendet.
