### ISSUE TITLE
Oswald auch im Forum

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#523]
Wir sollten die Schriftart auch im Forum verwenden. Im Wiki wird sie derzeit aus irgendwelchen Gründen auch nicht geladen, aber dedlfix weiß schon bescheid.

**Comment by ckruse** [comment]
Nur für die Überschriften, sehe ich das richtig?

**Comment by MatthiasApsel** [comment]
Sogar nur für h1.
