### ISSUE TITLE
kaputte Linkerzeugung der Beiträge

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#525]
https://forum.selfhtml.org/self/2015/dec/4/oliver/1656358#m1656358 

Sollte der nicht besser https://forum.selfhtml.org/self/2015/dec/4/darstellung-terminkalender/1656358#m1656358 heißen.

So war es mMn. auch früher.

Bestätigt. Da wars noch richtig: https://forum.selfhtml.org/self/2015/dec/4/symbla-symbox/1656422#m1656422

**Comment by ckruse** [comment]
Da ist nichts kaputt, sondern der Autor hat seinen Namen als Subject 
eingetragen gehabt. Siehe Edit-Protokoll. Und sobald einmal ein Slug 
generiert wurde, kann der nicht mehr geändert werden.
