### ISSUE TITLE
Benutzer sollen öffentlich voten dürfen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#527]
Benutzer sollen festlegen dürfen, ob ihre Positiv-Bewertungen beim entsprechenden Beitrag veröffentlicht werden dürfen (default: nein). Dazu sollte es eine Medaille geben, etwa bei 150 Punkten. Unter dem entsprechenden Beitrag kann dann

`positive Bewertungen [Avatarliste], 3 anonyme`

die Avatarliste geordnet nach dem Zeitpunkt der Bewertung, man könnte die Anzahl der Avatare auch auf beispielsweise 10 beschränken, dann müsste es heißen  

`positive Bewertungen [Avatarliste], 3 weitere`

**Comment by ckruse** [comment]
Ich habe das noch nicht zuende durchdacht, aber ich bin mir überhaupt nicht sicher, ob ich die Idee gut finde.

**Comment by auge8472** [comment]
Ich bin manchmal auch neugierig, wer denn das eine oder andere Posting bewertet haben mag. Dann fallen mir wieder die Diskussionen der ersten Monate ein, in denen die eine oder andere negative Bewertung beweint und die Forderung nach deren Begründung aufgestellt wurde. Ich kann mir durchaus Szenarien denken, in denen auch positive Bewertungen kontroverser Postings zu Forderungen nach Begründung der Bewertungen provozieren. Das möchte ich nicht. ich glaube auch nicht, dass das dem Klima im Forum zuträglich ist.

Von daher bin ich gegen die Veröffentlichung der Accounts der Bewertenden eines Postings.

**Comment by ckruse** [comment]
Nicht nur das. Das kann durchaus auch politischen Charakter haben. Zur Zeit zählt eine Stimme gleich viel; wenn jetzt $regular einschaltet, dass man seine Votes sehen kann, dann führt das dazu, dass eine Stimme mehr Gewicht hat („Guck, sogar $regular hat gevotet”) und/oder zum Politikum wird.
