### ISSUE TITLE
keine "Aktivität" auf der Portalseite

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#530]
Wenn es weder neue PMs noch neue notifications gibt, sollte die Info "keine neuen Mitteilungen" erscheinen.

**Comment by ckruse** [comment]
Warum? Das ist doch keine Null-Information: gäbe es neue Mitteilungen, stünden sie da.

Der Grund, warum ich das bei den Benachrichtigungen und Mails mache ist, weil es hässlich aussieht, wenn die Tabelle ohne Body da steht. Das ist hier doch gar nicht der Fall? Es verursacht nur mehr visual clutter?

**Comment by MatthiasApsel** [comment]
So haben wir eine Überschrift ohne Inhalt. Das sieht genauso hässlich aus.

**Comment by ckruse** [comment]
Dann muss die Überschrift verschwinden! ;-)

On 6 Dec 2015, at 21:25, MatthiasApsel wrote:

> So haben wir eine Überschrift ohne Inhalt. Das sieht genauso hässlich aus.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ckruse/cforum/issues/530#issuecomment-162344735


LG,
 CK

-- 
https://wwwtech.de/
