### ISSUE TITLE
Rendering android

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#532]
![screenshot_2015-12-07-07-53-49](https://cloud.githubusercontent.com/assets/2847625/11620994/0bc48884-9cb8-11e5-9ffd-1ff3c9aa7e82.png)

Ob das an meta viewport shrink to fit liegt?

**Comment by ckruse** [comment]
wohl eher an dem völlig kaputten Android Stock Browser

**Comment by ckruse** [comment]
die neue Geissel des Internets… alte Android Stock Browser. *brr*

**Comment by MatthiasApsel** [comment]
Ne ne Chrome.

**Comment by MatthiasApsel** [comment]
Im Android Stock siehts richtig aus.

**Comment by ckruse** [comment]
wohl eher an dem völlig kaputten Chrome-Browser

**Comment by MatthiasApsel** [comment]
*g*

**Comment by ckruse** [comment]
die neue Geissel des Internets… alte Android Browser. *brr*

**Comment by ckruse** [comment]
😂

**Comment by ckruse** [comment]
Keine Ahnung, ich kann es nicht testen. Unter iOS sieht es richtig aus. Und ein Android-Gerät besitze ich nicht...

**Comment by ckruse** [comment]
Im Chrome unter iOS sieht es auch richtig aus.

**Comment by MatthiasApsel** [comment]
Is ja nun auch nicht **so** schlimm.

**Comment by MatthiasApsel** [comment]
Möglicherweise ist irgendwas unterschiedlich registrierter - unregistrierter Nutzer?
