### ISSUE TITLE
Paginierung für Seiten der Zitatesammlung

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#537]
Ältere Zitate sind derzeit nicht erreichbar.

**Comment by ckruse** [comment]
Hihi, ups

**Comment by MatthiasApsel** [comment]
Passiert ;-)

Wenn man auf einer der Unterseiten der Zitatesammlung ist (/voting, /new) könnte in die Subnav ein Link "Zitate lesen". Ebenso könnte es einen Link mit geeignet Parametern (https://forum.selfhtml.org/search?utf8=%E2%9C%93&term=&sections%5B%5D=4&start_date%5Bday%5D=1&start_date%5Bmonth%5D=1&start_date%5Byear%5D=1998) zur Suche geben. ("Zitatesammlung durchsuchen")
