### ISSUE TITLE
Threads ohne Antworten in die Übersichtsseite aufnehmen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#538]

**Comment by ckruse** [comment]
Bitte?

**Comment by MatthiasApsel** [comment]
In der Übersichtsseite (forum.selfhtml.org) könnten auch die Threads aufgelistet werden, die noch keine Antwort haben. Vielleicht erbarmt sich dann ja jemand.

**Comment by auge8472** [comment]
Vielleicht verliert aber auch jemand die Übersicht? Wenn das „gerecht“ sein soll, gehören da *alle* unbeantworteten Threads hin. Wenn es die Leute mal berappeln sollte, können das auch mehr als die zwei oder drei Stück sein, die momentan üblich sind. Dann würde die Liste sehr lang und (mMn) sehr dominant sein.

Wie wäre es mit einer Zeile a la „*Es gibt 4 bisher unbeantwortete Threads/Anfragen im Forum Meta.*“?

**Comment by MatthiasApsel** [comment]
Ich denke eher an 

~~~
länger unbeantwortete Threads

 Thread 1 (der älteste)
 Thread 2
 Thread 3

alle anzeigen
~~~

Dies unterhalb des letzten Forums

**Comment by auge8472** [comment]
> Ich denke eher an …

Meinst du, das ist in der Übersicht notwendig?

Meiner Meinung nach ist die Angabe, wieviele unbeantwortete Threads es pro Forum gibt, ausreichend. Was macht denn der geneigte Benutzer dieser Ansicht? Er verschafft sich eine Übersicht und ruft dann (mit an Sicherheit grenzender Wahrscheinlichkeit) eines der oder die Foren (mit den unbeantworteten Threads) auf. Die Übersichtsseite ist ja einzig Portal *zum Forum*. Der Benutzer geht eh *dort hin*, weil es kein Anderswo gibt.

**Comment by MatthiasApsel** [comment]
> Er verschafft sich eine Übersicht und ruft dann (mit an Sicherheit grenzender Wahrscheinlichkeit) eines der oder die Foren (mit den unbeantworteten Threads) auf.

Die unbeantworteten Threads muss er aber dort auch wieder suchen.

**Comment by auge8472** [comment]
> Die unbeantworteten Threads muss er aber dort auch wieder suchen.

Das muss er, je nach den Einstellungen, tatsächlich.

**Comment by ckruse** [comment]
Ich bin hier Heikos Meinung, das ist der Übersicht IMHO
abträglich. Zumal es unbeantwortete Threads bei uns selten gibt.

**Comment by MatthiasApsel** [comment]
Wie gesagt, ich würde sie nicht in die einzelnen Foren einordnen, sondern ganz nach unten schieben.

> Zumal es unbeantwortete Threads bei uns selten gibt.

Das wäre erst recht ein Grund, auf sie hinzuweisen.

**Comment by MatthiasApsel** [comment]
Und der Link "alle anzeigen" verlinkt selbstverständlich auf `https://forum.selfhtml.org/all?ostwa=yes`

**Comment by ckruse** [comment]
Was ist `ostwa`?

**Comment by ckruse** [comment]
Only Show Threads Without Answer?

**Comment by MatthiasApsel** [comment]
Genau.
