### ISSUE TITLE
Benachrichtigungen wenn ein Zitat neu vorgeschlagen wurde

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#540]
Der default-Wert sollte `on` sein, damit sich möglichst viele an der Zitatesammlung beteiligen. Wenn das betreffende Zitat gelöscht wurde, muss entweder die Benachrichtigung gelöscht werden oder es sollte eine zweite hinterher geschickt werden.

**Comment by auge8472** [comment]
Wenn das umgesetzt wird, folgende Idee. Ungelesene Nachrichten sollten einfach aus dem Postfach verschwinden, wenn das Zitat gelöscht wird. Wozu sollte ich als Adressat schließlich auf eine Nachricht reagieren müssen, obwohl sich der Grund für die Benachrichtigung erledigt hat. Gelesene Nachrichten sollten hingegen mit einer neuen Nachricht ergänzt werden.

**Comment by ckruse** [comment]
Hab das mal so implementiert
