### ISSUE TITLE
Fehler im Benachrichtigungsbalken bei neuem Posting

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#541]
Wenn ein neues Posting vermeldet wird, wird mir eine Fehlermeldung statt der Anzahl der neuen Postings im Balken angezeigt. Da die immer nur kurz zu sehen ist, habe ich mir nur `translation missing` gemerkt. Das neue Posting selbst wird aber in die Seite eingefügt.

**Comment by ckruse** [comment]
Fixed
