### ISSUE TITLE
Anzahl der offenen Zitatabstimmungen neben Link zur Zitatesammlung unterbringen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#543]
https://forum.selfhtml.org/meta/2015/dec/9/benachrichtigung-bei-neuem-zitat-vorschlag/1656758#m1656758

**Comment by MatthiasApsel** [comment]
Am 2015-12-11 13:36, schrieb Christian Kruse:
> Closed #543 via ef7b4101bcc440ba7f425f15504bd9b7567868d8.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ckruse/cforum/issues/543#event-489298856

Das ist noch nicht ganz so, wie es soll

Gewünscht ist

<li>
   <a href="https://forum.selfhtml.org/cites">Zitatesammlung</a>
   (<a href="https://forum.selfhtml.org/cites/voting">3</a>)
</li>

Also ein Link zur Startseite der Sammlung und ggf. einer zu den 
Abstimmungen

-- 
Herzliche Grüße
Matthias

**Comment by MatthiasApsel** [comment]
Und *richtig* cool wäre es, wenn in Klammern die Anzahl derjenigen 
Abstimmungen steht, bei denen der angemeldete Nutzer noch nicht 
abgestimmt hat.

-- 
Herzliche Grüße
Matthias

**Comment by ckruse** [comment]
Ob das gewünscht ist sei jetzt mal dahin gestellt, aber ich habs jetzt so implementiert ;-)

**Comment by MatthiasApsel** [comment]
> Ob das gewünscht ist sei jetzt mal dahin gestellt, aber ich habs jetzt
> so implementiert ;-)

henman schrieb: Alternativ schlage ich vor, neben dem 
Zitatesammlung-Link in Klammern die Anzahl der offenen Vorschläge zu 
schreiben, verlinkt auf die Abstimmungsseite.
