### ISSUE TITLE
LaTeX in Zitaten?

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum#544]
So wie das für mich aussieht, wird [hier](https://forum.selfhtml.org/cites/2054) der LaTeX-Code nicht entsprechend umgesetzt. Schätze da muss der Renderer für LaTeX-Formeln noch für die Zitatesammlung aktiviert werden... (außer ich übersehe eine Fehlformatierung)

**Comment by ckruse** [comment]
Die Zitate-Sammlung nimmt nur plain text.


Das soll so. Es gibt dafür keine gute Lösung. Die alten Zitate sind wild durchmischt mit allen möglichen Formaten (oft wird z.B. noch &raquo; verwendet, manchmal werden völlig frei erfundene Konstrukte verwendet), eine automatische Umwandlung ist höchst problematisch. Deshalb habe ich sämtliche Formate einfach abgeschaltet.

**Comment by campingrider** [comment]
Siehe https://forum.selfhtml.org/intern/2015/dec/11/latex-in-zitatesammlung/1656845#m1656845
