### ISSUE TITLE
Störende Abfrage beim Löschen von Benachrichtigungen

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum#553]
Das Löschen einer Benachrichtigung erfordert IMHO keine Abfrage „Sind Sie sicher, dass Sie die Benachritigung löschen wollen?“ Es geht hier nicht um die Löschung eines Accounts. Die Abfrage erfordert eine zusätzliche Nutzeraktion und bringt keinen Mehrwert. Weg damit?

**Comment by ckruse** [comment]
Das sehe ich anders. Ich habe schon mehrfach beinahe aus Versehen eine
Benachrichtigung gelöscht. Und in der Tat ist das kein Löschen des
Accounts, nichts desto trotz ist es ärgerlich, wenn sie weg ist: für
mich ist das eine Erinnerung an etwas, das ich mit der Nachricht noch
tun wollte.
