### ISSUE TITLE
Unnütze Benachrichtigung beim Eintragen eines Zitats in die Sammlung

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum#554]
Wenn man selbst ein Zitat in die Sammlung einträgt, dann weiß man das. Man sollte darüber nicht benachrichtigt werden (nur jeweils alle anderen Abonnenten).

**Comment by MatthiasApsel** [comment]
Und wenn man das entsprechende Zitat bewertet hat, könnte die Benachrichtigung auch entfernt bzw. auf gelesen gesetzt werden, je nach Einstellung.
