### ISSUE TITLE
Enhancement - Zitatesammlung: Quelle bei internen Links nur Berechtigten anzeigen

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum#556]
Ich habe während dem Zitate-markdownisieren mit MApsel folgende Frage erörtert:

Momentan muss man, wenn man u.a. Beitragsdatum und Autor automatisch ermitteln lassen bzw. verlinken möchte, eine Quelle für die Zitatesammlung angeben. Bei Quellen aus dem geschlossenen Bereich des Forums kann ja nicht auf die Quelle zugegriffen werden - und der Hauptteil der Nutzer bekommt da nichts zu sehen. Teilweise wurden deshalb Quellen im Nachhinein entfernt, nachdem die Informationen automatisiert eingetragen wurden - eben damit nicht so viele Benutzer einen Fehler beim Zugriffsversuch bekommen. Es wäre mMn schön, wenn man die Problematik folgendermaßen umschiffen könnte: 

Bei Zitaten mit internen Quellen könnte die Berechtigung des ansehenden Benutzers dahingehend überprüft werden, ob er das Recht hat, die Quelle anzuzeigen. Falls ja: Situation wie bisher, mit Link, falls nein: Statt dem Quelle-Link ein "Quelle nicht öffentlich" oder "Quelle: geschlossener Bereich" oder ähnliches.

Das hat mehrere Vorteile: 
* Berechtigten wird die Quelle weiterhin angezeigt
* Unberechtigte versuchen nicht unnötigerweise, die Quelle zu öffnen
* Es gibt einen sichtbaren Unterschied zwischen "Keine Quelle angegeben" und "Quelle nicht öffentlich" (was bei der momentanen Praxis, geschlossene Quellen wegzueditieren, nicht gegeben ist) - dadurch wird es auch für die nicht-Berechtigten plausibel, dass das Zitat tatsächlich so gefallen ist, also dass es im Zweifelsfall nachprüfbar ist

**Comment by campingrider** [comment]
Vielen Dank :+1:

**Comment by ckruse** [comment]
Gern

**Comment by campingrider** [comment]
Wie verhält sich den die Zitatesammlung bei gelöschten bzw. Nnicht-archivierten Threads? Da sollte theoretisch die Quelle wohl auch ausgeblendet werden.

Wäre es vielleicht tatsächlich eine Option, bei Nicht-Anzeige der Quelle einen Grund stattdessen anzuzeigen, a la "Quelle: nicht zugriffsberechtigt" bzw. "Quelle: gelöschtes oder nicht-archiviertes Posting"?
