### ISSUE TITLE
Zitatesammlung: Pagination berücksichtigt gelöschte Zitate nicht

### ISSUE THREAD

**Issue by campingrider** [ckruse/cforum#558]
Versucht man in der Zitatesammlung von [#1395](https://forum.selfhtml.org/cites/1395) per Pagination-Button (<<) zum nächsten Zitat zu kommen, landet man auf [der vermeintlichen Seite zu #1396](https://forum.selfhtml.org/cites/1396) - einer 404-Fehler-Seite. Offensichtlich wurde das Zitat gelöscht. Demnach sollte der Pagination-Button eher auf [#1397](https://forum.selfhtml.org/cites/1397) führen - es muss also in der Pagination beachtet werden, ob Zitate gelöscht wurden.

**Comment by MatthiasApsel** [comment]
bei den neuen Zitaten ist das schon berücksichtigt.

**Comment by ckruse** [comment]
Es gibt keine gelöschten Zertifikate. Die existieren dann nicht in der Datenbank.

**Comment by ckruse** [comment]
Und es gibt auch einen 500er ("etwas ist schief gelaufen"), keinen 404 ;-)
