### ISSUE TITLE
unbekannte Sprache führt zum Abbruch

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#565]
Wenn über die MD-Buttons ein Codeblock eingefügt werden soll, kommt "Sprache? (z.B. js, html oder css. Leer lassen falls unbestimmt)" Leer lassen, führt nicht dazu, dass die `~~~` eingefügt werden.

**Comment by campingrider** [comment]
Stimmt, ich kann den Bug bestätigen, ist mir in der Vergangenheit auch aufgefallen.
