### ISSUE TITLE
Punkte, wenn Threads gelöscht werden

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#566]
Ggf. ändert sich der Punktestand (häufig zum negativen), wenn Beiträge gelöscht oder Threads nicht archiviert werden. Ich schlage vor

* entweder die Punkte zu behalten
* oder im Bewertungsverlauf zu dokumentieren, wo sie hin sind.

**Comment by campingrider** [comment]
Ich verstehe die Absicht (und unterstütze das prinzipiell), gehe allerdings davon aus, dass die Implementierung dieses Features eher teuer ist (ich gehe davon aus, dass dafür einige Systeme konzeptionell verändert werden müssen) und bin mir dann nicht sicher, ob der Nutzen den Aufwand rechtfertigt.

**Comment by ckruse** [comment]
Also, ich kann die Punkte relativ einfach belassen, wo sie sind. Aber ich habe das aus einem Grund nicht getan: es ist ein Problem der Transparenz. Wenn ich die Punkte belasse, aber das, worauf sie sich beziehen, weg ist, ist auch nicht mehr nachvollziehbar, woher sie kommen. Und ich bekomme auch ein Problem in der Darstellung: siehe /users/1, wie soll ich das da unterbringen?

Ich kann nicht die fehlenden Punkte in einer Art Protokoll darstellen, wo sie hin sind; das geht nicht, weil ich ein solches Protokoll nicht habe.

**Comment by MatthiasApsel** [comment]
<table><tr><td>10<td>Dieser Beitrag wurde gelöscht.</table>?

**Comment by ckruse** [comment]
Hab ich auch ausprobiert, aber die Gruppierung geht dann halt nicht mehr.

**Comment by MatthiasApsel** [comment]
Was ist die Gruppierung? Dies?

<table><tr><td>10 10 10 10<td>Dieser Beitrag wurde gelöscht.</table>

Es geht nicht darum, wenn ein Benutzer die Bewertung manuell oder durch Abmelden ändert. Sondern nur um Bewertungen, die verloren gehen, wenn der Beitrag nicht mehr existiert.

**Comment by ckruse** [comment]
Ich muss die Referenz auf den Beitrag auf NULL setzen, wenn der Beitrag gelöscht wird (oder halt den Datensatz mit der Referenz auch entfernen). Ich kann da nicht mehr gruppieren nach Nachricht, weil die Information, dass die Scores zu einer Nachricht gehören, nicht mehr vorhanden ist.

**Comment by MatthiasApsel** [comment]
Ah. Dann lassen wir es so. Gibts die Möglichkeit, betroffene Benutzer zu benachrichtigen?

**Comment by ckruse** [comment]
Jetzt habe ich das schon so umgesetzt... ;-) ich finde das nicht besonders schlimm, wenn ich es so vor mir sehe.

Was man auch machen könnte ist alle Scores für gelöschte Nachrichten zusammenfassen (ich kann ja erkennen, dass die Nachricht gelöscht wurde)

**Comment by MatthiasApsel** [comment]
Ein ganz schöner Aufwand :)

**Comment by ckruse** [comment]
Findest du? Ich fands moderat… hab da etwa 2h dran gearbeitet, inklusive Test.

**Comment by ckruse** [comment]
(ist aber noch nicht online)

**Comment by MatthiasApsel** [comment]
2 Stunden gearbeitet, also am Rechner gesessen. Ist es nicht so, dass man über Aufgabenstellungen nicht auch ein wenig nachdenken muss? ;-) Oder ist das für dich eigentlich schon gar kein Problem mehr?

**Comment by ckruse** [comment]
Das hängt von der Aufgabenstellung ab. In diesem Fall musste ich nicht darüber nachdenken, wie das gelöst wird, das ist ja trivial.
