### ISSUE TITLE
noch mal problematische Seite

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#570]
https://github.com/ckruse/cforum/commit/e0b0d9271e8213aeee826e8e24d347f2901d4fcb funktioniert aber nicht, zumindest für die Livevorschau. (#569)

**Comment by ckruse** [comment]
Doch

![screen shot 2016-01-04 at 08 37 03](https://cloud.githubusercontent.com/assets/175095/12085268/6432b6a0-b2be-11e5-9b9a-d826592ef48d.png)

Du musst natürlich auch was eintragen in das Feld ;-)

**Comment by MatthiasApsel** [comment]
Nur, wenn ich einen neuen Beitrag erstelle, nicht beim Antworten.
