### ISSUE TITLE
Benachrichtigung in Übersichtsseite soll direkt zum Beitrag linken

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#571]
Wenn in der Übersichtsseite Benachrichtigungen auftauchen "User hat auf Ihren Beitrag geantwortet", ist der Umweg über die Benachrichtigungsseite imho nicht notwendig. Das betrifft eigentlich alle Benachrichtigungen.

**Comment by MatthiasApsel** [comment]
Ich seh grad, das ist ja schon so?

**Comment by ckruse** [comment]
Das war schon immer so. Genauer gesagt: ich linke auf die Notification, 
die wiederum redirected auf den Beitrag. Ich mache das, weil ich anders 
die Benachrichtigung nicht als gelesen markieren oder löschen kann (ich 
müsste in allen möglichen Programmteilen die Benachrichtigung immer 
wieder auf gelesen setzen oder löschen; so nur an einer Stelle)

**Comment by MatthiasApsel** [comment]
ja, ich hatte mich über das Linkziel gewundert, dann die issue geschrieben und dann erst geklickt. 

Clevere Lösung.
