### ISSUE TITLE
Zusätzliche "neue Mail"-Links

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#574]
... wären aus meiner Sicht eine Verbesserung.

![forum-mail](https://cloud.githubusercontent.com/assets/2847625/12221567/191276e2-b7a0-11e5-8535-28ae9698538b.png)

**Comment by ckruse** [comment]
Ich will wirklich nicht immer so negativ klingen, aber ich finde, das sieht völlig verwirrend aus. Überall sind diese Brief-Icons. Das ist der totale UI-Clutter. :( Sorry.

**Comment by MatthiasApsel** [comment]
Ja, das Bild stellt ja auch ein "oder" dar ;-) Ganz rechts halte ich sie auch für fehlplatziert. Was wäre, wenn der "Parntername" zu "neue Mail an diesen Partner" verlinkt? Vielleicht sollte man die Icons auch auch in die erste Spalte setzen.
