### ISSUE TITLE
Hinter das Feld "problematische Seite" ein Papierkorb-Icon setzen, ...

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#576]
... das auf Klick dieses Feld leert.

Das halte ich für eine gute Idee.

**Comment by ckruse** [comment]
ich halte das nicht für sinnvoll. Das führt nur zu noch mehr clutter in der UI. Ich halte es für sinnvoller, die problematische seite nicht länger vorzubelegen mit dem Link des OP. Das hat mir von vornherein nicht besonders gefallen...

**Comment by MatthiasApsel** [comment]
oder nicht mit dem Link des OP vorbelegen, sondern mit dem Wert der in dem Beitrag steht, auf den man antwortet.

**Comment by ckruse** [comment]
Das ist ja bereits der Fall: nur meine Ausdrucksweise war schlampig:

    @message.problematic_site = @parent.problematic_site

**Comment by ckruse** [comment]
Hast du begründete Einwände dagegen, das vorbelegen wieder zu entfernen?

**Comment by MatthiasApsel** [comment]
Es ist irgendwie beides nicht optimal.

**Comment by ckruse** [comment]
Ich weiss nicht, was du erreichen möchtest. Was ist denn das Ziel? Das habe ich mich schon damals bei der Änderung mit dem vorbelegen gefragt.

**Comment by MatthiasApsel** [comment]
Nun, wie ich schon schrieb. TO setzt einen Link auf die problematische Seite. Wenn der nicht übernommen wird, befindet sich diese wichtige Information nur am OP. Siehe zum Beispiel die JS-Tutorial-Diskussion. Wenn jemand einen Beitrag liest, und im Text steht, "im Artikel steht aber ...", dann muss derjenige erst auf eine mehr oder weniger umständliche Weise den LInk zur problematischen Seite verschaffen. 

Ich kann verstehen, dass du das Papiekorbicon nicht haben möchtest, halte aber die jetzige Lösung für besser, wenn die problematische Seite praktisch an jeder Antwort steht, statt an keiner.

**Comment by ckruse** [comment]
Dann lassen wir es, wie es ist...
