### ISSUE TITLE
Zu besonderen Ereignissen gratulieren?

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#580]
Das Heise-Forum so:

`Heute seit 5 Jahren bei heise online: Herzlichen Glückwunsch!`
`Benutzername`

Findest du das für uns sinnvoll?

**Comment by ckruse** [comment]
Darüber hatte ich auch schon nachgedacht. Stackoverflow vergibt dafür
Badges (ohne Funktion). Finde ich eigentlich sympathisch.

Aber dass du seit 5 Jahren im Heise-Forum bist, das finde ich gruselig… ;-)

**Comment by MatthiasApsel** [comment]
Ich bin gar nicht im Heiseforum. Das bekommt offenbar jeder gezeigt. Ich durchschnüffele derzeit verschiedene Nutzungsbedingungen wegen der letzten Vorkommnisse..

**Comment by ckruse** [comment]
- 1 Jahr dabei, für jedes weitere Jahr wiederholt (Jährling, bronze)
- 100, 1000, 2000, 4000, 8000, 10.000 Beiträge (Schreiberling/bronze, Vielschreiber/bronze, ... Ideen!)
- wenn man Description und Homepage in seinem Profil angegeben hat (Autobiograph, bronze)
- wenn ein Beitrag positiv bewertet wurde
- wenn ein Beitrag 5 mal positiv bewertet wurde (gute Antwort, bronze)
- wenn ein Beitrag 10 mal positiv bewertet wurde (tolle Antwort, silber)
- wenn ein Beitrag 15 mal positiv bewertet wurde (grossartige Antwort, Gold)
- wenn ein Beitrag mindestens 5 mal positiv und negativ bewertet wurde (Kontrovers, bronze)
- wenn man den ersten Beitrag positiv bewertet (Entusiast, bronze)
- wenn man den ersten Beitrag negativ bewertet (Kritiker, bronze)
- wenn man eine Frage beantwortet, die mindestens einen Upvote hat (Lehrer, bronze)

Noch Ideen?

**Comment by MatthiasApsel** [comment]
Hallo,

die Ideen find ich Klasse.

Das zieht dann aber eine ganze Menge nach sich. Wenn man auf diese Weise 
Medaillen sammeln kann, müssen die auch irgendwo notiert werden.

Wenn man per Mail gratulieren möchte, muss man sich das Einverständnis 
holen, sonst heißt es unerwünschte Werbung, aber das kann ja in den 
Einstellungen passieren.

Es wären Medaillen, die mit den anderen nichts zu tun haben, weil man 
sich damit kein Recht erwirbt.

Herzliche Grüße
Matthias

**Comment by ckruse** [comment]
Klar müssen die notiert werden. Bei den restlichen Medallien. Eine
Trennung halte ich hier für nicht zielführend.

Eine Gratulation per Mail würde ich gar nicht machen, eine Gratulation
bei Besuch der Seite halte ich für völlig ausreichend.

Dass die Medallien keine Rechte vergeben halte ich nicht für einen
ausreichenden Grund für eine Trennung.

Ansonsten ist mir mein Notebook verstorben
(https://wwwtech.de/pictures/54), deshalb wird das mit der Arbeit am
Forum die nächste Woche schwierig; ein neues ist bereits bestellt, aber
das hat 5 Tage Lieferzeit.

**Comment by MatthiasApsel** [comment]
Vielleicht lassen sich trotzdem Gruppierungen für die Badges finden.

**Comment by ckruse** [comment]
Du musst genauer werden, ich weiss nicht recht was du meinst.

**Comment by MatthiasApsel** [comment]
Du schriebst

> Dass die Medallien keine Rechte vergeben halte ich nicht für einen
ausreichenden Grund für eine Trennung.

Man sollte sie vielleicht aber doch gruppieren.

* Medaillen, die man durch den Puntestand erreicht
* Medaillen, die aufgrund der Anzahl der Beiträge erreicht werden
    * > 1000 Affen
* Medaillen, die aufgrund der Dauer der "Mitgliedschaft" erreicht werden
* Medaillen, die aufgrund der Antworten erreicht werden
    * > gute Antwort
* Medaillen, die aufgrund des eigenen Bewertungsverhaltens erreicht werden
    * > Kritiker, Enthusiast

**Comment by ckruse** [comment]
Meine Frage ziehlte eher auf das „warum“ ab.

**Comment by MatthiasApsel** [comment]
Naja, weil sie auf verschiedene Weise erworben werden und mit einige nicht mit dem Erhalt von Rechten verbunden sind.

**Comment by ckruse** [comment]
Wir drehen uns im Kreis.

Ich glaube, dass dein Missverständnis darin liegt, dass Badges
prinzipiell mit Rechten versehen sind. Das war nie der Fall, beliebige
Badges anzulegen war schon immer Teil der Funktion des CForums. Es gibt
nichts spezielles an diesen Badges.

**Comment by MatthiasApsel** [comment]
> Wir drehen uns im Kreis.

Ja, das wollte ich auch schon schreiben. Aber du kannst auch nicht rational begründen, warum du keinen ausreichenden Grund für eine Trennung siehst. Ist halt Geschmackssache vs. Bauchgefühl ;-)

**Comment by ckruse** [comment]
So, ich habe das jetzt implementiert und könnte es Online schalten. Zur Zeit würden dann alle auf einmal n Jährling-Badges kriegen (maximal 10) und die Nachrichten-Badges (Schreibmaschine, Druckerpresse, ...) würden bei der nächsten geschriebenen Nachricht verteilt. Einwände?

**Comment by MatthiasApsel** [comment]
> Einwände?

keine. :-)

**Comment by ckruse** [comment]
Ist online.
