### ISSUE TITLE
title-Blacklist erstellen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#581]
Spam-URLs sind offenbar wesentlich interessanter als Seiten, die einfach nur Spam enthalten. Wir sollten eine Spam-Blacklist pflegen.

Wie im Wiki: https://wiki.selfhtml.org/wiki/MediaWiki:Titleblacklist, ergänzt um viagra, generica, ...

**Comment by ckruse** [comment]
Ist jetzt Verfügbar in Verwaltung->Einstellungen

**Comment by MatthiasApsel** [comment]
:+1: 

Das ging ja schnell. Steht auch schon was drin?

**Comment by ckruse** [comment]
Bisher nicht, nein. Aber die Syntax ist die gleiche: ein regulärer
Ausdruck pro Zeile, Leerzeilen und Zeilen, die mit # beginnen, werden
ignoriert.

**Comment by MatthiasApsel** [comment]
Und muss `.*` vorn und hinten dran? Wir sollten eine Info ins interne Wiki schreiben, dass es das gibt.

**Comment by ckruse** [comment]
Es wird kein Anchor verwendet (ausser du schreibst einen rein), also ist
auch kein .* nötig
