### ISSUE TITLE
Eingaben in die Blacklists werden nicht gespeichert

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#583]

**Comment by ckruse** [comment]
Ich glaube nicht, dass das stimmt. Hier geht alles, und wenn ich das online ausprobiere geht es auch.

Hast du die Checkbox aus "Default-Wert" rausgenommen?

**Comment by MatthiasApsel** [comment]
> Hast du die Checkbox aus "Default-Wert" rausgenommen?

natürlich nicht ;-)

Dass man das aber auch manuell machen muss ;-)

**Comment by MatthiasApsel** [comment]
Ich kann aber trotzdem entsprechende Beiträge erstellen. Siehe audit-log.

**Comment by ckruse** [comment]
Ich hatte glatt vergessen, das auch für neue Threads einzubauen ;-)

**Comment by MatthiasApsel** [comment]
Gibts für die menschlichen Spammer auch noch ne Fehlermeldung?
