### ISSUE TITLE
Mentions funktionieren nicht in der Livevorschau

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#586]
Wenn ich einen Benutzer mit seinem Benutzernamen erwähne und diese Erwähnung als Teil eines Linktextes benutzen will, funktioniert zwar der Link, aber die Formatierungsanweisungen des Mentions werden innerhalb des Linktextes als Kramdown-Quelltext ausgegeben.

![sf-mention-bug](https://cloud.githubusercontent.com/assets/1734660/13564994/b127aafe-e44d-11e5-8a81-baf5a3823897.png)

Tschö, Auge

**Comment by ckruse** [comment]
Das kann auch gar nicht funktionieren, denn ein Mention zieht auch immer
einen Link nach sich. Ein Link in einem Link - das geht nicht.

**Comment by auge8472** [comment]
Ähhm ja, logisch. Wo du es sagst, fällt mir wie Schuppen aus den Haaren, dass das schon auf dem Screenshot zu sehen ist. Naja, Bäume und Wälder.

Bleibt, um  beim Thema Mentions zu bleiben, ein weiterer Punkt. Die Formatierung des Mentions funktioniert in der extra aufzurufenden Vorschau, aber nicht in der Livevorschau.

**Comment by ckruse** [comment]
Ja… ist mir auch schon aufgefallen. Hatte aber bisher keine Zeit, das zu
fixen.
