### ISSUE TITLE
Markdown-Code eines Postings ansehen

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#587]
Manchmal fragt man sich, wie der Poster etwas in Markdown realisiert hat, daher wäre es eine praktische Funktion, sich den Markdown-Code eines Postings ansehen zu können, _ohne dass man die Berechtigung zum Editieren eines Postings_ haben muss.

Vielleicht ist das realisierbar.

**Comment by auge8472** [comment]
Öffne das Posting zum antworten und du siehst die Kramdown-Formatierungen.

**Comment by JuliusPC** [comment]
Ah, danke! Das war wikrlich zu naheliegend.

Sorry...

**Comment by ckruse** [comment]
Das muss ich machen ;-)

**Comment by MatthiasApsel** [comment]
Nö, der opener kann auch eine issue schließen.

**Comment by JuliusPC** [comment]
@MatthiasApsel Tatsächlich, wieder mal etwas klüger :-)

Eins fällt mir aber noch ein: Wenn ich die Kramdown-Syntax eines archivierten Posts anzeigen möchte, kann ich das natürlich nicht über das Zitieren erledigen. Aber es gibt ja genug nicht archivierte Posts...

**Comment by auge8472** [comment]
Zusätzlich hast du auch die Möglichkeit des Aufrufs der Forumshilfe. Über dem Textfeld für ein neues Posting/eine neue Antwort gibt es ein Link zur Kramdown-Hilfe des Forums. Du siehst dort zwar nicht die konkrete Verwendung in einem Posting, aber erklärt ist die Syntax, wenn auch nicht am Beispiel, ja trotzdem.

**Comment by JuliusPC** [comment]
Ich war wohl einfach zu dumm, die Stelle im Wiki-Artikel zu finden, wie das mit den [Fußnoten in Markdown](https://wiki.selfhtml.org/wiki/SELFHTML:Forum/Bedienung#Fu.C3.9Fnoten) funktioniert. Jetzt weiß ich es :-)
