### ISSUE TITLE
Rückverlinkung von Posting auf Zitat

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#588]
Ein Beispiel:  
Das [Zitat](https://forum.selfhtml.org/cites/2063) verlinkt nicht nur auf das [Ursprungsposting](https://forum.selfhtml.org/self/2016/jan/8/fehler-beim-import-des-sql-dump/1658488#m1658488) sondern auch umgekehrt (Posting → Zitat; z.B. ein kleiner Link „Dieses Posting bzw. ein Ausschnitt daraus wurde in die Zitatsammlung aufgenommen“).

**Comment by ckruse** [comment]
Ich weiß nicht, die Nachrichten-Ansicht ist eh schon so extrem voll. Was ist denn der Mehrwert davon?

**Comment by JuliusPC** [comment]
Einen wirklich konkreten Mehrwert außer „Oh, interessant – dieser Beitrag ist zitiert worden!“ kann ich nicht vorweisen. Ich finde es als etwas inkonsistent, einen Rückling zu setzen, wenn ein Beitrag auf einen anderen verweist, dies aber bei Zitaten nur in eine Richtung zu tun.

Der Link auf das Zitat könnte unter den Beitrag gesetzt werden, wo auch die anderen Rücklinks erfasst werden.

**Comment by ckruse** [comment]
Ein Backlink auf ein verweisendes Posting bietet aber einen echten Mehrwert: ggfls weiterführende Informationen.

Aber wirklich stören würde es glaub ich auch nicht, wenn man es in die Liste mit aufnimmt. Ich schau mal.

**Comment by MatthiasApsel** [comment]
"Oh, dieser Beitrag war Quelle eines Zitats" ist ein FunFact und wert mit in die Liste aufgenommen zu werden. 

"Folgendes Zitat stammt aus diesem Beitrag:"

**Comment by ckruse** [comment]
Das ist viel zu viel. Ein Link muss genügen, es wird doch so schon alles vollgekleistert mit Meta-Informationen.

**Comment by MatthiasApsel** [comment]
Ich würde sagen: So oder gar nicht. Wenn ein Link ohne Erläuterung in der Gegend rumsteht, ist es auch nicht schön.

**Comment by ckruse** [comment]
Ich habe nicht gesagt, dass es „ohne Erläuterung in der Gegend
herumstehen“ soll. Aber so wie ich es von dir verstanden habe ist es
viel zu viel. Ich dachte eher an sowas: „Dieses Posting dient als Quelle
für Zitat #224245“, wobei dann „Zitat #224245“ verlinkt ist.

**Comment by MatthiasApsel** [comment]
Ja, so ähnlich dachte ich auch. Was spricht dagegen, das genau so wie die akzeptierten Antworten zu gestalten?

**Comment by ckruse** [comment]
Nichts, das war ja mein Gedanke. Nur las sich das bei dir so als
wolltest du das ganze Zitat unter dem Posting anzeigen ;-)

**Comment by MatthiasApsel** [comment]
Gut, dass wir drüber gesprochen haben. ;-)

**Comment by MatthiasApsel** [comment]
> Closed #588 via d82c9a9babc48e1b2518de92e01a3ff57760e8f5.

Das funktioniert aber nicht wie erwartet.

https://forum.selfhtml.org/self/2016/feb/29/eingeschraenkte-abfrage-in-php/1662283#m1662283 
sollte eine entsprechende Mitteilung besitzen, weil es [Zitat 
2092](https://forum.selfhtml.org/cites/2092) enthält

**Comment by ckruse** [comment]
Das ist noch nicht online.
