### ISSUE TITLE
Message Bar wird an unpassenden Stellen angezeigt

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#589]
Wenn ich ein Posting erstellt oder geändert habe, wird mir der (Miss)-Erfolg der Aktion über den Balken angezeigt. So weit, so gut. Öffne ich danach ein anderes Posting oder lade eine der Forenübersichten neu, wird der Balken dort noch einmal angezeigt. Das habe ich zumindest in den ersten 10 bis 15 Sekunden nach dem absenden der Eingaben beobachtet. Es passiert auch in einem anderen Tab.

Browser: Firefox 43
OS: Windows 7

**Comment by ckruse** [comment]
Ist mir auch schon aufgefallen. Ich habe aber noch nicht herausgefunden,
woran es liegt.

**Comment by ckruse** [comment]
Das muss irgend eine Art von Race Condition sein. Bei mir lokal tritt das nicht auf. Ich muss mir mal anschauen, wie der Flash funktioniert.

**Comment by ckruse** [comment]
Ggfls muss ein `flash.discard` eingebaut werden... lieber wäre es mir aber, wenn ich heraus finde, wo der Grund dafür ist

**Comment by ckruse** [comment]
Mit einem `flash.clear` nach einem erfolgreichen Rendering der Nachrichten ist das Problem umgangen.

**Comment by ckruse** [comment]
Hm, race conditions gonna race. Ist doch noch da...

**Comment by ckruse** [comment]
es scheint etwas mit der Synchronisation via JS zu tun zu haben. Hm, ob ich vielleicht den Request einfach etwas verzögere?

**Comment by auge8472** [comment]
> Hm, ob ich vielleicht den Request einfach etwas verzögere?

Wie lange soll das sein? Meine letzte Aktion gestern (2016-03-16) war das Absenden [dieses Postings](https://forum.selfhtml.org/self/2016/mar/21/wie-am-besten-konfigurationsparameter-uebergeben/1663649#m1663649). Heute morgen habe ich den Rechner und den Browser gestartet und mein Profil sowie das SelfHTML-Forum und ein paar Postings aufgerufen, jedoch kein neues Posting angelegt, ohne dass ich eine Meldung zu sehen bekommen hätte. Beim ersten Aufruf des Meta-Forums, wie gesagt hatte ich zuvor bereits andere Seiten des Forums aufgerufen, wurde mir wieder der Balken angezeigt, der das Speichern eines Postings vermeldete.

Weitere Details folgen (muss weg).

**Comment by ckruse** [comment]
Das Problem scheint zu sein, dass durch den konkurrierenden Zugriff durch AJAX irgendwie die Cookie-Verwaltung bzgl des Flashes durcheinander kommt. Wenn ich das Feature ausschalte, dann wird der Flash korrekt gelöscht nach dem Rendern der Nachricht.

Wenn ich also der AJAX-Request verzögerte, dann, das ist die Vermutung, klappt das mit den Cookies.

Aber ich bin mir auch nicht sicher, ob das hilft; vor allem aber würde es die von Woodfighter beschriebene Problematik (das Aktualisieren ist zu langsam) verschärfen.

Ich bleibe dran, aber ich habe noch keine Lösung gefunden (ausser auf den Flash zu verzichten; aber das kann ja auch nicht das wahre sein)

**Comment by ckruse** [comment]
Ein anderer Session-Store als Cookie könnte auch helfen, hat aber auch unangenehme Nebenwirkungen...

**Comment by ckruse** [comment]
Synchrones AJAX könnte auch eine Lösung sein, ist aber auch, gelinde gesagt, scheisse...

**Comment by ckruse** [comment]
Ich glaube inzwischen, dass das einzige, was sinnvoll hilft, ein serverseitiger Session-Store ist, etwa in einem Memcached oder so.

**Comment by ckruse** [comment]
Ich habe da mal einen Memcached eingeschaltet als session storage, nur mal zum test. Mal sehen, ob das was bringt.

**Comment by ckruse** [comment]
Verwirrend. Das hilft auch nicht. Bisher scheint das einzige, was hilft, AJAX ausschalten zu sein.

**Comment by ckruse** [comment]
Zum kotzen. Ein verzögern via `setTimeout` funktioniert zumindest bei mir, dürfte aber abhängig sein von der Netzverbindung. Schön ist das nicht und eine Lösung ist das auf keinen Fall. *seufz*

**Comment by auge8472** [comment]
Du scheinst dich regelrecht in Rage zu bringen.  
Ostern steht vor der Tür und das ist ein kosmetisches Problem. Lass mal los. :-)

**Comment by ckruse** [comment]
Alles gut ;) mich ärgert es nur, wenn ich einen Bug nicht los werde.

**Comment by ckruse** [comment]
So, nach ausgiebiger Recherche und Sourcecode lesen muss ich feststellen, dass ich um das zuverlässig zu vermeiden einen eigenen session storage driver schreiben müsste... ich bin mir noch nicht sicher, ob ich das will.

**Comment by ckruse** [comment]
Will ich nicht. Das mit der künstlichen Pause funktioniert gut.
