### ISSUE TITLE
Autobiograph

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#595]
Ich bin jetzt auch Autobiograpf (Duden empfiehlt diese Schreibweise) Es gibt ja neben twitter und jabber noch andere soziale Netzwerke (, die ich zwar nicht oder nur sehr wenig nutze). Sollten wir da noch andere aufnehmen?

**Comment by ckruse** [comment]
Slack könnte noch Sinn machen, oder Facebook. Der Rest fristet ein Nischen-Dasein und kann getrost ignoriert werden, IMHO...

**Comment by MatthiasApsel** [comment]
> Slack könnte noch Sinn machen, oder Facebook. Der Rest fristet ein
> Nischen-Dasein und kann getrost ignoriert werden, IMHO...

Slack kenne ich gar nicht. Facebook natürlich, aber auch XING, LinkedIn 
halte ich für (wichtig ist das falsche Wort, erwähnenswert trifft es 
auch nicht) Instagram fällt mir noch ein.

**Comment by ckruse** [comment]
Gut, LinkedIn wäre tatsächlich noch relevant; Instagram ist Facebook,
aber wenn du das mit rein nimmst musst du auch Flickr mit rein nehmen.
XING ist irrelevant (und ich glaube auch nicht, dass die noch lange
überleben).

**Comment by ckruse** [comment]
Ich bin dafür das so zu lassen wie es it...

**Comment by MatthiasApsel** [comment]
Einverstanden.
