### ISSUE TITLE
Hilfeseite

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#597]
Durch die sehr vielen Medaillen wirkt die Hilfeseite nicht mehr sehr gelungen, weil neben den Medaillen viel freier Platz ist.

Vorschlag: Wir unterteilen die Medaillen in solche, die mit Rechten verbunden sind, solche die nur mit der Anzahl der Beiträge oder der Mitgliedsdauer (da finde ich [Orloks Vorschlag](https://forum.selfhtml.org/meta/2016/mar/8/neue-medallien/1662988#m1662988), statt Jährling  ... Untoter zu verwenden, super) und solche, die mit der Qualität der Antworten zu tun haben.

weitere Ideen?

**Comment by ckruse** [comment]
Bzgl Orloks Vorschlag: das ist halt ein Problem, weil ich dann jedes Jahr von Hand einen neuen Badge mit einer neuen Prüfung erstellen muss. Halte ich nicht für praktikabel.

**Comment by ckruse** [comment]
Es gibt jetzt badge groups.
