### ISSUE TITLE
Links in den Benachrichtigungs-E-Mails auf HTTPS umstellen

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#599]
In den E-Mails, die versendet werden, wenn jemand auf einen Beitrag geantwortet hat, wird noch auf die unverschlüsselte Version des Forums verlinkt.

Ein Beispiel:

> Hallo Julius,

> Unter dem URL [**http://**forum.selfhtml.org/self/2016/mar/23/erster-prototyp-des-php-forums/1663836#m1663836](http://forum.selfhtml.org/self/2016/mar/23/erster-prototyp-des-php-forums/1663836#m1663836) hat 1unitedpower eine neue
Antwort geschrieben:
> […]

**Comment by ckruse** [comment]
Fixed in 45516632a348d6b0ff9dacda81a3e657cab1b9a9
