### ISSUE TITLE
Fehler in Zitatnennung

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#600]
[Zitat 2098](https://forum.selfhtml.org/cites/2098): 

"Diese Nachricht wurde im Zitat #2098 zitiert." findet man in jedem Beitrag des Threads.

**Comment by MatthiasApsel** [comment]
Was hältst du von 

![kopf](https://cloud.githubusercontent.com/assets/2847625/14022234/3b86cdda-f1df-11e5-8d80-b01eb6ba1e3c.png)

**Comment by ckruse** [comment]
Der Bug ist gefixed. Was den Entwurf angeht: ich bin absolut kein Freund von solchen Verzierungen, ich finde das unbeholfen. Wenn es Verzierungen geben soll, dann bitte welcher visueller Natur und mit CSS umgesetzt; die Klammern sind völlig fehl am Platze.

Ausserdem bin ich nicht der Meinung, dass das in den Head gehört, der ist eh schon recht voll. Und die Starke Abhebung von dem Rest des Headers ist auch nicht so sinnvoll, es lenkt den Blick (mindestens bei besuchten Postings) unweigerlich auf das Zitat, dass aber bestenfalls ein "nice to know" ist.

**Comment by MatthiasApsel** [comment]
Es war CSS ;-)

**Comment by ckruse** [comment]
Naja, ob man die Zeichen mit CSS einfügt oder ins HTML schreibt ändert ja an meiner Argumentation nichts. Ich halte sie für eine Krücke.

Abgesehen davon habe ich mich ja nicht ausgesprochen gegen ein Refactoring, ich finde nur diese Variante nicht besonders gelungen.

**Comment by MatthiasApsel** [comment]
Ich fand "Grundlage für" so schön pregnant. Und das sieht zwischen den beiden Buttonleisten nicht schön aus.

**Comment by ckruse** [comment]
Ja, das ist dort zu kurz. Auf der anderen Seite finde ich es oben im Header aber halt auch zu stark ablenkend für ein Nebendetail.

**Comment by MatthiasApsel** [comment]
![fuss](https://cloud.githubusercontent.com/assets/2847625/14044076/4407e1ee-f28c-11e5-817b-84a7b53bdab5.png)

**Comment by ckruse** [comment]
Das gefällt mir
