### ISSUE TITLE
(Seltsame) Übersicht bei alten Forum-Links

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#604]
Beispielsweise führt der Link (Quelle: [input oder button für submit-Elemente?](https://blog.selfhtml.org/2015/02/09/input-oder-button-fuer-submit-elemente/))
  http://forum.de.selfhtml.org/?t=219370
auf eine nicht im CI von SEFLHTML erscheinende Seite () unter
   https://forum.selfhtml.org/self/2015/feb/10/input-oder-button-fuer-submit-elemente
statt auf den Thread unter
  https://forum.selfhtml.org/self/2015/feb/10/input-oder-button-fuer-submit-elemente/1631986#m1631986

Screenshot der seltsam aussehenden Ansicht:  
![2016-03-27 19-02-27](https://cloud.githubusercontent.com/assets/15018932/14066601/9e5e3440-f44e-11e5-9dfb-01d09a897d60.png)

**Comment by ckruse** [comment]
Ja, weil der Link falsch ist, da fehlt ein `&m=1631986`

**Comment by ckruse** [comment]
Der Link auf den Thread statt auf einen Beitrag ist Teil der JS-API. Eine Verlinkung darauf ist nicht vorgesehen. Ich habe den Link im Weblog mal gefixed, danke.

**Comment by JuliusPC** [comment]
Gibt es eigentlich eine stabile, kürzere Variante zur Verlinkung auf das Forum? – Also z.B. etwas in der Art _http://forum.selfhtml.org/?t=219370&m=1631986_

**Comment by ckruse** [comment]
Stabil ist die URL, die in deinem Web-Browser existiert ;) Kürzer... nicht wirklich, dafür müsstest du die Thread-ID wissen, und die ist nicht Teil der URL. Warum möchtest du das?

**Comment by JuliusPC** [comment]
Verhindern, dass Leute Kurz-URL-Dienste benutzen, weil die entsprechende Seite das nicht von sich aus angebietet.

Sowas ähnliches habe ich in mein WordPress reingebastelt, das dann zu jedem Post die ID im Kurzlink ausgibt, statt <https://blog.julius-cordes.de/2015/03/immer-aerger-mit-dem-internet-explorer/> dann nur <https://blog.julius-cordes.de?p=311>.

Mit stabil meine ich, dass das nicht irgendwelche „internen“ Features sind, die nur durch Zufall entdeckt und genutzt wurden und dann später entfernt werden, was im Fall von Kurzlinks bedeuten würde, dass diese nicht mehr existieren.

**Comment by ckruse** [comment]
Kurz-URLs werden vor allem bei Twitter benutzt - und da würde auch
forum.selfhtml.org/?t=12345&m=3453453 verkürzt, allein schon weil der
Hostname zu lang ist und tw.it/?34r34 viel kürzer ist.

Ich sehe also tatsächlich keinen Anwendungsfall dafür, wenn ich ehrlich
bin.

Entfernen werde ich btw nichts, zumindest nicht ohne das anzukündigen.

**Comment by JuliusPC** [comment]
> Kurz-URLs werden vor allem bei Twitter benutzt - und da würde auch forum.selfhtml.org/?t=12345&m=3453453 verkürzt, allein schon weil der Hostname zu lang ist und tw.it/?34r34 viel kürzer ist.

Mit `http://` vorne dran sind das schon 30 unnötig verschwendete Zeichen – du hast Recht.

> Ich sehe also tatsächlich keinen Anwendungsfall dafür, wenn ich ehrlich bin.

**Pure Spielerei:** Es ist einfach so ein kleines Hobby von mir, Links soweit wie möglich zu kürzen – ich habe schon die Verkürzungsmöglichkeiten einige Sites „geknackt“ bzw. gesammelt. – nur beim SELFHTML-Forum habe ich bisher einfach nicht herausfinden können, wie dieses `?t=12313&m=1234234` Schema aus den Nachrichten hervorgeht. Steht die Thread-ID eigentlich irgendwo drin?

**Comment by ckruse** [comment]
Die Thread-ID, die in t= referenziert wird, die wird heute gar nicht
mehr generiert ;-) Das gleiche gilt btw. für m= - das sind
Legacy-Überbleibsel aus der Version 3.

Aber ich habe, dir zu gefallen, einen Shortcut eingebaut:

https://forum.selfhtml.org/m<id>, wobei die ID die aus dem #m<id>
ist ;-)

**Comment by JuliusPC** [comment]
>  Aber ich habe, dir zu gefallen, einen Shortcut eingebaut:
>
> https://forum.selfhtml.org/m<id>, wobei die ID die aus dem #m<id> ist ;-)

Cool, danke! Ich muss nicht davon ausgehen, dass das ohne Not entfernt wird, oder?

**Comment by ckruse** [comment]
Nein ;-)
