### ISSUE TITLE
Codeblöcke in Zitaten in alten Posts aus CForum 3.x

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#605]
Ein Beispiel:
![codebloecke-zitat](https://cloud.githubusercontent.com/assets/15018932/14066781/8a15c8fe-f453-11e5-88e0-0d6f13c41042.png)
Quelle: <https://forum.selfhtml.org/self/2014/mar/4/button-definition/1604239?rm=thread-view#m1604239>

Ähnliche Beispiele:

- <https://forum.selfhtml.org/self/2014/feb/19/input-image-vs-button-mit-image/1603021?rm=thread-view#m1603021>
- <https://forum.selfhtml.org/self/2014/feb/19/input-image-vs-button-mit-image/1603029?rm=thread-view#m1603029>

**Comment by ckruse** [comment]
In der Tat, da ist ein ziemlicher Bug

**Comment by ckruse** [comment]
Das Markup ist aber auch ziemlich kaputt...

```
> [code lang=html]...
> [/code]

**Comment by JuliusPC** [comment]
Danke!
