### ISSUE TITLE
Kaputter interner Forumslink von 1999 ;-)

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#606]
<https://forum.selfhtml.org/self/1999/apr/27/parameteruebergabe/15624?rm=thread-view#m15624> beinhaltet einen kaputten internen Link, vielleicht ist das noch reparierbar...

Weitere Beispiele habe ich zwar schon mal irgendwo gesehen, konnte sie aber bisher nicht wiederfinden.

**Comment by ckruse** [comment]
Das alte Archiv (vor dem Perl-Forum) kann nicht wirklich konvertiert
werden, das hat zwei Gründe:

einerseits war damals noch beliebiger Code in Links möglich (die totale
XSS-Lücke), so dass das parsen der alten Links ernsthaft ein Problem
wäre; und andererseits hat n.d. damals das Archiv nicht konvertiert, so
dass es doppelte Thread-IDs und Message-IDs gibt.

Weiterhin wurden damals die XSS-Lücken dazu benutzt, beliebiges HTML zu
injecten.

Deshalb haben wir beschlossen, dass das alte Archiv (< 2001 oder so) as
is ausgeliefert wird. Es wäre einfach zu viel Aufwand das anzupassen.

**Comment by JuliusPC** [comment]
Also mit eigenen Worten ausgedrückt: Niemand weiß, was in dem Link drin steckt und daher ist es mit viel Aufwand verbunden und ungewiss, was passiert, wenn man es versucht, an heutige Verhältnisse anzupassen.

Für den Fall, dass ich mal einen Parser für irgendetwas schreibe: Hätte es damals nicht ausgereicht, eine HTML-Escape-Funktion (für mich als PHPler `htmlspecialchars`) über den Inhalt des Links zu jagen?

Damit ich dich nicht mit weiteren Fragen zum Archiv ärgere, welche Evolutionsstufen gab es und wo macht es keinen Sinn, Vorschläge zu machen?

1. Perl-Forum von Matt Wright (das meintest du mit Archiv, oder?)
2. Forum von André Malo
3. CForum <3
4. CForum 4

Quelle: <https://blog.selfhtml.org/2008/07/26/forum-jubilaeum/>

----

Für den Fall, dass ich mal ein Forum aufsetzen wollte, würdest du mir aus technischer Sicht (vom Konzept gefällt es mir sehr gut) das CForum empfehlen? Lohnt es sich, sich damit auseinanderzusetzen (Installation, ein bisschen Ruby lernen)?

**Comment by ckruse** [comment]
> Also mit eigenen Worten ausgedrückt: Niemand weiß, was in dem Link
> drin steckt und daher ist es mit viel Aufwand verbunden und ungewiss,
> was passiert, wenn man es versucht, an heutige Verhältnisse
> anzupassen.

Soweit richtig.

> Für den Fall, dass ich mal einen Parser für irgendetwas schreibe:
> Hätte es damals nicht ausgereicht, eine HTML-Escape-Funktion (für
> mich als PHPler `htmlspecialchars`) über den Inhalt des Links zu
> jagen?

Ja, hätte es. Aber wir sprechen von den Anfangstagen des Webs, da war
einfach kein Bewusstsein dafür da. Das Matt-Wright-Forum war z.B. auch
anfällig gegen konkurrierende Schreibzugriffe, man hat an Sicherheit
und ähnliche Absurditäten ;-) damals einfach keinen Gedanken
verschwendet.

> Damit ich dich nicht mit weiteren Fragen zum Archiv ärgere, welche
> Evolutionsstufen gab es und wo macht es keinen Sinn, Vorschläge zu
> machen?
> 
> 1. Perl-Forum von Matt Wright (das meintest du mit Archiv, oder?)
> 2. Forum von André Malo

Soweit richtig, den Sourcecode gibt es sogar noch bei Sourceforge:

<https://sourceforge.net/projects/selfforum/>

> 3. CForum <3

CForum <= 3 ;-)

> 4. CForum 4

Sinn macht es im Grunde ab der Software von n.d. - ab dort ist das
Archiv in einem sinnvollen Format.

> Für den Fall, dass ich mal ein Forum aufsetzen wollte, würdest du mir
> aus technischer Sicht (vom Konzept gefällt es mir sehr gut) das
> CForum empfehlen? Lohnt es sich, sich damit auseinanderzusetzen
> (Installation, ein bisschen Ruby lernen)?

Tja, das ist eher eine Frage der technischen Gegebenheiten als eine
Frage des persönlichen Könnens. Ich kann dir eine
Vier-Schritte-Anleitung zur Installation geben, aber dafür muss dein
Hoster Rails, NodeJS und PostgreSQL>=9.3 unterstützen.

Ansonsten bin ich da aber ach der falsche Ansprechpartner, als Autor
ist mir natürlich daran gelegen, dass die Software eingesetzt wird ;-)

**Comment by JuliusPC** [comment]
> > Für den Fall, dass ich mal einen Parser für irgendetwas schreibe:
> > Hätte es damals nicht ausgereicht, eine HTML-Escape-Funktion (für mich als PHPler `htmlspecialchars`) über den Inhalt des Links zu jagen?
>
> Ja, hätte es. Aber wir sprechen von den Anfangstagen des Webs, da war einfach kein Bewusstsein dafür da. Das Matt-Wright-Forum war z.B. auch anfällig gegen konkurrierende Schreibzugriffe, man hat an Sicherheit und ähnliche Absurditäten ;-) damals einfach keinen Gedanken verschwendet.

Kann ich verstehen. Die Demo von dem Forum ist immer noch online, zumindest einige Spammer scheinen das noch sehr interessant zu finden ;-)

> Sinn macht es im Grunde ab der Software von n.d. - ab dort ist das Archiv in einem sinnvollen Format.

Was / wer ist _n.d._?

> > Für den Fall, dass ich mal ein Forum aufsetzen wollte, würdest du mir aus technischer Sicht (vom Konzept gefällt es mir sehr gut) das CForum empfehlen? Lohnt es sich, sich damit auseinanderzusetzen (Installation, ein bisschen Ruby lernen)?
> 
> Tja, das ist eher eine Frage der technischen Gegebenheiten als eine Frage des persönlichen Könnens. Ich kann dir eine Vier-Schritte-Anleitung zur Installation geben, aber dafür muss dein Hoster Rails, NodeJS und PostgreSQL>=9.3 unterstützen.

Ich würde das bei [uberspace](https://wiki.uberspace.de/start) ausprobieren wollen. Für mich sieht es so aus, als ob Rails, Node.js und PostgreSQL zwar (für meinen Geschmack) etwas kompliziert aufzusetzen sind, aber verfügbar ist wohl alles Benötigte in den richtigen Versionen. Ich werde es also von den technischen Voraussetzungen her wohl hinbekommen können, meine Angst vor dem Unbekannten muss ich wohl einfach überwinden ;-)

Wenn [diese Anleitung](https://github.com/ckruse/cforum/wiki/Installation-%28de%29#cforum) nicht mehr als Einstieg taugt, wäre ich über eine kleine Anleitung sehr erfreut.  
Ich könnte mir auch vorstellen, je nach verfügbarer Zeit bei der Dokumentation der Einrichtung und Benutzung zu helfen, wenn es dem Projekt zuträglich ist.

> Ansonsten bin ich da aber auch der falsche Ansprechpartner, als Autor ist mir natürlich daran gelegen, dass die Software eingesetzt wird ;-)

Nicht unbedingt, du kennst deine Software (natürlich!) gut und bist von ihr überzeugt. Ich habe mal einen wüsten Haufen von Software entwickelt („zusammengedengelt“ träfe es eher), so ein Mischmasch aus Wiki, Cloud und Forum – das hätte ich wirklich nur jemandem nahe gelegt, dem ich wirklich hätte schaden wollen.

Dass außer SELFHTML scheinbar niemand das CForum einsetzt, ist wirklich schade. Vielleicht fehlt ein nur ein bisschen „Marketing“ (z.B. Berichte in der Blogosphäre) und Dokumentation...

P.S.: Ist hier der (thematisch) richtige Ort für diese Diskussion?

**Comment by MatthiasApsel** [comment]
> Dass außer SELFHTML scheinbar niemand das CForum einsetzt, ist wirklich schade. Vielleicht fehlt ein nur ein bisschen „Marketing“ (z.B. Berichte in der Blogosphäre) und Dokumentation...

und ein neutrales Template.

**Comment by JuliusPC** [comment]
Müsste man das denn komplett neu erstellen oder könnte man das SELFHTML-Template nehmen und dort das CSS austauschen und an einigen Stellen die Verweise auf SELFHTML entfernen?

**Comment by ckruse** [comment]
> > Sinn macht es im Grunde ab der Software von n.d. - ab dort ist das
> > Archiv in einem sinnvollen Format.  
> 
> Was / wer ist _n.d._?

André Malo hat sich im Forum immer n.d. genannt, als Wortwitz zu seinem
Spitznamen Andy (En-Di).

> Wenn [diese
> Anleitung](https://github.com/ckruse/cforum/wiki/Installation-%28de%29#cforum)
> nicht mehr als Einstieg taugt, wäre ich über eine kleine Anleitung
> sehr erfreut.

Doch, die trifft es im Wesentlichen. Man muss dann halt noch die
Services starten, das ist aber abhängig von der Art und Weise, wie
Uberspace Services managed.

> Ich könnte mir auch vorstellen, je nach verfügbarer
> Zeit bei der Dokumentation der Einrichtung und Benutzung zu helfen,
> wenn es dem Projekt zuträglich ist.

Das wäre natürlich super!

> Dass außer SELFHTML scheinbar niemand das CForum einsetzt, ist
> wirklich schade. Vielleicht fehlt ein nur ein bisschen
> „Marketing“ (z.B. Berichte in der Blogosphäre) und Dokumentation...

Ich habe ehrlich gesagt noch überhaupt kein Marketing gemacht, da mit
steigender Userzahl auch der Support-Bedarf steigt. Und da ich den
allein leisten muss habe ich wenig Motivation dazu ;-)

> P.S.: Ist hier der (thematisch) richtige Ort für diese Diskussion?

Besser wäre vermutlich E-Mail.

LG,
-- 
Christian Kruse
https://wwwtech.de/about

**Comment by ckruse** [comment]
> Müsste man das denn komplett neu erstellen oder könnte man das
> SELFHTML-Template nehmen und dort das CSS austauschen und an einigen
> Stellen die Verweise auf SELFHTML entfernen?

Wenn überhaupt ein "neutrales Template," dann nur mit Austausch des CSS.
Ich habe aus dem Fiasko des CForum 3 gelernt, mehrere Templates zu
pflegen ist ein Heidenaufwand.
