### ISSUE TITLE
Benachrichtigung per E-Mail bei neuer Post scheint nicht zu funktionieren

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#611]
Einstellung m. M. n. korrekt, aber ich bekomme keine E-Mail bei neuer Post:

![post-benachrichtigung](https://cloud.githubusercontent.com/assets/15018932/14410361/f94f638a-ff2d-11e5-8f09-c0f4b0ac7084.png)

**Comment by ckruse** [comment]
Faszinierend, ich glaube ich habe aus Versehen diese Funktion ausgebaut. Es gibt sie zumindest nicht mehr...

**Comment by ckruse** [comment]
Nein, nur verguckt, da ist was anderes kaputt
