### ISSUE TITLE
Post- bzw. Mail-Ansicht unübersichtlich

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#612]
Bei vielen Nachrichten bzw. Konversationsfäden wird die Post-Ansicht schnell unübersichtlich – Optionen zum Ändern der Ansicht habe ich nicht finden können. Zwei Ansätze zur Verbesserung der Übersichtlichkeit:

- Nachrichten mit gleichem Betreff und Konversationspartner unter einem Link „#Betreff# (10 Nachrichten)“ zusammenfassen und dann in der Nachricht einen „Nächste Nachricht“-Link einfügen
- Thread- und Nested-Ansicht wie im Forum einführen (praktisch eine Art privater Forumssthread)

Ich kann nicht beurteilen, ob das mit vertretbarem Aufwand einführbar wäre. Anfangs fand ich die PN-Funktion unnötig (wozu gibt es E-Mails, dachte ich mir), muss mittlerweile aber sagen, dass sie mir – vor allem wegen der bequemen Formatierung per Markdown – viel besser gefällt als E-Mail!

**Comment by ckruse** [comment]
Ein Threading für PMs wird nicht kommen, das war nie vorgesehen und könnte so nur eingeführt werden, indem man die Daten über ein Script ändert und Threads einführt. Das ist mir einfach zu gefährlich.

Aber das shallow threading, wie man es aus moderneren Mail-Programmen kennt, finde ich eine gute Idee.

**Comment by JuliusPC** [comment]
> Ein Threading für PMs wird nicht kommen, das war nie vorgesehen und könnte so nur eingeführt werden, indem man die Daten über ein Script ändert und Threads einführt. Das ist mir einfach zu gefährlich.

Du bist der Experte :)

> Aber das shallow threading, wie man es aus moderneren Mail-Programmen kennt, finde ich eine gute Idee.

Vielleicht zum Ausklappen und evtl. mit einer Gesamt-Übersicht, damit man nicht jede Nachricht einzeln aufrufen muss?

**Comment by ckruse** [comment]
> Vielleicht zum Ausklappen und evtl. mit einer Gesamt-Übersicht, damit man
> nicht jede Nachricht einzeln aufrufen muss?

Klingt gut. Mal sehen, heute Abend muss ich mich um mein Auto kümmern, weiß 
also nicht, ob ich dazu kommen werde. Spätestens Mittwoch (Dienstags hab ich 
immer Training).

LG,
-- 
Christian Kruse
https://wwwtech.de/about

**Comment by JuliusPC** [comment]
Vielen Dank!

Mein Großvater pflegte zu sagen, dass Auto mit „Au“ beginnt – in diesem Sinne viel Erfolg!
