### ISSUE TITLE
Sortiermöglichkeit für interessante Beiträge

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#614]
Die als interessante Beiträge markierten Postings werden momentan nach ihrem Datum aufsteigend sortiert. Das hat bei mir zur Folge, dass mir als erstes ein Posting vom 1.3.2006 angezeigt wird, ich, für die mich eher interessierenden aktuelleren Postings, an das Ende der Liste zur Paginations-Navigation scrollen muss.

Das ist aushaltbar, könnte aber bequemer sein. Ich wünsche mir daher eine Sortiermöglichkeit nach Datum, eine Filterfunktion [1] oder *zumindest* eine Doppelung der Paginations-Navigation, so dass diese zusätzlich oberhalb der.Liste der Postings angezeigt wird.

[1]: Filterung z.B. nach Tags. Sucht die Suche auf Ansage eigentlich auch explizit in den interessanten Beiträgen?

**Comment by ckruse** [comment]
Das mit der Suche wird schwierig… *grübel*

**Comment by auge8472** [comment]
Danke, die Sortierung ist sehr schön gelöst. :-)

**Comment by ckruse** [comment]
Ha, mit dieser Lösung bin ich richtig zufrieden :)
