### ISSUE TITLE
Neue Post, Gesprächsfaden bleibt zugeklappt

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#620]
Neuerdings sind die Gesprächsfäden in der Post (private Nachrichten) übersichtlicher gestaltet (#612), da sie zugeklappt werden. Das ist zu begrüßen. Allerdings bleiben sie zugeklappt, wenn in einem schon bestehenden Faden eine neue Nachricht ankommt.

`<dramatisierung>`Ich habe mich deshalb soeben geradezu dumm und dusselig gesucht.`</dramatisierung>`

**Comment by MatthiasApsel** [comment]
Passt hierzu: Die Reihenfolge in den zugeklappten Kommunikationen korrelliert nicht mit der Gesamtreihenfolge.

Beispiel:

neueste Post soll oben stehen, in den zugeklappten steht die älteste Post oben.

**Comment by auge8472** [comment]
> Die Reihenfolge in den zugeklappten Kommunikationen korrelliert nicht mit der Gesamtreihenfolge.
> 
> neueste Post soll oben stehen, in den zugeklappten steht die älteste Post oben.

@ckruse Kann man die Reihenfolge der Nachrichten von den Benutzereinstellungen zur Reihenfolge der Beiträge in Threads abhängig machen (neue Antworten unten/oben)?

**Comment by ckruse** [comment]
>> Die Reihenfolge in den zugeklappten Kommunikationen korrelliert nicht mit der Gesamtreihenfolge.
>> 
>> neueste Post soll oben stehen, in den zugeklappten steht die älteste Post oben.

Das ist durchaus Absicht. Analog zu der Thread-Ansicht in vielen Mail-Clients.

> @ckruse Kann man die Reihenfolge der Nachrichten von den Benutzereinstellungen zur Reihenfolge der Beiträge in Threads abhängig machen (neue Antworten unten/oben)?

Kann man, ich bin aber kein großer Fan davon. Ich glaube, besser fände
ich es, wenn man eine eigene Option dafür einbaut.
