### ISSUE TITLE
print-css kann noch verbessert werden

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#622]
So als Erinnerung für mich:

- Die Einrückung muss auf Null gesetzt werden, das war bisher nur in meinem User-CSS
- Tags brauchen nicht gedruckt zu werden, mindestens der Bonbon kann weg
- problematische Seite: Hintergrund und border-bottom

**Comment by auge8472** [comment]
Was meinst du bei den Tags mit "Bonbon"?

**Comment by MatthiasApsel** [comment]
den grauen Hintergrund. Irgendjemand prägte mal den Begriff Bonbon dafür. [Suche SELFHTML](https://forum.selfhtml.org/search?utf8=%E2%9C%93&term=bonbon&sections[]=2&start_date[day]=21&start_date[month]=5&start_date[year]=2014&stop_date[day]=21&stop_date[month]=5&stop_date[year]=2016&order=rank#results)

**Comment by auge8472** [comment]
Die Tags sollten nach meinem Regelsatz ohne Hintergrund und Rahmen ausgedruckt werden. Anbei ein Screenshot einer per Druckfunktion erstellten PDF-Datei. Kein Rahmen, kein grauer Hintergrund, nur ein Tag in Linkfarbe und ein Tag in schwarz. Ich habe allerdings die CSS-Druckregeln noch im Benutzerstylesheet. Die unterscheiden sich aber nicht von den Regeln im Repo.

![selfforum-tags-im-ausdruck](https://cloud.githubusercontent.com/assets/1734660/15453652/c89d2288-201e-11e6-961b-b0676106a664.png)


	header .details .cf-tags-list,
	/* Kram */
	article.thread-message {
		display: block;
	}
	/* Kram */
	.cf-tags-list::before {
		content: 'Tags: ';
	}
	.cf-tag {
		border: none;
		background: transparent;
		margin-left: 0;
		padding: 0.1em 0.1em 0;
	}
	.cf-tag:not(:last-child)::after {
		content: ', ';
	}

Die Regeln direkt zu `.cf-tag` entfernen die Bonbon-Optik. Die sind in deinem PR auch drin (ab Zeile 80). Komisch.

**Comment by MatthiasApsel** [comment]
Ja, es ist eine Frage der Reihenfolge der Einbindung. Also muss jetzt die Spezifität einiger Selektoren erhöht werden. Ich werde das in Ruhe testen.
