### ISSUE TITLE
JavaScript in Links...

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#628]
~~~~~
[Test](javascript:alert('Test!'))
~~~~

erzeugt im CForum einen Link mit JavaScript, hier bei GutHub wird das hingegen korrekt herausgefiltert...

**Comment by ckruse** [comment]
Urghs. Danke, fixed. Das hätte ins Auge gehen können.

**Comment by JuliusPC** [comment]
Geht leider immer noch, ich habe da noch etwas entdeckt...

- `[Test](&#106;&#97;&#118;&#97;&#115;&#99;&#114;&#105;&#112;&#116;&#58;&#97;&#108;&#101;&#114;&#116;&#40;
&#39;&#88;&#83;&#83;&#39;&#41;)` ergibt `javascript:alert('XSS')` vgl. [OWASP: Decimal HTML character references](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#Decimal_HTML_character_references)
- `[Test](jAvaScript:alert('XSS'))` funktioniert ebenfalls noch (vgl. [OWASP: Case insensitive XSS attack vector](https://www.owasp.org/index.php/XSS_Filter_Evasion_Cheat_Sheet#Case_insensitive_XSS_attack_vector))...

**Comment by ckruse** [comment]
Danke. Man sollte keine Bugs zwischen Tür und Angel fixen…

Such ruhig weiter, solche Beiträge sind sehr wertvoll!
