### ISSUE TITLE
codeblock für fehlerhaften/problematischen Code

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#630]
Es wäre schön, wenn man eine Möglichkeit hätte, code als fehlerhaft auszuzeichnen, quasi selfdown als kramdown-Erweiterung. 

Siehe https://forum.selfhtml.org/m1669649 

z.B. 

`~~~css|wrong`
`* html body {color: black;}`
`~~~`

**Comment by ckruse** [comment]
done
