### ISSUE TITLE
Inkonsistenz (Widersprüchlichkeit) in Beschriftung

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#634]
siehe <https://forum.selfhtml.org/m1670376>

**Comment by auge8472** [comment]
Könntest du bitte, bitte den Titel des Issues korrigieren. Ich lese immerzu „**Inkontinenz** in Beschriftung“ und das finde ich zutiefst verstörend. :-)

**Comment by MatthiasApsel** [comment]
gern

**Comment by ckruse** [comment]
Ich bin zur Zeit im Urlaub, mit eingeschränktem Internet

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by MatthiasApsel** [comment]
Kein Problem. Schönen Urlaub!

**Comment by ckruse** [comment]
fixed
