### ISSUE TITLE
unerwünschte Meldung über neue Nachrichten bei ausgeblendeten Threads

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#635]
Ich möchte keine Nachrichten zu neuen Beiträgen in von mir ausgeblendeten Threads erhalten. Ich blende die ja bewusst aus, weil ich bestimmte Themen ignorieren will. Das gelingt mir nicht, wenn ich imemr wieder darauf hingewiesen werde, dass es dort Bewegung gibt.

Heute fällt mir das wieder extrem auf, da mich bisher alle Nachrichten über neue Beiträge auf ausgeblendete Threads hinwiesen.

**[edit]**Der Titel schien mir zu mehrdeutig, weshalb ich ihn noch einmal konkretisiert habe.**[/edit]**

**Comment by ckruse** [comment]
Sprichst du von der grünen Box oder von den Notifications?

**Comment by ckruse** [comment]
schon gefunden, was du meinst ;)
