### ISSUE TITLE
Anderes Bewertungsformular bei erfolgter Bewertung aktualisieren

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#638]
Wenn ich eine Bewertung vornehme, wird das gewählte Zeichen ([-] oder [+]) im benutzten Formular hervorgehoben. Es gibt aber noch „das andere“ Formular (ober- bzw. unterhalb des Beitrags). Das wird bei dieser Gelegenheit nicht ebenfalls aktualisiert. Mit einer Hervorhebung in beiden Formularen wäre der Fall der versehentlichen Aufhebung einer erfolgten Bewertung über das jeweils andere Formular vermeidbar.

**Comment by ckruse** [comment]
Huch – stimmt. Da habe ich eine Klasse vergessen. Danke.
