### ISSUE TITLE
unnötige Zusatzzeilen bei einfügen von Codeblöcken

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#641]
Wenn die Kramdown-Tags für Codeblöcke per Button eingefügt werden, wird vor und nach dem Codeblock jeweils ein zusätzlicher Zeilenumbruch eingefügt, auch wenn das nicht notwendig ist.

siehe auch [dieses Posting im SelfForum](https://forum.selfhtml.org/self/2016/jul/31/warum-das-css-fuer-input-nicht-angewendet/1672477#m1672477)

**Comment by ckruse** [comment]
Möchtest du einen Patch schreiben?

**Comment by auge8472** [comment]
Möchten: ja. Momentan wird das bei und mit mir aber nichts. Bin aktuell voll ausgelastet.

**Comment by ckruse** [comment]
fixed by @CountOrlok
