### ISSUE TITLE
Links in die Zitatesammlung

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum#645]
Bsp. <https://forum.selfhtml.org/self/2010/sep/2/nth-child-element-n-weitere-elemente-beginnend-ab-x/1468478#m1468478>: der Link in die Zitatesammlung <http://community.de.selfhtml.org/zitatesammlung/zitat1882> funktioniert nicht mehr, in dem Fall müsste zu <https://forum.selfhtml.org/cites/1656> weitergeleitet werden.

**Comment by ckruse** [comment]
Ich hab Dedlfix darum gebeten eine Weiterleitung einzurichten, das hat er beim abschalten der alten Server wohl vergessen.

**Comment by dedlfix** [comment]
Gibt es denn einen Umsetzmechanismus von der alten Adresse in die neue? Wenn ja, welchen Teil der alten URL müsste ich wohl an welche neue URL anhängen?
Im Moment ist auf der gesamten Domain community.de.selfhtml.org nur ein 410er-Fehlerdokument hinterlegt mit einem generellen Hinweis auf den neuen Ort der Zitatesammlung in dessen Text.

**Comment by ckruse** [comment]
Ja, den gibt es. Aus `/zitatesammlung/zitat666` wird `https://forum.selfhtml.org/cites/old/zitat666`

**Comment by dedlfix** [comment]
Redirect für /zitatesammlung hinzugefügt.
