### ISSUE TITLE
Syntax-Highlighting für SVG

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum#646]
Gibt man SVG als Sprache an (`~~~svg` bzw. `{: .language-svg}`), kennt das der Syntax-Highlighter nicht. Er sollte aber dasselbe tun wie bei XML.

**Comment by ckruse** [comment]
Das geht nicht, da müssen wir auf [Upstream](https://github.com/tmm1/pygments.rb) warten…

**Comment by ckruse** [comment]
Ich habs jetzt mal reingehackt. Schön ist anders, aber upstream ist der Meinung, SVG als Alias für XML sei überflüssig.
