### ISSUE TITLE
Graph für die Benutzeraktivität zählt einen Monat doppelt

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#649]
Der nämliche Graph zeigt an seinem rechten Ende die Anzahl der Beiträge im aktuellen Monat an (was er auch soll), behauptet aber, dass dies die Beiträge im Vormonat seien. Die dahinterstehende Routine verzählt sich beim berechnen des aktuellen Monats, weil irgendwo zwischendrin ein Monat doppelt gezählt wird. [In meinem Profil](https://forum.selfhtml.org/users/15) und auch im [Profil von JürgenB](https://forum.selfhtml.org/users/68) ist es der März 2016, der zweimal aufgeführt wird. Dadurch verschieben sich alle folgenden Monate um einen Zählpunkt.

**Comment by ckruse** [comment]
Ich verstehe ehrlich gesagt nicht, was du meinst.

![screen shot 2016-09-02 at 10 26 45](https://cloud.githubusercontent.com/assets/175095/18197527/e4a52014-70f7-11e6-9374-6a86fe46f499.png)
![screen shot 2016-09-02 at 10 27 05](https://cloud.githubusercontent.com/assets/175095/18197533/eba4462e-70f7-11e6-9cd7-a9c63e00e76e.png)

Der März ist nur einmal drin und der September sieht mir richtig aus? Kannst du vielleicht mal einen Screenshot machen der darstellt, was schief läuft?

**Comment by auge8472** [comment]
Hier die Screenshots. Die Datumsangaben im Text beziehen sich auf die tatsächlichen Monate.

März 2016:
![shf-bar-march-2016](https://cloud.githubusercontent.com/assets/1734660/18198521/b82d9598-70fc-11e6-8517-ac069c85425e.png)

April 2016:
![shf-bar-april-2016](https://cloud.githubusercontent.com/assets/1734660/18198534/c8b7f6ba-70fc-11e6-929e-517fe4de4ffa.png)

September 2016:
![shf-bar-september-2016](https://cloud.githubusercontent.com/assets/1734660/18198548/d32dce1c-70fc-11e6-81a2-50d4842654ba.png)

Wenn das bei dir korrekt ausgegeben wird, vermute ich ein Browserdingens. Ich nutze aktuell den Firefox 48, aus dem auch die Screenshots stammen. Und tatsächlich, im Vivaldi werden die Monate im Graphen korrekt zugewiesen.

**Comment by ckruse** [comment]
Ok, jetzt hast du mein Interesse ;)

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by ckruse** [comment]
Witzig. Das ist ein Bug im Firefox-Datehandling mit Zeitzonen. Im März ist immer die Zeitumstellung, und ich loope so durch die Monate:

~~~ js
for(d = new Date(min); d <= max; d.setMonth(d.getMonth() + 1)) {
~~~

Und jeder März wird verdoppelt.
