### ISSUE TITLE
Forumsübersicht berücksichtigt gelöschte Beiträge offenbar nicht

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#652]
siehe https://forum.selfhtml.org/self/2016/sep/5/strukturierte-programmierung/1674941#m1674941

**Comment by ckruse** [comment]
Was er meint ist, dass die automatische Aktualisierung Nachrichten nicht
wieder entfernt wenn sie gelöscht werden. Ist mir bewusst. Find ich
nicht schlimm. Beim nächsten Reload oder der nächsten Nachricht in dem
Thread sind sie weg.
