### ISSUE TITLE
Sperrabstimung

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#653]
Es gibt ja nun die erste [Sperrabstimmung](https://forum.selfhtml.org/meta/2016/jul/26/self-treffen-2016-in-erfurt/1675498#m1675498). Die Nachricht ist geschlossen, weil "Dieser Beitrag ist unkonstruktiv oder provokativ und trägt zu einer Verschlechterung der allgemeinen Stimmung im Forum bei." Sollte der Beitrag nicht auch gelöscht werden?

**Comment by ckruse** [comment]
Nö. Aus den Einstellungen:

![screen shot 2016-09-19 at 10 20 24](https://cloud.githubusercontent.com/assets/175095/18626050/d2b72f4c-7e52-11e6-92ef-5762f042d857.png)
