### ISSUE TITLE
Tag löschen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#654]
Beim Versuch, das Tag [Mensch](https://forum.selfhtml.org/self/tags/mensch) zu löschen, kommt die Fehlermeldung "Das Tag ist noch Nachrichten zugeordnet. Es kann nicht gelöscht werden." Obwohl weiter unten steht "Bisher sind keine Beiträge mit diesem Tag geschrieben worden."

**Comment by ckruse** [comment]
`view_all=yes` setzen – es existieren noch gelöschte Beiträge bei diesem Tag.
