### ISSUE TITLE
Abosystem

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#661]
Es werden auch Teilbäume aboniert, wenn einer der übergeordneten Bäume schon aboniert ist. Das scheint mir nicht notwendig zu sein.

Beim Antworten sind im unteren Threadbaum die Icons falsch. (sie sind alle nicht aboniert)

**Comment by ckruse** [comment]
Die Icons sind jetzt richtig, das hatte ich schon auf dem Schirm :-)

Bzgl des Akzeptierens von Subscriptions in bereits abonierten Subtrees: ich weiss, aber das zu checken ist mehr Aufwand als das einfach zu akzeptieren, zumal jetzt ja auch die Icons richtig sind und so das nur selten bis gar nicht vorkommen sollte.

**Comment by MatthiasApsel** [comment]
Wenn die Automatik eingestellt ist, kommt das sehr häufig vor. Weil man ja mehrfach in einem Thread antwortet. Und dann sieht das schon komisch aus. Aber ich sehe, dass du da grad noch was geändert hast.

**Comment by MatthiasApsel** [comment]
Könnte man nicht interessant und Abo zusammenfassen? Wer eine Nachricht als interessant markiert, hat diese auch aboniert?

**Comment by ckruse** [comment]
Das habe ich auch überlegt, aber ich halte das nicht für sinnvoll. Die Interessant-Markierung löst keinerlei Benachrichtigungen aus, und umgekehrt verschwindet das Abo, wenn der Thread archiviert wird (zumindest sobald ich das implementiert habe).

Ich denke, das deckt zwei unterschiedliche Use Cases ab und sollte deshalb getrennt bleiben.

**Comment by ckruse** [comment]
Bzgl des Multi-Subscribes: point taken. Ich mach da mal was.

**Comment by ckruse** [comment]
Done.

**Comment by auge8472** [comment]
> > Könnte man nicht interessant und Abo zusammenfassen? Wer eine Nachricht als interessant markiert, hat diese auch aboniert?
> Ich denke, das deckt zwei unterschiedliche Use Cases ab und sollte deshalb getrennt bleiben.

Auch wenn das Issue schon zu ist, möchte ich dazu etwas sagen. Ich benutze die Interessant-Markierung dazu, mich später mit einzelnen Postings auseinandersetzen zu können. Das kann Tage oder auch Monate später sein. Bis dahin, oder bis der Thread inaktiv oder archiviert wird, möchte ich nicht mit Benachrichtigungen zu Aktivität im entsprechenden Thread "belästigt" zu werden. *Wenn* ich das möchte, kann ich immer noch das Abo hinzuschalten. Das ist dann aber, wie Christian schon sagte, eine andere Funktion.
