### ISSUE TITLE
interessantmarkieren und abonnieren setzen alle Beiträge des Threads auf gelesen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#662]
... auch wenn man sie gar nicht gelesen hat.

**Comment by ckruse** [comment]
Das kann ich nicht nachvollziehen, was genau passiert denn?

**Comment by auge8472** [comment]
Ich kann die Beobachtung auch nicht nachvollziehen. Ich habe in einem bis dahin von mir ungelesenen Thread verschiedene Beiträge abonniert und deabonniert, habe verschiedene Postings als interessant markiert und die Markierung wieder aufgehoben und bei keiner Aktion wurden mir die Beiträge als gelesen markiert.

**Comment by MatthiasApsel** [comment]
Ich verwende die nested-Ansicht sowie "Gelesene Nachrichten im Nested-Modus zusammenfalten". Ich öffne einen Thread, der mehrere ungelesene (also "geöffnete" Beiträge hat). Ich markiere einen als als interessant oder abonniere ihn. Es erfolgt ein Reload und alle bisher geöffneten Beiträge sind geschlossen. Einzig der, den ich gerade markiert habe, ist noch offen.

**Comment by ckruse** [comment]
äh, ja - natürlich. Not a bug. Das wird sich nicht ändern lassen, bei der Nested-Ansicht werden nach dem Rendern alle Nachrichten als gelesen markiert.

**Comment by MatthiasApsel** [comment]
Am 10.11.2016 um 22:34 schrieb Christian Kruse:
> äh, ja - natürlich. Not a bug. Das wird sich nicht ändern lassen, bei
> der Nested-Ansicht werden nach dem Rendern alle Nachrichten als gelesen
> markiert.

könnte man nicht einen Parameter mitschicken, der genau das unterbindet?

?nochangestatus=yes

**Comment by ckruse** [comment]
Zu dem Zeitpunkt ist es bereits zu spät. Das funktioniert so:

- du rufst ein Posting auf
- das CForum setzt die notwendigen Variablen für die Views
- die Gelesen-Markierung wird in die Datenbank eingetragen
- der Response wird ausgeliefert

Zu dem Zeitpunkt, an dem du die Nachrichten siehst, ist die Gelesen-Markierung bereits gespeichert. Ein Reload führt dann dazu, dass die Nachrichten auch als gelesen dargestellt werden. Anders kann man das ja auch nicht implementieren.

**Comment by MatthiasApsel** [comment]
>  Zu dem Zeitpunkt, an dem du die Nachrichten siehst, ist die
> Gelesen-Markierung bereits gespeichert.

klingt logisch.

Lässt sich das Reload unterbinden?

Also Klick auf Abonnieren bewirkt das Eintragen der Markierung in die 
Datenbank, per JS werden die Buttons getauscht und das Form-Element 
angepasst, aber die Seite wird nicht neu geladen?

**Comment by ckruse** [comment]
Doch, das ist geplant. Siehe auch

<https://forum.selfhtml.org/meta/2016/nov/8/cforum-4-punkt-4/1679569#m1679569>

**Comment by ckruse** [comment]
Und done.
