### ISSUE TITLE
Menü: Aufklappen des Untermenüs „Foren ▼“ funktioniert nicht

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum#666]
Das Aufklappen des Untermenüs „Foren ▼“ funktioniert nicht per Keyboard. Damit ein per Default nicht interaktives Element per Im Tab-Index ist, muss es zumindest `tabindex="0"` haben.

**Comment by ckruse** [comment]
Das `tabindex` war schon da, nur dummerweise am falschen Element :-)

**Comment by gunnarbittersmann** [comment]
Man kann „Foren ▼“ jetzt zwar aufklappen, aber nicht zu den Unterpunkten navigieren. (Das sollte – denke ich – per Pfeiltasen möglich sein.)

**Comment by ckruse** [comment]
Doch, kann man. Wie man auf alle Links navigieren kann: via Tab.

Die Pfeiltasten zusätzlich sind allerdings eine gute Idee.

Ah, ich sehe jetzt das Problem, das scheint Firefox-spezifisch zu sein, Chrome macht das einwandfrei. Muss ich mir mal genauer anschauen.

Im Safari ist das Verhalten übrigens *wirklich* kaputt: durch das Reordering muss man um in die Menü-Leiste zu kommen erst alle Links durchtabben. Mit einer Ausnahme: das tabindex-Element ist das erste Element, das angesprungen wird. Klappt man das Menü auf, muss man durchtabben bis zum Ende und kommt dann ins Menü.

Tastatur-Navigation ist definitiv nicht in Apples Fokus…
