### ISSUE TITLE
Syntax-Highlighter rendert `flex-direction` falsch

### ISSUE THREAD

**Issue by gunnarbittersmann** [ckruse/cforum#667]
Der Syntax-Highlighter ist entwerder nicht auf dem neusten Stand oder buggy. Er kennt offenbar die `flex-direction`-Eigenschaft nicht:
![screen shot 2016-11-23 at 22 39 57](https://cloud.githubusercontent.com/assets/409844/20579844/5456b266-b1cf-11e6-8b87-59263071fe40.png)

Siehe auch https://forum.selfhtml.org/self/2016/nov/22/flexbox-hoehe-beinflussen/1681060#m1681060

**Comment by ckruse** [comment]
Duplicate von #646

**Comment by ckruse** [comment]
(Wir müssen auf Upstream warten)
