### ISSUE TITLE
Übersetzungsangebot

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#671]
Wäre es sinnvoll, ein Angebot zur Übersetzung fremdsprachiger Phrasen anzubieten, ähnlich wie auf Twitter? 

![twitterubersetzung](https://cloud.githubusercontent.com/assets/2847625/20865144/78647484-ba0a-11e6-83fd-e4c540b025e4.png)

Ggf. könnte das auch Datenschutzprobleme geben.

**Comment by ckruse** [comment]
Ich denke nicht, dass das CForum sowas braucht… wozu auch?

**Comment by MatthiasApsel** [comment]
> Ich denke nicht, dass das CForum sowas braucht… wozu auch?

Weil der Gunnar ständig englische Texte postet und ich kein Englisch 
kann?

**Comment by ckruse** [comment]
Ich finde ehrlich gesagt, so ein Feature führt zu weit.

Eine Gefahr bei der Software-Entwicklung ist, dass man in Featuritis verfällt. Das fällt IMHO in diese Kategorie.

**Comment by MatthiasApsel** [comment]
Ja, damit kann ich auch leben. Ich hab ja auch nur nach deiner Meinung gefragt ;-)
