### ISSUE TITLE
Alter Archiv-Link

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#680]
Lässt sich <https://forum.selfhtml.org/archiv/1998_3/t00080.htm> vielleicht noch auflösen und das ins CForum integrieren?

**Comment by MatthiasApsel** [comment]
Auf welcher Seite steht dieser Link?

**Comment by ckruse** [comment]
Der "entsteht" nicht, sondern solche Links stehen leider haufenweise im
alten Archiv.

**Comment by JuliusPC** [comment]
Wird das `tXXXXX` nicht irgendwo aus Kompatibilitätsgründen gespeichert?

**Comment by ckruse** [comment]
Doch, wird es. Und im Prinzip kann man das auch auflösen, ich muss nur schauen, dass das auch getan wird. Aus persönlichen Gründen habe ich nur relativ wenig Freizeit zur Verfügung.
