### ISSUE TITLE
Auto-Vervollständigung: Mehrere Mentions hintereinander

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#690]
Wenn ich mehrere Mentions hintereinander eingeben will, schlägt mir die Vorschlagsfunktion nach Eingabe einer Mention keine Namen mehr vor.

Wenn ich also `@Christian Kruse @Mat` eintippe, bekomme ich keine Vorschläge mehr – wenn ich hinter `@Christian Kruse` einen Zeilenumbruch einfüge, bekomme ich auf die Eingabe von `@Mat` hin wieder Vorschläge.

Ist das ein Bug oder aus irgendeinem Grund gewollt?

**Comment by ckruse** [comment]
Das wird ein Bug sein.

**Comment by MatthiasApsel** [comment]
Kann ich bestätigen, und zwar auch dann wenn man ein Komma dazwischen setzt.

**Comment by MatthiasApsel** [comment]
Betrifft auch die Kombination mention smiley.

**Comment by ckruse** [comment]
Das Problem ist, dass der Regex für Mentions ziemlich offen gehalten werden muss: `/\B@([^\n]{2,})/`. Das matcht halt im Zweifel die ganze Zeile weg, auch auf eventuelle zweite Matches.

Ich hab den Regex etwas angepasst (`@` ist in Usernamen auch verboten), aber wie ich das mit den Smilieys oder Mentions hinkriegen soll weiss ich noch nicht…

**Comment by ckruse** [comment]
Ok, mir ist doch was eingefallen :-) ich mache den most exhaustive check einfach zuletzt.
