### ISSUE TITLE
Passwort-Ändern modifizeren (Autovervollständigung austricksen)

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#691]
Wenn man den Passwort-Manager seines Browser benutzt, füllt der Browser (bei mir derzeit FF51) das erste Passwortfeld (das mit der id `user_password`) aus, was beim Absenden dazu führt, dass das CForum das nicht ausgefüllte Bestätigungsfeld bemängelt. Da man aber eher selten sein Passwort ändert, aber dafür schon mal mit den anderen Optionen herumspielt, ist das nervig. Ich glaube, dass wir das Thema schon mal hatten und es keine Lösung dafür gab.

Mit meinen bescheidenen JS-Kenntnissen habe ich folgendes User-JS erstellt:

~~~js
var jpc_pass = document.getElementById("user_password");
var jpc_pass_conf = document.getElementById("user_password_confirmation");

if(jpc_pass != null && jpc_pass_conf != null) {
   document.getElementById("user_password").setAttribute('disabled','disabled');
   document.getElementById("user_password_confirmation").setAttribute('disabled','disabled');
}
~~~

Wäre das nicht eine Sache, die man in der Art fix ins CForum integrieren könnte (das Problem haben bestimmt mehr Nutzer)? In der Gestalt, dass man dann auf einen Button drücken muss und erst dann die Felder aktiv geschaltet werden? Das kann ja auch eine reine JS-Lösung sein – Nutzer ohne JS haben dadurch keine Einschränkung, weil ja erst das JS die Felder auf `disabled` setzt.

**Comment by ckruse** [comment]
Ich glaube ehrlich gesagt, der bessere Weg ist es Passwort ändern und 
Profil ändern zu trennen. Alles andere kann IMHO nur ein Hack werden.

**Comment by JuliusPC** [comment]
> Ich glaube ehrlich gesagt, der bessere Weg ist es Passwort ändern und Profil ändern zu trennen.

Macht auch von der Logik her Sinn, sein Passwort ändert man schließlich nicht alle naselang.

Bis es so weit ist, nutze ich den Hack :-)
