### ISSUE TITLE
Emojis in spans verpacken

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#700]
Wäre es möglich, die Postings beim Rendern nach den Zeichen aus der Emoji-Liste zu durchsuchen und selbige dann in ein `<span class="emoji" title=":code_für_das_emoji">` zu verpacken? Dadurch hätte man folgende Vorteile:

- Man hat eine textuelle Information, was das Emoji bedeutet, auch wenn es selbst nicht dargestellt werden kann oder dessen Bedeutung nicht klar ist
- Man könnte ein paar nette Extras in sein privates JS und CSS einbauen:
   - (bestimmte) Emoji vergrößern
   - sie ausblenden
   - Einen speziellen Font für sie einbinden
   - ... oder sie durch ihre ASCII-Pendants ersetzen

Siehe entsprechende Diskussion im Forum: <https://forum.selfhtml.org/meta/2017/feb/8/neue-autovervollstaendigung/1688308#m1688308>

**Comment by ckruse** [comment]
Das ist eine Frage der Machbarkeit…

**Comment by ckruse** [comment]
Ok, war einfacher als ich dachte nachdem ich mal drüber nachgedacht hatte ;-)

**Comment by JuliusPC** [comment]
Danke!

Wenn du gerade schon dabei bist, ist :thumbsup schon drin? Siehe <https://forum.selfhtml.org/meta/2017/feb/8/neue-autovervollstaendigung/1688718#m1688718> – ich habe es zwar upstream (bei der emoji-Liste) eingereicht, bin aber nicht sicher, ob es geklappt hat...

**Comment by ckruse** [comment]
Das ist als `:+1` drin

**Comment by JuliusPC** [comment]
Schon immer oder neuerdings?

**Comment by ckruse** [comment]
schon immer ;-)

**Comment by ckruse** [comment]
Man könnte aber diskutieren, ob man thumbsup stattdessen nimmt. +1 in der tat wenig eingängig

**Comment by JuliusPC** [comment]
Ups.

Aber +1 wurde schon ab und an benutzt. Evtl. ein Alias?

**Comment by ckruse** [comment]
Das ist ja egal, es wird ja das Emoji gespeichert, nicht der Name dafür

**Comment by JuliusPC** [comment]
Das ist klar. Ich meine, dass sowohl bei der Eingabe von +1 und :thumbsup das gleiche emoji vorgeschlagen wird.

**Comment by ckruse** [comment]
Was du gemeint hast ist mir klar, ich halte das nur nicht für nötig ;-) und wenn keine Ein-Eindeutige Beziehung vorliegt ist ja auch undefiniert, was bei dem `aria-label` drin stehen sollte.

**Comment by ckruse** [comment]
hab etwas rumprobiert… `.invert` nimmt den letzten Hash value, damit reicht es `thumbs_up` nach `+1` zu definieren. Done.
