### ISSUE TITLE
Kramdown: Durchstreichen via ~~

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#703]
Ich habe ab und an den Fall, dass sich während des Postens die Sachlage ändert (neue Erkenntnisse oder neue Beiträge mit solchen). Ich möchte dann den bereits geschriebenen Text einfach mit dem `del`-Element als obsolet kennzeichnen können, aber nur ungern löschen.

Es wäre schön, wenn man via `~~text~~` ein  `<del>text</del>` erzeugen könnte. Es ist semantischer als `_text_{: style="text-decoration:line-through; font-style:normal;"}`. Bei GitHub ist dies möglich: ~~text~~

**Comment by JuliusPC** [comment]
Cool, funktioniert. Danke!

Kleine Frage: Warum drei Tilden und nicht zwei – bei Github reichen bereits zwei ~~test~~ aus.

**Comment by ckruse** [comment]
Weil ich mich verlesen hatte ;-) Fixed.

**Comment by JuliusPC** [comment]
Interessant: bei Github gehen auch ~~~drei~~~, ~~~~vier~~~~ oder ~~~~~~~~~~noch mehr~~~~~~~~~~ (zehn)

Ich finde aber, dass zwei ausreichen.

Escapen funktioniert auch nicht: `\~\~test\~\~` sieht bei Github so aus \~\~test\~\~, im CForum wie eingegeben.
