### ISSUE TITLE
Codeauszeichnung erfolgt fehlerhaft.

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#704]
Eine vollständig markierte, alleinstehende Zeile mit zwei unmittelbar vorangehenden und zwei unmittelbar folgenden Zeilenumbrüchen wird als Inlinecode ausgezeichnet.

**Comment by CountOrlok** [comment]
Das ist richtig. Als ich mich das erste mal damit befasst hatte, war die Situation die, dass durch den Button praktisch ohne Unterscheidung immer ein Codeblock erzeugt wurde, selbst für Code in einer einzigen Zeile. Ein solcher Codeblock wurde dann wegen fehlender Zeilenumbrüche vor den Tilden nicht richtig gerendert. Backticks für Inlinecode wurden nur eingefügt, wenn im gesamten Inhalt der Textarea kein Zeilenumbruch vorkam.

Daraufhin hatte ich es dann so implementiert, dass nur dann ein Codeblock erzeugt wird, wenn im markierten Text mindestens ein Zeilenumbruch enthalten ist. Andernfalls wurde der Text als Inlinecode ausgezeichnet.

Das hat allerdings dazu geführt, dass es nicht mehr möglich war, über den Button einen Codeblock zu erzeugen, ohne etwas zu markieren, was von mir und anderen Forumsbenutzern als Problem identifizert wurde. Wie [diesem](https://forum.selfhtml.org/meta/2017/feb/25/code-kennzeichen/1688120#m1688120) vermutlich unbeachtet gebliebenen Posting zu entnehmen ist, habe ich diesen Mangel dann dahingehend behoben, dass nun geprüft wird, ob ob vor dem Cursor zwei Zeilenumbrüche sind. Dabei habe ich mich jedoch auf den Fall beschränkt, dass vom Benutzer nichts markiert wurde.

Wenn wir nun den Fall betrachten, dass Text markiert wurde, dann läuft es also auf die Frage hinaus, was höher zu gewichten ist, der Kontext oder der Inhalt. Also die Frage, ob bei zwei Zeilenumbrüchen vor der Auswahl grundsätzlich ein Codeblock erzeugt werden soll, oder ob weiterhin auch in diesem Fall danach unterschieden werden soll, ob im markierten Text Zeilenumbrüche enthalten sind oder nicht.

Ebenso wie du tendiere ich dazu, den Kontext höher zu gewichten. Das heißt, unabhängig davon, ob Text markiert wurde oder nicht, sollte bei zwei Zeilenumbrüchen vor der Auswahl ein Codeblock erzeugt werden. Wenn jemand dann einen neuen Absatz mit Inlinecode beginnen möchte, dann muss er oder sie, egal ob etwas markiert wurde oder nicht, an den Anfang der Zeile ein Leerzeichen setzen. Das Leerzeichen wird dann nicht gerendert, aber es verhindert, dass ein Codeblock erzeugt wird.

In dem Fall, dass vor der Auswahl keine zwei Zeilenumbrüche sind, wird dann nach wie vor geprüft, ob die Auswahl Zeilenumbrüche enthält oder nicht. Sind welche enthalten, dann wird auch hier ein Codeblock generiert, ansonsten Inlinecode.

Ich habe einen entsprechenden Fix bereits implementiert, aber ich möchte noch ein paar Tests machen, bevor ich ihn online stelle. Vorausgesetzt es besteht Konsens darüber, dass es so umgesetzt werden soll.

**Comment by ckruse** [comment]
> Das hat allerdings dazu geführt, dass es nicht mehr möglich war, 
> über den Button einen Codeblock zu erzeugen, ohne etwas zu markieren, 
> was von mir und anderen Forumsbenutzern als Problem identifizert 
> wurde. Wie 
> [diesem](https://forum.selfhtml.org/meta/2017/feb/25/code-kennzeichen/1688120#m1688120) 
> vermutlich unbeachtet gebliebenen Posting zu entnehmen ist, habe ich 
> diesen Mangel dann dahingehend behoben, dass nun geprüft wird, ob ob 
> vor dem Cursor zwei Zeilenumbrüche sind. Dabei habe ich mich jedoch 
> auf den Fall beschränkt, dass vom Benutzer nichts markiert wurde.

Hm, das war mir nicht klar. Warum das? Zwei Zeilenumbrüche vor dem Text 
sind IMHO ein deutliches Indiz dafür, dass ein Block gewünscht ist.

> Wenn wir nun den Fall betrachten, dass Text markiert wurde, dann 
> läuft es also auf die Frage hinaus, was höher zu gewichten ist, der 
> Kontext oder der Inhalt. Also die Frage, ob bei zwei Zeilenumbrüchen 
> vor der Auswahl grundsätzlich ein Codeblock erzeugt werden soll, oder 
> ob weiterhin auch in diesem Fall danach unterschieden werden soll, ob 
> im markierten Text Zeilenumbrüche enthalten sind oder nicht.

Wenn zwei Zeilenumbrüche vor dem Code sind und die ganze Zeile markiert 
ist (also String-Ende oder ein Newline folgt der Markierung), dann ist 
die Wahrscheinlichkeit, dass ein Block gewünscht ist, extrem hoch. Es 
sollte auch ein Block generiert werden.

LG,
  CK

-- 
<https://wwwtech.de/>

**Comment by CountOrlok** [comment]
Ja, so sehe ich das wie gesagt auch. Ich hatte es im letzten Fix nur nicht bedacht, da sich die vorangegangene Diskussion um den Fall drehte, wie ein Codeblock einzufügen wäre wenn nichts markiert ist.

**Comment by ckruse** [comment]
Der @CountOrlok hats gefixed.
