### ISSUE TITLE
abgetrennte Threads sortieren sich nicht richtig in die Threadliste ein

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#707]
Ich habe <https://forum.selfhtml.org/self/2017/feb/10/revenge-punkt-css/1686934#m1686934> abgetrennt. Und hätte erwartet, dass dieser Thread entsprechend meiner Einstellungen (nach letzter Antwort sortieren) ziemlich weit oben erscheint, weil die letzte Antwort von heute, 04:11 Uhr ist.  Er befindet sich aber bei mir erst auf Seite 2, wenn ich die gelesenen Threads ausblende und erst auf Seite 10, wenn die gelesenen Threads angezeigt werden. Der Ursprungsthread hingegen, also von dem abgetrennt wurde, befindet sich ganz oben.

**Comment by ckruse** [comment]
Hm ja, ich weiss schon, woran das liegt. Als Zwischenlösung kannst du 
den Thread einmal löschen und dann wieder herstellen.

**Comment by MatthiasApsel** [comment]
Das hast du bestimmt grade getan, oder? Jedenfalls stimmt es jetzt wieder.

> Hm ja, ich weiss schon, woran das liegt.

Du hast bestimmt parent und child vertauscht.

**Comment by ckruse** [comment]
Ja, habe ich getan. Nein, es liegt vermutlich daran, dass ich ein 
falsches Datum für `latest_message` im Thread setze, `find_youngest` 
wird einen Bug haben.

**Comment by ckruse** [comment]
Oh man… *facepalm* ja, hat es.
