### ISSUE TITLE
Escaping in der Suche kaputt (Posting von 2000)

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#708]
In der Suche funktioniert das Escapen des HTML bei [diesem Eintrag](https://forum.selfhtml.org/self/2000/sep/21/wert-von-radiobuttons/106872#m106872) nicht:

![html-Injection](https://cloud.githubusercontent.com/assets/15018932/23926203/22a287d6-0913-11e7-8e6b-d46bc4511180.png)

Link zur betroffenen Suchseite: <https://forum.selfhtml.org/search?order=document_created&page=2&sections%5B%5D=1&sections%5B%5D=2&start_date%5Bday%5D=14&start_date%5Bmonth%5D=3&start_date%5Byear%5D=2000&stop_date%5Bday%5D=14&stop_date%5Bmonth%5D=3&stop_date%5Byear%5D=2002&term=forumsauslese#results>

**Comment by ckruse** [comment]
Faszinierend ist, dass dass ich das Problem lokal nicht nachvollziehen 
kann, bei mir ist da kein <input>…

**Comment by JuliusPC** [comment]
Lokal bedeutet auf deiner Testinstallation? Aber im SELFHTML-Forum siehst du das auch – ich leide nicht unter Halluzinationen?!

**Comment by ckruse** [comment]
Nein, du hast schon recht, in Production ist das Input-Element da. 
Interessant ist, dass PostgreSQL das Escaping hier übernehmen müsste. 
Der Anreisser kommt hierher:

~~~
SELECT ts_headline('german', author || ' ' || title || ' ' || content, 
to_tsquery('german', '''forumsauslese'''), 'MaxFragments=3') AS 
headline_doc
~~~

Stimmt da was nicht mit der PostgreSQL-Konfiguration? *grübel*

**Comment by ckruse** [comment]
Auch in Production:

~~~
selfforum=> SELECT ts_headline('german',
  'Das <b>ist</b> ein sehr merkwürdiges <verhalten>',
  to_tsquery('merkwürdig'),
  'StartSel = XXX, StopSel = YYY');
            ts_headline
-----------------------------------
 Das  ist  ein sehr merkwürdiges
(1 row)
~~~

Hier *wird* also HTML gestripped. Warum nicht in diesem Fall?

**Comment by JuliusPC** [comment]
> Hier _wird_ also HTML gestripped.

Kann sein, dass ich dich falsch verstanden habe (falls das nur ein Test der generellen Funktionstüchtigkeit war), aber müsste das HTML nicht escaped statt entfernt werden? – Die Codebeispiele soll man ja weiterhin sehen können :-)

**Comment by ckruse** [comment]
Eins nach dem anderen, erstmal verstehen warum zur Hölle hier das HTML nicht entfernt wird aber an anderer Stelle schon.

**Comment by ckruse** [comment]
Wirklich faszinierend. Frischer Datenbank-Dump, Query lokal:

~~~
cforum_development=# SELECT ts_headline('german', 'Forumsauslese
cforum_development'# <input type=Radio name=tanz value=salsa>
cforum_development'# <input ...        name=tanz value=tango>', to_tsquery('german', 'forumsauslese'));
     ts_headline
----------------------
 <b>Forumsauslese</b>+
                     +

(1 row)
~~~

Gleiche Query auf dem Server:

~~~
selfforum=> SELECT ts_headline('german', 'Forumsauslese
selfforum'> <input type=Radio name=tanz value=salsa>
selfforum'> <input ...        name=tanz value=tango>', to_tsquery('german', 'forumsauslese'));
               ts_headline
------------------------------------------
 <b>Forumsauslese</b>                    +
                                         +
 <input ...        name=tanz value=tango>
(1 row)
~~~

**Comment by ckruse** [comment]
Ok, ich habe das Problem gefunden. Der Cluster wurde mit einem falschen collate & ctype erstellt:

~~~
   Name    |  Owner   | Encoding | Collate |  Ctype  |   Access privileges
-----------+----------+----------+---------+---------+-----------------------
 selfforum | cforum   | UTF8     | C.UTF-8 | C.UTF-8 |
~~~

Statt `C.UTF-8` müsste es `en_US.UTF-8` sein (oder von mir aus auch `de_DE.UTF-8`).

Lösung: `pg_dumpall`, Cluster neu erstellen, restore… 🤢💩

**Comment by ckruse** [comment]
Gut, hat nicht geholfen 😟

**Comment by ckruse** [comment]
Ich weiss, dass es an den non-breaking spaces in dem `<input>` liegt, aber warum der Parser das nicht erkennt ist mir schleierhaft.

**Comment by ckruse** [comment]
Ok, ich habe den Indexer umgeschrieben. Es werden jetzt ` <>&` entfernt von dem Such-Dokument. Der Indexer läuft, wird also vermutlich irgendwann morgen soweit sein ;-)

**Comment by JuliusPC** [comment]
Dann schaue ich morgen noch mal in die Suche :-)

– Die Downtime war wesentlich kürzer als die angekündigte halbe Stunde.

Ist `C.UTF-8` (hatte ich bisher nichts von gehört) etwas zu ASCII kompatibleres als `de_DE.UTF-8` und oder wofür braucht man das, warum die Unterscheidung?

BTW: Ist pillepalle, aber warum sagt die Statusseite, die man bekommt, nicht einfach, dass Wartungsarbeiten gemacht werden (und sendet einen 503er)? Wartungsarbeiten sind ja planmäßig und nicht weil etwas „schiefgelaufen“ ist

> Es werden jetzt  <>& entfernt von dem Such-Dokument

Bedeutet das dann, dass ich die beiden Strings für die Suche `<bla>` und `bla` gleich sind und man nicht mehr nach `&<>` suchen kann?

**Comment by ckruse** [comment]
`C` ist das POSIX-Locale, das ist im POSIX-Standard definiert und alle POSIX-kompatiblen Systeme müssen das implementieren. Und `C.UTF-8` ist eine Debian-Variante davon mit UTF-8 als Charset (statt ASCII). Ist eigentlich Unsinn, aber kommt halt dabei herum wenn jemand die Debian-Installation ohne Locales macht (wie in dem Install-Image des ISPs, bei dem der CForum-Server liegt).

Es gab keine Wartungsarbeiten-Seite, weil ich zu faul dazu war 😂

Und man konnte vorher schon nicht nach Non-breaking Spaces, `<`, `>` oder `&` suchen 😝

**Comment by ckruse** [comment]
Das Dokument wurde übrigens schon neu indiziert
