### ISSUE TITLE
Zusätzlicher Link auf Formatierungshilfe

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#709]
Zunächst: Mir ist aufgefallen, dass wir unterschiedliche Anreden verwenden: 

"Im Wiki erhalten Sie Hilfe bei der Formatierung Ihrer Beiträge.", "Bitte beachten Sie die Nutzungsbedingungen" vs. "Formuliere höflich und wertschätzend. Vermeide Vollzitate. Dein Beitrag wird dauerhaft archiviert."

Was hältst du von:
+    Formuliere **höflich und wertschätzend**.
+    Im Wiki erhältst du **Hilfe bei der Formatierung** deiner Beiträge.
+    Deine Beiträge werden **dauerhaft** archiviert.

natürlich mit den entsprechenden Links?

Damit es nicht so viel wird und die Vollzitat-Problematik offenbar nicht mehr besteht, kann "vermeide Vollzitate" mMn. weg.

cforum/app/views/messages/_post_notes.html.erb
cforum/app/views/messages/edit.html.erb

**Comment by campingrider** [comment]
+1 - Das korrespondiert mit unserer [erklärten Linie](http://wiki.selfhtml.org/wiki/SELFHTML:Wiki#Sie_oder_Du.3F), da ich das Forum insgesamt für einen Ort der Begegnung halte (auch in den GUI-Texten).
