### ISSUE TITLE
Beiträge mit negativem Score kennzeichnen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#711]
Auf [php.net](http://php.net/manual/en/function.date.php) sind Beiträge mit negativem Score durch eine geringere Opazität gebranntmarkt, sogar in Abstufungen. Was meinst du dazu?

**Comment by ckruse** [comment]
Habe ich auch mal drüber nachgedacht. Und wenn sie einen Score erreichen werden sie „versteckt“ und es braucht einen Extra-Klick um sie zu sehen.

Via Mobile, deshalb kurz. Nicht unhöflich gemeint!

**Comment by ckruse** [comment]
das ist zu vorschnell gewesen ;-) ich habe da noch mehr vor

**Comment by MatthiasApsel** [comment]
Ah, den zusätzlichen Klick.
