### ISSUE TITLE
Button "Zitat einfügen"

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#713]
Dieser Button ist auch da, wenn man antworten mit Zitat wählt bzw. das Zitat eingefügt hat.

**Comment by MatthiasApsel** [comment]
Was hältst du von dem Text "Beitrag zitieren", "Original zitieren"?

**Comment by MatthiasApsel** [comment]
Bei Klick auf diesen Button wird der bereits geschriebene Text gelöscht. Das sollte nicht sein. Stattdessen sollte das Zitat an der Cursorposition + 2 Zeilen eingefügt werden.

**Comment by ckruse** [comment]
Ich würde bei „Zitat einfügen” bleiben…
