### ISSUE TITLE
Neugestaltung Antwortfeld

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#714]
![unbenannt](https://cloud.githubusercontent.com/assets/2847625/24442085/c5294b80-145c-11e7-886e-1fc1cd48fe66.png)

Was hältst du davon? Die Buttons sind nicht so klobig, sie sind deutlich näher am Antwortfeld, das Fragezeichen, gern auch eins im Kreis führt zur Wikiseite.

Gern auch so, denn ich glaube, die fullscreenansicht wird nicht/kaum genutzt.

![unbenannt](https://cloud.githubusercontent.com/assets/2847625/24442669/693ed54e-145f-11e7-816c-03e3de4b3965.png)

**Comment by auge8472** [comment]
Wurde der Text zur Beschreibung der Buttonfunktion nicht eingeführt, um denen, die die Icon-Fonts nicht sehen oder nicht interpretieren können, diese Funktion mitzuteilen? Wieso soll das nun wieder aufgegeben werden?

**Comment by MatthiasApsel** [comment]
Ich habe die Beschriftungen ausgeblendet. Mit Beschriftung sähen sie halt alle so aus wie die letzten beiden. Allerdings kenne ich auch keine GUI, in der solcherart Buttons beschriftet wären. Sie müssen natürlich eine Beschriftung bekommen.

**Comment by MatthiasApsel** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/2847625/24451553/9da7903a-147f-11e7-81a9-2a7c1e8d7431.png)

Sähe dann so aus.

**Comment by ckruse** [comment]
ich hätte sie lieber ohne Beschriftung… prinzipiell gefällt mir das aber gut.

**Comment by MatthiasApsel** [comment]
Ich auch.

**Comment by ckruse** [comment]
Hast du das CSS hierfür irgendwo rumliegen? Dann muss ich das nicht selber alles nachbauen.

**Comment by MatthiasApsel** [comment]
Leider nein. Aber ich kann das CSS morgen rausschreiben. Ich habe das mit den Entwicklertools gebaut und da kann man sich ja relativ leicht über CSS-Regeln hinwegsetzen.

**Comment by ckruse** [comment]
Ja, das wäre nicht schlecht.

**Comment by MatthiasApsel** [comment]
Der Hilfe-Button fehlt noch ;-)

**Comment by ckruse** [comment]
Äh. Ja. Bin gerade essen, später oder morgen früh :)

**Comment by MatthiasApsel** [comment]
Nicht schlimm ;-) Lässt sich der Fokus auf die textarea so setzen, dass die Buttonleiste im Viewport ist?

**Comment by ckruse** [comment]
Das ist bereits der Fall. Das Fieldset wird in den Viewport gescrollt, die Button-Leiste ist Teil des Fieldsets. Und hier funktioniert das auch genau wie gewünscht.

**Comment by MatthiasApsel** [comment]
Hm. Stimmt. Muss ich mal schauen, warum das mit meinem User-JS nicht geht.

**Comment by MatthiasApsel** [comment]
Wenn der Hilfe-Button ein a-Element ist, dann `border: 2px solid #feebe6` sonst sind die Flächen unterschiedlich groß. Das dicke Fragezeichen `class="fa fa-question"` ist nicht erwünscht? Der Text soll bleiben?

**Comment by ckruse** [comment]
Bei mir ist die Fläche mit Border etwa zwei Pixel höher als die 
anderen Schaltflächen:

![](cid:0F35820D-0251-4B21-B519-C87120865775@wwwtech.de "Bildschirmfoto 
2017-04-03 um 09.05.35.png")

Ohne Border ist sie identisch hoch. Safari, Chrome und Firefox auf OS X.

Sicher, dass das nicht an deinem User-CSS liegt?

**Comment by MatthiasApsel** [comment]
Es liegt am Firefox 

~~~css
.btn-default.btn-sm.btn::-moz-focus-inner {
    padding: 0;
    margin: 0;
    border: 0;
}
~~~

macht die buttons kleiner.

Siehe http://stackoverflow.com/questions/5370609/difference-between-firefox-and-chrome-padding

**Comment by ckruse** [comment]
warum sehe ich das dann nicht bei mir im Firefox?

**Comment by MatthiasApsel** [comment]
Das frage ich mich auch. Bei mir ist es sowohl unter Windows als auch unter Mint sichtbar. Vielleicht unterstützt der FF und OS X dies nicht.

Wenn du in den Entwicklertools `::-moz-focus-inner { padding: 1em; }` eingibst, tut sich da was?

**Comment by ckruse** [comment]
Es scheinen andere Default-Werte zu sein. Wenn ich [diese 
Regel](https://github.com/ckruse/cforum/commit/6a2ba582ed316bf89f650426cd18677695e392f9) 
in den Entwickler-Tools beim Firefox deaktiviere und wieder aktivere im 
Wechsel, dann sehe ich, dass die Buttons zwar in die Breite aber nicht 
in die Höhe wachsen.

**Comment by MatthiasApsel** [comment]
Du könntest sogar `::-moz-focus-inner` schreiben, das Problem tritt nämlich auch bei den message-Links auf.
