### ISSUE TITLE
Andere Bezeichnung für problematische Seite

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#723]
Dies unter <https://forum.selfhtml.org/m1691649> vorgeschlagene 

"[Um diese Seite geht es.](http://example.com)" ließe sich recht einfach umsetzen, an

"Um [diese Seite](http://example.com) geht es." scheitere ich aber.

Ich könnte natürlich einfach 

~~~ruby
<p class="problematic-site">
Um 
<%= cf_link_to Message.human_attribute_name(:problematic_site), m.problematic_site, rel: 'nofollow' %>
geht es.
</p>
~~~

schreiben, weiß aber, dass das nicht deine Zustimmung trifft.

"Um diese Seite geht es" könnte/sollte es auch im Erstellungsformular heißen.

**Comment by ckruse** [comment]
Ich will ehrlich sein, ich finde diese „Diskussion” albern… ich würde es lassen, wie es ist. Das Styling dieser Box ist eh schon fragil, und da würde ich jetzt nicht rumspielen wollen nur weil sich jemand da an dem Begriff stößt.
