### ISSUE TITLE
Codeblöcke dezenter gestalten

### ISSUE THREAD

**Issue by JuliusPC** [ckruse/cforum#726]
Ich finde, dass die Codeblöcke im Forum etwas zu sehr dem CI von SELFHTML (sichtbare Grenzen und abgerundete Ecken) folgen, vielleicht ließe sich das etwas entschärfen:  
![Dezentere Rahmen um Codeblöcke](https://cloud.githubusercontent.com/assets/15018932/23836005/503644b0-0771-11e7-9156-e3d9971296e0.png)

Zum Vergleich, so sieht es im Moment aus:  
![Dominante Rahmen](https://cloud.githubusercontent.com/assets/15018932/25063567/fd312f28-21e7-11e7-9057-4ef701e34199.png)

Das betreffende User-CSS:

~~~css
code {
  border:none;
  background-color:rgba(0,0,0,0.04);
  border-radius:0;
  border:thin solid rgba(0,0,0,0.05);
}

code.block {
  border-left:medium solid #8a9da8;
  border-radius:0;
  background-color:white;
}
~~~

Vgl. auch die [Debatte um Inline-Styles](https://github.com/ckruse/cforum/issues/706).

**Comment by ckruse** [comment]
Mir gefällt der Vorschlag im großen und ganzen. Ich hab das etwas überarbeitet mal übernommen.
