### ISSUE TITLE
Glocke für Kennzeichnung neuer Nachrichten

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#727]
![unbenannt](https://cloud.githubusercontent.com/assets/2847625/25305902/0a9cd9d6-2784-11e7-8784-3885f1989142.png)

Das ist die Glocke aus font-awesome (fa-bell) mit der Farbe #8db243; 

Auch orange (#df6c20) sieht gut aus, gefällt mir fast besser.

![unbenannt](https://cloud.githubusercontent.com/assets/2847625/25305940/bb2e88b2-2784-11e7-9c41-e722bbc35812.png)

Gelb geht auch (#dfac20)

![unbenannt](https://cloud.githubusercontent.com/assets/2847625/25306000/91b46028-2785-11e7-9872-2fa66165906d.png)

Mein Favorit ist orange.

Was meinst du?

Die Umsetzung habe ich nicht hinbekommen. Schon allein, weil es in "unserem" font-awesome-css kein fa-bell gibt.

**Comment by MatthiasApsel** [comment]
**Semantisch** würde am besten c0000a passen.

![unbenannt](https://cloud.githubusercontent.com/assets/2847625/25308561/7f3c3376-27b7-11e7-95ee-a3a9b0fae01d.png)

In [Performers Farbtabelle](https://wiki.selfhtml.org/wiki/Hilfe:SELFHTML-Farbtabelle) steht c32e04. (Links im Bild)

![unbenannt](https://cloud.githubusercontent.com/assets/2847625/25308589/431565e2-27b8-11e7-8f75-d47c027276d8.png)

**Comment by ckruse** [comment]
Ich finds gut. Ich schau mir das mal an, aber ich will mich erst um das 
Folded-Ding kümmern.
