### ISSUE TITLE
eine EMail-Adresse verwenden, auf die man nicht antworten kann

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#745]
Jemand ist per Mail über einen neuen Beitrag benachrichtigt worden, statt weiterzuleiten hat er uns (forum@selfhtml.org) versehentlich geantwortet. Die Absenderadresse noreply@selfhtml.org wäre, denke ich, besser. Und die Mails sollten wir dann auch wirklich nicht entgegen nehmen.

**Comment by ckruse** [comment]
Ich halte das nicht für zielführend. Er bekäme dann eine „Mailer 
daemon“-Antwort, das ist genau der Grund, warum ich 
`forum@selfhtml.org` gewählt habe - jetzt können wir ihn darauf 
hinweisen, dass er im Forum antworten muss.

**Comment by ckruse** [comment]
Ich wollte hier kein Machtwort sprechen… ich habe nur meine Meinung 
geäußert?

**Comment by MatthiasApsel** [comment]
Kein Problem. Du hast dir was dabei gedacht. Ich finde die Möglichkeit, dass man ihn jetzt auf das Forum verweisen kann, auch nicht verkehrt.
