### ISSUE TITLE
 inkonsistente Paginierung

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#754]
Siehe und vergleiche etwa 

+ https://forum.selfhtml.org/users/1/scores
+ https://forum.selfhtml.org/users/1/scores?page=39

**Comment by ckruse** [comment]
Was meinst du?

**Comment by MatthiasApsel** [comment]
Wenn ich ganz am Anfang bin, gibt es die inaktiven Links "erste Seite" sowie "eine Seite zurück". Wenn ich ganz am Ende bin, gibt es die inaktiven Links "letzte Seite" und "eine Seite vor" nicht.

**Comment by ckruse** [comment]
Ach so – du hast mich nicht auf die letzte Seite geschickt, deshalb 
habe ich das nicht sehen können ;-)

**Comment by MatthiasApsel** [comment]
Für mich ist es die letzte Seite :-)

![unbenannt](https://user-images.githubusercontent.com/2847625/27752575-fa0c6e8a-5de1-11e7-9335-259145f60ee8.png)

**Comment by ckruse** [comment]
Ja, aber du siehst ja auch nur die Hälfte ;-)

**Comment by MatthiasApsel** [comment]
Stimmt. Bei dir sind ja auch die eigenen (-1)-Bewertungen drin, wenn du einen anderen Beitrag negativ bewertest ;-)
