### ISSUE TITLE
Autoreninfos an jedes Posting wären eine gute Idee.

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#77]
-etwa: Avatar, Anzahl Beiträge, Mail, Website, Anzahl Bewertungen, Mitglied seit, online-offline, Moderator ja/nein

**Comment by ckruse** [comment]
Gibt es hier einen Entwurf (z.B. von Performer?)

**Comment by MatthiasApsel** [comment]
Am 03.03.2015 um 11:05 schrieb Christian Kruse:
> Gibt es hier einen Entwurf (z.B. von Performer?)

Derzeit noch nicht, aber ich frage mal auf Trello nach. Ansonsten 4.1?

-- 
Matthias

**Comment by ckruse** [comment]
Ja, für die 4.0 halte ich das für eine schlechte Idee. Das wird noch ein wenig Arbeit kosten.
