### ISSUE TITLE
Flattr-Button an Postings nach Entfernung der Flattr-ID

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#774]
Vor kurzem habe ich die Flattr-ID aus meinen persönlichen Einstellungen entfernt. Dennoch wird der Button in den Postings aus der Zeit, als die ID in meinen Einstellungen existierte, weiterhin angezeigt. Ich halte das nicht für sinnvoll, zumal es den Flattr-Account mittlerweile nicht mehr gibt.

**Comment by ckruse** [comment]
Ich habe die Flattr-Unterstützung vollständig entfernt
