### ISSUE TITLE
archivlinks defekt

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#790]
In der Adminansicht sind die Links fürs Archiv fehlerhaft. Beispiel: `https://forum.selfhtml.org/all?view_all=yes/archive`, `https://forum.selfhtml.org/all?view_all=yes/2014`

**Comment by ckruse** [comment]
Huch, äh, wo?

**Comment by MatthiasApsel** [comment]
In der Adminansicht auf archivierte Beiträge klicken.

Das andere sind die Links zu Jahren oder Monaten z.B. auf der Seite <https://forum.selfhtml.org/self/archive?view_all=yes>
