### ISSUE TITLE
Etwas ist schief gelaufen

### ISSUE THREAD

**Issue by MatthiasApsel** [ckruse/cforum#792]
Ich kann keinen Beitrag dieses Threads https://forum.selfhtml.org/self/2018/apr/17/google-analytics-und-andere-tracking-software-rechtlich-korrekt-nutzen/1719805#m1719805 beantworten - etwas ist schief gelaufen.

**Comment by ckruse** [comment]
@MatthiasApsel mein guess: das liegt an deinem Adblocker. Ich hatte das Problem gerade auch, bis ich den Adblocker deaktiviert habe.

@auge8472 zu wenig Information... sorry. Ich brauche mehr Einzelheiten als "ging heute nicht"

**Comment by auge8472** [comment]
Nun gut, den Adblocker werde ich nicht ausschalten. Mal gucken, wie ich Ausnahmen definiere.

Bleibt für mich nur die Frage, warum es bei anderen Postings, wie z.B. [diesem hier](https://forum.selfhtml.org/self/2018/apr/25/ajax-feuert-mehrfach-problem-die-antworten-zuzuordnen/1720483#m1720483), funktioniert. Habe es gerade eben positiv bewertet.

**Comment by ckruse** [comment]
Ob der Adblocker anspringt oder nicht hängt an den Regeln. Und die haben als Metrik unter anderem eine Liste von Keywords für URLs. Bei [diesem Posting](https://forum.selfhtml.org/self/2018/apr/17/google-analytics-und-andere-tracking-software-rechtlich-korrekt-nutzen/1720443#m1720443) ist er vermutlich wegen des `tracking` in der URL angesprungen.

**Comment by MatthiasApsel** [comment]
Danke für die Recherche. Da hätte ich auch selbst mal schauen können. Verwundert war ich, weil ich zwar die fraglichen Beiträge editieren konnte, aber nicht beantworten.
