### ISSUE TITLE
zuviele ungelesene Beiträge auf der Übersichtsseite

### ISSUE THREAD

**Issue by auge8472** [ckruse/cforum#799]
Mir werden auf der Übersichtsseite des Selfforums aktuell 504 Beiträge in 34 Threads als ungelesen angezeigt. Die angezeigten Zahlen müssen aber falsch sein, denn ich habe (bis auf einen Thread mit aktuell 6 ungelesenen Beiträgen) *alle* Threads in *allen* mir zugänglichen Foren gelesen oder als gelesen markiert. Dazu gehören auch jene Threads, die ich ausgeblendet habe (habe testweise alle als gelesen markiert).

![cforum-2muchentries](https://user-images.githubusercontent.com/1734660/46283955-53f24800-c576-11e8-9058-870e366d53b9.png)

Ich habe Zugriff auf auf drei Unterforen und dieser Fehler fällt mir auf, seitdem mir Zugriff auf das Moderationsforum gewährt wurde. Wenn ich spekulieren dürfte, würde ich vermuten, dass in der Anzeige die Beiträge eines weiteren Forums, auf das ich *keinen Zugriff* habe, mitgezählt werden.

Das ist nun kein Showstopper, davon geht schließlich nix kaputt. Dennoch ist es mindestens verwirrend.

**Comment by ckruse** [comment]
Das ist kein Fehler, sondern eine Umstellung. Bis vor kurzem wurden nur die Beiträge gezählt, die seit dem letzten Login neu dazu kamen. Jetzt werden alle ungelesenen Beiträge gezählt, die nicht im Archiv sind. Viel wahrscheinlicher ist, dass auf einer der anderen Seiten (siehe das Paging der Foren) ungelesene Beiträge zu finden sind.

**Comment by auge8472** [comment]
> Jetzt werden alle ungelesenen Beiträge gezählt, die nicht im Archiv sind. Viel wahrscheinlicher ist, dass auf einer der anderen Seiten (siehe das Paging der Foren) ungelesene Beiträge zu finden sind.

Tatsächlich. Paging habe ich zwar nur im Bereich „ausgeblendete Threads“, aber im Moderationsforum sind mir einige ältere Threads durch die Lappen gegangen, weil ich – auch ganz ohne Paging – nicht mehr so weit heruntergescrollt habe.

`CLOSE`
