### ISSUE TITLE
Sichtbare Beschriftung Teil des zugänglichen Namens

### ISSUE THREAD

**Issue by MarcHaunschild** [ckruse/cforum#802]
[Sichtbare Beschriftung Teil des zugänglichen Namens](https://testen.bitv-test.de/index.php?a=di&iid=117&s=n)

Mein Gegenvorschlag: Erst Avatar (nicht verlinkt), dann Name des Beitrages und Uhrzeit, in Klammer dahinter den Namen des Autors als Link zum Profil:

😜 [**Classic Forum V5 - noch kleine Bugs** 22.06.2019 20:19](#) ([_Der Martin_](#))

**Comment by ckruse** [comment]
von Hand übertragen
