### ISSUE TITLE
Dropdown der Autokorrektur nicht am Text

### ISSUE THREAD

**Issue by MarcHaunschild** [ckruse/cforum#803]
![Bildschirmfoto 2019-06-24 um 09 25 48](https://user-images.githubusercontent.com/685898/59999957-85aac200-9663-11e9-8279-6a697bed2d92.png)

**Comment by MarcHaunschild** [comment]
Tritt nur sporadisch auf... :-(

**Comment by ckruse** [comment]
Zunächst mal: danke für deine Meldung!

Leider hast du das falsche Repository gewählt, nämlich das für Version 4. Hier jetzt nicht schlimm, ich trage das von Hand um, aber für das nächste Issue: das hier ist das richtige Repository: https://github.com/ckruse/cforum_ex/ (das ist auch aus dem Forums-Footer heraus verlinkt :-)

**Comment by ckruse** [comment]
Von Hand übertragen
